<?php
declare(strict_types=1);
require_once dirname(__DIR__,2) . '/includes/app/bootstrap.php';
require_permission('users.administer');
$requests=sort_records(data_collection('access_requests'),'submitted_at','desc');
render_app_start('Access Requests','admin-access','Account request administration','Review pending account requests, assign a company and role, record notes, and approve or decline access.','');
?>
<section class="metric-grid metric-grid-4"><article class="metric-card"><span>Total requests</span><strong><?= count($requests) ?></strong><small>Sample request history</small></article><article class="metric-card"><span>Pending</span><strong><?= count(array_filter($requests,fn($r)=>$r['status']==='pending')) ?></strong><small>Needs review</small></article><article class="metric-card"><span>Approved</span><strong><?= count(array_filter($requests,fn($r)=>$r['status']==='approved')) ?></strong><small>Account created</small></article><article class="metric-card"><span>Declined</span><strong><?= count(array_filter($requests,fn($r)=>$r['status']==='declined')) ?></strong><small>History retained</small></article></section>
<div class="access-request-list"><?php foreach($requests as $request): ?><article class="access-request-card"><header><div><span class="avatar"><?= h(initials($request['first_name'].' '.$request['last_name'])) ?></span><div><span><?= h(date_us($request['submitted_at'],true)) ?></span><h2><?= h($request['first_name'].' '.$request['last_name']) ?></h2><small><?= h($request['email']) ?> · <?= h($request['job_title']) ?></small></div></div><?= badge($request['status']) ?></header><dl><div><dt>Requested company</dt><dd><?= h(data_company_name($request['company_id'])) ?></dd></div><div><dt>Requested role</dt><dd><?= h(data_role_name($request['requested_role'])) ?></dd></div><div><dt>Review note</dt><dd><?= h($request['review_note']?:'No note recorded.') ?></dd></div></dl><?php if($request['status']==='pending'): ?><form class="request-review-form" action="<?= h(app_url('action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="access_request_review"><input type="hidden" name="id" value="<?= (int)$request['id'] ?>"><input type="hidden" name="return_to" value="admin/access-requests.php"><label><span>Company</span><select name="company_id"><?= company_options($request['company_id']) ?></select></label><label><span>Role</span><select name="role_code"><?php foreach(data_collection('roles') as $role): if(!in_array($role['code'],data_assignable_role_codes(),true))continue; ?><option value="<?= h($role['code']) ?>" <?= $request['requested_role']===$role['code']?'selected':'' ?>><?= h($role['name']) ?></option><?php endforeach; ?></select></label><label class="span-2"><span>Review note</span><textarea name="review_note" rows="3"><?= h($request['review_note']) ?></textarea></label><div class="span-2 row-actions"><button class="button danger" type="submit" name="decision" value="declined">Decline</button><button class="button primary" type="submit" name="decision" value="approved">Approve & create user</button></div></form><?php else: ?><footer><small>Reviewed by <?= h(data_user_name($request['reviewed_by']??null)) ?> on <?= h(date_us($request['reviewed_at']??null,true)) ?></small></footer><?php endif; ?></article><?php endforeach; ?></div>
<?php render_app_end(); ?>
