<?php
declare(strict_types=1);
require_once dirname(__DIR__,2) . '/includes/app/bootstrap.php';
require_permission('audit.view');
$events=data_visible_collection('audit_events');$q=strtolower(query_string('q'));$userId=query_int('user');$companyId=query_int('company');$module=query_string('module');$action=query_string('action');$dateFrom=query_string('date_from');$dateTo=query_string('date_to');
$events=array_values(array_filter($events,static function(array $e)use($q,$userId,$companyId,$module,$action,$dateFrom,$dateTo):bool{
 $hay=strtolower(($e['module']??'').' '.($e['action']??'').' '.($e['entity_type']??'').' '.($e['entity_id']??'').' '.data_user_name($e['user_id']??null));
 if($q!==''&&!str_contains($hay,$q))return false;if($userId&&(int)($e['user_id']??0)!==$userId)return false;if($companyId&&(int)($e['company_id']??0)!==$companyId)return false;if($module!==''&&($e['module']??'')!==$module)return false;if($action!==''&&($e['action']??'')!==$action)return false;
 $date=substr((string)$e['created_at'],0,10);if($dateFrom!==''&&$date<$dateFrom)return false;if($dateTo!==''&&$date>$dateTo)return false;return true;
}));
$events=sort_records($events,'created_at','desc');$pagination=paginate_records($events,query_int('page',1),10);$modules=array_values(array_unique(array_column($events,'module')));sort($modules);$actions=array_values(array_unique(array_column($events,'action')));sort($actions);
$export=can('audit.export')?'<button class="button secondary" type="button" data-demo-export>Export Filtered CSV</button>':'';
render_app_start('Audit Log','admin-audit','Immutable event viewer','Search and filter user, company, module, action, entity, IP, and before/after change details.',$export);
?>
<section class="notice-card audit-notice"><div><span class="notice-icon">≡</span><div><strong>Immutable-event presentation</strong><p>Audit records are append-only. Demo resets replace only the isolated sample dataset; Production Data audit events cannot be edited or deleted through the application.</p></div></div><span><?= $pagination['total'] ?> matching events</span></section>
<section class="panel"><form class="audit-filter-grid" method="get"><label class="span-2"><span>Search action, entity, user</span><input name="q" value="<?= h(query_string('q')) ?>"></label><label><span>Date from</span><input type="date" name="date_from" value="<?= h($dateFrom) ?>"></label><label><span>Date to</span><input type="date" name="date_to" value="<?= h($dateTo) ?>"></label><label><span>User</span><select name="user"><option value="0">All users</option><?= user_options($userId,false) ?></select></label><label><span>Company</span><select name="company"><option value="0">All companies</option><?= company_options($companyId) ?></select></label><label><span>Module</span><select name="module"><option value="">All modules</option><?php foreach($modules as $value): ?><option value="<?= h($value) ?>" <?= $module===$value?'selected':'' ?>><?= h($value) ?></option><?php endforeach; ?></select></label><label><span>Action</span><select name="action"><option value="">All actions</option><?php foreach($actions as $value): ?><option value="<?= h($value) ?>" <?= $action===$value?'selected':'' ?>><?= h(status_label($value)) ?></option><?php endforeach; ?></select></label><div class="span-2 filter-actions"><button class="button primary" type="submit">Apply filters</button><a class="button ghost" href="<?= h(app_url('admin/audit.php')) ?>">Reset</a></div></form></section>
<section class="panel"><div class="table-wrap"><table class="data-table audit-table"><thead><tr><th>Date</th><th>User / IP</th><th>Company</th><th>Module / action</th><th>Entity</th><th>Change details</th><th>Immutable</th></tr></thead><tbody><?php foreach($pagination['items'] as $event): ?><tr><td><?= h(date_us($event['created_at'],true)) ?></td><td><strong><?= h(data_user_name($event['user_id'])) ?></strong><small><code><?= h($event['ip_address']) ?></code></small></td><td><?= h(data_company_name($event['company_id'])) ?></td><td><strong><?= h($event['module']) ?></strong><small><?= h(status_label($event['action'])) ?></small></td><td><?= h(status_label($event['entity_type'])) ?><small>#<?= h($event['entity_id']??'—') ?></small></td><td><details class="change-details"><summary>View before / after</summary><div><section><span>Before</span><pre><?= h(json_encode($event['before'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)) ?></pre></section><section><span>After</span><pre><?= h(json_encode($event['after'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)) ?></pre></section></div></details></td><td><span class="immutable-mark">◆ Locked</span></td></tr><?php endforeach; ?></tbody></table></div><?= render_pagination($pagination,['q'=>query_string('q'),'user'=>$userId,'company'=>$companyId,'module'=>$module,'action'=>$action,'date_from'=>$dateFrom,'date_to'=>$dateTo]) ?></section>
<?php render_app_end(); ?>
