<?php
declare(strict_types=1);
require_once dirname(__DIR__,2) . '/includes/app/bootstrap.php';
require_permission('companies.view');
$companies=data_permitted_companies();$editId=query_int('edit');$edit=$editId?data_find('companies',$editId):null;if($edit&&!data_company_within_scope($edit['id'])){$edit=null;http_response_code(403);render_access_denied('companies.view.company_scope');exit;}
render_app_start('Companies','admin-companies','Company administration','Manage company profiles, contacts, operational owners, memberships, completion metrics, modules, retention, and company settings.','');
?>
<section class="company-admin-grid"><?php foreach($companies as $company): $users=count(array_filter(data_admin_visible_users(),fn($u)=>in_array((int)$company['id'],array_map('intval',$u['company_ids']),true))); ?><article class="company-admin-card"><header><div><span><?= h($company['code']) ?></span><h2><?= h($company['name']) ?></h2><small><?= h($company['industry']) ?></small></div><?= badge($company['status']) ?></header><div class="company-completion"><div><span>Data completeness</span><b><?= (int)$company['completion'] ?>%</b></div><div class="progress-track"><i style="width:<?= (int)$company['completion'] ?>%"></i></div></div><dl><div><dt>Members</dt><dd><?= $users ?></dd></div><div><dt>Modules</dt><dd><?= count($company['modules']) ?></dd></div><div><dt>Data owner</dt><dd><?= h(data_user_name($company['data_owner_id'])) ?></dd></div><div><dt>Procurement owner</dt><dd><?= h(data_user_name($company['procurement_owner_id'])) ?></dd></div><div><dt>Accounting reviewer</dt><dd><?= h(data_user_name($company['accounting_reviewer_id'])) ?></dd></div><div><dt>Retention</dt><dd><?= number_format($company['retention_days']) ?> days</dd></div></dl><footer><?php if(can('companies.edit')): ?><a class="button secondary full" href="<?= h(app_url('admin/companies.php?edit='.(int)$company['id'])) ?>">Edit company</a><?php endif; ?></footer></article><?php endforeach; ?></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Cross-company governance</span><h2>Company owners and settings</h2></div><span class="panel-meta">Permitted Gruber companies</span></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Company</th><th>Contact</th><th>Data owner</th><th>Procurement owner</th><th>Accounting reviewer</th><th>Modules</th><th>Retention</th></tr></thead><tbody><?php foreach($companies as $company): ?><tr><td><strong><?= h($company['name']) ?></strong><small><?= h($company['code']) ?> · <?= badge($company['status']) ?></small></td><td><?= h($company['email']) ?><small><?= h($company['phone']) ?></small></td><td><?= h(data_user_name($company['data_owner_id'])) ?></td><td><?= h(data_user_name($company['procurement_owner_id'])) ?></td><td><?= h(data_user_name($company['accounting_reviewer_id'])) ?></td><td><div class="company-chip-row"><?php foreach($company['modules'] as $module): ?><span><?= h(strtoupper(substr($module,0,3))) ?></span><?php endforeach; ?></div></td><td><?= number_format($company['retention_days']) ?> days</td></tr><?php endforeach; ?></tbody></table></div></section>
<?php if($edit&&can('companies.edit')): ?><div class="modal" id="companyModal" data-auto-open="true"><div class="modal-backdrop" data-modal-close></div><section class="modal-card modal-card-wide"><header><div><span class="eyebrow">Company settings</span><h2><?= h($edit['name']) ?></h2></div><button type="button" data-modal-close>×</button></header><form class="modal-body form-grid" action="<?= h(app_url('action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_company"><input type="hidden" name="id" value="<?= (int)$edit['id'] ?>"><input type="hidden" name="return_to" value="admin/companies.php"><label><span>Company name</span><input name="name" value="<?= h($edit['name']) ?>" required></label><label><span>Company code</span><input name="code" value="<?= h($edit['code']) ?>" required></label><label class="span-2"><span>Industry / description</span><input name="industry" value="<?= h($edit['industry']) ?>"></label><label><span>Status</span><select name="status"><option value="active" <?= $edit['status']==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= $edit['status']==='inactive'?'selected':'' ?>>Inactive</option></select></label><label><span>Retention days</span><input type="number" name="retention_days" value="<?= (int)$edit['retention_days'] ?>"></label><label><span>Contact email</span><input type="email" name="email" value="<?= h($edit['email']) ?>"></label><label><span>Contact phone</span><input name="phone" value="<?= h($edit['phone']) ?>"></label><label><span>Data owner</span><select name="data_owner_id"><?= user_options($edit['data_owner_id']) ?></select></label><label><span>Procurement owner</span><select name="procurement_owner_id"><?= user_options($edit['procurement_owner_id']) ?></select></label><label class="span-2"><span>Accounting reviewer</span><select name="accounting_reviewer_id"><?= user_options($edit['accounting_reviewer_id']) ?></select></label><div class="span-2"><span class="field-label">Enabled modules</span><div class="checkbox-grid"><?php foreach(['discovery','suppliers','items','purchase_orders','inventory','savings','scorecards','imports'] as $module): ?><label class="check-card"><input type="checkbox" name="modules[]" value="<?= h($module) ?>" <?= in_array($module,$edit['modules'],true)?'checked':'' ?>><span><strong><?= h(status_label($module)) ?></strong><small>Company module</small></span></label><?php endforeach; ?></div></div><div class="span-2 modal-actions"><a class="button secondary" href="<?= h(app_url('admin/companies.php')) ?>">Cancel</a><button class="button primary" type="submit">Save company</button></div></form></section></div><?php endif; ?>
<?php render_app_end(); ?>
