<?php
declare(strict_types=1);
require_once dirname(__DIR__,2) . '/includes/app/bootstrap.php';
require_permission('platform.administer');
$metrics=data_admin_metrics();$security=array_slice(sort_records(data_collection('security_events'),'created_at','desc'),0,6);$audit=array_slice(data_collection('audit_events'),0,8);$env=environment_snapshot();
render_app_start('Admin Console','admin','Platform administration','Manage users, roles, companies, security, sessions, settings, environment health, and immutable audit history.','<a class="button secondary" href="'.h(app_url('admin/environment.php')).'">Environment Status</a><a class="button primary" href="'.h(app_url('admin/users.php')).'">Manage Users</a>');
?>
<section class="metric-grid metric-grid-6"><article class="metric-card"><span>Total users</span><strong><?= $metrics['total_users'] ?></strong><small><?= $metrics['active_users'] ?> active</small></article><article class="metric-card"><span>Suspended</span><strong><?= $metrics['suspended_users'] ?></strong><small>Administrative hold</small></article><article class="metric-card"><span>Access requests</span><strong><?= $metrics['pending_access_requests'] ?></strong><small>Pending review</small></article><article class="metric-card"><span>Active sessions</span><strong><?= $metrics['active_sessions'] ?></strong><small>Across active accounts</small></article><article class="metric-card"><span>Pending approvals</span><strong><?= $metrics['pending_approvals'] ?></strong><small>Operational workflows</small></article><article class="metric-card"><span>Audit events</span><strong><?= $metrics['audit_events'] ?></strong><small>Immutable presentation</small></article></section>
<div class="admin-status-grid"><a href="<?= h(app_url('admin/users.php')) ?>"><i>◉</i><span>Users<strong><?= $metrics['total_users'] ?></strong><small>Create, suspend, assign, restore</small></span></a><a href="<?= h(app_url('admin/roles.php')) ?>"><i>⌘</i><span>Roles<strong><?= $metrics['roles'] ?></strong><small>Permission matrix and membership</small></span></a><a href="<?= h(app_url('admin/companies.php')) ?>"><i>▦</i><span>Companies<strong><?= $metrics['companies'] ?></strong><small>Owners, modules, retention</small></span></a><a href="<?= h(app_url('admin/access-requests.php')) ?>"><i>＋</i><span>Access requests<strong><?= $metrics['pending_access_requests'] ?></strong><small>Approve or decline requests</small></span></a><a href="<?= h(app_url('admin/security.php')) ?>"><i>◆</i><span>Failed sign-ins<strong><?= $metrics['failed_sign_ins'] ?></strong><small>Policies and security events</small></span></a><a href="<?= h(app_url('admin/environment.php')) ?>"><i>●</i><span>Environment<strong><?= h($env['mode']) ?></strong><small>DB <?= h($env['database']) ?> · Config <?= h($env['config']) ?></small></span></a></div>
<div class="dashboard-grid"><section class="panel"><header class="panel-head"><div><span class="eyebrow">Security operations</span><h2>Recent security activity</h2></div><a href="<?= h(app_url('admin/security.php')) ?>">View security</a></header><div class="issue-list"><?php foreach($security as $event): ?><article><i class="<?= h(status_class($event['severity'])) ?>">!</i><div><strong><?= h(status_label($event['event'])) ?></strong><small><?= h($event['details']) ?> · <?= h($event['ip_address']) ?></small></div><time><?= h(date_us($event['created_at'],true)) ?></time></article><?php endforeach; ?></div></section><section class="panel"><header class="panel-head"><div><span class="eyebrow">Platform readiness</span><h2>Environment status</h2></div><a href="<?= h(app_url('admin/environment.php')) ?>">Full diagnostics</a></header><dl class="detail-list"><div><dt>Environment</dt><dd><?= badge(strtolower($env['mode'])) ?></dd></div><div><dt>Database</dt><dd><?= badge(strtolower($env['database'])) ?></dd></div><div><dt>Configuration</dt><dd><?= badge(strtolower($env['config'])) ?></dd></div><div><dt>Schema version</dt><dd><code><?= h($env['schema_version']) ?></code></dd></div><div><dt>Data completeness</dt><dd><?= $metrics['data_completeness'] ?>%</dd></div><div><dt>Setup method</dt><dd><?= badge(strtolower($env['setup'])) ?></dd></div></dl></section></div>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Immutable activity</span><h2>Recent audit events</h2></div><a href="<?= h(app_url('admin/audit.php')) ?>">Open Audit Log</a></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>User</th><th>Company</th><th>Module</th><th>Action</th><th>Entity</th><th>IP</th></tr></thead><tbody><?php foreach($audit as $event): ?><tr><td><?= h(date_us($event['created_at'],true)) ?></td><td><?= h(data_user_name($event['user_id'])) ?></td><td><?= h(data_company_name($event['company_id'])) ?></td><td><?= h($event['module']) ?></td><td><?= badge($event['action']) ?></td><td><?= h(status_label($event['entity_type'])) ?> #<?= h($event['entity_id']??'—') ?></td><td><code><?= h($event['ip_address']) ?></code></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php render_app_end(); ?>
