<?php
declare(strict_types=1);
require_once dirname(__DIR__,2) . '/includes/app/bootstrap.php';
require_permission('roles.view');
$roles=data_collection('roles');$visibleUsers=data_admin_visible_users();$editId=query_int('edit');$editRole=$editId?data_find('roles',$editId):null;$catalog=permission_catalog();
$actions=can('roles.create')?'<button class="button primary" data-modal-open="roleModal" type="button">Create Role</button>':'';
render_app_start('Roles & Permissions','admin-roles','Authorization administration','Create, edit, clone, and archive roles while protecting seeded system roles from deletion.',$actions);
?>
<section class="role-card-grid"><?php foreach($roles as $role): $members=count(array_filter($visibleUsers,fn($u)=>in_array($role['code'],$u['role_codes'],true))); ?><article class="role-card"><header><div><span><?= $role['system']?'SYSTEM ROLE':'CUSTOM ROLE' ?></span><h2><?= h($role['name']) ?></h2></div><?= badge($role['status']) ?></header><p><?= h($role['description']) ?></p><dl><div><dt>Code</dt><dd><code><?= h($role['code']) ?></code></dd></div><div><dt>Members</dt><dd><?= $members ?></dd></div><div><dt>Permissions</dt><dd><?= count($role['permissions']) ?></dd></div></dl><footer><?php if(can('roles.edit')): ?><a class="mini-button secondary" href="<?= h(app_url('admin/roles.php?edit='.(int)$role['id'])) ?>">Edit</a><?php endif; ?><?php if(can('roles.create')): ?><form action="<?= h(app_url('action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="clone_role"><input type="hidden" name="id" value="<?= (int)$role['id'] ?>"><input type="hidden" name="return_to" value="admin/roles.php"><button class="mini-button ghost" type="submit">Clone</button></form><?php endif; ?><?php if(can('roles.delete')&&!$role['system']&&$role['status']==='active'): ?><form action="<?= h(app_url('action.php')) ?>" method="post" data-confirm="Archive this custom role?"><?= csrf_field() ?><input type="hidden" name="action" value="archive_role"><input type="hidden" name="id" value="<?= (int)$role['id'] ?>"><input type="hidden" name="return_to" value="admin/roles.php"><button class="mini-button danger" type="submit">Archive</button></form><?php endif; ?></footer></article><?php endforeach; ?></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Effective access model</span><h2>Permission matrix</h2></div><span class="panel-meta"><?= count(all_permissions()) ?> permissions</span></header><div class="permission-matrix-wrap"><table class="permission-matrix"><thead><tr><th>Area / action</th><?php foreach($roles as $role): ?><th title="<?= h($role['name']) ?>"><?= h($role['name']) ?><small><?= h($role['code']) ?></small></th><?php endforeach; ?></tr></thead><tbody><?php foreach($catalog as $area=>$actionsList): foreach($actionsList as $action): $permission=$area.'.'.$action; ?><tr><td><strong><?= h(status_label($area)) ?></strong><small><?= h(status_label($action)) ?></small></td><?php foreach($roles as $role): ?><td><span class="matrix-check <?= in_array($permission,$role['permissions'],true)?'yes':'no' ?>"><?= in_array($permission,$role['permissions'],true)?'✓':'—' ?></span></td><?php endforeach; ?></tr><?php endforeach; endforeach; ?></tbody></table></div></section>
<?php if(can('roles.create')||$editRole): $model=$editRole??['id'=>null,'code'=>'','name'=>'','description'=>'','status'=>'active','permissions'=>[],'system'=>false]; ?><div class="modal" id="roleModal" <?= $editRole?'data-auto-open="true"':'hidden' ?>><div class="modal-backdrop" data-modal-close></div><section class="modal-card modal-card-wide"><header><div><span class="eyebrow"><?= $editRole?'Edit role':'New custom role' ?></span><h2><?= h($editRole?$editRole['name']:'Create role') ?></h2></div><button type="button" data-modal-close>×</button></header><form class="modal-body" action="<?= h(app_url('action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_role"><input type="hidden" name="id" value="<?= h($model['id']??'') ?>"><input type="hidden" name="return_to" value="admin/roles.php"><div class="form-grid"><label><span>Role name</span><input name="name" value="<?= h($model['name']) ?>" required></label><label><span>Role code</span><input name="code" value="<?= h($model['code']) ?>" <?= !empty($model['system'])?'readonly':'' ?> required></label><label class="span-2"><span>Description</span><textarea name="description" rows="3"><?= h($model['description']) ?></textarea></label><label class="span-2"><span>Status</span><select name="status"><option value="active" <?= $model['status']==='active'?'selected':'' ?>>Active</option><option value="archived" <?= $model['status']==='archived'?'selected':'' ?>>Archived</option></select></label></div><div class="permission-editor"><?php foreach($catalog as $area=>$actionsList): ?><fieldset><legend><?= h(status_label($area)) ?></legend><div><?php foreach($actionsList as $action): $permission=$area.'.'.$action; ?><label><input type="checkbox" name="permissions[]" value="<?= h($permission) ?>" <?= in_array($permission,$model['permissions'],true)?'checked':'' ?>><span><?= h(status_label($action)) ?></span></label><?php endforeach; ?></div></fieldset><?php endforeach; ?></div><div class="modal-actions"><a class="button secondary" href="<?= h(app_url('admin/roles.php')) ?>">Cancel</a><button class="button primary" type="submit">Save role</button></div></form></section></div><?php endif; ?>
<?php render_app_end(); ?>
