<?php
declare(strict_types=1);
require_once dirname(__DIR__,2) . '/includes/app/bootstrap.php';
require_permission('security.view');
$sessions=sort_records(data_collection('sessions'),'last_activity','desc');
$actions=can('security.administer')?'<form action="'.h(app_url('action.php')).'" method="post" data-confirm="Revoke every other active session in this environment?">'.csrf_field().'<input type="hidden" name="action" value="revoke_other_sessions"><input type="hidden" name="return_to" value="admin/sessions.php"><button class="button danger" type="submit">Revoke All Other Sessions</button></form>':'';
render_app_start('Session Management','admin-sessions','Security administration','Review active sessions, devices, IP addresses, activity, expiration, and revocation controls.',$actions);
?>
<section class="metric-grid metric-grid-4"><article class="metric-card"><span>Total sessions</span><strong><?= count($sessions) ?></strong><small>Sample session history</small></article><article class="metric-card"><span>Active</span><strong><?= count(array_filter($sessions,fn($s)=>$s['status']==='active')) ?></strong><small>Not expired or revoked</small></article><article class="metric-card"><span>Expired</span><strong><?= count(array_filter($sessions,fn($s)=>$s['status']==='expired')) ?></strong><small>Lifetime reached</small></article><article class="metric-card"><span>Revoked</span><strong><?= count(array_filter($sessions,fn($s)=>$s['status']==='revoked')) ?></strong><small>Administrator action</small></article></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Active-session inventory</span><h2>Browser and device sessions</h2></div><span class="panel-meta">Current session protected</span></header><div class="table-wrap"><table class="data-table"><thead><tr><th>User</th><th>IP address</th><th>Browser / device</th><th>Started</th><th>Last activity</th><th>Expiration</th><th>Status</th><th>Control</th></tr></thead><tbody><?php foreach($sessions as $session): ?><tr><td><strong><?= h(data_user_name($session['user_id'])) ?></strong><?php if($session['current']): ?><small><?= badge('current','Current session') ?></small><?php endif; ?></td><td><code><?= h($session['ip_address']) ?></code></td><td><?= h($session['device']) ?></td><td><?= h(date_us($session['started_at'],true)) ?></td><td><?= h(date_us($session['last_activity'],true)) ?></td><td><?= h(date_us($session['expires_at'],true)) ?></td><td><?= badge($session['status']) ?></td><td><?php if(can('security.administer')&&!$session['current']&&$session['status']==='active'): ?><form action="<?= h(app_url('action.php')) ?>" method="post" data-confirm="Revoke this session?"><?= csrf_field() ?><input type="hidden" name="action" value="revoke_session"><input type="hidden" name="id" value="<?= h((string)$session['id']) ?>"><input type="hidden" name="return_to" value="admin/sessions.php"><button class="mini-button danger" type="submit">Revoke</button></form><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php render_app_end(); ?>
