<?php
declare(strict_types=1);
require_once dirname(__DIR__,2) . '/includes/app/bootstrap.php';
require_permission('settings.administer');
$settings=data_settings();
render_app_start('Platform Settings','admin-settings','Platform administration','Configure naming, support, formatting, import limits, uploads, notification defaults, approvals, retention, Demo Mode, maintenance, and Agent Workspace access.','');
?>
<form class="platform-settings-grid" action="<?= h(app_url('action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_platform_settings"><input type="hidden" name="return_to" value="admin/settings.php">
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Platform identity</span><h2>General settings</h2></div></header><div class="settings-form"><label><span>Platform name</span><input name="platform_name" value="<?= h($settings['platform_name']) ?>" maxlength="120" required></label><label><span>Support contact</span><input type="email" name="support_contact" value="<?= h($settings['support_contact']) ?>"></label><label><span>Default timezone</span><select name="default_timezone"><option value="America/Phoenix" selected>America/Phoenix</option><option value="UTC">UTC</option></select></label><label><span>Date formatting</span><select name="date_format"><option value="M j, Y" selected>Jul 25, 2026</option><option value="m/d/Y">07/25/2026</option></select></label><label><span>Currency</span><select name="currency"><option value="USD" selected>USD · U.S. Dollar</option></select></label><label><span>Email sender</span><input type="email" name="email_sender" value="<?= h($settings['email_sender']) ?>"></label></div></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Data controls</span><h2>Imports, uploads, and retention</h2></div></header><div class="settings-form"><label><span>Import row limit</span><input type="number" name="import_row_limit" value="<?= (int)$settings['import_row_limit'] ?>" min="100" max="1000000" required></label><label><span>Upload limit (MB)</span><input type="number" name="upload_limit_mb" value="<?= (int)$settings['upload_limit_mb'] ?>" min="1" max="100" required></label><label><span>Allowed file types</span><input name="allowed_file_types" value="<?= h(implode(', ',$settings['allowed_file_types'])) ?>"><small>Comma-separated.</small></label><label><span>Data retention (days)</span><input type="number" name="data_retention_days" value="<?= (int)$settings['data_retention_days'] ?>" min="30" max="36500" required></label><div class="settings-summary-box"><span>Approval thresholds</span><strong>PO over <?= money($settings['approval_requirements']['po_over']) ?></strong><small>Savings over <?= money($settings['approval_requirements']['savings_over']) ?></small></div><div class="settings-summary-box"><span>Notification defaults</span><strong>In-app enabled</strong><small>Email delivery requires an external mail service; no password is emailed by this application.</small></div></div></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Environment behavior</span><h2>Availability and maintenance</h2></div></header><div class="settings-form"><label class="toggle-row"><span><strong>Demo Mode availability</strong><small>Allow intentional database-free review access.</small></span><input type="checkbox" name="demo_mode_available" <?= $settings['demo_mode_available']?'checked':'' ?>></label><label class="toggle-row"><span><strong>Maintenance Mode</strong><small>Show a maintenance state for production users.</small></span><input type="checkbox" name="maintenance_mode" <?= $settings['maintenance_mode']?'checked':'' ?>></label><label class="toggle-row"><span><strong>Agent Workspace access</strong><small>Make supervised agents available to permitted roles.</small></span><input type="checkbox" name="agent_workspace_access" <?= $settings['agent_workspace_access']?'checked':'' ?>></label><label class="toggle-row"><span><strong>Approved-data-only Agent mode</strong><small>Restrict agent answers to reviewed evidence.</small></span><input type="checkbox" name="approved_data_only_agent" <?= $settings['approved_data_only_agent']?'checked':'' ?>></label></div></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Review summary</span><h2>Current platform policy</h2></div></header><dl class="detail-list"><div><dt>Session lifetime</dt><dd><?= (int)$settings['session_lifetime'] ?> minutes</dd></div><div><dt>Password reset</dt><dd><?= (int)$settings['password_reset_lifetime'] ?> minutes</dd></div><div><dt>Strong password minimum</dt><dd><?= (int)$settings['password_min_length'] ?> characters</dd></div><div><dt>Demo persistence</dt><dd>PHP session storage</dd></div><div><dt>Agent guardrail</dt><dd><?= $settings['approved_data_only_agent']?'Approved data only':'Broader context allowed' ?></dd></div><div><dt>Currency formatting</dt><dd>USD · U.S. standard</dd></div></dl><button class="button primary full" type="submit">Save platform settings</button></section>
</form>
<?php render_app_end(); ?>
