<?php
declare(strict_types=1);
$root=dirname(__DIR__);$_SERVER['SCRIPT_NAME']='/gruber/app/knowledge-adoption.php';$_SERVER['REQUEST_METHOD']='GET';$_SERVER['REMOTE_ADDR']='127.0.0.1';$_SERVER['HTTP_USER_AGENT']='Section 30 quality test';require $root.'/includes/app/bootstrap.php';if(!demo_start_session(1)){fwrite(STDERR,"Could not start demo session.\n");exit(1);}require_once $root.'/includes/app/knowledge_adoption_governance.php';$_SESSION['gruber_demo_state']=[];
function s30(bool$condition,string$message):void{if(!$condition){fwrite(STDERR,"Section 30 failure: {$message}\n");exit(1);}}
function s30_user(int$id,int|string$company='enterprise'):void{$_SESSION['gruber_demo_user_id']=$id;$_SESSION['gruber_demo_company_id']=$company;}
function s30_throws(callable$callback,string$message):void{try{$callback();s30(false,$message);}catch(RuntimeException){}}

s30(knowledge_adoption_tables_ready(),'Demo mode must report Section 30 tables ready.');
s30(count(knowledge_adoption_tables())===10,'Section 30 must define ten governed knowledge and adoption tables.');
s30(count(permission_catalog()['knowledge_adoption']??[])===13,'Section 30 must expose thirteen dedicated permissions.');
s30(count(knowledge_documents())>=2&&count(knowledge_versions())>=2,'Demo mode must seed policy documents and versions.');
$seed=knowledge_find_version(1);s30($seed!==null&&$seed['status']==='published'&&!empty($seed['locked_at'])&&strlen((string)$seed['content_hash'])===64,'Demo mode must include an immutable published policy version.');

s30_user(5,2);s30(knowledge_find_document(2)!==null,'Company-two administrator must resolve the company-two SOP.');s30(knowledge_find_document(1)===null,'Company-two users must not resolve sibling-company policy documents by forged ID.');$beforeVersions=count(knowledge_versions());s30_throws(static fn()=>knowledge_save_version(['id'=>null,'document_id'=>2,'version_number'=>'0.2','status'=>'draft','effective_from'=>date('Y-m-d'),'effective_to'=>null,'content'=>'Forged sibling initiative binding.','change_summary'=>'Must fail before persistence.','content_hash'=>'','source_initiative_id'=>2,'process_id'=>1,'process_version_id'=>1,'process_step_id'=>1,'prepared_by'=>5,'reviewed_by'=>3,'approved_by'=>2,'review_note'=>'','approval_note'=>'','submitted_at'=>null,'reviewed_at'=>null,'published_at'=>null,'locked_at'=>null]),'Company-two policy must reject sibling-company initiative or process evidence.');s30(count(knowledge_versions())===$beforeVersions,'Rejected policy version must not leave a partial record.');

s30_user(1,'enterprise');$initiative=strategy_find_initiative(2);s30($initiative!==null,'Section 29 source initiative is required.');if($initiative['stage']==='business_case'){$gate=strategy_prepare_gate(2,'reviewed','Section 30 source initiative business case evidence.');s30_user(3,'enterprise');strategy_review_gate((int)$gate['id'],'Independent review for Section 30 source initiative.');s30_user(6,'enterprise');strategy_approve_gate((int)$gate['id'],'Approved reviewed stage for Section 30 source initiative.');s30_user(1,'enterprise');$gate=strategy_prepare_gate(2,'approved','Section 30 source initiative approval evidence.');s30_user(3,'enterprise');strategy_review_gate((int)$gate['id'],'Independent approval-stage review.');s30_user(6,'enterprise');strategy_approve_gate((int)$gate['id'],'Approved initiative for policy and adoption work.');}
s30_user(1,'enterprise');s30(strategy_find_initiative(2)['stage']==='approved','Section 30 source initiative must be independently approved.');

$document=knowledge_save_document(['id'=>null,'document_number'=>'POL-S30-TEST','title'=>'Controlled Process Adoption Policy','document_type'=>'policy','entity_id'=>101,'company_id'=>null,'owner_user_id'=>1,'reviewer_user_id'=>3,'approver_user_id'=>6,'purpose'=>'Validate the complete Section 30 strategy, process, policy, training, waiver, adoption and evidence chain.','status'=>'draft','current_version_id'=>null,'created_by'=>1]);
$process=process_mapping_find_process(1);$processVersion=$process?process_mapping_process_version($process):null;s30($process!==null&&$processVersion!==null,'Published process and active version fixtures are required.');
$version1=knowledge_save_version(['id'=>null,'document_id'=>$document['id'],'version_number'=>'1.0','status'=>'draft','effective_from'=>date('Y-m-d'),'effective_to'=>null,'content'=>'Version one requires controlled training and independent competency validation.','change_summary'=>'Initial controlled adoption version.','content_hash'=>'','source_initiative_id'=>2,'process_id'=>1,'process_version_id'=>$processVersion['id'],'process_step_id'=>1,'prepared_by'=>1,'reviewed_by'=>3,'approved_by'=>6,'review_note'=>'','approval_note'=>'','submitted_at'=>null,'reviewed_at'=>null,'published_at'=>null,'locked_at'=>null]);s30(strlen((string)$version1['content_hash'])===64,'Draft policy version must receive a deterministic content hash.');
$version1=knowledge_submit_version((int)$version1['id'],'Submission includes source initiative, process, step and change evidence.');s30_throws(static fn()=>knowledge_publish_governed_version((int)$version1['id'],'Invalid direct publication.'),'Policy publication must reject versions without independent review.');s30_user(3,'enterprise');$version1=knowledge_review_version((int)$version1['id'],'Independent reviewer confirmed policy content, process alignment and controls.');s30_user(6,'enterprise');$version1=knowledge_publish_governed_version((int)$version1['id'],'Approved version one for controlled publication.');s30($version1['status']==='published'&&!empty($version1['locked_at']),'Reviewed version must publish and lock.');$version1Content=$version1['content'];$version1Hash=$version1['content_hash'];

s30_user(1,'enterprise');$version2=knowledge_save_version(['id'=>null,'document_id'=>$document['id'],'version_number'=>'2.0','status'=>'draft','effective_from'=>date('Y-m-d',strtotime('+1 day')),'effective_to'=>null,'content'=>'Version two adds waiver expiration, compensating controls, adoption snapshots and evidence manifests.','change_summary'=>'Add governed exception, adoption and evidence controls.','content_hash'=>'','source_initiative_id'=>2,'process_id'=>1,'process_version_id'=>$processVersion['id'],'process_step_id'=>1,'prepared_by'=>1,'reviewed_by'=>3,'approved_by'=>6,'review_note'=>'','approval_note'=>'','submitted_at'=>null,'reviewed_at'=>null,'published_at'=>null,'locked_at'=>null]);knowledge_submit_version((int)$version2['id'],'Version two submission evidence.');s30_user(3,'enterprise');knowledge_review_version((int)$version2['id'],'Version two independently reviewed.');s30_user(6,'enterprise');$version2=knowledge_publish_governed_version((int)$version2['id'],'Version two approved and effective.');$prior=knowledge_find_version((int)$version1['id']);s30($prior!==null&&$prior['status']==='superseded'&&$prior['content']===$version1Content&&$prior['content_hash']===$version1Hash&&!empty($prior['effective_to']),'Supersession must close the prior effective period without mutating locked content or hash.');s30(knowledge_find_document((int)$document['id'])['current_version_id']===$version2['id'],'Published version must become the document current version.');

s30_user(1,'enterprise');$campaignRecord=['id'=>null,'campaign_number'=>'CAM-S30-EARLY','version_id'=>$version2['id'],'entity_id'=>101,'company_id'=>0,'campaign_name'=>'Early launch must fail','delivery_mode'=>'self_paced','required_score'=>80,'due_at'=>date('Y-m-d H:i:s',strtotime('+21 days')),'renewal_days'=>365,'status'=>'active','owner_user_id'=>1,'reviewer_user_id'=>3,'approver_user_id'=>6,'evidence_note'=>'Missing approved impact.','source_key'=>hash('sha256','s30-early'),'published_at'=>date('Y-m-d H:i:s'),'closed_at'=>null];s30_throws(static fn()=>knowledge_create_governed_campaign($campaignRecord),'Training campaign must reject launch without approved impact evidence.');
$impact=knowledge_save_impact(['id'=>null,'version_id'=>$version2['id'],'initiative_id'=>2,'process_id'=>1,'process_step_id'=>1,'entity_id'=>101,'company_id'=>0,'role_code'=>'data_contributor','system_code'=>'gruber','impact_level'=>'high','impact_description'=>'Affected contributors must use the version-two controls.','required_action'=>'Complete training, pass the competency check, attest, and follow the published workflow.','status'=>'prepared','prepared_by'=>1,'reviewed_by'=>3,'approved_by'=>6,'review_note'=>'','approval_note'=>'','reviewed_at'=>null,'approved_at'=>null,'locked_at'=>null]);s30_user(3,'enterprise');knowledge_review_impact((int)$impact['id'],'Impact independently reviewed against the active process and initiative.');s30_user(6,'enterprise');$impact=knowledge_approve_impact((int)$impact['id'],'Impact approved for role-targeted training.');s30($impact['status']==='approved'&&!empty($impact['locked_at']),'Approved change impacts must be locked.');

s30_user(1,'enterprise');$campaignRecord['campaign_number']='CAM-S30-TEST';$campaignRecord['campaign_name']='Controlled Process Adoption — Certification';$campaignRecord['evidence_note']='Approved impact supports training deployment.';$campaignRecord['source_key']=hash('sha256','s30-campaign');$campaign=knowledge_create_governed_campaign($campaignRecord);s30((int)$campaign['company_id']===1&&$campaign['status']==='active','Campaign must derive company scope from its target entity.');$assignment=knowledge_assign_training((int)$campaign['id'],4,'data_contributor',3,true);$replay=knowledge_assign_training((int)$campaign['id'],4,'data_contributor',3,true);s30((int)$assignment['id']===(int)$replay['id'],'Training assignment must be replay-safe.');s30(!empty($assignment['work_item_id'])&&!empty($assignment['calendar_event_id']),'Training assignment must create Section 26 work and a Section 27 calendar event.');$work=work_management_find_item((int)$assignment['work_item_id']);$event=operational_calendar_find_event((int)$assignment['calendar_event_id']);s30($work!==null&&$work['source_module']==='knowledge_adoption','Training work must retain Section 30 source identity.');s30($event!==null&&$event['source_module']==='knowledge_adoption','Training deadline must be immediately visible in Section 27.');s30(!empty($assignment['process_instance_id'])&&!empty($assignment['step_instance_id']),'Training assignment must preserve active Section 25 runtime references when available.');

s30_user(4,1);knowledge_submit_attestation((int)$assignment['id'],'I read and understand the exact published version assigned to me.',92,'Completed the competency scenario using the governed process step.');$attestation=knowledge_attestations((int)$assignment['id'])[0]??null;s30($attestation!==null&&$attestation['status']==='submitted'&&hash_equals((string)$version2['content_hash'],(string)$attestation['policy_hash']),'Learner attestation must bind to the exact published policy hash.');s30_user(3,1);$attestation=knowledge_validate_governed_attestation((int)$attestation['id'],'Independent validator confirmed the learner applied the required controls.');s30($attestation['status']==='validated'&&!empty($attestation['locked_at']),'Competency validation must lock the attestation.');$completed=knowledge_find_assignment((int)$assignment['id']);s30($completed['status']==='completed'&&!empty($completed['completed_at'])&&!empty($completed['renewal_due_at']),'Validated competency must complete the assignment and schedule renewal.');s30_throws(static function()use($attestation):void{$copy=$attestation;$copy['quiz_score']=99;knowledge_save_attestation($copy);},'Validated attestations must be immutable.');

s30_user(1,'enterprise');$waiverAssignment=knowledge_assign_training((int)$campaign['id'],2,'executive',3,false);s30_user(2,'enterprise');$waiver=knowledge_request_waiver((int)$waiverAssignment['id'],'Temporary system-access constraint prevents completion before the campaign deadline.','Manager-supervised execution with daily evidence review until access is restored.',3,6,date('Y-m-d H:i:s',strtotime('+30 days')));s30_throws(static fn()=>knowledge_approve_waiver((int)$waiver['id'],'Invalid direct approval.'),'Waiver must reject approval before independent review.');s30_user(3,'enterprise');knowledge_review_waiver((int)$waiver['id'],'Reviewer confirmed the compensating control and limited duration.');s30_user(6,'enterprise');$waiver=knowledge_approve_waiver((int)$waiver['id'],'Approved for thirty days with no automatic extension.');s30($waiver['status']==='approved'&&!empty($waiver['locked_at']),'Approved waiver must be time-limited and locked.');s30(knowledge_find_assignment((int)$waiverAssignment['id'])['status']==='waived','Approved waiver must update the governed assignment state.');

s30_user(1,'enterprise');$snapshot=knowledge_snapshot_adoption((int)$campaign['id'],'Certification snapshot after competency validation and waiver approval.');$snapshotReplay=knowledge_snapshot_adoption((int)$campaign['id'],'Replay');s30((int)$snapshot['id']===(int)$snapshotReplay['id'],'Adoption snapshots must be replay-safe.');s30(!empty($snapshot['locked_at'])&&(float)$snapshot['adoption_rate']>0,'Adoption snapshot must be immutable and measured.');$manifest=knowledge_generate_governed_manifest((int)$version2['id'],'Certification evidence package.');$manifestReplay=knowledge_generate_governed_manifest((int)$version2['id'],'Certification evidence package.');s30((int)$manifest['id']===(int)$manifestReplay['id']&&strlen((string)$manifest['manifest_hash'])===64&&!empty($manifest['locked_at']),'Evidence manifest must be replay-safe, hash-locked, and immutable.');

$workspace=knowledge_agent_extend_workspace(strategy_agent_extend_workspace(executive_intelligence_agent_extend_workspace(operational_calendar_agent_extend_workspace(work_management_agent_extend_workspace(['prompts'=>[],'lookups'=>[],'metrics'=>[],'briefing'=>['priorities'=>[]]])))));s30(($workspace['prompts'][0]['response_title']??'')==='Knowledge & Adoption Agent','Agent Workspace must lead with Section 30 knowledge and adoption intelligence.');foreach(['knowledge_documents','knowledge_published_versions','knowledge_campaigns','knowledge_assignments','knowledge_overdue','knowledge_open_waivers','knowledge_adoption_rate']as$key)s30(array_key_exists($key,$workspace['metrics']),'Agent Workspace metric '.$key.' must be available.');
$migration=file_get_contents($root.'/database/20260727_section30_policy_sop_knowledge_adoption.sql');foreach(knowledge_adoption_tables()as$table)s30(str_contains($migration,'CREATE TABLE IF NOT EXISTS '.$table),'Migration must create '.$table.'.');s30(str_contains($migration,"'5.9-section30'")&&str_contains($migration,"'knowledge_adoption.assign_training'")&&str_contains($migration,"'knowledge_adoption.attest'"),'Migration must record Section 30 and its training and attestation permissions.');s30(str_contains($migration,'content_hash CHAR(64) NOT NULL')&&str_contains($migration,'work_item_id BIGINT UNSIGNED NULL')&&str_contains($migration,'calendar_event_id BIGINT UNSIGNED NULL')&&str_contains($migration,'manifest_hash CHAR(64) NOT NULL UNIQUE'),'Migration must persist policy hashes, work, calendar and evidence-manifest references.');
$action=file_get_contents($root.'/app/knowledge-adoption-action.php');foreach(['verify_csrf','knowledge_publish_governed_version','knowledge_create_governed_campaign','knowledge_assign_training','knowledge_validate_governed_attestation','knowledge_generate_governed_manifest']as$needle)s30(str_contains($action,$needle),'Section 30 action boundary must use '.$needle.'.');
echo "Section 30 policy, SOP, process impact, training, attestations, waivers, adoption, evidence, Agent and isolation tests passed.\n";
