<?php
declare(strict_types=1);
$root=dirname(__DIR__);
$_SERVER['SCRIPT_NAME']='/gruber/app/process-maps.php';$_SERVER['REQUEST_METHOD']='GET';$_SERVER['REMOTE_ADDR']='127.0.0.1';$_SERVER['HTTP_USER_AGENT']='Section 25 quality test';
require $root.'/includes/app/bootstrap.php';
if(!demo_start_session(1)){fwrite(STDERR,"Could not start demo session.\n");exit(1);}require_once $root.'/includes/app/process_mapping.php';
function s25(bool$c,string$m):void{if(!$c){fwrite(STDERR,"Section 25 failure: {$m}\n");exit(1);}}
function s25_user(int$id):void{$_SESSION['gruber_demo_user_id']=$id;}
s25(process_mapping_tables_ready(),'Demo mode must report process tables ready.');s25(count(process_mapping_tables())===12,'Section 25 must govern twelve supplemental process tables.');
$catalog=process_mapping_template_catalog();s25(count($catalog)===9,'Nine process templates are required.');foreach(array_keys($catalog)as$code){$preview=process_mapping_template_preview($code);s25($preview['valid'],'Template '.$code.' must validate.');s25($preview['lane_count']>=4,'Template '.$code.' must contain cross-functional swimlanes.');s25($preview['step_count']>=6,'Template '.$code.' must contain an operating workflow.');}
$processes=process_mapping_processes();s25(count($processes)===9,'Demo catalog must seed nine visual process maps.');$model=process_mapping_map_model(1,1);s25(count($model['lanes'])===5,'Procure-to-pay must contain five swimlanes.');s25(count($model['steps'])===14,'Procure-to-pay must contain fourteen governed steps.');s25(count($model['transitions'])===14,'Procure-to-pay must retain normal and exception transitions.');foreach($model['steps']as$step){s25((int)$step['position_x']>0&&(int)$step['position_y']>0,'Every visual step requires stored coordinates.');s25($step['canonical_record_type']!=='','Every step must identify its canonical record domain.');}
ob_start();process_mapping_render_svg($model,false);$svg=(string)ob_get_clean();foreach(['<svg','process-lane','process-node','processArrow','data-step-id','Live process view']as$needle)s25(str_contains($svg,$needle),'Visual process map is missing '.$needle.'.');
$copy=process_mapping_create_from_template('procure_to_pay','Template reviewed against Section 24 entities, shared services, permissions, controls, and integrations.',3,6);s25($copy['status']==='draft','A governed template copy must begin as draft.');$version=process_mapping_process_version($copy);s25($version!==null&&$version['status']==='draft','The copied version must remain editable until publication.');$draftSteps=process_mapping_steps((int)$version['id']);$first=$draftSteps[0];process_mapping_save_layout((int)$version['id'],[(string)$first['id']=>['x'=>260,'y'=>90]],'Visual layout reviewed and repositioned.');s25((int)process_mapping_find_step((int)$first['id'])['position_x']===260,'Draft visual coordinates must persist.');$version=process_mapping_publish_version($version,'Independent review and approval completed; visual process version locked.');s25($version['status']==='published'&&!empty($version['locked_at']),'Published process versions must lock permanently.');try{process_mapping_save_layout((int)$version['id'],[(string)$first['id']=>['x'=>300,'y'=>100]],'Attempt to change published layout.');s25(false,'Published layouts must be immutable.');}catch(RuntimeException){}
$instance=process_mapping_start_instance(1,102,'purchase_order',2,'Section 25 live process test','Canonical purchase order linked to the process instance.');s25($instance['status']==='in_progress','A live process instance must start in progress.');$active=array_values(array_filter(process_mapping_step_instances((int)$instance['id']),fn($r)=>$r['status']==='active'));s25(count($active)===1,'Exactly one process step must be active at startup.');$instance=process_mapping_advance_step((int)$active[0]['id'],'complete','Start event confirmed.');$active=array_values(array_filter(process_mapping_step_instances((int)$instance['id']),fn($r)=>$r['status']==='active'));s25(count($active)===1,'The default transition must activate the next step.');$exception=process_mapping_open_exception((int)$active[0]['id'],'missing_evidence','high','Required purchase-request evidence was incomplete.',3);s25($exception['status']==='open','A process exception must open under separate ownership and review.');s25_user(3);$exception=process_mapping_resolve_exception((int)$exception['id'],'Independent reviewer confirmed corrected evidence and cleared the block.');s25($exception['status']==='resolved','Only the assigned reviewer must resolve the exception.');s25_user(1);
$metrics=process_mapping_metrics();s25(array_key_exists('touchless_percent',$metrics)&&array_key_exists('overdue_steps',$metrics),'Process metrics must expose automation and overdue intelligence.');$analytics=process_mapping_analytics();s25(isset($analytics['by_process'],$analytics['bottlenecks']),'Process analytics must include process and bottleneck views.');s25(count(process_mapping_events())>=4,'Immutable process events must accumulate.');
$migration=file_get_contents($root.'/database/20260727_section25_process_mapping_orchestration_control_intelligence.sql');foreach(process_mapping_tables()as$table)s25(str_contains($migration,'CREATE TABLE IF NOT EXISTS '.$table),'Migration must create '.$table.'.');s25(str_contains($migration,"'5.4-section25'"),'Migration version must be recorded.');s25(str_contains($migration,"'process_mapping.view'"),'Dedicated process permissions must be seeded.');s25(str_contains($migration,"'PROC-P2P'"),'Production migration must seed the visual procure-to-pay reference process.');
$js=file_get_contents($root.'/app/assets/js/process-maps.js');foreach(['requestFullscreen','viewBox','pointerdown','data-layout-json']as$needle)s25(str_contains($js,$needle),'Visual interaction script is missing '.$needle.'.');$action=file_get_contents($root.'/app/process-maps-action.php');s25(str_contains($action,"require_permission('companies.administer')"),'Process mutations require governed administration permission.');s25(str_contains($action,"open_exception"),'Process exception actions must be available.');
echo "Section 25 visual process mapping, orchestration, controls, live tracking, and intelligence tests passed.\n";
