<?php
declare(strict_types=1);
$root=dirname(__DIR__);$_SERVER['SCRIPT_NAME']='/gruber/app/strategy-portfolio.php';$_SERVER['REQUEST_METHOD']='GET';$_SERVER['REMOTE_ADDR']='127.0.0.1';$_SERVER['HTTP_USER_AGENT']='Section 29 quality test';require $root.'/includes/app/bootstrap.php';if(!demo_start_session(1)){fwrite(STDERR,"Could not start demo session.\n");exit(1);}require_once $root.'/includes/app/strategy_portfolio_security.php';
function s29(bool$condition,string$message):void{if(!$condition){fwrite(STDERR,"Section 29 failure: {$message}\n");exit(1);}}
function s29_user(int$id,int|string$company='enterprise'):void{$_SESSION['gruber_demo_user_id']=$id;$_SESSION['gruber_demo_company_id']=$company;}
function s29_throws(callable$callback,string$message):void{try{$callback();s29(false,$message);}catch(RuntimeException){}}

s29(strategy_portfolio_tables_ready(),'Demo mode must report Section 29 tables ready.');
s29(count(strategy_portfolio_tables())===9,'Section 29 must define nine governed strategy-portfolio tables.');
s29(count(permission_catalog()['portfolio_intelligence']??[])===10,'Section 29 must expose ten dedicated application permissions.');
s29(count(strategy_portfolios())>=1&&count(strategy_initiatives())>=2,'Demo mode must seed a portfolio and strategic initiatives.');
$processInitiative=strategy_find_initiative(2);s29($processInitiative!==null,'A process-bound demo initiative is required.');$process=process_mapping_find_process((int)$processInitiative['process_id']);$step=process_mapping_find_step((int)$processInitiative['process_step_id']);$version=$process?process_mapping_process_version($process):null;s29($process!==null&&$process['status']==='published'&&$version!==null&&$step!==null&&(int)$step['version_id']===(int)$version['id'],'Initiatives must resolve to the active published Section 25 process and step.');
$companyOneKpi=null;$companyTwoKpi=null;foreach(executive_intelligence_kpi_definitions()as$definition){if((int)($definition['company_id']??0)===1)$companyOneKpi=$definition;if((int)($definition['company_id']??0)===2)$companyTwoKpi=$definition;}s29($companyOneKpi!==null&&$companyTwoKpi!==null,'Company-scoped KPI fixtures are required for Section 29 isolation tests.');

$portfolioOne=strategy_save_portfolio(['id'=>null,'portfolio_number'=>'PORT-S29-C1','portfolio_name'=>'Company One Transformation Portfolio','portfolio_type'=>'procurement_transformation','entity_id'=>101,'company_id'=>1,'fiscal_year'=>(int)date('Y'),'funding_limit'=>250000,'capacity_limit_hours'=>1800,'strategic_theme'=>'Company-one portfolio for governed stage, process, work, calendar, funding, and benefit tests.','status'=>'draft','owner_user_id'=>4,'reviewer_user_id'=>3,'approver_user_id'=>6,'evidence_note'=>'Company one portfolio evidence.','published_at'=>null,'locked_at'=>null,'created_by'=>1]);
$companyOneInitiative=strategy_create_governed_initiative(['id'=>null,'initiative_number'=>'INIT-S29-C1','portfolio_id'=>$portfolioOne['id'],'parent_initiative_id'=>null,'entity_id'=>101,'company_id'=>1,'initiative_name'=>'Company One controlled process initiative','description'=>'Validate the complete strategy-to-process-to-execution-to-benefit chain.','initiative_type'=>'process_automation','stage'=>'idea','health'=>'not_started','strategic_alignment_score'=>92,'value_score'=>88,'urgency_score'=>82,'risk_score'=>65,'confidence_pct'=>72,'proposed_cost'=>50000,'forecast_cost'=>50000,'actual_cost'=>0,'expected_annual_benefit'=>95000,'realized_benefit'=>0,'capacity_demand_hours'=>420,'start_date'=>date('Y-m-d'),'target_date'=>date('Y-m-d',strtotime('+90 days')),'owner_user_id'=>4,'sponsor_user_id'=>1,'reviewer_user_id'=>3,'approver_user_id'=>6,'benefit_validator_user_id'=>2,'primary_goal_id'=>null,'primary_kpi_definition_id'=>$companyOneKpi['id'],'process_id'=>1,'process_step_id'=>1,'budget_envelope_id'=>null,'savings_opportunity_id'=>null,'evidence_note'=>'Company-one governed process initiative evidence.','submitted_at'=>null,'reviewed_at'=>null,'approved_at'=>null,'funded_at'=>null,'started_at'=>null,'completed_at'=>null,'cancelled_at'=>null,'locked_at'=>null,'created_by'=>1]);$initiativeId=(int)$companyOneInitiative['id'];
$portfolioTwo=strategy_save_portfolio(['id'=>null,'portfolio_number'=>'PORT-S29-C2','portfolio_name'=>'Company Two Transformation Portfolio','portfolio_type'=>'procurement_transformation','entity_id'=>102,'company_id'=>2,'fiscal_year'=>(int)date('Y'),'funding_limit'=>300000,'capacity_limit_hours'=>2000,'strategic_theme'=>'Company-scoped portfolio for adversarial Section 29 tests.','status'=>'draft','owner_user_id'=>5,'reviewer_user_id'=>3,'approver_user_id'=>2,'evidence_note'=>'Company two portfolio evidence.','published_at'=>null,'locked_at'=>null,'created_by'=>1]);
$beforeCount=count(strategy_initiatives());s29_throws(static fn()=>strategy_create_governed_initiative(['id'=>null,'initiative_number'=>'INIT-S29-BAD','portfolio_id'=>$portfolioTwo['id'],'parent_initiative_id'=>null,'entity_id'=>102,'company_id'=>2,'initiative_name'=>'Forged sibling KPI initiative','description'=>'Must fail before persistence.','initiative_type'=>'process_improvement','stage'=>'idea','health'=>'not_started','strategic_alignment_score'=>80,'value_score'=>80,'urgency_score'=>80,'risk_score'=>80,'confidence_pct'=>70,'proposed_cost'=>10000,'forecast_cost'=>10000,'actual_cost'=>0,'expected_annual_benefit'=>15000,'realized_benefit'=>0,'capacity_demand_hours'=>80,'start_date'=>date('Y-m-d'),'target_date'=>date('Y-m-d',strtotime('+60 days')),'owner_user_id'=>5,'sponsor_user_id'=>1,'reviewer_user_id'=>3,'approver_user_id'=>2,'benefit_validator_user_id'=>6,'primary_goal_id'=>null,'primary_kpi_definition_id'=>$companyOneKpi['id'],'process_id'=>1,'process_step_id'=>1,'budget_envelope_id'=>null,'savings_opportunity_id'=>null,'evidence_note'=>'Invalid sibling evidence.','submitted_at'=>null,'reviewed_at'=>null,'approved_at'=>null,'funded_at'=>null,'started_at'=>null,'completed_at'=>null,'cancelled_at'=>null,'locked_at'=>null,'created_by'=>1]),'Initiative creation must reject a sibling-company KPI before persistence.');s29(count(strategy_initiatives())===$beforeCount,'Rejected initiative must not leave a partial record.');
$companyTwoInitiative=strategy_create_governed_initiative(['id'=>null,'initiative_number'=>'INIT-S29-C2','portfolio_id'=>$portfolioTwo['id'],'parent_initiative_id'=>null,'entity_id'=>102,'company_id'=>2,'initiative_name'=>'Company Two governed initiative','description'=>'Validate company scope and governed KPI linkage.','initiative_type'=>'process_improvement','stage'=>'idea','health'=>'not_started','strategic_alignment_score'=>85,'value_score'=>80,'urgency_score'=>70,'risk_score'=>60,'confidence_pct'=>70,'proposed_cost'=>12000,'forecast_cost'=>12000,'actual_cost'=>0,'expected_annual_benefit'=>22000,'realized_benefit'=>0,'capacity_demand_hours'=>100,'start_date'=>date('Y-m-d'),'target_date'=>date('Y-m-d',strtotime('+60 days')),'owner_user_id'=>5,'sponsor_user_id'=>1,'reviewer_user_id'=>3,'approver_user_id'=>2,'benefit_validator_user_id'=>6,'primary_goal_id'=>null,'primary_kpi_definition_id'=>$companyTwoKpi['id'],'process_id'=>1,'process_step_id'=>1,'budget_envelope_id'=>null,'savings_opportunity_id'=>null,'evidence_note'=>'Valid company two strategy evidence.','submitted_at'=>null,'reviewed_at'=>null,'approved_at'=>null,'funded_at'=>null,'started_at'=>null,'completed_at'=>null,'cancelled_at'=>null,'locked_at'=>null,'created_by'=>1]);s29((int)$companyTwoInitiative['company_id']===2,'Initiative company must derive from its operating entity.');
s29_user(5,2);s29(strategy_find_portfolio((int)$portfolioTwo['id'])!==null&&strategy_find_initiative((int)$companyTwoInitiative['id'])!==null,'Company contributor must resolve their company portfolio and initiative.');s29(strategy_find_initiative($initiativeId)===null,'Company contributor must not resolve a sibling-company initiative by forged ID.');

s29_user(1,'enterprise');$initiative=strategy_find_initiative($initiativeId);s29($initiative!==null&&$initiative['stage']==='idea','Company initiative must begin at idea stage.');
$gate1=strategy_prepare_gate($initiativeId,'business_case','Initial business case includes goal, KPI, process, cost, risk, capacity and benefit evidence.');$replayGate=strategy_prepare_gate($initiativeId,'business_case','Replay');s29((int)$gate1['id']===(int)$replayGate['id'],'Stage-gate preparation must be replay-safe.');s29_throws(static fn()=>strategy_approve_gate((int)$gate1['id'],'Invalid direct approval.'),'Stage gate must reject approval before independent review.');s29_user(3,1);$gate1=strategy_review_gate((int)$gate1['id'],'Independent reviewer confirmed the initial business case and process impact.');s29($gate1['status']==='reviewed','Assigned independent reviewer must review the stage gate.');s29_user(6,1);$gate1=strategy_approve_gate((int)$gate1['id'],'Approved to business-case stage.');s29($gate1['status']==='approved'&&!empty($gate1['locked_at']),'Approved stage gates must be locked.');s29(strategy_find_initiative($initiativeId)['stage']==='business_case','Approved gate must advance the initiative exactly one stage.');
s29_user(1,'enterprise');$gate2=strategy_prepare_gate($initiativeId,'reviewed','Business case is complete for independent decision review.');s29_user(3,1);strategy_review_gate((int)$gate2['id'],'Second-stage review confirmed the evidence.');s29_user(6,1);strategy_approve_gate((int)$gate2['id'],'Approved to reviewed stage.');s29(strategy_find_initiative($initiativeId)['stage']==='reviewed','Second gate must advance initiative to reviewed.');
s29_user(1,'enterprise');$gate3=strategy_prepare_gate($initiativeId,'approved','Reviewed initiative is ready for final approval.');s29_user(3,1);strategy_review_gate((int)$gate3['id'],'Final independent review confirmed readiness.');s29_user(6,1);strategy_approve_gate((int)$gate3['id'],'Initiative approved for funding consideration.');s29(strategy_find_initiative($initiativeId)['stage']==='approved','Third gate must advance initiative to approved.');

s29_user(1,'enterprise');$budgetOne=demand_save_budget(['id'=>null,'company_id'=>1,'department_id'=>null,'project_workorder_id'=>null,'category_id'=>1,'period_start'=>date('Y-01-01'),'period_end'=>date('Y-12-31'),'budget_amount'=>100000,'requested_amount'=>0,'approved_amount'=>0,'committed_amount'=>0,'actual_amount'=>0,'owner_id'=>3,'status'=>'active','evidence_note'=>'Section 29 company-one budget fixture.']);s29_user(6,1);s29_throws(static fn()=>strategy_reserve_governed_funding($initiativeId,(int)$budgetOne['id'],120000,'Over budget.'),'Funding must reject an amount above the Section 17 available envelope.');$funding=strategy_reserve_governed_funding($initiativeId,(int)$budgetOne['id'],25000,'Approved funding within the governed Section 17 envelope.');$fundingReplay=strategy_reserve_governed_funding($initiativeId,(int)$budgetOne['id'],25000,'Replay');s29((int)$funding['id']===(int)$fundingReplay['id']&&$funding['status']==='approved','Funding must be replay-safe and approved by the assigned approver.');s29(strategy_find_initiative($initiativeId)['stage']==='funded','Approved funding must move the initiative into funded stage.');

s29_user(1,'enterprise');$milestone=strategy_create_milestone($initiativeId,'Complete Section 29 controlled pilot','delivery',4,date('Y-m-d H:i:s',strtotime('+14 days')),'Complete the pilot with governed evidence and no direct published-process mutation.',true);$milestoneReplay=strategy_create_milestone($initiativeId,'Complete Section 29 controlled pilot','delivery',4,date('Y-m-d H:i:s',strtotime('+14 days')),'Replay',true);s29((int)$milestone['id']===(int)$milestoneReplay['id'],'Milestone creation must be replay-safe.');s29(!empty($milestone['work_item_id'])&&!empty($milestone['calendar_event_id']),'Milestone must create Section 26 work and a Section 27 calendar event.');$work=work_management_find_item((int)$milestone['work_item_id']);$event=operational_calendar_find_event((int)$milestone['calendar_event_id']);s29($work!==null&&$work['source_module']==='strategy_portfolio','Initiative milestone work must retain Section 29 source identity.');s29($event!==null&&$event['source_module']==='strategy_portfolio','Initiative milestone must be immediately visible in the Section 27 calendar.');s29(!empty($milestone['process_instance_id'])&&!empty($milestone['step_instance_id']),'Milestone must preserve active Section 25 process and step runtime references when available.');

$processBefore=process_mapping_find_process(1);$versionBefore=process_mapping_process_version($processBefore);$stepsBefore=count(process_mapping_steps((int)$versionBefore['id']));$proposal=strategy_create_change_proposal($initiativeId,'Add supervised recommendation evidence before the control step.','Reduce repeat analysis while preserving human review.','Cycle-time improvement without control removal.',3,6);s29($proposal['status']==='submitted','Process change must begin as a proposal.');s29(process_mapping_find_process(1)===$processBefore&&count(process_mapping_steps((int)$versionBefore['id']))===$stepsBefore,'Creating a proposal must not mutate the published Section 25 process.');s29_user(3,1);strategy_review_change_proposal((int)$proposal['id'],'Independent process-impact review completed.');s29_user(6,1);$proposal=strategy_approve_change_proposal((int)$proposal['id'],'Proposal approved as input to a separate Section 25 version workflow.');s29($proposal['status']==='approved'&&!empty($proposal['locked_at']),'Approved process-change proposals must be locked.');s29(process_mapping_find_process(1)===$processBefore&&count(process_mapping_steps((int)$versionBefore['id']))===$stepsBefore,'Approving a proposal must still not mutate the published process.');

s29_user(1,'enterprise');s29_throws(static fn()=>strategy_create_governed_benefit(['id'=>null,'initiative_id'=>$initiativeId,'benefit_number'=>'BEN-S29-BAD','benefit_type'=>'financial','baseline_value'=>0,'expected_value'=>10,'actual_value'=>5,'financial_value'=>5000,'unit'=>'USD','confidence_pct'=>60,'kpi_definition_id'=>null,'baseline_snapshot_id'=>null,'actual_snapshot_id'=>null,'savings_realization_period_id'=>null,'status'=>'submitted','owner_user_id'=>4,'validator_user_id'=>2,'evidence_note'=>'Unsupported claim.','validation_note'=>'','idempotency_key'=>null,'submitted_at'=>date('Y-m-d H:i:s'),'validated_at'=>null,'locked_at'=>null]),'Benefit claims must require governed KPI or Section 20 evidence.');$benefit=strategy_create_governed_benefit(['id'=>null,'initiative_id'=>$initiativeId,'benefit_number'=>'BEN-S29-VALID','benefit_type'=>'cycle_time','baseline_value'=>72,'expected_value'=>95,'actual_value'=>84,'financial_value'=>15000,'unit'=>'%','confidence_pct'=>75,'kpi_definition_id'=>$companyOneKpi['id'],'baseline_snapshot_id'=>null,'actual_snapshot_id'=>null,'savings_realization_period_id'=>null,'status'=>'submitted','owner_user_id'=>4,'validator_user_id'=>2,'evidence_note'=>'Measured against the governed company-one KPI and pilot evidence.','validation_note'=>'','idempotency_key'=>null,'submitted_at'=>date('Y-m-d H:i:s'),'validated_at'=>null,'locked_at'=>null]);s29_user(2,'enterprise');$benefit=strategy_validate_governed_benefit((int)$benefit['id'],'Independent validator confirmed the KPI-linked measured improvement.');s29($benefit['status']==='validated'&&!empty($benefit['locked_at']),'Validated benefits must be independently locked.');s29_throws(static function()use($benefit):void{$copy=$benefit;$copy['actual_value']=(float)$copy['actual_value']+1;strategy_save_benefit($copy);},'Validated benefits must be immutable.');

s29_user(1,'enterprise');$stagesBefore=array_column(strategy_initiatives((int)$portfolioOne['id']),'stage','id');$scenario=strategy_generate_scenario((int)$portfolioOne['id'],'constrained_budget',120000,1200,3,'Compare the highest-value initiatives under budget and capacity constraints.');$scenarioReplay=strategy_generate_scenario((int)$portfolioOne['id'],'constrained_budget',120000,1200,3,'Replay');s29((int)$scenario['id']===(int)$scenarioReplay['id'],'Portfolio scenarios must be replay-safe.');s29(array_column(strategy_initiatives((int)$portfolioOne['id']),'stage','id')===$stagesBefore,'Advisory scenarios must not approve, fund, pause, or cancel initiatives.');
$workspace=strategy_agent_extend_workspace(executive_intelligence_agent_extend_workspace(operational_calendar_agent_extend_workspace(work_management_agent_extend_workspace(['prompts'=>[],'lookups'=>[],'metrics'=>[],'briefing'=>['priorities'=>[]]]))));s29(($workspace['prompts'][0]['response_title']??'')==='Strategy Portfolio Agent','Agent Workspace must lead with Section 29 strategy intelligence.');foreach(['strategy_initiatives','strategy_at_risk','strategy_approved_funding','strategy_validated_benefit','strategy_capacity_demand']as$key)s29(array_key_exists($key,$workspace['metrics']),'Agent Workspace metric '.$key.' must be available.');$capacity=strategy_assert_portfolio_capacity((int)$portfolioOne['id']);foreach(['funding','funding_limit','capacity','capacity_limit','funding_over','capacity_over']as$key)s29(array_key_exists($key,$capacity),'Portfolio capacity evidence must expose '.$key.'.');
$migration=file_get_contents($root.'/database/20260727_section29_strategy_portfolio_initiative_benefits.sql');foreach(strategy_portfolio_tables()as$table)s29(str_contains($migration,'CREATE TABLE IF NOT EXISTS '.$table),'Migration must create '.$table.'.');s29(str_contains($migration,"'5.8-section29'")&&str_contains($migration,"'portfolio_intelligence.validate_benefits'"),'Migration must record Section 29 and its benefit-validation permission.');s29(str_contains($migration,'process_id BIGINT UNSIGNED NULL')&&str_contains($migration,'work_item_id BIGINT UNSIGNED NULL')&&str_contains($migration,'calendar_event_id BIGINT UNSIGNED NULL'),'Migration must persist process, work, and calendar integration references.');$action=file_get_contents($root.'/app/strategy-portfolio-action.php');foreach(['verify_csrf','strategy_create_governed_initiative','strategy_reserve_governed_funding','strategy_create_governed_benefit','strategy_validate_governed_benefit']as$needle)s29(str_contains($action,$needle),'Section 29 action boundary must use '.$needle.'.');
echo "Section 29 strategy portfolios, initiatives, process impact, stage gates, funding, work, calendar, scenarios, benefits, Agent, and isolation tests passed.\n";