<?php
declare(strict_types=1);
$root=dirname(__DIR__);$_SERVER['SCRIPT_NAME']='/gruber/app/executive-command.php';$_SERVER['REQUEST_METHOD']='GET';$_SERVER['REMOTE_ADDR']='127.0.0.1';$_SERVER['HTTP_USER_AGENT']='Section 28 quality test';require $root.'/includes/app/bootstrap.php';if(!demo_start_session(1)){fwrite(STDERR,"Could not start demo session.\n");exit(1);}require_once $root.'/includes/app/executive_intelligence_governance.php';
function s28(bool$condition,string$message):void{if(!$condition){fwrite(STDERR,"Section 28 failure: {$message}\n");exit(1);}}
function s28_user(int$id,int|string$company='enterprise'):void{$_SESSION['gruber_demo_user_id']=$id;$_SESSION['gruber_demo_company_id']=$company;}
function s28_throws(callable$callback,string$message):void{try{$callback();s28(false,$message);}catch(RuntimeException){}}

s28(executive_intelligence_tables_ready(),'Demo mode must report executive-intelligence tables ready.');
s28(count(executive_intelligence_tables())===8,'Section 28 must define eight governed goal, KPI, scorecard, review, and decision tables.');
s28(count(permission_catalog()['executive_intelligence']??[])===8,'Section 28 must expose eight dedicated application permissions.');
s28(count(executive_intelligence_goals())>=3,'Demo mode must seed enterprise and company goals.');
s28(count(executive_intelligence_kpi_definitions())>=4,'Demo mode must seed governed KPI definitions.');
s28(count(executive_intelligence_kpi_snapshots())>=4,'Demo mode must seed immutable KPI snapshots.');
$processDefinition=null;foreach(executive_intelligence_kpi_definitions()as$definition)if(!empty($definition['process_id'])&&!empty($definition['process_step_id'])){$processDefinition=$definition;break;}
s28($processDefinition!==null,'At least one KPI must bind directly to a published Section 25 process and process step.');
$boundProcess=process_mapping_find_process((int)$processDefinition['process_id']);$boundStep=process_mapping_find_step((int)$processDefinition['process_step_id']);s28($boundProcess!==null&&$boundProcess['status']==='published'&&$boundStep!==null,'KPI process bindings must resolve to the active visible Section 25 map.');
$boundVersion=process_mapping_process_version($boundProcess);s28($boundVersion!==null&&(int)$boundStep['version_id']===(int)$boundVersion['id'],'KPI process steps must belong to the active published process version.');
$context=executive_intelligence_process_context($processDefinition);s28(isset($context['instances'],$context['step_instances'],$context['exceptions']),'KPI calculations must expose process-instance, step-instance, and exception evidence.');
$metric=executive_intelligence_metric_value($processDefinition);s28(is_float($metric),'Process-aware KPI calculation must return a deterministic numeric value.');

$firstSnapshot=executive_intelligence_generate_snapshot((int)$processDefinition['id']);$repeatSnapshot=executive_intelligence_generate_snapshot((int)$processDefinition['id']);s28((int)$firstSnapshot['id']===(int)$repeatSnapshot['id'],'KPI snapshot generation must be replay-safe by definition, version, and period.');
s28(str_contains((string)$firstSnapshot['evidence_json'],'process_instances')&&str_contains((string)$firstSnapshot['evidence_json'],'process_step_id'),'KPI snapshots must preserve process evidence references.');
$copy=$firstSnapshot;$copy['actual_value']=(float)$copy['actual_value']+100;$unchanged=executive_intelligence_save_snapshot($copy);s28((float)$unchanged['actual_value']===(float)$firstSnapshot['actual_value'],'Historical KPI snapshot replay must return the immutable original value.');

$entity=entity_system_find_by_code('COMP-GC');s28($entity!==null,'The Gruber Communications entity must resolve for Section 28 tests.');
$definition=executive_intelligence_save_definition(['id'=>null,'kpi_code'=>'KPI-S28-TEST','kpi_name'=>'Section 28 governed process KPI','description'=>'Validate independent methodology governance and Section 25 process integration.','entity_id'=>$entity['id'],'company_id'=>1,'source_module'=>'process_mapping','metric_key'=>'process_sla_compliance_pct','process_id'=>$processDefinition['process_id'],'process_step_id'=>$processDefinition['process_step_id'],'owner_user_id'=>1,'data_owner_user_id'=>3,'refresh_frequency'=>'daily','status'=>'draft','active_version_id'=>null,'created_by'=>1]);
$version=executive_intelligence_save_version(['id'=>null,'definition_id'=>$definition['id'],'version_number'=>'1.0','status'=>'draft','calculation_method'=>'Calculate visible active published process-step SLA compliance.','calculation_json'=>'{"metric_key":"process_sla_compliance_pct","scope":"approved_visible_records"}','unit'=>'%','direction'=>'higher_better','target_value'=>95,'warning_value'=>90,'critical_value'=>80,'prepared_by'=>1,'reviewed_by'=>6,'approved_by'=>2,'review_note'=>'','approval_note'=>'','evidence_note'=>'Methodology is bound to the active published Section 25 process and process step.','effective_from'=>date('Y-m-d'),'published_at'=>null,'locked_at'=>null]);
s28($version['status']==='draft','New KPI versions must begin as drafts.');
s28_throws(static fn()=>executive_intelligence_publish_governed_version((int)$version['id'],'Invalid direct approval.'),'KPI publication must reject versions without independent review.');
s28_user(6,'enterprise');$version=executive_intelligence_review_version((int)$version['id'],'Independent reviewer verified the calculation, thresholds, source scope, and process binding.');s28($version['status']==='reviewed','Assigned independent reviewer must move KPI methodology to reviewed.');
s28_user(2,'enterprise');$version=executive_intelligence_publish_governed_version((int)$version['id'],'Executive approver authorized the governed KPI version.');s28($version['status']==='published'&&!empty($version['locked_at']),'Published KPI versions must be permanently locked.');
s28_throws(static function()use($version):void{$copy=$version;$copy['target_value']=99;executive_intelligence_save_version($copy);},'Published KPI versions must be immutable.');

s28_user(1,'enterprise');$goal=executive_intelligence_save_goal(['id'=>null,'goal_number'=>'GOAL-S28-TEST','parent_goal_id'=>null,'entity_id'=>$entity['id'],'company_id'=>1,'goal_name'=>'Section 28 integration goal','description'=>'Tie executive performance to the governed Section 25 process and Section 26 execution layer.','goal_type'=>'operational','unit'=>'%','direction'=>'higher_better','target_value'=>95,'period_start'=>date('Y-m-01'),'period_end'=>date('Y-m-t'),'owner_user_id'=>4,'reviewer_user_id'=>6,'executive_sponsor_user_id'=>2,'status'=>'active','confidence_pct'=>70,'evidence_note'=>'Measured by the governed process-aware KPI.','created_by'=>1]);
$link=executive_intelligence_create_goal_link(['id'=>null,'goal_id'=>$goal['id'],'link_type'=>'kpi_definition','source_id'=>$definition['id'],'relationship_label'=>'Primary governed KPI','created_by'=>1]);s28((int)$link['goal_id']===(int)$goal['id'],'Goals must link to governed KPI definitions.');

s28_user(5,2);$allowed5=array_fill_keys(permitted_company_ids(),true);foreach(executive_intelligence_goals()as$row)s28(isset($allowed5[(int)$row['company_id']]),'Company contributor goals must not expose sibling companies or enterprise-only goals.');foreach(executive_intelligence_kpi_definitions()as$row)s28(isset($allowed5[(int)$row['company_id']]),'Company contributor KPIs must not expose sibling companies or enterprise-only definitions.');s28(executive_intelligence_find_goal((int)$goal['id'])===null,'A sibling-company user must not resolve a Gruber Communications goal by forged ID.');s28(executive_intelligence_find_definition((int)$definition['id'])===null,'A sibling-company user must not resolve a Gruber Communications KPI by forged ID.');

s28_user(1,'enterprise');$companyTwoDefinition=null;foreach(executive_intelligence_kpi_definitions()as$row)if((int)($row['company_id']??0)===2){$companyTwoDefinition=$row;break;}s28($companyTwoDefinition!==null,'A company-two KPI is required for cross-company decision testing.');s28_throws(static fn()=>executive_intelligence_create_goal_link(['id'=>null,'goal_id'=>$goal['id'],'link_type'=>'kpi_definition','source_id'=>$companyTwoDefinition['id'],'relationship_label'=>'Invalid sibling-company KPI','created_by'=>1]),'Company goals must reject sibling-company KPI links.');

$review=executive_intelligence_find_review(1);s28($review!==null&&$review['status']==='reviewed','Demo mode must include an independently reviewed executive review.');
s28_throws(static fn()=>executive_intelligence_create_governed_review(1,102,'weekly_operating_review',date('Y-m-d H:i:s',strtotime('+2 days 09:00')),date('Y-m-d H:i:s',strtotime('+2 days 10:00')),'Invalid cross-company review',3,6),'A company scorecard must not be scheduled under a sibling operating entity.');
s28_throws(static fn()=>executive_intelligence_record_governed_decision((int)$review['id'],null,(int)$companyTwoDefinition['id'],'corrective_action','Invalid cross-company decision','This must be rejected.',4,date('Y-m-d H:i:s',strtotime('+2 days')),true),'Executive decisions must reject sibling-company KPI references.');
s28_throws(static fn()=>executive_intelligence_record_governed_decision((int)$review['id'],2,2,'corrective_action','Invalid reviewer ownership','This must be rejected.',6,date('Y-m-d H:i:s',strtotime('+2 days')),true),'Decision execution ownership must remain separate from review and approval.');
s28_throws(static fn()=>executive_intelligence_record_governed_decision((int)$review['id'],2,2,'corrective_action','Invalid approver-created work','This must be rejected.',4,date('Y-m-d H:i:s',strtotime('+2 days')),true),'The final approver must not create work they are assigned to approve.');
s28_user(3,'enterprise');$review=executive_intelligence_find_review(1);$runtime=executive_intelligence_runtime_link(executive_intelligence_find_definition(2),(int)$review['entity_id']);$decision=executive_intelligence_record_governed_decision((int)$review['id'],2,2,'corrective_action','Resolve Section 28 process performance gap','Trace the KPI variance to its published process step, resolve the governed work evidence, and confirm the result in the next executive review.',4,date('Y-m-d H:i:s',strtotime('+3 days 17:00')),true);$replay=executive_intelligence_record_governed_decision((int)$review['id'],2,2,'corrective_action','Resolve Section 28 process performance gap','Trace the KPI variance to its published process step, resolve the governed work evidence, and confirm the result in the next executive review.',4,date('Y-m-d H:i:s',strtotime('+3 days 17:00')),true);s28((int)$decision['id']===(int)$replay['id'],'Executive decision replays must return the original governed receipt.');s28(!empty($decision['work_item_id'])&&!empty($decision['calendar_event_id']),'Governed executive decisions must create Section 26 work and Section 27 calendar follow-up.');$work=work_management_find_item((int)$decision['work_item_id']);s28($work!==null&&$work['source_module']==='executive_intelligence','Decision work must remain visibly sourced from Section 28.');if(!empty($runtime['process_instance_id']))s28((int)$work['process_instance_id']===(int)$runtime['process_instance_id'],'Decision work must preserve the active Section 25 process-instance reference.');if(!empty($runtime['step_instance_id']))s28((int)$work['step_instance_id']===(int)$runtime['step_instance_id'],'Decision work must preserve the active Section 25 process-step reference.');$decisionEvents=array_values(array_filter(operational_calendar_events(),static fn(array$event):bool=>$event['source_module']==='executive_intelligence'&&$event['source_type']==='executive_decision'));s28(count($decisionEvents)>=1,'Executive decision deadlines must appear in the Section 27 calendar.');

$workspace=executive_intelligence_agent_extend_workspace(operational_calendar_agent_extend_workspace(work_management_agent_extend_workspace(['prompts'=>[],'lookups'=>[],'metrics'=>[],'briefing'=>['priorities'=>[]]])));s28(($workspace['prompts'][0]['response_title']??'')==='Executive Performance Agent','Agent Workspace must lead with the Section 28 executive performance briefing.');foreach(['executive_goals','at_risk_goals','critical_kpis','published_scorecards']as$key)s28(array_key_exists($key,$workspace['metrics']),'Agent Workspace metric '.$key.' must be available.');
$migration=file_get_contents($root.'/database/20260727_section28_executive_command_goals_performance.sql');foreach(executive_intelligence_tables()as$table)s28(str_contains($migration,'CREATE TABLE IF NOT EXISTS '.$table),'Migration must create '.$table.'.');s28(str_contains($migration,"'5.7-section28'"),'Migration version must be recorded.');s28(str_contains($migration,"'executive_intelligence.view'"),'Dedicated executive-intelligence permissions must be seeded.');s28(str_contains($migration,'process_id BIGINT UNSIGNED NULL')&&str_contains($migration,'process_step_id BIGINT UNSIGNED NULL'),'KPI definitions must persist Section 25 process and step bindings.');s28(str_contains($migration,'work_item_id BIGINT UNSIGNED NULL')&&str_contains($migration,'calendar_event_id BIGINT UNSIGNED NULL'),'Executive decisions must persist Section 26 and Section 27 handoffs.');
$action=file_get_contents($root.'/app/executive-command-action.php');s28(str_contains($action,'verify_csrf'),'All Section 28 mutations must verify CSRF.');s28(str_contains($action,'executive_intelligence_create_goal_link'),'Goal links must use the hardened scope boundary.');s28(str_contains($action,'executive_intelligence_record_governed_decision'),'Decision actions must use the hardened process/company boundary.');
echo "Section 28 goals, process-aware KPI governance, snapshots, scorecards, reviews, decisions, work, calendar, Agent, and isolation tests passed.\n";
