<?php
declare(strict_types=1);
$root=dirname(__DIR__);$_SERVER['SCRIPT_NAME']='/gruber/app/strategy-portfolio.php';$_SERVER['REQUEST_METHOD']='GET';$_SERVER['REMOTE_ADDR']='127.0.0.1';$_SERVER['HTTP_USER_AGENT']='Section 29 quality test';require $root.'/includes/app/bootstrap.php';if(!demo_start_session(1)){fwrite(STDERR,"Could not start demo session.\n");exit(1);}require_once $root.'/includes/app/strategy_portfolio_security.php';
function s29(bool$condition,string$message):void{if(!$condition){fwrite(STDERR,"Section 29 failure: {$message}\n");exit(1);}}
function s29_user(int$id,int|string$company='enterprise'):void{$_SESSION['gruber_demo_user_id']=$id;$_SESSION['gruber_demo_company_id']=$company;}
function s29_throws(callable$callback,string$message):void{try{$callback();s29(false,$message);}catch(RuntimeException){}}
function s29_initiative(array$overrides=[]):array{return array_replace(['id'=>null,'initiative_number'=>'INIT-S29-BASE','portfolio_id'=>0,'parent_initiative_id'=>null,'entity_id'=>101,'company_id'=>1,'initiative_name'=>'Governed initiative','description'=>'Section 29 governed initiative test.','initiative_type'=>'process_automation','stage'=>'idea','health'=>'not_started','strategic_alignment_score'=>90,'value_score'=>85,'urgency_score'=>80,'risk_score'=>65,'confidence_pct'=>72,'proposed_cost'=>50000,'forecast_cost'=>50000,'actual_cost'=>0,'expected_annual_benefit'=>95000,'realized_benefit'=>0,'capacity_demand_hours'=>420,'start_date'=>date('Y-m-d'),'target_date'=>date('Y-m-d',strtotime('+90 days')),'owner_user_id'=>4,'sponsor_user_id'=>1,'reviewer_user_id'=>3,'approver_user_id'=>2,'benefit_validator_user_id'=>6,'primary_goal_id'=>null,'primary_kpi_definition_id'=>null,'process_id'=>1,'process_step_id'=>1,'budget_envelope_id'=>null,'savings_opportunity_id'=>null,'evidence_note'=>'Governed strategy evidence.','submitted_at'=>null,'reviewed_at'=>null,'approved_at'=>null,'funded_at'=>null,'started_at'=>null,'completed_at'=>null,'cancelled_at'=>null,'locked_at'=>null,'created_by'=>1],$overrides);}

s29(strategy_portfolio_tables_ready(),'Demo mode must report Section 29 tables ready.');
s29(count(strategy_portfolio_tables())===9,'Section 29 must define nine governed strategy-portfolio tables.');
s29(count(permission_catalog()['portfolio_intelligence']??[])===10,'Section 29 must expose ten dedicated permissions.');
s29(count(strategy_portfolios())>=1&&count(strategy_initiatives())>=2,'Demo mode must seed portfolio intelligence.');
$processInitiative=strategy_find_initiative(2);$process=$processInitiative?process_mapping_find_process((int)$processInitiative['process_id']):null;$step=$processInitiative?process_mapping_find_step((int)$processInitiative['process_step_id']):null;$version=$process?process_mapping_process_version($process):null;s29($process!==null&&$process['status']==='published'&&$version!==null&&$step!==null&&(int)$step['version_id']===(int)$version['id'],'Initiatives must resolve to the active published Section 25 process and step.');
$companyOneKpi=null;$companyTwoKpi=null;foreach(executive_intelligence_kpi_definitions()as$definition){if((int)($definition['company_id']??0)===1)$companyOneKpi=$definition;if((int)($definition['company_id']??0)===2)$companyTwoKpi=$definition;}s29($companyOneKpi!==null&&$companyTwoKpi!==null,'Company KPI fixtures are required.');

$portfolioOne=strategy_save_portfolio(['id'=>null,'portfolio_number'=>'PORT-S29-C1','portfolio_name'=>'Company One Transformation Portfolio','portfolio_type'=>'procurement_transformation','entity_id'=>101,'company_id'=>1,'fiscal_year'=>(int)date('Y'),'funding_limit'=>250000,'capacity_limit_hours'=>1800,'strategic_theme'=>'Company-one strategy, process, execution, funding, and benefit governance.','status'=>'draft','owner_user_id'=>4,'reviewer_user_id'=>3,'approver_user_id'=>2,'evidence_note'=>'Company one portfolio evidence.','published_at'=>null,'locked_at'=>null,'created_by'=>1]);
$companyOneInitiative=strategy_create_governed_initiative(s29_initiative(['initiative_number'=>'INIT-S29-C1','portfolio_id'=>$portfolioOne['id'],'initiative_name'=>'Company One controlled process initiative','primary_kpi_definition_id'=>$companyOneKpi['id']]));$initiativeId=(int)$companyOneInitiative['id'];
$portfolioTwo=strategy_save_portfolio(['id'=>null,'portfolio_number'=>'PORT-S29-C2','portfolio_name'=>'Company Two Transformation Portfolio','portfolio_type'=>'procurement_transformation','entity_id'=>102,'company_id'=>2,'fiscal_year'=>(int)date('Y'),'funding_limit'=>300000,'capacity_limit_hours'=>2000,'strategic_theme'=>'Company-two adversarial isolation portfolio.','status'=>'draft','owner_user_id'=>5,'reviewer_user_id'=>3,'approver_user_id'=>2,'evidence_note'=>'Company two portfolio evidence.','published_at'=>null,'locked_at'=>null,'created_by'=>1]);
$beforeCount=count(strategy_initiatives());s29_throws(static fn()=>strategy_create_governed_initiative(s29_initiative(['initiative_number'=>'INIT-S29-BAD','portfolio_id'=>$portfolioTwo['id'],'entity_id'=>102,'company_id'=>2,'owner_user_id'=>5,'benefit_validator_user_id'=>6,'initiative_name'=>'Forged sibling KPI initiative','primary_kpi_definition_id'=>$companyOneKpi['id']])), 'Initiative creation must reject a sibling-company KPI before persistence.');s29(count(strategy_initiatives())===$beforeCount,'Rejected initiative must not leave a partial record.');
$companyTwoInitiative=strategy_create_governed_initiative(s29_initiative(['initiative_number'=>'INIT-S29-C2','portfolio_id'=>$portfolioTwo['id'],'entity_id'=>102,'company_id'=>2,'owner_user_id'=>5,'benefit_validator_user_id'=>6,'initiative_name'=>'Company Two governed initiative','primary_kpi_definition_id'=>$companyTwoKpi['id']]));s29((int)$companyTwoInitiative['company_id']===2,'Initiative company must derive from its entity.');
s29_user(5,2);s29(strategy_find_portfolio((int)$portfolioTwo['id'])!==null&&strategy_find_initiative((int)$companyTwoInitiative['id'])!==null,'Company contributor must resolve their company portfolio and initiative.');s29(strategy_find_initiative($initiativeId)===null,'Sibling-company initiative ID must remain hidden.');

s29_user(1,'enterprise');$gate1=strategy_prepare_gate($initiativeId,'business_case','Initial business case includes goal, KPI, process, cost, risk, capacity, and benefit evidence.');$gateReplay=strategy_prepare_gate($initiativeId,'business_case','Replay');s29((int)$gate1['id']===(int)$gateReplay['id'],'Stage-gate preparation must be replay-safe.');s29_throws(static fn()=>strategy_approve_gate((int)$gate1['id'],'Invalid direct approval.'),'Approval before review must fail.');s29_user(3,1);strategy_review_gate((int)$gate1['id'],'Independent business-case review completed.');s29_user(2,'enterprise');$gate1=strategy_approve_gate((int)$gate1['id'],'Approved to business-case stage.');s29($gate1['status']==='approved'&&!empty($gate1['locked_at'])&&strategy_find_initiative($initiativeId)['stage']==='business_case','First gate must lock and advance exactly one stage.');
s29_user(1,'enterprise');$gate2=strategy_prepare_gate($initiativeId,'reviewed','Business case is ready for decision review.');s29_user(3,1);strategy_review_gate((int)$gate2['id'],'Second independent review completed.');s29_user(2,'enterprise');strategy_approve_gate((int)$gate2['id'],'Approved to reviewed stage.');s29(strategy_find_initiative($initiativeId)['stage']==='reviewed','Second gate must advance to reviewed.');
s29_user(1,'enterprise');$gate3=strategy_prepare_gate($initiativeId,'approved','Reviewed initiative is ready for final approval.');s29_user(3,1);strategy_review_gate((int)$gate3['id'],'Final independent review completed.');s29_user(2,'enterprise');strategy_approve_gate((int)$gate3['id'],'Approved for funding consideration.');s29(strategy_find_initiative($initiativeId)['stage']==='approved','Third gate must advance to approved.');

s29_user(1,'enterprise');$budgetOne=demand_save_budget(['id'=>null,'company_id'=>1,'department_id'=>null,'project_workorder_id'=>null,'category_id'=>1,'period_start'=>date('Y-01-01'),'period_end'=>date('Y-12-31'),'budget_amount'=>100000,'requested_amount'=>0,'approved_amount'=>0,'committed_amount'=>0,'actual_amount'=>0,'owner_id'=>3,'status'=>'active','evidence_note'=>'Section 29 company-one budget fixture.']);s29_user(2,'enterprise');s29_throws(static fn()=>strategy_reserve_governed_funding($initiativeId,(int)$budgetOne['id'],120000,'Over budget.'),'Funding above the Section 17 envelope must fail.');$funding=strategy_reserve_governed_funding($initiativeId,(int)$budgetOne['id'],25000,'Approved funding within the Section 17 envelope.');$fundingReplay=strategy_reserve_governed_funding($initiativeId,(int)$budgetOne['id'],25000,'Replay');s29((int)$funding['id']===(int)$fundingReplay['id']&&$funding['status']==='approved'&&strategy_find_initiative($initiativeId)['stage']==='funded','Funding must be assigned, replay-safe, and advance the initiative.');

s29_user(1,'enterprise');$due=date('Y-m-d H:i:s',strtotime('+14 days'));$milestone=strategy_create_milestone($initiativeId,'Complete Section 29 controlled pilot','delivery',4,$due,'Complete the pilot with governed evidence and no direct process mutation.',true);$milestoneReplay=strategy_create_milestone($initiativeId,'Complete Section 29 controlled pilot','delivery',4,$due,'Replay',true);$work=work_management_find_item((int)$milestone['work_item_id']);$event=operational_calendar_find_event((int)$milestone['calendar_event_id']);s29((int)$milestone['id']===(int)$milestoneReplay['id'],'Milestones must be replay-safe.');s29($work!==null&&$work['source_module']==='strategy_portfolio'&&$event!==null&&$event['source_module']==='strategy_portfolio','Milestones must create visible Section 26 work and Section 27 events.');s29(!empty($milestone['process_instance_id'])&&!empty($milestone['step_instance_id']),'Milestones must preserve Section 25 runtime references when available.');

$processBefore=process_mapping_find_process(1);$versionBefore=process_mapping_process_version($processBefore);$stepsBefore=count(process_mapping_steps((int)$versionBefore['id']));$proposal=strategy_create_change_proposal($initiativeId,'Add supervised recommendation evidence before the control step.','Reduce repeat analysis while preserving human review.','Cycle-time improvement without control removal.',3,2);s29(process_mapping_find_process(1)===$processBefore&&count(process_mapping_steps((int)$versionBefore['id']))===$stepsBefore,'Creating a change proposal must not mutate Section 25.');s29_user(3,1);strategy_review_change_proposal((int)$proposal['id'],'Independent process-impact review completed.');s29_user(2,'enterprise');$proposal=strategy_approve_change_proposal((int)$proposal['id'],'Approved only as input to a separate Section 25 version workflow.');s29($proposal['status']==='approved'&&!empty($proposal['locked_at'])&&process_mapping_find_process(1)===$processBefore&&count(process_mapping_steps((int)$versionBefore['id']))===$stepsBefore,'Approved proposals must lock without mutating the published process.');

s29_user(1,'enterprise');s29_throws(static fn()=>strategy_create_governed_benefit(['id'=>null,'initiative_id'=>$initiativeId,'benefit_number'=>'BEN-S29-BAD','benefit_type'=>'financial','baseline_value'=>0,'expected_value'=>10,'actual_value'=>5,'financial_value'=>5000,'unit'=>'USD','confidence_pct'=>60,'kpi_definition_id'=>null,'baseline_snapshot_id'=>null,'actual_snapshot_id'=>null,'savings_realization_period_id'=>null,'status'=>'submitted','owner_user_id'=>4,'validator_user_id'=>6,'evidence_note'=>'Unsupported claim.','validation_note'=>'','idempotency_key'=>null,'submitted_at'=>date('Y-m-d H:i:s'),'validated_at'=>null,'locked_at'=>null]),'Unsupported benefit claims must fail.');$benefit=strategy_create_governed_benefit(['id'=>null,'initiative_id'=>$initiativeId,'benefit_number'=>'BEN-S29-VALID','benefit_type'=>'cycle_time','baseline_value'=>72,'expected_value'=>95,'actual_value'=>84,'financial_value'=>15000,'unit'=>'%','confidence_pct'=>75,'kpi_definition_id'=>$companyOneKpi['id'],'baseline_snapshot_id'=>null,'actual_snapshot_id'=>null,'savings_realization_period_id'=>null,'status'=>'submitted','owner_user_id'=>4,'validator_user_id'=>6,'evidence_note'=>'Measured against governed KPI and pilot evidence.','validation_note'=>'','idempotency_key'=>null,'submitted_at'=>date('Y-m-d H:i:s'),'validated_at'=>null,'locked_at'=>null]);s29_user(6,1);$benefit=strategy_validate_governed_benefit((int)$benefit['id'],'Independent validator confirmed the KPI-linked improvement.');s29($benefit['status']==='validated'&&!empty($benefit['locked_at']),'Validated benefits must lock.');s29_throws(static function()use($benefit):void{$copy=$benefit;$copy['actual_value']=(float)$copy['actual_value']+1;strategy_save_benefit($copy);},'Validated benefits must be immutable.');

s29_user(1,'enterprise');$stagesBefore=array_column(strategy_initiatives((int)$portfolioOne['id']),'stage','id');$scenario=strategy_generate_scenario((int)$portfolioOne['id'],'constrained_budget',120000,1200,3,'Compare initiatives under budget and capacity constraints.');$scenarioReplay=strategy_generate_scenario((int)$portfolioOne['id'],'constrained_budget',120000,1200,3,'Replay');s29((int)$scenario['id']===(int)$scenarioReplay['id'],'Scenarios must be replay-safe.');s29(array_column(strategy_initiatives((int)$portfolioOne['id']),'stage','id')===$stagesBefore,'Advisory scenarios must not change initiative stages.');
$workspace=strategy_agent_extend_workspace(executive_intelligence_agent_extend_workspace(operational_calendar_agent_extend_workspace(work_management_agent_extend_workspace(['prompts'=>[],'lookups'=>[],'metrics'=>[],'briefing'=>['priorities'=>[]]]))));s29(($workspace['prompts'][0]['response_title']??'')==='Strategy Portfolio Agent','Agent Workspace must lead with Section 29 strategy intelligence.');foreach(['strategy_initiatives','strategy_at_risk','strategy_approved_funding','strategy_validated_benefit','strategy_capacity_demand']as$key)s29(array_key_exists($key,$workspace['metrics']),'Agent metric '.$key.' must be available.');$capacity=strategy_assert_portfolio_capacity((int)$portfolioOne['id']);foreach(['funding','funding_limit','capacity','capacity_limit','funding_over','capacity_over']as$key)s29(array_key_exists($key,$capacity),'Portfolio capacity evidence must expose '.$key.'.');
$migration=file_get_contents($root.'/database/20260727_section29_strategy_portfolio_initiative_benefits.sql');foreach(strategy_portfolio_tables()as$table)s29(str_contains($migration,'CREATE TABLE IF NOT EXISTS '.$table),'Migration must create '.$table.'.');s29(str_contains($migration,"'5.8-section29'")&&str_contains($migration,"'portfolio_intelligence.validate_benefits'"),'Migration must record Section 29 and benefit validation.');s29(str_contains($migration,'process_id BIGINT UNSIGNED NULL')&&str_contains($migration,'work_item_id BIGINT UNSIGNED NULL')&&str_contains($migration,'calendar_event_id BIGINT UNSIGNED NULL'),'Migration must persist process, work, and calendar references.');$action=file_get_contents($root.'/app/strategy-portfolio-action.php');foreach(['verify_csrf','strategy_create_governed_initiative','strategy_reserve_governed_funding','strategy_create_governed_benefit','strategy_validate_governed_benefit']as$needle)s29(str_contains($action,$needle),'Action boundary must use '.$needle.'.');
echo "Section 29 strategy portfolios, initiatives, process impact, stage gates, funding, work, calendar, scenarios, benefits, Agent, and isolation tests passed.\n";