<?php
declare(strict_types=1);
$root=dirname(__DIR__);$_SERVER['SCRIPT_NAME']='/gruber/app/entity-system.php';$_SERVER['REQUEST_METHOD']='GET';$_SERVER['REMOTE_ADDR']='127.0.0.1';$_SERVER['HTTP_USER_AGENT']='Section 24 quality test';require $root.'/includes/app/bootstrap.php';if(!demo_start_session(1)){fwrite(STDERR,"Could not start demo session.\n");exit(1);}require_once $root.'/includes/app/entity_system.php';
function s24(bool$c,string$m):void{if(!$c){fwrite(STDERR,"Section 24 failure: {$m}\n");exit(1);}}
function s24_user(int$id):void{$_SESSION['gruber_demo_user_id']=$id;}
s24(entity_system_tables_ready(),'Demo mode must report entity tables ready.');s24(count(entity_system_tables())===15,'Section 24 must govern fifteen supplemental entity and integration tables.');
$carry=entity_system_carryover_snapshot();s24($carry['companies']===6,'All six existing businesses must be discovered.');s24($carry['company_ids']===[1,2,3,4,5,6],'Canonical company IDs must remain unchanged.');
$entities=entity_system_entities();$bindings=entity_system_bindings();s24(count(array_filter($entities,static fn(array$e):bool=>$e['entity_type']==='operating_company'))===6,'Six operating entities must be backfilled.');s24(count($bindings)===6,'Each company must have one entity binding.');foreach($bindings as$b)s24((int)$b['company_id']===(int)(entity_system_find($entities,(int)$b['entity_id'])['company_id']??0),'Binding must preserve the same company ID.');
$preview=entity_system_template_preview('gruber_shared_services');s24(count($preview['nodes'])===9,'Gruber template must preview root, two shared services, and six companies.');s24(count($preview['relationships'])===18,'Gruber template must preview ownership and two service relationships per company.');s24($preview['validation']['valid'],'Existing relationships must validate before template application.');
$validation=entity_system_validate_current_relationships();s24($validation['valid'],'Existing memberships and shared records must reference valid companies.');s24($carry['user_memberships']>0&&$carry['supplier_company_links']>0,'User and supplier relationships must be carried into the audit snapshot.');
s24(count(entity_system_access_scopes())>=6,'Existing memberships must produce entity access scopes.');s24(count(entity_system_authorities())>=10,'Data-authority policies must be present.');
$connection=['id'=>null,'connection_number'=>'INT-TEST-24','connection_name'=>'Section 24 ERP Test','provider'=>'test-provider','system_type'=>'erp','environment'=>'sandbox','auth_type'=>'external_secret_reference','secret_reference'=>'vault://tests/entity-system','adapter_version'=>'1.0','status'=>'draft','capabilities_json'=>'["companies","suppliers"]','last_success_at'=>null,'created_by'=>1,'reviewer_id'=>6,'evidence_note'=>'Test connection stores only an external secret reference.'];entity_system_validate_connection_payload($connection);$connection=entity_system_save_connection($connection);s24(str_starts_with($connection['secret_reference'],'vault://'),'Connection must store only a secret reference.');try{$bad=$connection;$bad['connection_name']='Bad';$bad['secret_reference']='password=secret';entity_system_validate_connection_payload($bad);s24(false,'Raw credentials must be rejected.');}catch(RuntimeException){}
$entity=entity_system_find_by_code('COMP-GPS');s24($entity!==null&&(int)$entity['company_id']===2,'GPS entity must retain Company ID 2.');$binding=entity_system_save_integration_binding(['id'=>null,'connection_id'=>$connection['id'],'entity_id'=>$entity['id'],'external_organization_id'=>'ORG-24','external_company_id'=>'COMPANY-GPS','external_tenant_id'=>'TENANT-24','sync_direction'=>'bidirectional','enabled_domains_json'=>'["companies","suppliers"]','data_authority'=>'internal_governed','status'=>'draft','effective_from'=>date('Y-m-d'),'effective_to'=>null,'evidence_note'=>'Test entity integration binding.']);s24((int)$binding['entity_id']===(int)$entity['id'],'Connection must bind to the preserved operating entity.');
$mapping=entity_system_save_mapping(['id'=>null,'connection_id'=>$connection['id'],'entity_id'=>$entity['id'],'domain_code'=>'companies','internal_record_type'=>'company','internal_record_id'=>2,'external_record_type'=>'company','external_record_id'=>'COMPANY-GPS','external_parent_id'=>'ORG-24','mapping_status'=>'pending_review','effective_from'=>date('Y-m-d'),'effective_to'=>null,'evidence_note'=>'Company ID 2 mapped without modifying it.']);$key=hash('sha256','section24-idempotency');$event=entity_system_queue_integration_event((int)$connection['id'],(int)$entity['id'],'outbox','mapping_created','external_id_mapping',(int)$mapping['id'],$key,$mapping,'Test event.');$repeat=entity_system_queue_integration_event((int)$connection['id'],(int)$entity['id'],'outbox','mapping_created','external_id_mapping',(int)$mapping['id'],$key,$mapping,'Repeated event.');s24((int)$event['id']===(int)$repeat['id'],'Integration events must be idempotent.');
$readiness=entity_system_readiness();s24(array_key_exists('score',$readiness),'Readiness assessment must provide a score.');$metrics=entity_system_metrics();s24($metrics['preserved_company_ids']===true,'Portfolio metrics must confirm canonical company IDs.');
$migration=file_get_contents($root.'/database/20260727_section24_business_entity_integration_foundation.sql');foreach(entity_system_tables()as$t)s24(str_contains($migration,'CREATE TABLE IF NOT EXISTS '.$t),'Migration must create '.$t.'.');s24(str_contains($migration,"'5.3-section24'"),'Migration version must be recorded.');s24(str_contains($migration,'SELECT CONCAT(\'COMP-\',UPPER(code))'),'Migration must backfill company entities from existing companies.');s24(str_contains($migration,'company_memberships'),'Migration must carry active company memberships into entity access scopes.');s24(str_contains($migration,'supplier_master'),'Template must seed cross-domain authority policies.');
$action=file_get_contents($root.'/app/entity-system-action.php');s24(str_contains($action,"require_permission('companies.administer')"),'Template application must require company administration permission.');s24(str_contains($action,'entity_system_validate_connection_payload'),'Connection writes must validate secret references.');
$export=file_get_contents($root.'/includes/app/entity_system_export.php');s24(str_contains($export,'spreadsheet_safe'),'CSV exports must use formula-injection protection.');
echo "Section 24 modular business entity, template, relationship carryover, and integration foundation tests passed.\n";
