<?php
declare(strict_types=1);
$root=dirname(__DIR__);$_SERVER['SCRIPT_NAME']='/gruber/app/spend-strategy.php';$_SERVER['REQUEST_METHOD']='GET';$_SERVER['REMOTE_ADDR']='127.0.0.1';$_SERVER['HTTP_USER_AGENT']='Gruber Section 21 quality test';
require $root.'/includes/app/bootstrap.php';if(!demo_start_session(1)){fwrite(STDERR,"Could not start demo session.\n");exit(1);}require_once $root.'/includes/app/spend_strategy.php';
[$start,$end]=spend_strategy_period_default();$cube=spend_strategy_build_cube($start,$end);if(!$cube){fwrite(STDERR,"Spend cube is empty.\n");exit(1);}foreach(['company_id','category_id','supplier_id','ordered_spend','received_spend','open_commitments','contracted_spend','off_contract_spend','addressable_spend','spend_under_management','spend_under_contract','high_risk_spend'] as $field)if(!array_key_exists($field,$cube[0])){fwrite(STDERR,"Spend cube missing {$field}.\n");exit(1);}
$metrics=spend_strategy_portfolio_metrics($cube);foreach(['total_spend','addressable_spend','spend_under_contract_pct','off_contract_spend','validated_savings','supplier_concentration_pct','category_plan_completion_pct'] as $field)if(!array_key_exists($field,$metrics)){fwrite(STDERR,"Portfolio metrics missing {$field}.\n");exit(1);}
$rows=spend_strategy_refresh($start,$end,1,6,'Section 21 governed snapshot quality evidence.');if(!$rows||!spend_strategy_snapshots()){fwrite(STDERR,"Snapshot refresh failed.\n");exit(1);}if(!spend_strategy_events()){fwrite(STDERR,"Snapshot event failed.\n");exit(1);}
$categoryId=(int)($cube[0]['category_id']??1);$profile=spend_strategy_category_profile($categoryId,$cube);foreach(['total_spend','addressable_spend','supplier_count','concentration_pct','validated_savings'] as $field)if(!array_key_exists($field,$profile)){fwrite(STDERR,"Category profile missing {$field}.\n");exit(1);}
$strategy=spend_strategy_save_strategy(['id'=>null,'strategy_number'=>'CAT-QUALITY-021','company_id'=>(int)$cube[0]['company_id'],'category_id'=>$categoryId,'fiscal_year'=>(int)date('Y'),'title'=>'Section 21 quality category strategy','status'=>'draft','owner_id'=>3,'reviewer_id'=>6,'approval_id'=>null,'current_spend'=>$profile['total_spend'],'addressable_spend'=>$profile['addressable_spend'],'contracted_spend'=>$profile['spend_under_contract'],'supplier_count'=>$profile['supplier_count'],'concentration_pct'=>$profile['concentration_pct'],'high_risk_spend'=>$profile['high_risk_spend'],'validated_savings'=>$profile['validated_savings'],'demand_summary'=>'Quality demand evidence.','market_structure'=>'Quality market evidence.','supplier_panel'=>'Quality supplier panel evidence.','risk_summary'=>'Quality risk evidence.','inventory_alternatives'=>'Quality inventory evidence.','performance_summary'=>'Quality performance evidence.','negotiation_strategy'=>'Quality negotiation evidence.','sourcing_strategy'=>'Quality sourcing evidence.','target_terms'=>'Quality commercial terms.','strategy_decision'=>'consolidate_with_alternates','review_date'=>date('Y-m-d',strtotime('+30 days')),'renewal_date'=>date('Y-m-d',strtotime('+365 days')),'evidence_note'=>'Section 21 category strategy quality evidence.','submitted_at'=>null,'approved_at'=>null,'locked_at'=>null]);
$submitted=spend_strategy_submit_strategy($strategy);if($submitted['status']!=='submitted'||empty($submitted['approval_id'])){fwrite(STDERR,"Strategy submission failed.\n");exit(1);} $approved=spend_strategy_approve_strategy($submitted,'Independent Section 21 strategy approval evidence.');if($approved['status']!=='locked'){fwrite(STDERR,"Strategy lock failed.\n");exit(1);}
$action=spend_strategy_save_action(['id'=>null,'strategy_id'=>$approved['id'],'company_id'=>$approved['company_id'],'action_number'=>'ACT-QUALITY-021','action_type'=>'competitive_bid','title'=>'Run quality sourcing event','owner_id'=>3,'due_date'=>date('Y-m-d',strtotime('+45 days')),'status'=>'planned','planned_value'=>25000,'actual_value'=>0,'milestone'=>'Quality milestone evidence.','evidence_note'=>'Quality action evidence.','completed_at'=>null]);if((int)$action['id']<=0){fwrite(STDERR,"Strategy action failed.\n");exit(1);}
$plan=spend_strategy_save_plan(['id'=>null,'plan_number'=>'PLAN-QUALITY-021','company_id'=>(int)$cube[0]['company_id'],'fiscal_year'=>(int)date('Y'),'period_type'=>'annual','period_label'=>'Section 21 Quality Plan','period_start'=>$start,'period_end'=>$end,'version_number'=>1,'status'=>'draft','owner_id'=>3,'reviewer_id'=>6,'approval_id'=>null,'evidence_note'=>'Section 21 plan quality evidence.','submitted_at'=>null,'approved_at'=>null,'locked_at'=>null]);
$target=spend_strategy_recalculate_target(['id'=>null,'planning_period_id'=>$plan['id'],'company_id'=>$plan['company_id'],'metric_code'=>'spend_under_contract_pct','category_id'=>null,'supplier_id'=>null,'target_value'=>90,'actual_value'=>0,'variance_value'=>0,'variance_pct'=>0,'tolerance_pct'=>5,'status'=>'draft','owner_id'=>3,'root_cause'=>'Contract coverage quality assumption.','corrective_action'=>'Launch sourcing and contract actions for uncovered spend.','revised_forecast'=>85,'executive_decision'=>'Review after sourcing wave.','evidence_note'=>'Section 21 target quality evidence.'],$metrics);$target=spend_strategy_save_target($target);if((int)$target['id']<=0){fwrite(STDERR,"Plan target failed.\n");exit(1);}
$submittedPlan=spend_strategy_submit_plan($plan,$metrics);if($submittedPlan['status']!=='submitted'){fwrite(STDERR,"Plan submission failed.\n");exit(1);} $lockedPlan=spend_strategy_approve_plan($submittedPlan,'Independent Section 21 plan approval evidence.');if($lockedPlan['status']!=='locked'){fwrite(STDERR,"Plan lock failed.\n");exit(1);}
if(spend_strategy_csv_cell('=SUM(A1:A2)')!=="'=SUM(A1:A2)"){fwrite(STDERR,"CSV protection failed.\n");exit(1);}
$page=file_get_contents($root.'/app/spend-strategy.php');$handler=file_get_contents($root.'/app/spend-strategy-action.php');$sql=file_get_contents($root.'/database/20260727_section21_enterprise_spend_category_strategy_planning.sql');$reports=file_get_contents($root.'/app/reports.php');$dashboard=file_get_contents($root.'/app/dashboard.php');
foreach(['Enterprise Spend Analytics & Category Strategy','Enterprise spend cube','Category strategies','Procurement plans','Spend classifications','Strategy events'] as $needle)if(!str_contains($page,$needle)){fwrite(STDERR,"Workspace missing {$needle}.\n");exit(1);}foreach(['refresh_snapshot','save_strategy','submit_strategy','approve_strategy','save_plan','save_target','submit_plan','approve_plan'] as $needle)if(!str_contains($handler,$needle)){fwrite(STDERR,"Handler missing {$needle}.\n");exit(1);}foreach(['CREATE TABLE IF NOT EXISTS procurement_spend_snapshots','CREATE TABLE IF NOT EXISTS procurement_spend_classifications','CREATE TABLE IF NOT EXISTS procurement_category_strategies','CREATE TABLE IF NOT EXISTS procurement_category_strategy_actions','CREATE TABLE IF NOT EXISTS procurement_planning_periods','CREATE TABLE IF NOT EXISTS procurement_plan_targets','CREATE TABLE IF NOT EXISTS procurement_strategy_events','5.0-section21'] as $needle)if(!str_contains($sql,$needle)){fwrite(STDERR,"Migration missing {$needle}.\n");exit(1);}if(!str_contains($reports,'spend-strategy.php')||!str_contains($dashboard,'spend-strategy.php')){fwrite(STDERR,"Section 21 handoffs are missing.\n");exit(1);}if(str_contains($sql,'gruber_ai_procurement_single_install_v3')){fwrite(STDERR,"Section 21 migration must not reimport the fresh-install schema.\n");exit(1);}fwrite(STDOUT,"Section 21 enterprise spend, category strategy, planning, variance, and governance gates passed.\n");