<?php
declare(strict_types=1);
$root=dirname(__DIR__);$_SERVER['SCRIPT_NAME']='/gruber/app/operational-calendar.php';$_SERVER['REQUEST_METHOD']='GET';$_SERVER['REMOTE_ADDR']='127.0.0.1';$_SERVER['HTTP_USER_AGENT']='Section 27 quality test';require $root.'/includes/app/bootstrap.php';if(!demo_start_session(1)){fwrite(STDERR,"Could not start demo session.\n");exit(1);}require_once $root.'/includes/app/operational_calendar.php';
function s27(bool$condition,string$message):void{if(!$condition){fwrite(STDERR,"Section 27 failure: {$message}\n");exit(1);}}
function s27_user(int$id,int|string$company='enterprise'):void{$_SESSION['gruber_demo_user_id']=$id;$_SESSION['gruber_demo_company_id']=$company;}
function s27_runtime(callable$callback,string$message):void{try{$callback();s27(false,$message);}catch(RuntimeException){}}

s27(count(operational_calendar_tables())===8,'Section 27 must define eight governed tables.');
s27(count(permission_catalog()['operational_calendar']??[])===8,'Section 27 must expose eight dedicated application permissions.');
s27(count(operational_calendar_events())>=9,'Enterprise calendar must contain work deadlines and operating cadence.');
$created=operational_calendar_sync_work_items();$afterFirst=count(operational_calendar_events());$repeatCreated=operational_calendar_sync_work_items();s27($created>=0&&$repeatCreated===0&&count(operational_calendar_events())===$afterFirst,'Second work-item calendar synchronization must be idempotent.');
$private=array_values(array_filter(operational_calendar_events(),static fn(array$event):bool=>$event['visibility']==='private'));s27(count($private)===1,'System administrator must see the owned private event.');
$ics=operational_calendar_ics(array_slice(operational_calendar_events(),0,2));s27(str_starts_with($ics,'BEGIN:VCALENDAR')&&str_contains($ics,'BEGIN:VEVENT')&&str_ends_with($ics,"END:VCALENDAR\r\n"),'ICS export must be a complete calendar document.');
$first=operational_calendar_queue_notification(['id'=>null,'user_id'=>1,'entity_id'=>101,'work_item_id'=>1,'calendar_event_id'=>1,'notification_type'=>'test','severity'=>'warning','title'=>'Test notification','message'=>'Controlled test notification.','channel'=>'in_app','status'=>'queued','dedupe_key'=>hash('sha256','section27-dedupe'),'scheduled_at'=>date('Y-m-d H:i:s'),'sent_at'=>null,'read_at'=>null,'delivery_receipt_json'=>'{}']);$second=operational_calendar_queue_notification(['id'=>null,'user_id'=>1,'entity_id'=>101,'work_item_id'=>1,'calendar_event_id'=>1,'notification_type'=>'test','severity'=>'warning','title'=>'Duplicate','message'=>'Must not duplicate.','channel'=>'in_app','status'=>'queued','dedupe_key'=>hash('sha256','section27-dedupe'),'scheduled_at'=>date('Y-m-d H:i:s'),'sent_at'=>null,'read_at'=>null,'delivery_receipt_json'=>'{}']);s27((int)$first['id']===(int)$second['id'],'Notification queue must reject replay by dedupe key.');
$digestA=operational_calendar_generate_digest('daily');$digestB=operational_calendar_generate_digest('daily');s27((int)$digestA['id']===(int)$digestB['id'],'Digest generation must be idempotent by account and period.');
$subscription=operational_calendar_create_subscription('Section 27 test feed',['scope'=>'visible_events'],1);s27(strlen((string)$subscription['_token'])===48,'Calendar subscription must issue a strong one-time token.');s27(!hash_equals((string)$subscription['token_hash'],(string)$subscription['_token'])&&hash_equals((string)$subscription['token_hash'],hash('sha256',(string)$subscription['_token'])),'Calendar feed must persist only the token hash.');
s27_runtime(fn()=>operational_calendar_save_delegation(['id'=>null,'delegation_number'=>'DEL-SELF','source_user_id'=>1,'delegate_user_id'=>1,'entity_id'=>101,'permission_keys_json'=>['work_management.execute'],'starts_at'=>date('Y-m-d H:i:s'),'ends_at'=>date('Y-m-d H:i:s',strtotime('+1 day')),'status'=>'planned','reason'=>'Invalid self delegation','created_by'=>1,'reviewed_by'=>null,'approved_by'=>null,'activated_at'=>null,'revoked_at'=>null]),'Self-delegation must be rejected.');
$capacity=operational_calendar_capacity_snapshot();s27(count($capacity)>=1&&isset($capacity[0]['utilization_pct'],$capacity[0]['state']),'Capacity analytics must calculate utilization and state.');

s27_user(4,1);$allowed4=array_fill_keys(permitted_company_ids(),true);foreach(operational_calendar_events()as$event){s27(isset($allowed4[(int)$event['company_id']]),'Company administrator calendar must not expose unassigned companies.');s27($event['visibility']!=='private','Private executive event must not be visible to another user.');}
s27(count(operational_calendar_notifications())===0,'A user must not see another user’s Section 27 notification queue.');

s27_user(5,2);$allowed5=array_fill_keys(permitted_company_ids(),true);$events=operational_calendar_events();s27(count($events)>0,'Company contributor must see permitted work deadlines.');foreach($events as$event)s27(isset($allowed5[(int)$event['company_id']]),'Company contributor must not see sibling-company calendar events.');foreach(operational_calendar_delegations()as$delegation)s27((int)$delegation['source_user_id']===5||(int)$delegation['delegate_user_id']===5,'Delegations must remain personal unless calendar administration is granted.');

s27_user(1,'enterprise');$workspace=operational_calendar_agent_extend_workspace(work_management_agent_extend_workspace(['prompts'=>[],'lookups'=>[],'metrics'=>[],'briefing'=>['priorities'=>[]]]));s27(isset($workspace['metrics']['calendar_events'],$workspace['metrics']['over_capacity']),'Agent Workspace must include calendar and capacity metrics.');s27(($workspace['prompts'][0]['response_title']??'')==='Operational Calendar Agent','Agent Workspace must lead with the operational calendar briefing.');
$migration=file_get_contents($root.'/database/20260727_section27_operational_calendar_notifications_capacity.sql');foreach(operational_calendar_tables()as$table)s27(str_contains($migration,'CREATE TABLE IF NOT EXISTS '.$table),'Migration must create '.$table.'.');s27(str_contains($migration,"'5.6-section27'"),'Migration version must be recorded.');s27(str_contains($migration,"'operational_calendar.view'"),'Dedicated operational-calendar permissions must be seeded.');
$action=file_get_contents($root.'/app/operational-calendar-action.php');s27(str_contains($action,'verify_csrf'),'All Section 27 mutations must verify CSRF.');s27(str_contains($action,"action==='sync_work_items'"),'Work-deadline synchronization must be available only through the governed action endpoint.');s27(str_contains($action,"action==='create_subscription'"),'Expiring private feed creation must be available.');
echo "Section 27 operational calendar, notification, capacity, delegation, digest, export, and isolation tests passed.\n";