<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/app/bootstrap.php';
require_permission('approvals.view');
$user=require_app_user();
$statusFilter=query_string('status','all');$assignmentFilter=query_string('assigned','all');$overdueOnly=query_string('overdue')==='1';
$allApprovals=sort_records(data_visible_collection('workflow_approvals'),'submitted_at','desc');
$approvals=array_values(array_filter($allApprovals,static function(array $approval)use($statusFilter,$assignmentFilter,$overdueOnly,$user):bool{
    if($statusFilter!=='all'&&(string)($approval['status']??'')!==$statusFilter)return false;
    if($assignmentFilter==='me'&&(int)($approval['assigned_to']??0)!==(int)$user['id'])return false;
    if($overdueOnly&&(!in_array((string)($approval['status']??''),['pending','in_review'],true)||empty($approval['due_date'])||$approval['due_date']>=date('Y-m-d')))return false;
    return true;
}));
$selectedApprovalId=query_int('approval_id',(int)($approvals[0]['id']??0));$selected=null;foreach($allApprovals as $candidate)if((int)$candidate['id']===$selectedApprovalId){$selected=$candidate;break;}
if($selected&&!data_record_visible($selected))$selected=null;
$allComments=data_visible_collection('comments');$comments=[];
if($selected){foreach($allComments as $comment){$workflowComment=($comment['entity_type']??'')==='workflow_approval'&&(int)($comment['entity_id']??0)===(int)$selected['id'];$sourceComment=($comment['entity_type']??'')===($selected['entity_type']??'')&&(int)($comment['entity_id']??0)===(int)($selected['entity_id']??0);if($workflowComment||$sourceComment)$comments[]=$comment;}}
$comments=sort_records($comments,'created_at','asc');$prefillComment=query_string('body');
$pending=count(array_filter($allApprovals,fn($a)=>($a['status']??'')==='pending'));$overdue=count(array_filter($allApprovals,fn($a)=>in_array((string)($a['status']??''),['pending','in_review'],true)&&!empty($a['due_date'])&&$a['due_date']<date('Y-m-d')));
render_app_start('Reviews & Approvals','approvals','Evidence-based workflow','Review submitted records, validate evidence, request changes, approve outcomes, and preserve comments and audit history.','');
?>
<section class="metric-grid metric-grid-4"><article class="metric-card"><span>Visible approvals</span><strong><?= count($allApprovals) ?></strong><small><?= h(current_scope_label()) ?></small></article><article class="metric-card"><span>Pending</span><strong><?= $pending ?></strong><small>Awaiting action</small></article><article class="metric-card"><span>Assigned to me</span><strong><?= count(array_filter($allApprovals,fn($a)=>(int)($a['assigned_to']??0)===(int)$user['id']&&in_array((string)($a['status']??''),['pending','in_review'],true))) ?></strong><small>Personal review queue</small></article><article class="metric-card"><span>Overdue</span><strong><?= $overdue ?></strong><small>Pending past due date</small></article></section>
<section class="panel"><form class="filter-bar" method="get"><label><span>Status</span><select name="status"><?php foreach(['all'=>'All statuses','pending'=>'Pending','in_review'=>'In review','approved'=>'Approved','changes_requested'=>'Changes requested'] as $value=>$label): ?><option value="<?= h($value) ?>" <?= $statusFilter===$value?'selected':'' ?>><?= h($label) ?></option><?php endforeach; ?></select></label><label><span>Assignment</span><select name="assigned"><option value="all" <?= $assignmentFilter==='all'?'selected':'' ?>>All reviewers</option><option value="me" <?= $assignmentFilter==='me'?'selected':'' ?>>Assigned to me</option></select></label><label class="checkbox-inline"><input type="checkbox" name="overdue" value="1" <?= $overdueOnly?'checked':'' ?>><span>Overdue only</span></label><button class="button secondary" type="submit">Apply filters</button><a class="button ghost" href="<?= h(app_url('approvals.php')) ?>">Reset</a></form></section>
<div class="approval-layout"><section class="approval-queue" aria-label="Approval queue">
<?php foreach($approvals as $approval):$isSelected=$selected&&(int)$selected['id']===(int)$approval['id'];$isOverdue=in_array((string)$approval['status'],['pending','in_review'],true)&&!empty($approval['due_date'])&&$approval['due_date']<date('Y-m-d'); ?><article class="approval-card <?= $isSelected?'is-selected':'' ?>" id="approval-<?= (int)$approval['id'] ?>"><header><div><span><?= h(strtoupper((string)$approval['module'])) ?></span><h2><a href="<?= h(app_url('approvals.php?approval_id='.(int)$approval['id'])) ?>"><?= h($approval['title']) ?></a></h2><small><?= h(data_company_name($approval['company_id'])) ?> · Submitted <?= h(date_us($approval['submitted_at'],true)) ?> <?= sample_badge() ?></small></div><?= badge($approval['status']) ?></header><dl><div><dt>Submitted by</dt><dd><?= h(data_user_name($approval['submitted_by'])) ?></dd></div><div><dt>Assigned reviewer</dt><dd><?= h(data_user_name($approval['assigned_to'])) ?></dd></div><div><dt>Due</dt><dd class="<?= $isOverdue?'critical-text':'' ?>"><?= h(date_us($approval['due_date'])) ?><?= $isOverdue?' · Overdue':'' ?></dd></div><div><dt>Entity</dt><dd><?= h(status_label($approval['entity_type'])) ?> #<?= (int)$approval['entity_id'] ?></dd></div></dl><p><?= h($approval['notes']) ?></p><footer><a class="mini-button secondary" href="<?= h(app_url('approvals.php?approval_id='.(int)$approval['id'].'#reviewRecord')) ?>">Review record</a><?= workflow_actions('workflow_approvals',(int)$approval['id'],$approval['status'],'approvals','approvals.php?approval_id='.(int)$approval['id']) ?></footer></article><?php endforeach; ?>
<?php if(!$approvals): ?><?php render_empty_state('No approvals found','No approval requests match the selected filters and company scope.'); ?><?php endif; ?></section>
<aside class="approval-comments panel" id="reviewRecord"><header class="panel-head"><div><span class="eyebrow">Review record</span><h2><?= h($selected['title']??'Select an approval') ?></h2></div><span class="panel-meta"><?= count($comments) ?> comments</span></header>
<?php if(!$selected): ?><?php render_empty_state('No approval selected','Choose an approval from the queue to review its evidence and comments.'); ?><?php else: ?><dl class="detail-list"><div><dt>Decision status</dt><dd><?= badge($selected['status']) ?></dd></div><div><dt>Source record</dt><dd><?= h(status_label($selected['entity_type'])) ?> #<?= (int)$selected['entity_id'] ?></dd></div><div><dt>Reviewer</dt><dd><?= h(data_user_name($selected['assigned_to'])) ?></dd></div><div><dt>Due date</dt><dd><?= h(date_us($selected['due_date'])) ?></dd></div></dl><div class="comment-list"><?php foreach($comments as $comment): ?><article><span class="avatar"><?= h(initials(data_user_name($comment['user_id']))) ?></span><div><strong><?= h(data_user_name($comment['user_id'])) ?></strong><p><?= h($comment['body']) ?></p><small><?= h(date_us($comment['created_at'],true)) ?> · <?= h(status_label($comment['entity_type'])) ?> #<?= (int)$comment['entity_id'] ?></small></div></article><?php endforeach; ?><?php if(!$comments): ?><div class="dropdown-empty">No review comments have been recorded for this approval or its source record.</div><?php endif; ?></div>
<?php if(can('approvals.review')): ?><form class="comment-form" action="<?= h(app_url('action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="add_comment"><input type="hidden" name="return_to" value="approvals.php?approval_id=<?= (int)$selected['id'] ?>"><input type="hidden" name="company_id" value="<?= (int)$selected['company_id'] ?>"><input type="hidden" name="entity_type" value="workflow_approval"><input type="hidden" name="entity_id" value="<?= (int)$selected['id'] ?>"><label><span>Review comment</span><textarea name="body" rows="4" required maxlength="3000" placeholder="Add evidence, a question, or a decision note"><?= h($prefillComment) ?></textarea></label><button class="button primary full" type="submit">Add comment</button></form><?php endif; ?><?php endif; ?></aside></div>
<?php render_app_end(); ?>
