<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/app/bootstrap.php';
require_once dirname(__DIR__) . '/includes/app/contract_management.php';
require_app_user();
if(request_method()!=='POST')redirect_to(app_url('contracts.php'));
verify_csrf();

function contract_notify_user(int $userId,?int $companyId,string $title,string $message,string $severity='info'): void
{
    data_upsert('notifications',['id'=>null,'company_id'=>$companyId??data_default_company_id(current_user()),'user_id'=>$userId,'title'=>$title,'message'=>$message,'severity'=>$severity,'read'=>false,'created_at'=>date('Y-m-d H:i:s')]);
}
function contract_valid_date(string $value,bool $allowEmpty=false): ?string
{
    $value=trim($value);if($value===''&&$allowEmpty)return null;if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$value))throw new RuntimeException('Valid contract dates are required.');return $value;
}

try{
    $action=post_string('action');
    if($action==='save_contract'){
        require_permission('suppliers.edit');$id=post_int('id');$before=$id?contract_find_record($id):null;if($id&&!$before)throw new RuntimeException('The supplier contract is outside the active scope.');
        $supplierId=post_int('supplier_id');$supplier=data_find('suppliers',$supplierId);if(!$supplier)throw new RuntimeException('Select a valid supplier.');
        $companyRaw=post_string('company_id');$companyId=$companyRaw==='enterprise'||$companyRaw==='0'||$companyRaw===''?null:(int)$companyRaw;if(!data_company_within_scope($companyId))throw new RuntimeException('The selected company scope is not permitted.');
        $number=trim(post_string('number'));$title=trim(post_string('title'));$evidence=trim(post_string('evidence_note'));if($number===''||$title===''||$evidence==='')throw new RuntimeException('Contract number, title, and governance evidence are required.');
        $start=contract_valid_date(post_string('start_date'),true);$end=contract_valid_date(post_string('end_date'),true);if($start&&$end&&$end<$start)throw new RuntimeException('The contract end date cannot precede the start date.');
        $status=post_string('status',$before['status']??'draft');if(!in_array($status,contract_statuses(),true))$status='draft';
        $performance=contract_latest_performance($supplierId);$risk=(string)($performance['risk_tier']??$supplier['risk']??'medium');
        $record=['id'=>$id?:null,'supplier_id'=>$supplierId,'company_id'=>$companyId,'number'=>mb_substr($number,0,100),'title'=>mb_substr($title,0,240),'start_date'=>$start,'end_date'=>$end,'auto_renew'=>post_string('auto_renew')==='1','payment_terms'=>mb_substr(trim(post_string('payment_terms',$supplier['payment_terms']??'')),0,100),'freight_terms'=>mb_substr(trim(post_string('freight_terms')),0,160),'warranty_terms'=>mb_substr(trim(post_string('warranty_terms')),0,5000),'service_level_terms'=>mb_substr(trim(post_string('service_level_terms')),0,5000),'annual_value'=>max(0,(float)post_string('annual_value','0')),'status'=>$status,'document_path'=>mb_substr(trim(post_string('document_path')),0,500),'owner_id'=>max(1,post_int('owner_id')),'reviewer_id'=>max(1,post_int('reviewer_id')),'renewal_notice_days'=>max(0,min(365,post_int('renewal_notice_days'))),'review_status'=>$before['review_status']??'draft','risk_tier'=>$risk,'performance_review_id'=>$performance['id']??null,'approval_id'=>$before['approval_id']??null,'committed_spend'=>max(0,(float)post_string('committed_spend',(string)($before['committed_spend']??0))),'actual_spend'=>max(0,(float)post_string('actual_spend',(string)($before['actual_spend']??0))),'off_contract_spend'=>max(0,(float)post_string('off_contract_spend',(string)($before['off_contract_spend']??0))),'evidence_note'=>mb_substr($evidence,0,5000),'next_review_date'=>contract_valid_date(post_string('next_review_date'),true),'created_at'=>$before['created_at']??date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')];
        if($record['committed_spend']<=0)$record['committed_spend']=$record['annual_value'];if($record['actual_spend']<=0)$record['actual_spend']=contract_purchase_spend($record);
        $saved=contract_save_master($record);contract_add_event((int)$saved['id'],$before?'contract_updated':'contract_created','contract',(int)$saved['id'],$before['status']??null,$saved['status'],$risk,$before?'Contract terms and governance evidence updated.':'Supplier contract governance record created.');
        data_add_audit('Contracts',$before?'contract_updated':'contract_created','supplier_contract',$saved['id'],$before,$saved,$saved['company_id']);flash('success','Contract saved: '.$saved['number'].'.');redirect_to(app_url('contracts.php?id='.(int)$saved['id']));
    }
    if($action==='save_obligation'){
        require_permission('suppliers.edit');$id=post_int('id');$before=$id?contract_find_obligation($id):null;if($id&&!$before)throw new RuntimeException('The contract obligation is outside the active scope.');$contractId=post_int('contract_id');$contract=contract_find_record($contractId);if(!$contract)throw new RuntimeException('The supplier contract is outside the active scope.');
        $title=trim(post_string('title'));$evidence=trim(post_string('evidence_note'));if($title===''||$evidence==='')throw new RuntimeException('Obligation title and evidence are required.');$status=post_string('status',$before['status']??'not_started');if(!in_array($status,contract_obligation_statuses(),true))$status='not_started';$due=contract_valid_date(post_string('due_date'));
        $record=['id'=>$id?:null,'obligation_number'=>$before['obligation_number']??null,'contract_id'=>$contractId,'company_id'=>$contract['company_id'],'title'=>mb_substr($title,0,190),'obligation_type'=>mb_substr(post_string('obligation_type','service_level'),0,50),'owner_id'=>max(1,post_int('owner_id')),'due_date'=>$due,'status'=>$status,'target_value'=>(float)post_string('target_value','0'),'actual_value'=>(float)post_string('actual_value','0'),'unit'=>mb_substr(trim(post_string('unit','percent')),0,30),'evidence_note'=>mb_substr($evidence,0,5000),'completed_at'=>in_array($status,['met','waived','cancelled'],true)?($before['completed_at']??date('Y-m-d H:i:s')):null,'created_at'=>$before['created_at']??date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')];
        $saved=contract_save_obligation($record);$eventType=$status==='breached'?'obligation_breached':($before?'obligation_updated':'obligation_created');contract_add_event($contractId,$eventType,'obligation',(int)$saved['id'],$before['status']??null,$status,$status==='breached'?'critical':'medium',$saved['obligation_number'].' · '.$saved['evidence_note']);
        if($status==='breached'){contract_notify_user((int)$contract['owner_id'],$contract['company_id'],'Contract obligation breached',$saved['obligation_number'].' is breached for '.$contract['number'].'.','critical');}
        data_add_audit('Contracts',$eventType,'supplier_contract_obligation',$saved['id'],$before,$saved,$contract['company_id']);flash('success','Contract obligation saved: '.$saved['obligation_number'].'.');redirect_to(app_url('contracts.php?id='.$contractId));
    }
    if($action==='save_amendment'){
        require_permission('suppliers.edit');$id=post_int('id');$before=$id?contract_find_amendment($id):null;if($id&&!$before)throw new RuntimeException('The contract amendment is outside the active scope.');$contractId=post_int('contract_id');$contract=contract_find_record($contractId);if(!$contract)throw new RuntimeException('The supplier contract is outside the active scope.');
        $title=trim(post_string('title'));$beforeTerms=trim(post_string('before_terms'));$afterTerms=trim(post_string('after_terms'));$rationale=trim(post_string('rationale'));if($title===''||$beforeTerms===''||$afterTerms===''||$rationale==='')throw new RuntimeException('Amendment title, before terms, after terms, and rationale are required.');$status=post_string('status',$before['status']??'draft');if(!in_array($status,contract_amendment_statuses(),true))$status='draft';
        $record=['id'=>$id?:null,'amendment_number'=>$before['amendment_number']??null,'contract_id'=>$contractId,'company_id'=>$contract['company_id'],'title'=>mb_substr($title,0,190),'status'=>$status,'effective_date'=>contract_valid_date(post_string('effective_date')),'value_change'=>(float)post_string('value_change','0'),'term_change_days'=>post_int('term_change_days'),'before_terms'=>mb_substr($beforeTerms,0,5000),'after_terms'=>mb_substr($afterTerms,0,5000),'rationale'=>mb_substr($rationale,0,5000),'approval_id'=>$before['approval_id']??null,'created_by'=>(int)current_user()['id'],'created_at'=>$before['created_at']??date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')];
        $saved=contract_save_amendment($record);contract_add_event($contractId,$before?'amendment_updated':'amendment_created','amendment',(int)$saved['id'],$before['status']??null,$status,'medium',$saved['amendment_number'].' · '.$saved['rationale']);data_add_audit('Contracts',$before?'amendment_updated':'amendment_created','supplier_contract_amendment',$saved['id'],$before,$saved,$contract['company_id']);flash('success','Contract amendment saved: '.$saved['amendment_number'].'.');redirect_to(app_url('contracts.php?id='.$contractId));
    }
    if($action==='save_decision'){
        require_permission('suppliers.edit');$id=post_int('id');$before=$id?contract_find_decision($id):null;if($id&&!$before)throw new RuntimeException('The renewal decision is outside the active scope.');$contractId=post_int('contract_id');$contract=contract_find_record($contractId);if(!$contract)throw new RuntimeException('The supplier contract is outside the active scope.');
        $decision=post_string('decision','renegotiate');if(!in_array($decision,contract_renewal_decisions(),true))throw new RuntimeException('Select a valid renewal decision.');$rationale=trim(post_string('rationale'));$objectives=trim(post_string('negotiation_objectives'));$evidence=trim(post_string('evidence_note'));if($rationale===''||$objectives===''||$evidence==='')throw new RuntimeException('Decision rationale, negotiation objectives, and evidence are required.');$proposed=max(0,(float)post_string('proposed_annual_value',(string)$contract['annual_value']));$performance=contract_latest_performance((int)$contract['supplier_id']);
        $record=['id'=>$id?:null,'decision_number'=>$before['decision_number']??null,'contract_id'=>$contractId,'company_id'=>$contract['company_id'],'supplier_id'=>$contract['supplier_id'],'performance_review_id'=>$performance['id']??null,'decision'=>$decision,'status'=>$before['status']??'draft','owner_id'=>max(1,post_int('owner_id')),'reviewer_id'=>max(1,post_int('reviewer_id')),'approval_id'=>$before['approval_id']??null,'current_annual_value'=>(float)$contract['annual_value'],'proposed_annual_value'=>$proposed,'value_change'=>round($proposed-(float)$contract['annual_value'],2),'effective_date'=>contract_valid_date(post_string('effective_date')),'alternative_supplier_id'=>post_int('alternative_supplier_id')?:null,'rationale'=>mb_substr($rationale,0,5000),'negotiation_objectives'=>mb_substr($objectives,0,5000),'evidence_note'=>mb_substr($evidence,0,5000),'implemented_at'=>$before['implemented_at']??null,'created_at'=>$before['created_at']??date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')];
        $saved=contract_save_decision($record);contract_add_event($contractId,$before?'decision_updated':'decision_created','renewal_decision',(int)$saved['id'],$before['status']??null,$saved['status'],$contract['risk_tier'],$saved['decision_number'].' · '.$saved['evidence_note']);data_add_audit('Contracts',$before?'renewal_decision_updated':'renewal_decision_created','supplier_contract_renewal_decision',$saved['id'],$before,$saved,$contract['company_id']);flash('success','Renewal decision saved: '.$saved['decision_number'].'.');redirect_to(app_url('contracts.php?id='.$contractId));
    }
    if($action==='submit_decision'){
        require_permission('approvals.submit');$id=post_int('id');$decision=contract_find_decision($id);if(!$decision)throw new RuntimeException('The renewal decision is outside the active scope.');$contract=contract_find_record((int)$decision['contract_id']);if(!$contract)throw new RuntimeException('The supplier contract is outside the active scope.');if(!in_array(contract_decision_effective_status($decision),['draft','changes_requested'],true))throw new RuntimeException('This renewal decision is already routed or completed.');
        $approval=data_upsert('workflow_approvals',['id'=>null,'company_id'=>$contract['company_id']??data_default_company_id(current_user()),'module'=>'suppliers','entity_type'=>'supplier_contract_renewal_decision','entity_id'=>$id,'title'=>$contract['number'].' · '.status_label($decision['decision']),'submitted_by'=>(int)current_user()['id'],'assigned_to'=>(int)$decision['reviewer_id'],'status'=>'pending','submitted_at'=>date('Y-m-d H:i:s'),'due_date'=>date('Y-m-d',strtotime('+3 days')),'notes'=>'Review contract value, performance evidence, SLA breaches, obligations, amendments, notice deadlines, alternatives, commercial objectives, and proposed renewal action.']);
        $before=$decision;$decision['approval_id']=(int)$approval['id'];$decision['status']='submitted';$decision=contract_save_decision($decision);contract_add_event((int)$decision['contract_id'],'decision_submitted','renewal_decision',$id,$before['status'],'submitted',$contract['risk_tier'],'Renewal decision routed for human approval.');contract_notify_user((int)$decision['reviewer_id'],$contract['company_id'],'Contract renewal decision awaiting review',$decision['decision_number'].' requires review for '.$contract['number'].'.',$contract['risk_tier']);data_add_audit('Contracts','renewal_decision_submitted','supplier_contract_renewal_decision',$id,$before,$decision,$contract['company_id']);flash('success','Renewal decision routed to Reviews & Approvals.');redirect_to(app_url('contracts.php?id='.(int)$decision['contract_id']));
    }
    if($action==='implement_decision'){
        require_permission('suppliers.approve');$id=post_int('id');$decision=contract_find_decision($id);if(!$decision)throw new RuntimeException('The renewal decision is outside the active scope.');$contract=contract_find_record((int)$decision['contract_id']);if(!$contract)throw new RuntimeException('The supplier contract is outside the active scope.');$effective=contract_decision_effective_status($decision);if(contract_decision_requires_approval($decision,$contract)&&$effective!=='approved')throw new RuntimeException('Approve the renewal decision before implementation.');if($decision['status']==='implemented')throw new RuntimeException('This renewal decision is already implemented.');
        $beforeDecision=$decision;$beforeContract=$contract;$decision['status']='implemented';$decision['implemented_at']=date('Y-m-d H:i:s');$decision=contract_save_decision($decision);$contract['status']=match($decision['decision']){'terminate_for_cause'=>'terminated','expire_without_renewal'=>'expired','competitive_rebid','transition_alternate'=>'expiring',default=>'active'};$contract['review_status']='implemented';$contract['approval_id']=$decision['approval_id'];$contract['annual_value']=$decision['proposed_annual_value'];$contract=contract_save_master($contract);contract_add_event((int)$contract['id'],'decision_implemented','renewal_decision',$id,$beforeDecision['status'],'implemented',$contract['risk_tier'],'Implemented '.status_label($decision['decision']).' with approved commercial evidence.');contract_notify_user((int)$contract['owner_id'],$contract['company_id'],'Contract renewal decision implemented',$decision['decision_number'].' was implemented for '.$contract['number'].'.','info');data_add_audit('Contracts','renewal_decision_implemented','supplier_contract_renewal_decision',$id,['decision'=>$beforeDecision,'contract'=>$beforeContract],['decision'=>$decision,'contract'=>$contract],$contract['company_id']);flash('success','Renewal decision implemented.');redirect_to(app_url('contracts.php?id='.(int)$contract['id']));
    }
    throw new RuntimeException('Unknown contract-governance action.');
}catch(Throwable $exception){flash('error','The contract-governance action could not be completed: '.$exception->getMessage());redirect_to(app_url('contracts.php'));}
