<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/app/bootstrap.php';
require_once dirname(__DIR__) . '/includes/app/execution_management.php';
require_app_user();
if(request_method()!=='POST')redirect_to(app_url('executions.php'));
verify_csrf();

function execution_post_actual(array $existing=[]): array
{
    return [
        'recovery_value'=>max(0,(float)post_string('actual_recovery_value',(string)($existing['recovery_value']??0))),
        'cost'=>max(0,(float)post_string('actual_cost',(string)($existing['cost']??0))),
        'risk_score'=>max(0,min(100,(float)post_string('after_risk_score',(string)($existing['risk_score']??0)))),
        'lead_time_days'=>max(0,(int)post_string('after_lead_time_days',(string)($existing['lead_time_days']??0))),
        'inventory_exposure_reduced'=>max(0,(float)post_string('inventory_exposure_reduced',(string)($existing['inventory_exposure_reduced']??0))),
        'po_value_redirected'=>max(0,(float)post_string('po_value_redirected',(string)($existing['po_value_redirected']??0))),
        'service_level'=>max(0,min(100,(float)post_string('service_level_after',(string)($existing['service_level']??0)))),
    ];
}

function execution_notify(int $userId,?int $companyId,string $title,string $message,string $severity): void
{
    data_upsert('notifications',['id'=>null,'company_id'=>$companyId??data_default_company_id(current_user()),'user_id'=>$userId,'title'=>$title,'message'=>$message,'severity'=>$severity,'read'=>false,'created_at'=>date('Y-m-d H:i:s')]);
}

try{
    $action=post_string('action');
    if($action==='save_execution'){
        require_permission('savings.edit');$id=post_int('id');$before=$id?execution_find_record($id):null;if($id&&!$before)throw new RuntimeException('The execution record is outside the active scope.');
        $planId=post_int('plan_id');$actionId=post_int('action_id');$plan=mitigation_find_record($planId);$mitigationAction=mitigation_find_action($actionId);if(!$plan||!$mitigationAction||(int)$mitigationAction['plan_id']!==$planId)throw new RuntimeException('Select a valid mitigation plan action.');
        $blueprint=execution_blueprint($plan,$mitigationAction);$title=trim(post_string('title'));$evidence=trim(post_string('evidence_note'));$rollback=trim(post_string('rollback_plan'));if($title===''||$evidence===''||$rollback==='')throw new RuntimeException('Execution title, evidence requirements, and rollback plan are required.');
        $risk=post_string('change_risk',$blueprint['change_risk']);if(!in_array($risk,execution_risk_levels(),true))$risk=$blueprint['change_risk'];$scheduled=post_string('scheduled_date',$blueprint['scheduled_date']);if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$scheduled))throw new RuntimeException('A valid scheduled date is required.');
        $record=['id'=>$id?:null,'execution_number'=>$before['execution_number']??execution_next_number(),'company_id'=>$plan['company_id']??(current_company_id()==='enterprise'?null:(int)current_company_id()),'plan_id'=>$planId,'action_id'=>$actionId,'execution_type'=>$blueprint['execution_type'],'title'=>mb_substr($title,0,190),'owner_id'=>max(1,post_int('owner_id')),'status'=>$before['status']??'proposed','change_risk'=>$risk,'approval_id'=>$before['approval_id']??null,'before'=>$before['before']??$blueprint['before'],'target'=>$before['target']??$blueprint['target'],'actual'=>$before['actual']??[],'rollback_plan'=>mb_substr($rollback,0,5000),'evidence_note'=>mb_substr($evidence,0,5000),'scheduled_date'=>$scheduled,'started_at'=>$before['started_at']??null,'completed_at'=>$before['completed_at']??null,'created_at'=>$before['created_at']??date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')];
        $saved=execution_save_record($record);if(!$before)execution_add_event((int)$saved['id'],'created',null,'proposed','Execution record created from '.$plan['plan_number'].'.',['plan_id'=>$planId,'action_id'=>$actionId]);data_add_audit('Mitigation Execution',$before?'execution_updated':'execution_created','procurement_mitigation_execution',$saved['id'],$before,$saved,$saved['company_id']);flash('success','Execution record saved: '.$saved['execution_number'].'.');redirect_to(app_url('executions.php?id='.(int)$saved['id']));
    }
    if($action==='submit'){
        require_permission('approvals.submit');$id=post_int('id');$record=execution_find_record($id);if(!$record)throw new RuntimeException('The execution record is outside the active scope.');if(!execution_requires_approval($record))throw new RuntimeException('This change does not require approval and can be scheduled directly.');$status=execution_effective_status($record);if(!in_array($status,['proposed','changes_requested'],true))throw new RuntimeException('This change is already routed or executing.');
        $reviewerId=(int)current_user()['id'];foreach(data_admin_visible_users() as $candidate){if(($candidate['status']??'')==='active'&&can('approvals.review',$candidate)&&(int)$candidate['id']!==(int)current_user()['id']){$reviewerId=(int)$candidate['id'];break;}}$companyId=$record['company_id']??data_default_company_id(current_user());$metrics=execution_metrics($record);
        $approval=data_upsert('workflow_approvals',['id'=>null,'company_id'=>$companyId,'module'=>'reports','entity_type'=>'procurement_mitigation_execution','entity_id'=>$id,'title'=>$record['title'].' · '.$record['execution_number'],'submitted_by'=>(int)current_user()['id'],'assigned_to'=>$reviewerId,'status'=>'pending','submitted_at'=>date('Y-m-d H:i:s'),'due_date'=>date('Y-m-d',strtotime('+2 days')),'notes'=>'Review change risk, before/target snapshots, planned recovery of '.money($metrics['planned_recovery_value']).', planned cost of '.money($metrics['planned_cost']).', evidence requirements, owner, schedule, and rollback plan.']);
        $before=$record;$record['approval_id']=(int)$approval['id'];$record['status']='pending_approval';$record=execution_save_record($record);execution_add_event($id,'submitted',$status,'pending_approval','High-impact procurement change routed for approval.',['approval_id'=>$approval['id']]);execution_notify($reviewerId,$companyId,'Procurement change awaiting review',$record['execution_number'].' is a '.status_label($record['change_risk']).'-risk controlled change.',$record['change_risk']);data_add_audit('Mitigation Execution','submitted','procurement_mitigation_execution',$id,$before,$record,$companyId);flash('success','Execution change routed to Reviews & Approvals.');redirect_to(app_url('executions.php?id='.$id));
    }
    if($action==='start'){
        require_permission('savings.edit');$id=post_int('id');$record=execution_find_record($id);if(!$record)throw new RuntimeException('The execution record is outside the active scope.');$plan=mitigation_find_record((int)$record['plan_id']);if(!$plan)throw new RuntimeException('The source mitigation plan is unavailable.');if(mitigation_operational_status($plan)!=='active')throw new RuntimeException('Activate the mitigation plan before starting controlled execution.');if(!execution_can_start($record))throw new RuntimeException('This high-impact change must be approved before execution.');$from=execution_effective_status($record);if(!in_array($from,['proposed','approved','scheduled'],true))throw new RuntimeException('This execution cannot be started from its current state.');
        $before=$record;$record['status']='in_progress';$record['started_at']=date('Y-m-d H:i:s');$record=execution_save_record($record);execution_add_event($id,'started',$from,'in_progress','Execution owner started the controlled change.');execution_notify((int)$record['owner_id'],$record['company_id'],'Controlled procurement change started',$record['execution_number'].' is now in progress. Capture operational evidence before completion.',$record['change_risk']);data_add_audit('Mitigation Execution','started','procurement_mitigation_execution',$id,$before,$record,$record['company_id']);flash('success','Controlled execution started.');redirect_to(app_url('executions.php?id='.$id));
    }
    if($action==='update_progress'||$action==='complete'){
        require_permission('savings.edit');$id=post_int('id');$record=execution_find_record($id);if(!$record)throw new RuntimeException('The execution record is outside the active scope.');$from=execution_effective_status($record);if(!in_array($from,['in_progress','blocked'],true))throw new RuntimeException('Only active execution records can be updated.');$note=trim(post_string('evidence_note'));if($note==='')throw new RuntimeException('An execution evidence note is required.');$before=$record;$record['actual']=execution_post_actual($record['actual']??[]);$record['evidence_note']=mb_substr($note,0,5000);
        if($action==='complete'){$record['status']='completed';$record['completed_at']=date('Y-m-d H:i:s');$event='completed';$message='Execution completed. Recovery verification is now required.';}else{$newStatus=post_string('status',$from);if(!in_array($newStatus,['in_progress','blocked'],true))throw new RuntimeException('The selected progress status is invalid.');$record['status']=$newStatus;$event=$newStatus==='blocked'?'blocked':'progress_updated';$message='Execution progress updated.';}
        $record=execution_save_record($record);execution_add_event($id,$event,$from,$record['status'],$note,$record['actual']);$plan=mitigation_find_record((int)$record['plan_id']);if($record['status']==='blocked'&&$plan)execution_notify((int)$plan['owner_id'],$record['company_id'],'Execution blocker requires intervention',$record['execution_number'].' is blocked: '.$note,'high');if($record['status']==='completed'){foreach(data_admin_visible_users() as $candidate){if(($candidate['status']??'')==='active'&&can('approvals.review',$candidate)){execution_notify((int)$candidate['id'],$record['company_id'],'Recovery verification required',$record['execution_number'].' is complete and awaiting independent recovery verification.',$record['change_risk']);break;}}}data_add_audit('Mitigation Execution',$event,'procurement_mitigation_execution',$id,$before,$record,$record['company_id']);flash('success',$message);redirect_to(app_url('executions.php?id='.$id));
    }
    if($action==='verify'){
        require_permission('approvals.review');$id=post_int('id');$record=execution_find_record($id);if(!$record)throw new RuntimeException('The execution record is outside the active scope.');$from=execution_effective_status($record);if(!in_array($from,['completed','failed'],true))throw new RuntimeException('Complete the execution before recovery verification.');$status=post_string('verification_status','verified');if(!in_array($status,['verified','failed','needs_follow_up'],true))throw new RuntimeException('The verification outcome is invalid.');$note=trim(post_string('verification_evidence'));if($note==='')throw new RuntimeException('Independent verification evidence is required.');$actual=execution_post_actual($record['actual']??[]);$beforeSnapshot=$record['before'];$target=$record['target'];
        $verification=execution_save_verification(['id'=>null,'verification_number'=>execution_next_verification_number(),'company_id'=>$record['company_id'],'execution_id'=>$id,'status'=>$status,'planned_recovery_value'=>(float)($target['recovery_value']??0),'actual_recovery_value'=>$actual['recovery_value'],'planned_cost'=>(float)($target['cost']??0),'actual_cost'=>$actual['cost'],'before_risk_score'=>(float)($beforeSnapshot['risk_score']??0),'after_risk_score'=>$actual['risk_score'],'before_lead_time_days'=>(int)($beforeSnapshot['lead_time_days']??0),'after_lead_time_days'=>$actual['lead_time_days'],'inventory_exposure_reduced'=>$actual['inventory_exposure_reduced'],'po_value_redirected'=>$actual['po_value_redirected'],'service_level_before'=>(float)($beforeSnapshot['service_level']??0),'service_level_after'=>$actual['service_level'],'reviewer_id'=>(int)current_user()['id'],'evidence_note'=>mb_substr($note,0,5000),'verified_at'=>date('Y-m-d H:i:s'),'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);
        $before=$record;$record['actual']=$actual;$record['status']=$status==='verified'?'verified':($status==='failed'?'failed':'blocked');$record=execution_save_record($record);$event=$status==='verified'?'verified':($status==='failed'?'verification_failed':'follow_up_required');execution_add_event($id,$event,$from,$record['status'],$note,['verification_id'=>$verification['id']]);$plan=mitigation_find_record((int)$record['plan_id']);if($plan)execution_notify((int)$plan['owner_id'],$record['company_id'],'Recovery verification '.$status,$record['execution_number'].' verification result: '.status_label($status).'.',$status==='verified'?'low':'high');data_add_audit('Recovery Verification',$event,'procurement_recovery_verification',$verification['id'],$before,['execution'=>$record,'verification'=>$verification],$record['company_id']);flash('success','Recovery verification recorded: '.status_label($status).'.');redirect_to(app_url('executions.php?id='.$id));
    }
    if($action==='rollback'||$action==='cancel'){
        require_permission('savings.edit');$id=post_int('id');$record=execution_find_record($id);if(!$record)throw new RuntimeException('The execution record is outside the active scope.');$from=execution_effective_status($record);$isRollback=$action==='rollback';$allowed=$isRollback?['blocked','completed','verified','failed']:['proposed','pending','in_review','approved','scheduled','changes_requested'];if(!in_array($from,$allowed,true))throw new RuntimeException('This execution cannot be '.$action.'ed from its current state.');$note=trim(post_string($isRollback?'rollback_evidence':'cancel_evidence'));if($note==='')throw new RuntimeException(($isRollback?'Rollback':'Cancellation').' evidence is required.');$before=$record;$record['status']=$isRollback?'rolled_back':'cancelled';$record['evidence_note']=mb_substr($note,0,5000);$record=execution_save_record($record);execution_add_event($id,$record['status'],$from,$record['status'],$note,$isRollback?['rollback_plan'=>$record['rollback_plan']]:[]);data_add_audit('Mitigation Execution',$record['status'],'procurement_mitigation_execution',$id,$before,$record,$record['company_id']);flash('success',$isRollback?'The controlled change was rolled back and recorded.':'Execution record cancelled.');redirect_to(app_url('executions.php?id='.$id));
    }
    throw new RuntimeException('Unknown execution action.');
}catch(Throwable $exception){flash('error','The execution action could not be completed: '.$exception->getMessage());redirect_to(app_url('executions.php'));}
