<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/app/bootstrap.php';
require_once dirname(__DIR__).'/includes/app/executive_intelligence_governance.php';
require_app_user();
if(request_method()!=='POST'){http_response_code(405);exit('Method not allowed.');}
verify_csrf();$action=post_string('action');$return='executive-command.php';
try{
    if($action==='create_goal'){
        require_permission('executive_intelligence.create');$entity=post_int('entity_id')?:null;$number='GOAL-'.date('Y').'-'.str_pad((string)(count(executive_intelligence_goals())+1),4,'0',STR_PAD_LEFT);
        $goal=executive_intelligence_save_goal(['id'=>null,'goal_number'=>$number,'parent_goal_id'=>null,'entity_id'=>$entity,'company_id'=>executive_intelligence_company_id($entity),'goal_name'=>mb_substr(post_string('goal_name'),0,190),'description'=>mb_substr(post_string('description'),0,5000),'goal_type'=>post_string('goal_type','operational'),'unit'=>post_string('unit','%'),'direction'=>post_string('direction','higher_better'),'target_value'=>(float)post_string('target_value','0'),'period_start'=>post_string('period_start'),'period_end'=>post_string('period_end'),'owner_user_id'=>post_int('owner_user_id'),'reviewer_user_id'=>post_int('reviewer_user_id'),'executive_sponsor_user_id'=>post_int('executive_sponsor_user_id'),'status'=>'active','confidence_pct'=>post_int('confidence_pct',50),'evidence_note'=>mb_substr(post_string('evidence_note'),0,5000),'created_by'=>(int)current_user()['id']]);
        $definitionId=post_int('kpi_definition_id');if($definitionId){$definition=executive_intelligence_find_definition($definitionId);if(!$definition)throw new RuntimeException('Selected KPI is outside the active scope.');executive_intelligence_save_goal_link(['id'=>null,'goal_id'=>$goal['id'],'link_type'=>'kpi_definition','source_id'=>$definitionId,'relationship_label'=>'Primary KPI','created_by'=>(int)current_user()['id']]);if(!empty($definition['process_id']))executive_intelligence_save_goal_link(['id'=>null,'goal_id'=>$goal['id'],'link_type'=>'process','source_id'=>$definition['process_id'],'relationship_label'=>'Governing process','created_by'=>(int)current_user()['id']]);if(!empty($definition['process_step_id']))executive_intelligence_save_goal_link(['id'=>null,'goal_id'=>$goal['id'],'link_type'=>'process_step','source_id'=>$definition['process_step_id'],'relationship_label'=>'Measured process step','created_by'=>(int)current_user()['id']]);}
        flash('success','Governed goal created and connected to its KPI and process evidence.');$return.='?tab=goals';
    }elseif($action==='create_kpi'){
        require_permission('executive_intelligence.create');$entity=post_int('entity_id')?:null;$metricKey=post_string('metric_key');$catalog=executive_intelligence_metric_catalog();if(!isset($catalog[$metricKey]))throw new RuntimeException('Unsupported governed KPI metric.');$sourceModule=str_starts_with($metricKey,'process_')?'process_mapping':(str_starts_with($metricKey,'work_')||$metricKey==='critical_open_work'?'work_management':($metricKey==='over_capacity_count'?'operational_calendar':(str_starts_with($metricKey,'savings_')?'savings':(str_contains($metricKey,'supplier')?'suppliers':(str_contains($metricKey,'purchase_order')?'purchase_orders':'accounts_payable')))));
        $code='KPI-'.strtoupper(substr(hash('sha256',$metricKey.'|'.microtime(true)),0,10));$definition=executive_intelligence_save_definition(['id'=>null,'kpi_code'=>$code,'kpi_name'=>mb_substr(post_string('kpi_name'),0,190),'description'=>mb_substr(post_string('description'),0,5000),'entity_id'=>$entity,'company_id'=>executive_intelligence_company_id($entity),'source_module'=>$sourceModule,'metric_key'=>$metricKey,'process_id'=>post_int('process_id')?:null,'process_step_id'=>post_int('process_step_id')?:null,'owner_user_id'=>post_int('owner_user_id'),'data_owner_user_id'=>post_int('data_owner_user_id'),'refresh_frequency'=>'daily','status'=>'draft','active_version_id'=>null,'created_by'=>(int)current_user()['id']]);
        executive_intelligence_save_version(['id'=>null,'definition_id'=>$definition['id'],'version_number'=>'1.0','status'=>'draft','calculation_method'=>'Deterministic aggregation of approved visible records using metric '.$metricKey.'.','calculation_json'=>json_encode(['metric_key'=>$metricKey,'process_id'=>$definition['process_id'],'process_step_id'=>$definition['process_step_id'],'scope'=>'approved_visible_records'],JSON_UNESCAPED_SLASHES),'unit'=>$catalog[$metricKey]['unit'],'direction'=>post_string('direction',$catalog[$metricKey]['direction']),'target_value'=>(float)post_string('target_value','0'),'warning_value'=>(float)post_string('warning_value','0'),'critical_value'=>(float)post_string('critical_value','0'),'prepared_by'=>(int)current_user()['id'],'reviewed_by'=>post_int('reviewed_by'),'approved_by'=>post_int('approved_by'),'review_note'=>'','approval_note'=>'','evidence_note'=>mb_substr(post_string('evidence_note'),0,5000),'effective_from'=>date('Y-m-d'),'published_at'=>null,'locked_at'=>null]);
        flash('success','Draft KPI definition created with governed process binding. The assigned reviewer and approver must complete publication.');$return.='?tab=kpis';
    }elseif($action==='review_kpi_version'){
        executive_intelligence_review_version(post_int('version_id'),post_string('note'));flash('success','KPI methodology independently reviewed.');$return.='?tab=kpis';
    }elseif($action==='publish_kpi_version'){
        executive_intelligence_assert_publishable_version(post_int('version_id'));executive_intelligence_publish_version(post_int('version_id'),post_string('note'));flash('success','KPI version published and permanently locked.');$return.='?tab=kpis';
    }elseif($action==='snapshot_all'){
        require_permission('executive_intelligence.snapshot');$rows=executive_intelligence_generate_all_snapshots();flash('success',count($rows).' governed KPI snapshots generated or replayed safely.');$return.='?tab=kpis';
    }elseif($action==='create_scorecard'){
        $entity=post_int('entity_id')?:null;$card=executive_intelligence_generate_scorecard($entity,post_string('period_start'),post_string('period_end'),post_string('note'),post_int('reviewer_id'),post_int('approver_id'));flash('success',$card['scorecard_number'].' prepared for independent review.');$return.='?tab=scorecards';
    }elseif($action==='review_scorecard'){
        executive_intelligence_review_scorecard(post_int('scorecard_id'),post_string('note'));flash('success','Scorecard independently reviewed.');$return.='?tab=scorecards';
    }elseif($action==='publish_scorecard'){
        executive_intelligence_publish_scorecard(post_int('scorecard_id'),post_string('note'));flash('success','Scorecard published and permanently locked.');$return.='?tab=scorecards';
    }elseif($action==='create_review'){
        $review=executive_intelligence_create_review(post_int('scorecard_id'),post_int('entity_id'),post_string('review_type','weekly_operating_review'),str_replace('T',' ',post_string('meeting_start')),str_replace('T',' ',post_string('meeting_end')),post_string('agenda'),post_int('reviewer_id'),post_int('approver_id'));flash('success',$review['review_number'].' scheduled in the Section 27 operational calendar.');$return.='?tab=reviews';
    }elseif($action==='review_review'){
        executive_intelligence_review_review(post_int('review_id'),post_string('note'));flash('success','Executive review evidence confirmed by the independent reviewer.');$return.='?tab=reviews';
    }elseif($action==='publish_review'){
        executive_intelligence_publish_review(post_int('review_id'),post_string('note'));flash('success','Executive review published and locked.');$return.='?tab=reviews';
    }elseif($action==='record_decision'){
        $decision=executive_intelligence_record_decision(post_int('review_id'),post_int('goal_id')?:null,post_int('kpi_definition_id')?:null,post_string('decision_type','corrective_action'),post_string('title'),post_string('description'),post_int('owner_user_id'),str_replace('T',' ',post_string('due_at')),post_int('create_work',1)===1);flash('success',$decision['decision_number'].' recorded with governed work and calendar follow-up.');$return.='?tab=reviews';
    }else throw new RuntimeException('Unsupported executive-intelligence action.');
}catch(Throwable$exception){flash('error',$exception->getMessage());}
redirect_to(app_url($return));
