<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/app/bootstrap.php';
require_once dirname(__DIR__).'/includes/app/executive_intelligence_governance.php';
require_permission('executive_intelligence.view');
$definitions=executive_intelligence_kpi_definitions();
$actions='<a class="button secondary" href="'.h(app_url('executive-command.php?tab=kpis')).'">Back to KPI Catalog</a><a class="button secondary" href="'.h(app_url('process-maps.php')).'">Inspect Process Maps</a>';
render_app_start('KPI Definition Governance','executive-kpi-governance','Independent methodology review','Review and approve versioned KPI definitions without changing published Section 25 process maps or historical KPI snapshots.',$actions);
executive_intelligence_render_styles();
?>
<section class="exec-card"><span class="exec-eyebrow">Three-person control</span><h2>KPI versions awaiting review or approval</h2><div class="exec-list">
<?php $visible=0;foreach($definitions as$definition):foreach(executive_intelligence_kpi_versions((int)$definition['id'])as$version):if(!in_array($version['status'],['draft','reviewed'],true))continue;$visible++;$process=!empty($definition['process_id'])?process_mapping_find_process((int)$definition['process_id']):null;$step=!empty($definition['process_step_id'])?process_mapping_find_step((int)$definition['process_step_id']):null;?>
<article class="exec-row <?=h($version['status'])?>"><div><strong><?=h($definition['kpi_code'].' · '.$definition['kpi_name'].' · v'.$version['version_number'])?></strong><p><?=h($version['calculation_method'])?></p><small><?=h(($process['process_name']??status_label($definition['source_module'])).($step?' · '.$step['step_name']:''))?> · prepared <?=h(data_user_name((int)$version['prepared_by']))?> · reviewer <?=h(data_user_name((int)$version['reviewed_by']))?> · approver <?=h(data_user_name((int)$version['approved_by']))?></small></div><div><span class="exec-eyebrow">Target</span><strong><?=h(number_format((float)$version['target_value'],2).' '.$version['unit'])?></strong></div><div><span class="exec-eyebrow">Thresholds</span><strong><?=h(number_format((float)$version['warning_value'],2).' / '.number_format((float)$version['critical_value'],2))?></strong></div><div><?=badge($version['status'])?><div class="exec-actions" style="margin-top:8px"><?php if($version['status']==='draft'&&(int)$version['reviewed_by']===(int)current_user()['id']&&can('executive_intelligence.review')):?><form method="post" action="<?=h(app_url('executive-command-action.php'))?>"><?=csrf_field()?><input type="hidden" name="action" value="review_kpi_version"><input type="hidden" name="version_id" value="<?=(int)$version['id']?>"><input type="hidden" name="note" value="Calculation method, thresholds, source scope, and Section 25 process binding independently reviewed."><button class="button secondary" type="submit">Review</button></form><?php endif;?><?php if($version['status']==='reviewed'&&(int)$version['approved_by']===(int)current_user()['id']&&can('executive_intelligence.approve')):?><form method="post" action="<?=h(app_url('executive-command-action.php'))?>"><?=csrf_field()?><input type="hidden" name="action" value="publish_kpi_version"><input type="hidden" name="version_id" value="<?=(int)$version['id']?>"><input type="hidden" name="note" value="Approved for governed scorecards and permanently locked."><button class="button primary" type="submit">Publish</button></form><?php endif;?></div></div></article>
<?php endforeach;endforeach;?>
<?php if(!$visible)render_empty_state('No KPI versions awaiting governance','All visible KPI versions are either published or inactive.');?>
</div></section>
<?php render_app_end();?>
