<?php
declare(strict_types=1);
    if($action==='update_exception'){
        require_permission('purchase_orders.review');$exception=fulfillment_find_exception(post_int('id'));if(!$exception)throw new RuntimeException('The invoice exception is outside the active scope.');$invoice=fulfillment_find_invoice((int)$exception['invoice_id']);$status=post_string('status',$exception['status']);if(!in_array($status,fulfillment_exception_statuses(),true))throw new RuntimeException('Select a valid exception status.');$resolution=trim(post_string('resolution_note',$exception['resolution_note']));$waiver=trim(post_string('waiver_reason',$exception['waiver_reason']));if($status==='resolved'&&$resolution==='')throw new RuntimeException('Resolution evidence is required.');if($status==='waived'&&$waiver==='')throw new RuntimeException('A waiver rationale is required.');$before=$exception;$exception['status']=$status;$exception['resolution_note']=mb_substr($resolution,0,5000);$exception['waiver_reason']=mb_substr($waiver,0,5000);$exception['supplier_credit_amount']=max(0,(float)post_string('supplier_credit_amount',(string)$exception['supplier_credit_amount']));if($status==='waived'&&((float)$exception['disputed_amount']>=5000||in_array((string)$exception['severity'],['high','critical'],true))){$approval=data_upsert('workflow_approvals',['id'=>null,'company_id'=>$invoice['company_id'],'module'=>'purchase_orders','entity_type'=>'invoice_exception','entity_id'=>$exception['id'],'title'=>$exception['exception_number'].' waiver · '.money($exception['disputed_amount']),'submitted_by'=>(int)current_user()['id'],'assigned_to'=>$exception['reviewer_id'],'status'=>'pending','submitted_at'=>date('Y-m-d H:i:s'),'due_date'=>date('Y-m-d',strtotime('+2 days')),'notes'=>$waiver]);$exception['approval_id']=(int)$approval['id'];$exception['status']='pending_approval';fulfillment_notify((int)$exception['reviewer_id'],(int)$invoice['company_id'],'Invoice exception waiver review',$exception['exception_number'].' requests waiver of '.money($exception['disputed_amount']).'.','warning');}fulfillment_save_exception($exception);fulfillment_add_event((int)$exception['purchase_order_id'],(int)$exception['invoice_id'],'exception_updated','invoice_exception',(int)$exception['id'],$before['status'],$exception['status'],$exception['severity'],$resolution?:$waiver);data_add_audit('Fulfillment Governance','invoice_exception_updated','invoice_exception',$exception['id'],$before,$exception,$invoice['company_id']);flash('success','Invoice exception updated.');redirect_to(app_url('fulfillment.php?id='.(int)$exception['purchase_order_id'].'&invoice_id='.(int)$exception['invoice_id']));
    }
    if($action==='request_payment_release'){
        require_permission('approvals.submit');$invoice=fulfillment_find_invoice(post_int('invoice_id'));if(!$invoice)throw new RuntimeException('The invoice is outside the active scope.');$match=fulfillment_matches((int)$invoice['id'])[0]??null;if(!$match)throw new RuntimeException('Complete three-way matching before requesting payment release.');$exceptions=fulfillment_exceptions((int)$invoice['id']);if(!fulfillment_payment_release_ready($invoice,$match,$exceptions))throw new RuntimeException('Resolve or approve all material exceptions before payment release.');$approval=data_upsert('workflow_approvals',['id'=>null,'company_id'=>$invoice['company_id'],'module'=>'purchase_orders','entity_type'=>'supplier_invoice','entity_id'=>$invoice['id'],'title'=>$invoice['invoice_number'].' payment release · '.money($invoice['total_amount']),'submitted_by'=>(int)current_user()['id'],'assigned_to'=>$invoice['reviewer_id'],'status'=>'pending','submitted_at'=>date('Y-m-d H:i:s'),'due_date'=>date('Y-m-d',strtotime('+2 days')),'notes'=>'Validate PO, accepted receipt, invoice, contract terms, exceptions, credits, and payment-release evidence.']);$before=$invoice;$invoice['approval_id']=(int)$approval['id'];$invoice['status']='on_hold';$invoice['hold_reason']='Payment release is awaiting accounting approval.';fulfillment_save_invoice($invoice);fulfillment_add_event((int)$invoice['purchase_order_id'],(int)$invoice['id'],'payment_release_requested','supplier_invoice',(int)$invoice['id'],$before['status'],'on_hold','medium','Accounting approval requested with three-way match evidence.');fulfillment_notify((int)$invoice['reviewer_id'],(int)$invoice['company_id'],'Payment release approval',$invoice['invoice_number'].' requests release of '.money($invoice['total_amount']).'.','warning');data_add_audit('Fulfillment Governance','payment_release_requested','supplier_invoice',$invoice['id'],$before,$invoice,$invoice['company_id']);flash('success','Payment release routed to Reviews & Approvals.');redirect_to(app_url('fulfillment.php?id='.(int)$invoice['purchase_order_id'].'&invoice_id='.(int)$invoice['id']));
    }
    if($action==='release_payment'){
        require_permission('purchase_orders.approve');$invoice=fulfillment_find_invoice(post_int('invoice_id'));if(!$invoice)throw new RuntimeException('The invoice is outside the active scope.');$match=fulfillment_matches((int)$invoice['id'])[0]??null;if(!$match)throw new RuntimeException('A completed match is required.');if((int)($invoice['approval_id']??0)>0){$approval=data_find('workflow_approvals',(int)$invoice['approval_id']);if(!$approval||($approval['status']??'')!=='approved')throw new RuntimeException('Accounting approval is still required.');}if(!fulfillment_payment_release_ready($invoice,$match,fulfillment_exceptions((int)$invoice['id'])))throw new RuntimeException('Material exceptions remain unresolved.');$before=$invoice;$invoice['status']='approved_for_payment';$invoice['hold_reason']='';$invoice['released_at']=date('Y-m-d H:i:s');fulfillment_save_invoice($invoice);fulfillment_add_event((int)$invoice['purchase_order_id'],(int)$invoice['id'],'payment_released','supplier_invoice',(int)$invoice['id'],$before['status'],'approved_for_payment','low','Payment release approved from matched and resolved evidence.');data_add_audit('Fulfillment Governance','payment_released','supplier_invoice',$invoice['id'],$before,$invoice,$invoice['company_id']);flash('success','Invoice released for payment.');redirect_to(app_url('fulfillment.php?id='.(int)$invoice['purchase_order_id'].'&invoice_id='.(int)$invoice['id']));
    }
    if($action==='mark_paid'){
        require_permission('accounts_payable.execute');
        throw new RuntimeException('Direct paid-state updates are disabled. Record external settlement evidence in Accounts Payable so the canonical invoice is updated under dual control.');
    }
    if($action==='void_invoice'){
        require_permission('purchase_orders.approve');$invoice=fulfillment_find_invoice(post_int('invoice_id'));if(!$invoice)throw new RuntimeException('The invoice is outside the active scope.');if($invoice['status']==='paid')throw new RuntimeException('A paid invoice cannot be voided through this workflow.');$reason=trim(post_string('hold_reason'));if($reason==='')throw new RuntimeException('Void evidence is required.');$before=$invoice;$invoice['status']='void';$invoice['hold_reason']=mb_substr($reason,0,5000);fulfillment_save_invoice($invoice);fulfillment_add_event((int)$invoice['purchase_order_id'],(int)$invoice['id'],'invoice_voided','supplier_invoice',(int)$invoice['id'],$before['status'],'void','high',$reason);data_add_audit('Fulfillment Governance','invoice_voided','supplier_invoice',$invoice['id'],$before,$invoice,$invoice['company_id']);flash('success','Invoice voided with audit evidence.');redirect_to(app_url('fulfillment.php?id='.(int)$invoice['purchase_order_id']));
    }
