<?php
declare(strict_types=1);
    if($action==='save_fulfillment'){
        require_permission('purchase_orders.edit');$poId=post_int('purchase_order_id');$po=fulfillment_find_order($poId);if(!$po)throw new RuntimeException('The purchase order is outside the active company scope.');$status=post_string('shipment_status',$po['shipment_status']);if(!in_array($status,fulfillment_shipment_statuses(),true))throw new RuntimeException('Select a valid shipment status.');$evidence=trim(post_string('fulfillment_evidence'));if($evidence==='')throw new RuntimeException('Fulfillment evidence is required.');$ack=fulfillment_valid_datetime(post_string('supplier_acknowledged_at'),true);$before=fulfillment_profile_for_po($poId);
        $saved=fulfillment_save_profile(['id'=>$before['id']??null,'purchase_order_id'=>$poId,'owner_id'=>max(1,post_int('owner_id',(int)$po['owner_id'])),'reviewer_id'=>max(1,post_int('reviewer_id',(int)$po['reviewer_id'])),'shipment_status'=>$status,'asn_number'=>mb_substr(trim(post_string('asn_number')),0,100),'carrier'=>mb_substr(trim(post_string('carrier')),0,160),'tracking_number'=>mb_substr(trim(post_string('tracking_number')),0,160),'shipment_reference'=>mb_substr(trim(post_string('shipment_reference')),0,5000),'fulfillment_evidence'=>mb_substr($evidence,0,5000)]);
        if($ack){if(data_is_demo()){$po['supplier_acknowledged_at']=$ack;data_upsert('purchase_orders',$po);}else production_database_connection()->prepare('UPDATE purchase_orders SET supplier_acknowledged_at=?,updated_at=NOW() WHERE id=?')->execute([$ack,$poId]);}
        $eventType=$ack&&!($before['supplier_acknowledged_at']??null)?'supplier_acknowledged':'shipment_updated';fulfillment_add_event($poId,null,$eventType,'purchase_order',$poId,$before['shipment_status']??null,$status,$status==='delayed'?'high':'medium',$evidence);data_add_audit('Fulfillment Governance',$eventType,'purchase_order',$poId,$before,$saved,$po['company_id']);flash('success','Fulfillment status updated for '.$po['po_number'].'.');redirect_to(app_url('fulfillment.php?id='.$poId));
    }
    if($action==='save_receipt'){
        require_permission('inventory.create');$poId=post_int('purchase_order_id');$po=fulfillment_find_order($poId);if(!$po)throw new RuntimeException('The purchase order is outside the active company scope.');$poLine=fulfillment_find_po_line(post_int('purchase_order_line_id'));if(!$poLine||(int)$poLine['purchase_order_id']!==$poId)throw new RuntimeException('Select a valid purchase-order line.');$received=max(0,(float)post_string('quantity_received','0'));$accepted=max(0,(float)post_string('quantity_accepted','0'));$rejected=max(0,(float)post_string('quantity_rejected','0'));if($received<=0||abs(($accepted+$rejected)-$received)>.0001)throw new RuntimeException('Accepted plus rejected quantity must equal the received quantity.');$remaining=max(0,(float)$poLine['quantity_ordered']-(float)$poLine['quantity_received']);if($accepted>$remaining+.0001)throw new RuntimeException('Accepted quantity exceeds the remaining purchase-order quantity.');$condition=post_string('condition_status','accepted');if(!in_array($condition,fulfillment_conditions(),true))throw new RuntimeException('Select a valid receipt condition.');if($condition==='accepted'&&$rejected>0)throw new RuntimeException('Rejected quantity requires a damaged, incorrect, quality-hold, or returned condition.');if($condition!=='accepted'&&$rejected<=0)throw new RuntimeException('A non-accepted condition requires rejected or held quantity.');$locationId=post_int('location_id');if($locationId<=0)throw new RuntimeException('A receiving location is required.');$notes=trim(post_string('notes'));if($notes==='')throw new RuntimeException('Receipt inspection evidence is required.');$pdo=data_is_production()?production_database_connection():null;if($pdo)$pdo->beginTransaction();
        try{$receipt=fulfillment_save_receipt(['receipt_number'=>trim(post_string('receipt_number'))?:null,'purchase_order_id'=>$poId,'location_id'=>$locationId,'received_by'=>(int)current_user()['id'],'received_at'=>fulfillment_valid_datetime(post_string('received_at',date('Y-m-d H:i:s'))),'packing_slip_number'=>mb_substr(trim(post_string('packing_slip_number')),0,100),'carrier'=>mb_substr(trim(post_string('carrier',$po['carrier'])),0,160),'tracking_number'=>mb_substr(trim(post_string('tracking_number',$po['tracking_number'])),0,160),'notes'=>mb_substr($notes,0,5000)]);$line=fulfillment_save_receipt_line(['receipt_id'=>$receipt['id'],'purchase_order_line_id'=>$poLine['id'],'quantity_received'=>$received,'quantity_accepted'=>$accepted,'quantity_rejected'=>$rejected,'condition_status'=>$condition,'serial_or_lot_reference'=>mb_substr(trim(post_string('serial_or_lot_reference')),0,240),'notes'=>mb_substr($notes,0,5000)]);fulfillment_post_inventory($po,$poLine,$receipt,$line);if($rejected>0||$condition!=='accepted')fulfillment_record_quality_event($po,$poLine,$line);$profile=fulfillment_profile_for_po($poId)??['purchase_order_id'=>$poId,'owner_id'=>$po['owner_id'],'reviewer_id'=>$po['reviewer_id'],'asn_number'=>$po['asn_number'],'carrier'=>$po['carrier'],'tracking_number'=>$po['tracking_number'],'shipment_reference'=>$po['shipment_reference'],'fulfillment_evidence'=>$po['fulfillment_evidence']];$acceptedTotals=fulfillment_received_quantities($poId);$complete=true;foreach(fulfillment_po_lines($poId) as $candidate){if((float)($acceptedTotals[(int)$candidate['id']]['accepted']??0)+.0001<(float)$candidate['quantity_ordered']){$complete=false;break;}}$profile['shipment_status']=$complete?'received':'partially_received';$profile['fulfillment_evidence']=$notes;fulfillment_save_profile($profile);fulfillment_refresh_po_status($poId);fulfillment_add_event($poId,null,'receipt_created','receipt',(int)$receipt['id'],$po['status'],$profile['shipment_status'],$rejected>0?'high':'medium',$receipt['receipt_number'].' · accepted '.number_format($accepted,4).' · rejected '.number_format($rejected,4).'.');fulfillment_add_event($poId,null,'receipt_posted','receipt',(int)$receipt['id'],null,'posted','low','Only accepted quantity was posted to inventory.');if($pdo&&$pdo->inTransaction())$pdo->commit();}catch(Throwable $e){if($pdo&&$pdo->inTransaction())$pdo->rollBack();throw $e;}
        if($rejected>0){fulfillment_add_event($poId,null,'quality_exception','receipt_line',(int)$line['id'],'received',$condition,'high',$notes);fulfillment_notify((int)$po['reviewer_id'],(int)$po['company_id'],'Receipt quality exception',$po['po_number'].' has '.number_format($rejected,4).' rejected or held units.','warning');}data_add_audit('Fulfillment Governance','receipt_posted','receipt',$receipt['id'],null,['receipt'=>$receipt,'line'=>$line],$po['company_id']);flash('success','Receipt '.$receipt['receipt_number'].' posted; accepted inventory updated.');redirect_to(app_url('fulfillment.php?id='.$poId));
    }
