<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/app/bootstrap.php';
require_once dirname(__DIR__) . '/includes/data/import_engine.php';
require_permission('imports.view');
$jobs=sort_records(data_visible_collection('import_jobs'),'created_at','desc');
$visibleJobIds=array_map('intval',array_column($jobs,'id'));
$errors=array_values(array_filter(data_collection('import_validation_errors'),fn(array $error):bool=>in_array((int)$error['import_job_id'],$visibleJobIds,true)));
$receipts=array_values(array_filter(data_collection('import_receipts'),fn(array $receipt):bool=>in_array((int)$receipt['import_job_id'],$visibleJobIds,true)));
$jobFilter=query_int('job');$errorStatus=query_string('error_status','all');
$filteredErrors=array_values(array_filter($errors,static function(array $error)use($jobFilter,$errorStatus):bool{if($jobFilter>0&&(int)$error['import_job_id']!==$jobFilter)return false;if($errorStatus!=='all'&&(string)($error['status']??'open')!==$errorStatus)return false;return true;}));
$pageActions='';
if($errors&&can('imports.review'))$pageActions.='<a class="button secondary" href="'.h(app_url('import-errors-export.php?job='.$jobFilter.'&status='.rawurlencode($errorStatus))).'">Export validation errors</a>';
if(can('imports.create'))$pageActions.='<button class="button primary" type="button" data-modal-open="uploadImportModal">Upload source file</button>';
render_app_start(
    'Import & Data Quality Center','imports','Controlled data onboarding',
    'Upload CSV/XLSX files, map source columns, validate every row, resolve exceptions, and commit authorized changes with receipt evidence.',
    $pageActions
);
?>
<section class="metric-grid metric-grid-4">
<article class="metric-card"><span>Import jobs</span><strong><?= count($jobs) ?></strong><small><?= h(current_scope_label()) ?></small></article>
<article class="metric-card"><span>Total rows</span><strong><?= number_format(array_sum(array_column($jobs,'rows_total'))) ?></strong><small>Uploaded source rows</small></article>
<article class="metric-card"><span>Validation errors</span><strong><?= count(array_filter($errors,fn($e)=>in_array($e['status'],['open','review'],true))) ?></strong><small>Requires disposition</small></article>
<article class="metric-card"><span>Committed receipts</span><strong><?= count(array_filter($receipts,fn($r)=>!empty($r['committed_at']))) ?></strong><small>Immutable commit evidence</small></article>
</section>

<?php if(can('imports.create')): ?>
<div class="modal" id="uploadImportModal" hidden><div class="modal-backdrop" data-modal-close></div><section class="modal-card"><header><div><span class="eyebrow">Protected staging</span><h2>Upload procurement data</h2></div><button type="button" data-modal-close>×</button></header>
<form class="modal-body form-grid" action="<?= h(app_url('action.php')) ?>" method="post" enctype="multipart/form-data">
<?= csrf_field() ?><input type="hidden" name="action" value="upload_import"><input type="hidden" name="return_to" value="imports.php">
<label><span>Import type</span><select name="import_type" required><option value="supplier_master">Supplier master</option><option value="item_master">Item / SKU master</option><option value="purchase_orders">Purchase orders</option><option value="inventory_snapshot">Inventory snapshot</option></select></label>
<label><span>Company scope</span><select name="company_id" required><?= company_options(current_company_id(),can_use_enterprise_view()) ?></select></label>
<label class="span-2"><span>CSV or XLSX file</span><input type="file" name="import_file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required><small>Files are stored under protected import storage. The configured row and upload limits apply.</small></label>
<div class="span-2 modal-actions"><button class="button secondary" type="button" data-modal-close>Cancel</button><button class="button primary" type="submit">Upload and validate</button></div>
</form></section></div>
<?php endif; ?>

<section class="panel"><header class="panel-head"><div><span class="eyebrow">Import queue</span><h2>Source files and mappings</h2></div><span class="panel-meta">CSV / XLSX</span></header>
<?php if(!$jobs): ?><div class="empty-state"><strong>No imports yet</strong><p>Upload a source file to create a protected staging job.</p></div><?php else: ?><div class="import-job-grid">
<?php foreach($jobs as $job): $jobErrors=array_values(array_filter($errors,fn($e)=>(int)$e['import_job_id']===(int)$job['id'])); ?>
<article class="import-job-card"><header><div><span><?= h(strtoupper($job['type'])) ?></span><h3><?= h($job['name']) ?></h3><small><?= h($job['file_name']) ?> <?= sample_badge() ?></small></div><?= badge($job['status']) ?></header>
<div class="import-stats"><span><b><?= number_format($job['rows_total']) ?></b>Total</span><span><b><?= number_format($job['rows_valid']) ?></b>Valid</span><span><b><?= number_format($job['rows_error']) ?></b>Error rows</span></div>
<div class="import-integrity-row"><span><b>Checksum</b><code><?= h(substr((string)($job['checksum']??'not available'),0,16)) ?></code></span><span><b>Mapping</b><?= count($job['mapping']??[]) ?> fields</span><span><b>Validated</b><?= h(date_us($job['validation_summary']['validated_at']??null,true)) ?></span></div><div class="mapping-list"><?php if($job['mapping']):foreach($job['mapping'] as $source=>$target):?><span><code><?= h($source) ?></code><i>→</i><code><?= h($target) ?></code></span><?php endforeach;else:?><p>No mapping saved.</p><?php endif;?></div>
<footer><div class="row-actions"><?php if(can('imports.edit')):?><button class="mini-button secondary" type="button" data-modal-open="mappingModal<?= (int)$job['id'] ?>">Edit mapping</button><?php endif;?><?php if(can('imports.approve')&&in_array($job['status'],['ready','validating'],true)):?><form action="<?= h(app_url('action.php')) ?>" method="post" data-confirm="Commit this import to <?= data_is_demo()?'Demo Data':'Production Data' ?>? Production commits run inside a database transaction."><?= csrf_field() ?><input type="hidden" name="action" value="commit_import"><input type="hidden" name="id" value="<?= (int)$job['id'] ?>"><input type="hidden" name="return_to" value="imports.php"><button class="mini-button primary" type="submit" <?= count(array_filter($jobErrors,fn($e)=>in_array($e['status'],['open','review'],true)))?'disabled':'' ?>>Commit import</button></form><?php endif;?></div></footer></article>
<?php if(can('imports.edit')): ?><div class="modal" id="mappingModal<?= (int)$job['id'] ?>" hidden><div class="modal-backdrop" data-modal-close></div><section class="modal-card"><header><div><span class="eyebrow">Column mapper</span><h2><?= h($job['name']) ?></h2></div><button type="button" data-modal-close>×</button></header><form class="modal-body" action="<?= h(app_url('action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_import_mapping"><input type="hidden" name="id" value="<?= (int)$job['id'] ?>"><input type="hidden" name="return_to" value="imports.php"><div class="mapping-editor"><?php $sourceColumns=$job['mapping']?array_keys($job['mapping']):['Column A','Column B','Column C','Column D'];foreach($sourceColumns as $source):?><div><input name="source_columns[]" value="<?= h($source) ?>" readonly><span>→</span><select name="target_columns[]"><?php foreach(['','supplier_number','name','legal_name','website','category_id','payment_terms','status','risk','company_id','item_number','sku','description','uom','standard_cost','po_number','supplier_id','order_date','required_date','expected_date','total_amount','buyer_id','inventory_location_id','item_id','quantity_on_hand','average_unit_cost','last_usage_date'] as $target):?><option value="<?= h($target) ?>" <?= (($job['mapping'][$source]??'')===$target)?'selected':'' ?>><?= h($target?:'Ignore column') ?></option><?php endforeach;?></select></div><?php endforeach;?></div><div class="modal-actions"><button class="button secondary" type="button" data-modal-close>Cancel</button><button class="button primary" type="submit">Save mapping and validate</button></div></form></section></div><?php endif; ?>
<?php endforeach; ?></div><?php endif; ?></section>

<section class="panel"><header class="panel-head"><div><span class="eyebrow">Validation workbench</span><h2>Import validation errors</h2></div><span class="panel-meta"><?= count($filteredErrors) ?> visible issues</span></header><form class="filter-bar" method="get"><label><span>Import job</span><select name="job"><option value="0">All visible jobs</option><?php foreach($jobs as $job): ?><option value="<?= (int)$job['id'] ?>" <?= $jobFilter===(int)$job['id']?'selected':'' ?>><?= h($job['name']) ?></option><?php endforeach; ?></select></label><label><span>Status</span><select name="error_status"><?php foreach(['all'=>'All statuses','open'=>'Open','review'=>'Review','accepted'=>'Accepted','resolved'=>'Resolved'] as $value=>$label): ?><option value="<?= h($value) ?>" <?= $errorStatus===$value?'selected':'' ?>><?= h($label) ?></option><?php endforeach; ?></select></label><button class="button secondary" type="submit">Apply filters</button><a class="button ghost" href="<?= h(app_url('imports.php')) ?>">Reset</a></form><div class="table-wrap"><table class="data-table"><caption class="sr-only">Import validation errors for <?= h(current_scope_label()) ?></caption><thead><tr><th scope="col">Import</th><th scope="col">Row / field</th><th scope="col">Value</th><th scope="col">Error</th><th scope="col">Status</th><th scope="col">Disposition</th></tr></thead><tbody>
<?php foreach($filteredErrors as $error):$job=data_find('import_jobs',$error['import_job_id']);if(!$job||!data_record_visible($job))continue;?><tr><td><strong><?= h($job['name']) ?></strong></td><td>Row <?= (int)$error['row_number'] ?><small><?= h($error['field']) ?></small></td><td><code><?= h($error['value']?:'blank') ?></code></td><td><?= h($error['message']) ?></td><td><?= badge($error['status']) ?></td><td><?php if(can('imports.review')):?><div class="row-actions"><?php $states=in_array((string)($error['error_code']??''),import_security_error_codes(),true)?['review']:['review','accepted','resolved'];foreach($states as $state):?><form action="<?= h(app_url('action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="import_error_status"><input type="hidden" name="id" value="<?= (int)$error['id'] ?>"><input type="hidden" name="status" value="<?= h($state) ?>"><input type="hidden" name="return_to" value="imports.php"><button class="mini-button <?= $state==='resolved'?'primary':'ghost' ?>" type="submit"><?= h(status_label($state)) ?></button></form><?php endforeach;?></div><?php else:?>—<?php endif;?></td></tr><?php endforeach; ?>
<?php if(!$filteredErrors): ?><tr><td colspan="6"><?php render_empty_state('No validation errors','No import validation errors match the selected filters.'); ?></td></tr><?php endif; ?></tbody></table></div></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Commit evidence</span><h2>Import receipts</h2></div><span class="panel-meta">Immutable presentation</span></header><div class="receipt-grid"><?php foreach($receipts as $receipt):if(empty($receipt['committed_at']))continue;$job=data_find('import_jobs',$receipt['import_job_id']);?><article><span><?= h($receipt['receipt_number']) ?></span><h3><?= h($job['name']??'Import job') ?></h3><p>Created <?= number_format($receipt['records_created']) ?> · Updated <?= number_format($receipt['records_updated']) ?> · Skipped <?= number_format($receipt['records_skipped']) ?></p><code><?= h($receipt['hash']) ?></code><small><?= h(date_us($receipt['committed_at'],true)) ?> by <?= h(data_user_name($receipt['committed_by'])) ?></small></article><?php endforeach;?></div></section>
<?php render_app_end(); ?>
