<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/app/bootstrap.php';
require_permission('items.view');
$items=data_visible_collection('items');
$search=strtolower(query_string('q'));$status=query_string('status');$review=query_string('review');
$items=array_values(array_filter($items,static function(array $i)use($search,$status,$review):bool{
 if($search!==''&&!str_contains(strtolower($i['item_number'].' '.$i['sku'].' '.$i['description']),$search))return false;
 if($status!==''&&$i['status']!==$status)return false;if($review!==''&&$i['review_status']!==$review)return false;return true;
}));
$pagination=paginate_records(sort_records($items,'item_number'),query_int('page',1),9);
$actions=can('items.create')?'<button class="button primary" data-modal-open="itemModal" type="button">Create Item / SKU</button>':'';
render_app_start('Item / SKU Master','items','Standardized item data','Maintain normalized items, supplier SKUs, categories, units of measure, costs, company scope, and review evidence.',$actions);
?>
<section class="metric-grid metric-grid-4"><article class="metric-card"><span>Visible items</span><strong><?= count(data_visible_collection('items')) ?></strong><small><?= h(current_scope_label()) ?></small></article><article class="metric-card"><span>Approved</span><strong><?= count(array_filter(data_visible_collection('items'),fn($i)=>$i['review_status']==='approved')) ?></strong><small>Ready for approved-data workflows</small></article><article class="metric-card"><span>Needs review</span><strong><?= count(array_filter(data_visible_collection('items'),fn($i)=>in_array($i['review_status'],['submitted','changes_requested'],true))) ?></strong><small>Workflow queue</small></article><article class="metric-card"><span>Inventory positions</span><strong><?= count(data_visible_collection('inventory_snapshots')) ?></strong><small>Latest inventory snapshots</small></article></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Catalog governance</span><h2>Item and SKU records</h2></div><span class="panel-meta"><?= $pagination['total'] ?> matching records</span></header><form class="filter-bar" method="get"><label><span>Search</span><input name="q" value="<?= h(query_string('q')) ?>" placeholder="Item number, SKU, or description"></label><label><span>Status</span><select name="status"><option value="">All statuses</option><?php foreach(['active','draft','inactive'] as $value): ?><option value="<?= h($value) ?>" <?= $status===$value?'selected':'' ?>><?= h(status_label($value)) ?></option><?php endforeach; ?></select></label><label><span>Review</span><select name="review"><option value="">All review states</option><?php foreach(['draft','submitted','validated','approved','changes_requested'] as $value): ?><option value="<?= h($value) ?>" <?= $review===$value?'selected':'' ?>><?= h(status_label($value)) ?></option><?php endforeach; ?></select></label><button class="button secondary" type="submit">Apply filters</button><a class="button ghost" href="<?= h(app_url('items.php')) ?>">Reset</a></form><div class="table-wrap"><table class="data-table" data-table><caption class="sr-only">Item and SKU records for <?= h(current_scope_label()) ?></caption><thead><tr><th scope="col" data-sort>Item</th><th scope="col" data-sort>Category</th><th scope="col">Company scope</th><th scope="col" data-sort>UOM</th><th scope="col" class="numeric" data-sort>Standard cost</th><th scope="col" data-sort>Owner</th><th scope="col" data-sort>Status</th><th scope="col">Workflow</th></tr></thead><tbody><?php foreach($pagination['items'] as $item): $cat=data_find('categories',$item['category_id']); ?><tr><td><strong><?= h($item['item_number']) ?></strong><small><?= h($item['description']) ?> · SKU <?= h($item['sku']?:'—') ?> <?= sample_badge() ?></small></td><td><?= h($cat['name']??'Uncategorized') ?></td><td><div class="company-chip-row"><?php foreach($item['company_ids'] as $cid): ?><span><?= h(data_find('companies',$cid)['code']??$cid) ?></span><?php endforeach; ?></div></td><td><?= h($item['uom']) ?></td><td class="numeric"><strong><?= money($item['standard_cost']) ?></strong></td><td><?= h(data_user_name($item['owner_id'])) ?></td><td><?= badge($item['status']) ?><small><?= badge($item['review_status']) ?></small></td><td><?= workflow_actions('items',(int)$item['id'],$item['review_status'],'items','items.php') ?></td></tr><?php endforeach; ?><?php if(!$pagination['items']): ?><tr><td colspan="8"><?php render_empty_state('No items found','Adjust the filters or select another permitted company scope.'); ?></td></tr><?php endif; ?></tbody></table></div><?= render_pagination($pagination,['q'=>query_string('q'),'status'=>$status,'review'=>$review]) ?></section>
<?php if(can('items.create')): ?><div class="modal" id="itemModal" hidden><div class="modal-backdrop" data-modal-close></div><section class="modal-card"><header><div><span class="eyebrow">New item catalog record</span><h2>Create item / SKU</h2></div><button type="button" data-modal-close>×</button></header><form class="modal-body form-grid" action="<?= h(app_url('action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_item"><input type="hidden" name="return_to" value="items.php"><label><span>Item number</span><input name="item_number" required value="ITEM-<?= str_pad((string)data_next_id('items'),4,'0',STR_PAD_LEFT) ?>"></label><label><span>Supplier SKU</span><input name="sku"></label><label class="span-2"><span>Description</span><input name="description" required></label><label><span>Category</span><select name="category_id"><?= category_options(1) ?></select></label><label><span>Unit of measure</span><input name="uom" value="EA" maxlength="20" required></label><label><span>Standard cost</span><input type="number" min="0" step="0.01" name="standard_cost" value="0"></label><label><span>Owner</span><select name="owner_id"><?= user_options(current_user()['id']) ?></select></label><label><span>Status</span><select name="status"><option value="active">Active</option><option value="draft">Draft</option><option value="inactive">Inactive</option></select></label><div class="span-2"><span class="field-label">Company scope</span><?= company_checkbox_grid(current_company_id()==='enterprise'?[1]:[(int)current_company_id()]) ?></div><div class="span-2 modal-actions"><button class="button secondary" type="button" data-modal-close>Cancel</button><button class="button primary" type="submit">Create item</button></div></form></section></div><?php endif; ?>
<?php render_app_end(); ?>
