<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/app/bootstrap.php';
require_once dirname(__DIR__).'/includes/app/knowledge_adoption_governance.php';
require_app_user();
if(request_method()!=='POST'){http_response_code(405);exit('Method not allowed.');}
verify_csrf();$action=post_string('action');$return='knowledge-adoption.php';
try{
 if($action==='create_document'){
  require_permission('knowledge_adoption.create');$entity=post_int('entity_id')?:null;$row=knowledge_save_document(['id'=>null,'document_number'=>'DOC-'.date('Y').'-'.str_pad((string)(count(knowledge_documents())+1),4,'0',STR_PAD_LEFT),'title'=>mb_substr(post_string('title'),0,190),'document_type'=>post_string('document_type','policy'),'entity_id'=>$entity,'company_id'=>null,'owner_user_id'=>post_int('owner_user_id'),'reviewer_user_id'=>post_int('reviewer_user_id'),'approver_user_id'=>post_int('approver_user_id'),'purpose'=>mb_substr(post_string('purpose'),0,5000),'status'=>'draft','current_version_id'=>null,'created_by'=>(int)current_user()['id']]);flash('success',$row['document_number'].' created as a governed draft.');$return.='?tab=library';
 }elseif($action==='create_version'){
  require_permission('knowledge_adoption.create');$processId=post_int('process_id')?:null;$processVersionId=null;if($processId){$process=process_mapping_find_process($processId);$version=$process?process_mapping_process_version($process):null;$processVersionId=$version?(int)$version['id']:null;}$row=knowledge_save_version(['id'=>null,'document_id'=>post_int('document_id'),'version_number'=>mb_substr(post_string('version_number'),0,40),'status'=>'draft','effective_from'=>post_string('effective_from'),'effective_to'=>post_string('effective_to')?:null,'content'=>post_string('content'),'change_summary'=>post_string('change_summary'),'content_hash'=>'','source_initiative_id'=>post_int('source_initiative_id')?:null,'process_id'=>$processId,'process_version_id'=>$processVersionId,'process_step_id'=>post_int('process_step_id')?:null,'prepared_by'=>(int)current_user()['id'],'reviewed_by'=>post_int('reviewed_by'),'approved_by'=>post_int('approved_by'),'review_note'=>'','approval_note'=>'','submitted_at'=>null,'reviewed_at'=>null,'published_at'=>null,'locked_at'=>null]);flash('success','Policy version '.$row['version_number'].' created with governed source bindings.');$return.='?tab=versions';
 }elseif($action==='submit_version'){knowledge_submit_version(post_int('version_id'),post_string('note'));flash('success','Policy version submitted for independent review.');$return.='?tab=versions';
 }elseif($action==='review_version'){knowledge_review_version(post_int('version_id'),post_string('note'));flash('success','Policy version independently reviewed.');$return.='?tab=versions';
 }elseif($action==='publish_version'){knowledge_publish_governed_version(post_int('version_id'),post_string('note'));flash('success','Policy version published, hash-locked, and made effective.');$return.='?tab=versions';
 }elseif($action==='create_link'){require_permission('knowledge_adoption.edit');knowledge_create_link(post_int('version_id'),post_string('link_type'),post_int('source_id'),post_string('label'));flash('success','Governed policy source link created.');$return.='?tab=versions';
 }elseif($action==='create_impact'){
  require_permission('knowledge_adoption.create');$version=knowledge_find_version(post_int('version_id'));if(!$version)throw new RuntimeException('Policy version is outside the active scope.');$row=knowledge_save_impact(['id'=>null,'version_id'=>$version['id'],'initiative_id'=>post_int('initiative_id'),'process_id'=>$version['process_id']?:null,'process_step_id'=>$version['process_step_id']?:null,'entity_id'=>post_int('entity_id'),'company_id'=>0,'role_code'=>mb_substr(post_string('role_code'),0,80),'system_code'=>mb_substr(post_string('system_code'),0,80),'impact_level'=>post_string('impact_level','medium'),'impact_description'=>post_string('impact_description'),'required_action'=>post_string('required_action'),'status'=>'prepared','prepared_by'=>(int)current_user()['id'],'reviewed_by'=>post_int('reviewed_by'),'approved_by'=>post_int('approved_by'),'review_note'=>'','approval_note'=>'','reviewed_at'=>null,'approved_at'=>null,'locked_at'=>null]);flash('success','Change impact '.$row['id'].' prepared for independent review.');$return.='?tab=impact';
 }elseif($action==='review_impact'){knowledge_review_impact(post_int('impact_id'),post_string('note'));flash('success','Change impact independently reviewed.');$return.='?tab=impact';
 }elseif($action==='approve_impact'){knowledge_approve_impact(post_int('impact_id'),post_string('note'));flash('success','Change impact approved and locked.');$return.='?tab=impact';
 }elseif($action==='create_campaign'){
  require_permission('knowledge_adoption.create');$versionId=post_int('version_id');$entityId=post_int('entity_id');$sourceKey=hash('sha256','knowledge_campaign|'.$versionId.'|'.$entityId.'|'.strtolower(post_string('campaign_name')));$row=knowledge_create_governed_campaign(['id'=>null,'campaign_number'=>'CAM-'.date('Y').'-'.str_pad((string)(count(knowledge_campaigns())+1),4,'0',STR_PAD_LEFT),'version_id'=>$versionId,'entity_id'=>$entityId,'company_id'=>0,'campaign_name'=>mb_substr(post_string('campaign_name'),0,190),'delivery_mode'=>post_string('delivery_mode','self_paced'),'required_score'=>post_int('required_score',80),'due_at'=>str_replace('T',' ',post_string('due_at')),'renewal_days'=>post_int('renewal_days',0),'status'=>'active','owner_user_id'=>(int)current_user()['id'],'reviewer_user_id'=>post_int('reviewer_user_id'),'approver_user_id'=>post_int('approver_user_id'),'evidence_note'=>mb_substr(post_string('evidence_note'),0,5000),'source_key'=>$sourceKey,'published_at'=>date('Y-m-d H:i:s'),'closed_at'=>null]);flash('success',$row['campaign_number'].' launched from the immutable published policy version.');$return.='?tab=training';
 }elseif($action==='assign_training'){knowledge_assign_training(post_int('campaign_id'),post_int('assigned_user_id'),post_string('assigned_role_code'),post_int('validator_user_id'),post_int('create_work',0)===1);flash('success','Training assigned with governed work and calendar handoff.');$return.='?tab=training';
 }elseif($action==='submit_attestation'){knowledge_submit_attestation(post_int('assignment_id'),post_string('acknowledgement'),(float)post_string('quiz_score','0'),post_string('evidence_note'));flash('success','Learner attestation submitted for independent competency validation.');$return.='?tab=attestations';
 }elseif($action==='validate_attestation'){knowledge_validate_governed_attestation(post_int('attestation_id'),post_string('note'));flash('success','Competency evidence independently validated and locked.');$return.='?tab=attestations';
 }elseif($action==='request_waiver'){knowledge_request_waiver(post_int('assignment_id'),post_string('reason'),post_string('compensating_control'),post_int('reviewed_by'),post_int('approved_by'),str_replace('T',' ',post_string('expires_at')));flash('success','Time-limited waiver submitted with a compensating control.');$return.='?tab=waivers';
 }elseif($action==='review_waiver'){knowledge_review_waiver(post_int('waiver_id'),post_string('note'));flash('success','Waiver independently reviewed.');$return.='?tab=waivers';
 }elseif($action==='approve_waiver'){knowledge_approve_waiver(post_int('waiver_id'),post_string('note'));flash('success','Waiver approved, time-limited, and locked.');$return.='?tab=waivers';
 }elseif($action==='snapshot_adoption'){knowledge_snapshot_adoption(post_int('campaign_id'),post_string('note'));flash('success','Immutable adoption snapshot created.');$return.='?tab=adoption';
 }elseif($action==='generate_manifest'){knowledge_generate_governed_manifest(post_int('version_id'),post_string('note'));flash('success','Evidence manifest generated and hash-locked.');$return.='?tab=evidence';
 }else throw new RuntimeException('Unsupported knowledge and adoption action.');
}catch(Throwable$e){flash('error',$e->getMessage());}
redirect_to(app_url($return));
