<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/app/bootstrap.php';
$user=require_app_user();require_permission('platform.view');
$state=query_string('state','all');$severity=query_string('severity','all');
$all=array_values(array_filter(data_collection('notifications'),fn($n)=>(int)$n['user_id']===(int)$user['id']));$all=sort_records($all,'created_at','desc');
$notifications=array_values(array_filter($all,static function(array $n)use($state,$severity):bool{if($state==='unread'&&!empty($n['read']))return false;if($state==='read'&&empty($n['read']))return false;if($severity!=='all'&&(string)($n['severity']??'info')!==$severity)return false;return true;}));
$unread=count(array_filter($all,fn($n)=>empty($n['read'])));
function notification_destination(array $notification):string{$module=(string)($notification['module']??'');$id=(int)($notification['entity_id']??0);return match($module){'purchase_orders'=>app_url('purchase-orders.php?q='.rawurlencode((string)(data_find('purchase_orders',$id)['po_number']??''))),'inventory'=>app_url('inventory.php'),'suppliers'=>app_url('suppliers.php'),'savings'=>app_url('savings.php?edit='.$id),'approvals'=>app_url('approvals.php?approval_id='.$id),default=>app_url('dashboard.php')};}
$actions=$unread?'<form action="'.h(app_url('action.php')).'" method="post">'.csrf_field().'<input type="hidden" name="action" value="mark_notifications_read"><input type="hidden" name="return_to" value="notifications.php"><button class="button secondary" type="submit">Mark all read</button></form>':'';
render_app_start('Notifications','notifications','Personal activity center','Review workflow, data-quality, supplier, purchasing, and savings notifications for the active account.',$actions);
?>
<section class="metric-grid metric-grid-4"><article class="metric-card"><span>Total messages</span><strong><?= count($all) ?></strong><small>Current account</small></article><article class="metric-card"><span>Unread</span><strong><?= $unread ?></strong><small>Requires review</small></article><article class="metric-card"><span>Critical</span><strong><?= count(array_filter($all,fn($n)=>($n['severity']??'')==='critical')) ?></strong><small>Highest priority</small></article><article class="metric-card"><span>Visible</span><strong><?= count($notifications) ?></strong><small>Selected filters</small></article></section>
<section class="panel"><form class="filter-bar" method="get"><label><span>Read state</span><select name="state"><?php foreach(['all'=>'All messages','unread'=>'Unread','read'=>'Read'] as $value=>$label): ?><option value="<?= h($value) ?>" <?= $state===$value?'selected':'' ?>><?= h($label) ?></option><?php endforeach; ?></select></label><label><span>Severity</span><select name="severity"><?php foreach(['all'=>'All severities','critical'=>'Critical','warning'=>'Warning','info'=>'Information'] as $value=>$label): ?><option value="<?= h($value) ?>" <?= $severity===$value?'selected':'' ?>><?= h($label) ?></option><?php endforeach; ?></select></label><button class="button secondary" type="submit">Apply filters</button><a class="button ghost" href="<?= h(app_url('notifications.php')) ?>">Reset</a></form></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Notification center</span><h2><?= count($notifications) ?> visible messages</h2></div><span class="panel-meta"><?= $unread ?> unread</span></header><div class="notification-page-list"><?php foreach($notifications as $notification): ?><article class="<?= empty($notification['read'])?'unread':'' ?>"><i class="<?= h(status_class($notification['severity'])) ?>">!</i><div><header><strong><a href="<?= h(notification_destination($notification)) ?>"><?= h($notification['title']) ?></a></strong><?= badge($notification['severity']) ?></header><p><?= h($notification['message']) ?></p><small><?= h(date_us($notification['created_at'],true)) ?> · <?= h(status_label($notification['module'])) ?> <?= sample_badge() ?></small></div><div class="row-actions"><a class="mini-button ghost" href="<?= h(notification_destination($notification)) ?>">Open record</a><?php if(empty($notification['read'])): ?><form action="<?= h(app_url('action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="mark_notification_read"><input type="hidden" name="id" value="<?= (int)$notification['id'] ?>"><input type="hidden" name="return_to" value="notifications.php"><button class="mini-button secondary" type="submit">Mark read</button></form><?php endif; ?></div></article><?php endforeach; ?><?php if(!$notifications): ?><?php render_empty_state('No notifications found','No account notifications match the selected filters.'); ?><?php endif; ?></div></section>
<?php render_app_end(); ?>
