<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/app/bootstrap.php';
require_once dirname(__DIR__).'/includes/app/operational_calendar.php';
require_permission('operational_calendar.view');
if(query_string('export')==='ics')operational_calendar_export_ics();
if(query_string('export')==='csv')operational_calendar_export_csv();
$tab=query_string('tab','calendar');
$tabs=['calendar'=>'Operational Calendar','capacity'=>'Workload Capacity','notifications'=>'Notifications','delegation'=>'Delegation & Coverage','digests'=>'Digests & Cadence','settings'=>'Preferences & Feeds'];
if(!isset($tabs[$tab]))$tab='calendar';
$metrics=operational_calendar_metrics();$events=operational_calendar_events();$capacity=operational_calendar_capacity_snapshot();$notifications=operational_calendar_notifications();$delegations=operational_calendar_delegations();$digests=operational_calendar_digest_runs();$cadences=operational_calendar_cadences();$preferences=operational_calendar_preferences();$subscriptions=operational_calendar_subscriptions();
$actions='<a class="button secondary" href="'.h(app_url('work-management.php')).'">Work Command Center</a><a class="button secondary" href="'.h(app_url('agent.php?prompt='.rawurlencode('Create a morning operating summary from today’s work queue, calendar, notifications, delegation coverage, and workload capacity.'))).'">Analyze in Agent</a>';
if(can('operational_calendar.export'))$actions.='<a class="button ghost" href="'.h(app_url('operational-calendar.php?export=ics')).'">Export Calendar</a>';
render_app_start('Operational Calendar, Notifications & Capacity','operational-calendar','Enterprise operating cadence','Coordinate governed work deadlines, personal and team calendars, workload capacity, delegation coverage, notifications, and daily operating summaries.',$actions);
operational_calendar_render_styles();
?>
<section class="calendar-metrics"><article><span>Visible events</span><strong><?=$metrics['events']?></strong><small>Active company scope</small></article><article><span>Today</span><strong><?=$metrics['today']?></strong><small>Scheduled activity</small></article><article><span>Upcoming</span><strong><?=$metrics['upcoming']?></strong><small>Open calendar items</small></article><article><span>Unread alerts</span><strong><?=$metrics['unread_notifications']?></strong><small>Personal queue</small></article><article><span>Over capacity</span><strong><?=$metrics['over_capacity']?></strong><small>Critical utilization</small></article><article><span>Delegations</span><strong><?=$metrics['active_delegations']?></strong><small>Active coverage</small></article></section>
<nav class="calendar-tabs" aria-label="Operational calendar sections"><?php foreach($tabs as$key=>$label):?><a class="<?=$tab===$key?'active':''?>" href="<?=h(app_url('operational-calendar.php?tab='.$key))?>"><?=h($label)?></a><?php endforeach;?></nav>
<?php if($tab==='calendar'):?>
<div class="calendar-grid"><section class="panel"><header class="panel-head"><div><span class="eyebrow">Shared operating calendar</span><h2>Upcoming work and cadence</h2><p>Section 26 deadlines and Section 27 events share the same company and entity authorization boundary.</p></div><div class="row-actions"><?php if(can('operational_calendar.create')):?><form method="post" action="<?=h(app_url('operational-calendar-action.php'))?>"><?=csrf_field()?><input type="hidden" name="action" value="sync_work_items"><button class="button secondary" type="submit">Sync Work Deadlines</button></form><button class="button primary" type="button" data-modal-open="calendarEventModal">Create Event</button><?php endif;?></div></header><?php foreach($events as$event)operational_calendar_render_event($event);if(!$events)render_empty_state('No scheduled events','No calendar events are visible in the active company scope.');?></section><aside><section class="panel"><header class="panel-head"><div><span class="eyebrow">Operating cadence</span><h2>Governed routines</h2></div></header><?php foreach($cadences as$cadence):?><article class="calendar-event"><div class="calendar-time"><?=h(strtoupper($cadence['cadence_type']))?></div><div><h3><?=h($cadence['cadence_name'])?></h3><p><?=h(status_label($cadence['role_code']).' · '.$cadence['timezone'])?></p></div><?=badge($cadence['status'])?></article><?php endforeach;?></section></aside></div>
<?php if(can('operational_calendar.create')):?><div class="modal" id="calendarEventModal" hidden><div class="modal-backdrop" data-modal-close></div><section class="modal-card"><header><div><span class="eyebrow">Governed calendar event</span><h2>Create event</h2></div><button type="button" data-modal-close>×</button></header><form class="modal-body calendar-form-grid" method="post" action="<?=h(app_url('operational-calendar-action.php'))?>"><?=csrf_field()?><input type="hidden" name="action" value="create_event"><label><span>Operating entity</span><select name="entity_id" required><?php foreach(entity_system_entities()as$entity):if((int)($entity['company_id']??0)<=0)continue;?><option value="<?=(int)$entity['id']?>"><?=h($entity['entity_name'])?></option><?php endforeach;?></select></label><label><span>Event type</span><select name="event_type"><option value="meeting">Meeting</option><option value="deadline">Deadline</option><option value="focus_time">Focus time</option><option value="operating_cadence">Operating cadence</option></select></label><label class="span-2"><span>Title</span><input name="title" required maxlength="190"></label><label class="span-2"><span>Description</span><textarea name="description" required></textarea></label><label><span>Starts</span><input type="datetime-local" name="starts_at" required></label><label><span>Ends</span><input type="datetime-local" name="ends_at" required></label><label><span>Visibility</span><select name="visibility"><option value="company">Company</option><option value="team">Team</option><option value="private">Private</option></select></label><label><span>Location</span><input name="location"></label><button class="button primary span-2" type="submit">Create Event</button></form></section></div><?php endif;?>
<?php elseif($tab==='capacity'):?>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Capacity intelligence</span><h2>Workload and operating limits</h2><p>Estimated effort is derived from active Section 26 priority and compared with governed weekly capacity.</p></div></header><div class="capacity-grid"><?php foreach($capacity as$row):$profile=$row['profile'];?><article class="capacity-card <?=h($row['state'])?>"><span class="eyebrow"><?=h(data_company_name((int)$profile['company_id']))?></span><h3><?=h(data_user_name($row['user_id']))?></h3><strong><?=h(number_format((float)$row['utilization_pct'],1))?>%</strong><div class="capacity-meter"><i style="width:<?=min(100,(float)$row['utilization_pct'])?>%"></i></div><small><?=(int)$row['active_items']?> active items · <?=h(number_format((float)$row['estimated_hours'],1))?> estimated hours / <?=h(number_format((float)$profile['weekly_capacity_hours'],1))?> hours</small><?=badge($row['state'])?></article><?php endforeach;?></div></section>
<?php if(can('operational_calendar.manage_capacity')):?><section class="panel"><header class="panel-head"><div><span class="eyebrow">Capacity profile</span><h2>Set operating limits</h2></div></header><form class="calendar-form-grid" method="post" action="<?=h(app_url('operational-calendar-action.php'))?>"><?=csrf_field()?><input type="hidden" name="action" value="save_capacity"><label><span>User</span><select name="user_id"><?=user_options()?></select></label><label><span>Company</span><select name="company_id"><?=company_options()?></select></label><label><span>Weekly hours</span><input type="number" name="weekly_capacity_hours" value="40" min="1" max="80" step="0.5"></label><label><span>Daily hours</span><input type="number" name="daily_capacity_hours" value="8" min="1" max="24" step="0.5"></label><label><span>Maximum active items</span><input type="number" name="max_active_items" value="15" min="1" max="500"></label><label class="span-2"><span>Evidence</span><textarea name="evidence_note" required>Capacity reviewed against current role, operating calendar, active work mix, and expected availability.</textarea></label><button class="button primary span-2" type="submit">Save Capacity Profile</button></form></section><?php endif;?>
<?php elseif($tab==='notifications'):?>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Personal notification queue</span><h2><?=count($notifications)?> visible messages</h2><p>Notifications remain internal and adapter-gated until a configured delivery service records a receipt.</p></div></header><?php foreach($notifications as$notification):?><article class="notification-row-ops <?=h($notification['severity'])?>"><i></i><div><strong><?=h($notification['title'])?></strong><p><?=h($notification['message'])?></p><small><?=h(date_us($notification['scheduled_at'],true).' · '.status_label($notification['notification_type']).' · '.status_label($notification['channel']))?></small></div><?=badge($notification['status'])?></article><?php endforeach;?><?php if(!$notifications)render_empty_state('No queued notifications','No calendar or workload notifications are visible for the active account.');?></section>
<?php elseif($tab==='delegation'):?>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Out-of-office and backup coverage</span><h2>Active and planned delegation</h2><p>Delegation grants only listed permission keys for one visible entity and never changes identity or company membership.</p></div></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Delegation</th><th>Source</th><th>Delegate</th><th>Entity</th><th>Window</th><th>Status</th></tr></thead><tbody><?php foreach($delegations as$d):?><tr><td><strong><?=h($d['delegation_number'])?></strong><small><?=h($d['reason'])?></small></td><td><?=h(data_user_name((int)$d['source_user_id']))?></td><td><?=h(data_user_name((int)$d['delegate_user_id']))?></td><td><?=h(entity_system_find_entity((int)$d['entity_id'])['entity_name']??'')?></td><td><?=h(date_us($d['starts_at'],true))?><small>to <?=h(date_us($d['ends_at'],true))?></small></td><td><?=badge($d['status'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php if(can('operational_calendar.delegate')):?><section class="panel"><header class="panel-head"><div><span class="eyebrow">Governed coverage</span><h2>Create delegation</h2></div></header><form class="calendar-form-grid" method="post" action="<?=h(app_url('operational-calendar-action.php'))?>"><?=csrf_field()?><input type="hidden" name="action" value="create_delegation"><label><span>Source user</span><select name="source_user_id"><?=user_options((int)(current_user()['id']??0))?></select></label><label><span>Delegate user</span><select name="delegate_user_id"><?=user_options()?></select></label><label><span>Entity</span><select name="entity_id"><?php foreach(entity_system_entities()as$entity):if((int)($entity['company_id']??0)<=0)continue;?><option value="<?=(int)$entity['id']?>"><?=h($entity['entity_name'])?></option><?php endforeach;?></select></label><label><span>Permissions</span><input name="permission_keys" value="work_management.execute,purchase_orders.edit" required></label><label><span>Starts</span><input type="datetime-local" name="starts_at" required></label><label><span>Ends</span><input type="datetime-local" name="ends_at" required></label><label class="span-2"><span>Reason</span><textarea name="reason" required></textarea></label><button class="button primary span-2" type="submit">Create Delegation</button></form></section><?php endif;?>
<?php elseif($tab==='digests'):?>
<div class="calendar-grid"><section class="panel"><header class="panel-head"><div><span class="eyebrow">Operating summaries</span><h2>Generated digests</h2></div><div class="row-actions"><form method="post" action="<?=h(app_url('operational-calendar-action.php'))?>"><?=csrf_field()?><input type="hidden" name="action" value="generate_digest"><input type="hidden" name="digest_type" value="daily"><button class="button secondary" type="submit">Generate Daily</button></form><form method="post" action="<?=h(app_url('operational-calendar-action.php'))?>"><?=csrf_field()?><input type="hidden" name="action" value="generate_digest"><input type="hidden" name="digest_type" value="weekly"><button class="button secondary" type="submit">Generate Weekly</button></form></div></header><?php foreach($digests as$digest):?><article class="calendar-event"><div class="calendar-time"><?=h(strtoupper($digest['digest_type']))?></div><div><h3><?=h($digest['summary_text'])?></h3><small><?=h(date_us($digest['generated_at'],true))?> · <?=(int)$digest['item_count']?> work · <?=(int)$digest['event_count']?> events</small></div><?=badge($digest['status'])?></article><?php endforeach;?></section><aside><section class="panel"><header class="panel-head"><div><span class="eyebrow">Leadership rhythm</span><h2>Cadence catalog</h2></div></header><?php foreach($cadences as$cadence):?><article><strong><?=h($cadence['cadence_name'])?></strong><p><?=h(status_label($cadence['cadence_type']).' · '.status_label($cadence['role_code']))?></p></article><?php endforeach;?></section></aside></div>
<?php elseif($tab==='settings'):?>
<div class="calendar-grid"><section class="panel"><header class="panel-head"><div><span class="eyebrow">Notification preferences</span><h2>Personal delivery rules</h2></div></header><form class="calendar-form-grid" method="post" action="<?=h(app_url('operational-calendar-action.php'))?>"><?=csrf_field()?><input type="hidden" name="action" value="save_preferences"><label><span>Timezone</span><input name="timezone" value="<?=h($preferences['timezone']??'America/Phoenix')?>"></label><label><span>Minimum severity</span><select name="minimum_severity"><?php foreach(['info','warning','critical']as$severity):?><option value="<?=$severity?>" <?=($preferences['minimum_severity']??'info')===$severity?'selected':''?>><?=h(status_label($severity))?></option><?php endforeach;?></select></label><label><span>Quiet hours start</span><input type="time" name="quiet_hours_start" value="<?=h(substr((string)($preferences['quiet_hours_start']??'19:00'),0,5))?>"></label><label><span>Quiet hours end</span><input type="time" name="quiet_hours_end" value="<?=h(substr((string)($preferences['quiet_hours_end']??'07:00'),0,5))?>"></label><?php foreach(['email_enabled'=>'Email queue','in_app_enabled'=>'In-app alerts','daily_digest_enabled'=>'Daily digest','weekly_digest_enabled'=>'Weekly digest','morning_summary_enabled'=>'Morning summary','end_of_day_summary_enabled'=>'End-of-day summary']as$key=>$label):?><label><span><?=$label?></span><select name="<?=$key?>"><option value="1" <?=!isset($preferences[$key])||!empty($preferences[$key])?'selected':''?>>Enabled</option><option value="0" <?=isset($preferences[$key])&&empty($preferences[$key])?'selected':''?>>Disabled</option></select></label><?php endforeach;?><button class="button primary span-2" type="submit">Save Preferences</button></form></section><aside><section class="panel"><header class="panel-head"><div><span class="eyebrow">Private calendar feeds</span><h2>Subscriptions</h2></div></header><?php foreach($subscriptions as$subscription):?><article><strong><?=h($subscription['subscription_name'])?></strong><p>Token <?=h($subscription['token_prefix'])?>… · expires <?=h(date_us($subscription['expires_at']))?></p><?=badge($subscription['status'])?></article><?php endforeach;?><form method="post" action="<?=h(app_url('operational-calendar-action.php'))?>"><?=csrf_field()?><input type="hidden" name="action" value="create_subscription"><label><span>Feed name</span><input name="subscription_name" value="My governed operational calendar" required></label><button class="button secondary full" type="submit">Create Expiring Feed</button></form><p><small>Feed tokens are displayed once and stored only as SHA-256 hashes. No Google or Microsoft credentials are stored.</small></p></section></aside></div>
<?php endif;?>
<?php render_app_end();?>