<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/app/bootstrap.php';
require_once dirname(__DIR__) . '/includes/app/performance_management.php';
require_app_user();
if(request_method()!=='POST')redirect_to(app_url('performance.php'));
verify_csrf();

function performance_post_metrics(string $prefix,array $fallback=[]): array
{
    $result=[];foreach(['on_time_delivery','quality','responsiveness','cost_competitiveness','fill_rate','service_level','lead_time_variance_days','defect_rate_pct','price_variance_pct','corrective_closure_pct'] as $key){$value=(float)post_string($prefix.$key,(string)($fallback[$key]??0));if(!in_array($key,['lead_time_variance_days','defect_rate_pct','price_variance_pct'],true))$value=max(0,min(100,$value));else$value=max(0,$value);$result[$key]=$value;}return $result;
}
function performance_notify_user(int $userId,?int $companyId,string $title,string $message,string $severity): void
{
    data_upsert('notifications',['id'=>null,'company_id'=>$companyId??data_default_company_id(current_user()),'user_id'=>$userId,'title'=>$title,'message'=>$message,'severity'=>$severity,'read'=>false,'created_at'=>date('Y-m-d H:i:s')]);
}

try{
    $action=post_string('action');
    if($action==='save_review'){
        require_permission('scorecards.create');$id=post_int('id');$before=$id?performance_find_review($id):null;if($id&&!$before)throw new RuntimeException('The supplier performance review is outside the active scope.');
        $supplierId=post_int('supplier_id');$supplier=data_find('suppliers',$supplierId);if(!$supplier)throw new RuntimeException('Select a valid supplier.');$window=(int)post_string('review_window_days','30');if(!in_array($window,[30,60,90],true))$window=30;$execution=performance_source_execution($supplierId);$blueprint=performance_review_blueprint($supplier,$execution,$window);
        $baseline=$before['baseline']??performance_post_metrics('baseline_',$blueprint['baseline']);$current=performance_post_metrics('current_',$before['current']??$blueprint['current']);$targets=performance_post_metrics('target_',$before['targets']??$blueprint['targets']);$evidence=trim(post_string('evidence_note'));if($evidence==='')throw new RuntimeException('Performance evidence is required.');
        $periodEnd=post_string('period_end',date('Y-m-d'));$periodStart=post_string('period_start',date('Y-m-d',strtotime('-'.$window.' days')));$next=post_string('next_review_date',date('Y-m-d',strtotime('+30 days')));foreach([$periodStart,$periodEnd,$next] as $date)if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))throw new RuntimeException('Valid review dates are required.');
        $draft=['baseline'=>$baseline,'current'=>$current,'targets'=>$targets,'spend_exposure'=>max(0,(float)post_string('spend_exposure',(string)($before['spend_exposure']??$blueprint['spend_exposure']))),'savings_retained'=>max(0,(float)post_string('savings_retained',(string)($before['savings_retained']??$blueprint['savings_retained']))),'repeated_failure_count'=>max(0,post_int('repeated_failure_count'))];$metrics=performance_metrics($draft,$before?performance_actions($id):[]);
        $recommendation=post_string('recommendation',$metrics['recommendation']);if(!in_array($recommendation,performance_recommendations(),true))$recommendation=$metrics['recommendation'];$risk=post_string('risk_tier',$metrics['risk_tier']);if(!in_array($risk,performance_risk_tiers(),true))$risk=$metrics['risk_tier'];
        $record=['id'=>$id?:null,'review_number'=>$before['review_number']??performance_next_review_number(),'company_id'=>$before['company_id']??$blueprint['company_id'],'supplier_id'=>$supplierId,'source_execution_id'=>$before['source_execution_id']??((int)($execution['id']??0)?:null),'source_verification_id'=>$before['source_verification_id']??((int)($blueprint['verification']['id']??0)?:null),'review_window_days'=>$window,'period_start'=>$periodStart,'period_end'=>$periodEnd,'owner_id'=>max(1,post_int('owner_id')),'reviewer_id'=>max(1,post_int('reviewer_id')),'status'=>$before['status']??'draft','recommendation'=>$recommendation,'risk_tier'=>$risk,'approval_id'=>$before['approval_id']??null,'baseline'=>$baseline,'current'=>$current,'targets'=>$targets,'overall_score'=>$metrics['current_score'],'improvement_pct'=>$metrics['improvement_pct'],'sustainability_pct'=>$metrics['sustainability_pct'],'repeated_failure_count'=>$draft['repeated_failure_count'],'spend_exposure'=>$draft['spend_exposure'],'savings_retained'=>$draft['savings_retained'],'evidence_note'=>mb_substr($evidence,0,5000),'next_review_date'=>$next,'created_at'=>$before['created_at']??date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')];
        $saved=performance_save_review($record);performance_add_event((int)$saved['id'],$before?'review_updated':'review_created',null,null,null,null,$risk,$before?'Performance review evidence and current metrics updated.':'Supplier performance review created.');foreach($metrics['regressions'] as $regression){performance_add_event((int)$saved['id'],'metric_regression',$regression['metric'],$regression['before'],$regression['current'],$regression['threshold'],$regression['severity'],status_label($regression['metric']).' regressed against baseline or target.');}if($metrics['regression_count']>0){performance_notify_user((int)$saved['owner_id'],$saved['company_id'],'Supplier performance regression',$saved['review_number'].' identified '.$metrics['regression_count'].' supplier performance regressions.',$metrics['risk_tier']);}
        data_add_audit('Supplier Performance',$before?'performance_review_updated':'performance_review_created','supplier_performance_review',$saved['id'],$before,['review'=>$saved,'metrics'=>$metrics],$saved['company_id']);flash('success','Supplier performance review saved: '.$saved['review_number'].'.');redirect_to(app_url('performance.php?id='.(int)$saved['id']));
    }
    if($action==='submit'){
        require_permission('approvals.submit');$id=post_int('id');$review=performance_find_review($id);if(!$review)throw new RuntimeException('The performance review is outside the active scope.');$status=performance_effective_status($review);if(!in_array($status,['draft','changes_requested'],true))throw new RuntimeException('This review is already routed or monitoring.');$actions=performance_actions($id);$metrics=performance_metrics($review,$actions);if(!performance_requires_approval($review,$metrics))throw new RuntimeException('This review does not require approval and can enter monitoring directly.');
        $reviewerId=(int)$review['reviewer_id'];$companyId=$review['company_id']??data_default_company_id(current_user());$approval=data_upsert('workflow_approvals',['id'=>null,'company_id'=>$companyId,'module'=>'scorecards','entity_type'=>'supplier_performance_review','entity_id'=>$id,'title'=>data_supplier_name((int)$review['supplier_id']).' · '.$review['review_number'],'submitted_by'=>(int)current_user()['id'],'assigned_to'=>$reviewerId,'status'=>'pending','submitted_at'=>date('Y-m-d H:i:s'),'due_date'=>date('Y-m-d',strtotime('+2 days')),'notes'=>'Review supplier recommendation, risk tier, sustainability, repeated failures, spend exposure, recovery retention, regressions, corrective actions, evidence, and sourcing feedback.']);$before=$review;$review['approval_id']=(int)$approval['id'];$review['status']='submitted';$review=performance_save_review($review);performance_add_event($id,'submitted',null,null,null,null,$review['risk_tier'],'Supplier performance recommendation routed for approval.');performance_notify_user($reviewerId,$companyId,'Supplier recommendation awaiting review',$review['review_number'].' recommends '.status_label($review['recommendation']).' status for '.data_supplier_name((int)$review['supplier_id']).'.',$review['risk_tier']);data_add_audit('Supplier Performance','submitted','supplier_performance_review',$id,$before,$review,$companyId);flash('success','Supplier performance review routed to Reviews & Approvals.');redirect_to(app_url('performance.php?id='.$id));
    }
    if($action==='start_monitoring'){
        require_permission('scorecards.create');$id=post_int('id');$review=performance_find_review($id);if(!$review)throw new RuntimeException('The performance review is outside the active scope.');$metrics=performance_metrics($review,performance_actions($id));if(performance_requires_approval($review,$metrics)&&performance_effective_status($review)!=='approved')throw new RuntimeException('Approve the supplier recommendation before starting monitoring.');$from=performance_effective_status($review);if(!in_array($from,['draft','approved','changes_requested'],true))throw new RuntimeException('This review cannot enter monitoring from its current state.');$before=$review;$review['status']='monitoring';$review['risk_tier']=$metrics['risk_tier'];$review['recommendation']=$metrics['recommendation'];$review=performance_save_review($review);performance_add_event($id,'monitoring_started',null,null,null,null,$review['risk_tier'],'Continuous supplier monitoring started.');performance_notify_user((int)$review['owner_id'],$review['company_id'],'Supplier monitoring active',$review['review_number'].' is now monitoring '.data_supplier_name((int)$review['supplier_id']).'.',$review['risk_tier']);data_add_audit('Supplier Performance','monitoring_started','supplier_performance_review',$id,$before,$review,$review['company_id']);flash('success','Continuous supplier monitoring started.');redirect_to(app_url('performance.php?id='.$id));
    }
    if($action==='save_corrective_action'){
        require_permission('scorecards.create');$id=post_int('id');$before=$id?performance_find_action($id):null;if($id&&!$before)throw new RuntimeException('The corrective action is outside the active scope.');$reviewId=post_int('review_id');$review=performance_find_review($reviewId);if(!$review)throw new RuntimeException('The supplier performance review is outside the active scope.');$title=trim(post_string('title'));$root=trim(post_string('root_cause'));$corrective=trim(post_string('corrective_action'));$evidence=trim(post_string('evidence_note'));if($title===''||$root===''||$corrective===''||$evidence==='')throw new RuntimeException('Title, root cause, corrective action, and evidence are required.');$status=post_string('status',$before['status']??'planned');if(!in_array($status,performance_action_statuses(),true))$status='planned';$severity=post_string('severity',$before['severity']??'medium');if(!in_array($severity,['low','medium','high','critical'],true))$severity='medium';$due=post_string('due_date',$before['due_date']??date('Y-m-d',strtotime('+14 days')));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$due))throw new RuntimeException('A valid due date is required.');$metric=post_string('target_metric','on_time_delivery');if(!in_array($metric,['on_time_delivery','quality','responsiveness','cost_competitiveness','fill_rate','service_level','lead_time_variance_days','defect_rate_pct','price_variance_pct','corrective_closure_pct'],true))throw new RuntimeException('Select a valid target metric.');
        $record=['id'=>$id?:null,'action_number'=>$before['action_number']??performance_next_action_number(),'company_id'=>$review['company_id'],'review_id'=>$reviewId,'supplier_id'=>$review['supplier_id'],'title'=>mb_substr($title,0,190),'root_cause'=>mb_substr($root,0,5000),'corrective_action'=>mb_substr($corrective,0,5000),'owner_id'=>max(1,post_int('owner_id')),'status'=>$status,'severity'=>$severity,'due_date'=>$due,'target_metric'=>$metric,'target_value'=>(float)post_string('target_value','0'),'actual_value'=>(float)post_string('actual_value','0'),'evidence_note'=>mb_substr($evidence,0,5000),'completed_at'=>in_array($status,['completed','verified'],true)?($before['completed_at']??date('Y-m-d H:i:s')):null,'verified_at'=>$status==='verified'?date('Y-m-d H:i:s'):($before['verified_at']??null),'created_at'=>$before['created_at']??date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')];$saved=performance_save_action($record);performance_add_event($reviewId,$status==='verified'?'corrective_action_verified':($before?'corrective_action_updated':'corrective_action_created'),$metric,(float)($before['actual_value']??0),(float)$saved['actual_value'],(float)$saved['target_value'],$severity,$saved['action_number'].' · '.$saved['evidence_note']);if($status==='blocked')performance_notify_user((int)$review['owner_id'],$review['company_id'],'Supplier corrective action blocked',$saved['action_number'].' requires intervention for '.$review['review_number'].'.',$severity);data_add_audit('Supplier Performance',$before?'corrective_action_updated':'corrective_action_created','supplier_corrective_action',$saved['id'],$before,$saved,$review['company_id']);flash('success','Corrective action saved: '.$saved['action_number'].'.');redirect_to(app_url('performance.php?id='.$reviewId));
    }
    if($action==='close_review'){
        require_permission('scorecards.create');$id=post_int('id');$review=performance_find_review($id);if(!$review)throw new RuntimeException('The performance review is outside the active scope.');$actions=performance_actions($id);$readiness=performance_close_readiness($review,$actions);if(!$readiness['ready'])throw new RuntimeException('Verify or cancel every corrective action, maintain at least 80% sustainability, and clear critical regressions before closure.');$before=$review;$review['status']='closed';$review['risk_tier']=$readiness['metrics']['risk_tier'];$review['recommendation']=$readiness['metrics']['recommendation'];$review=performance_save_review($review);performance_add_event($id,'review_closed',null,null,null,null,$review['risk_tier'],'Continuous-improvement review closed with sustainable performance evidence.');data_add_audit('Supplier Performance','review_closed','supplier_performance_review',$id,$before,$review,$review['company_id']);flash('success','Supplier performance review closed.');redirect_to(app_url('performance.php?id='.$id));
    }
    throw new RuntimeException('Unknown supplier performance action.');
}catch(Throwable $exception){flash('error','The supplier performance action could not be completed: '.$exception->getMessage());redirect_to(app_url('performance.php'));}
