<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/app/bootstrap.php';
require_once dirname(__DIR__).'/includes/app/process_mapping.php';
require_permission('companies.view');
$tab=query_string('tab','live');$tabs=['live'=>'Live Map','designer'=>'Designer','catalog'=>'Catalog','instances'=>'Instances','analytics'=>'Analytics','governance'=>'Governance'];if(!isset($tabs[$tab]))$tab='live';
if(query_string('export')==='csv')process_mapping_export_csv();
$processes=process_mapping_processes();$processId=query_int('process_id')?:((int)($processes[0]['id']??0));$instances=process_mapping_instances($processId);$instanceId=query_int('instance_id')?:((int)($instances[0]['id']??0));$model=process_mapping_map_model($processId,$instanceId?:null);$metrics=process_mapping_metrics();$analytics=process_mapping_analytics();$catalog=process_mapping_template_catalog();$events=process_mapping_events();$allExceptions=process_mapping_exceptions();
$actions='<a class="button ghost" href="'.h(app_url('entity-system.php')).'">Business Entities</a>';if(can('reports.export'))$actions.='<a class="button secondary" href="'.h(app_url('process-maps.php?export=csv')).'">Export Catalog</a>';$actions.='<a class="button primary" href="'.h(app_url('agent.php?prompt='.rawurlencode('Analyze the visual enterprise process catalog, entity swimlanes, live process instances, overdue steps, exceptions, controls, integration events, bottlenecks, cycle times, and compliance gaps. Preserve canonical procurement records and recommend governed process improvements.'))).'">Analyze in Agent</a>';
render_app_start('Enterprise Process Mapping & Control Intelligence','process-maps','Visual operating models and live workflow intelligence','Design reusable cross-entity process maps, connect controls and integrations, and track real work through interactive swimlanes without replacing canonical operational records.',$actions);
process_mapping_render_styles();
?>
<section class="process-summary">
<article><span>Process maps</span><strong><?= number_format($metrics['processes']) ?></strong></article><article><span>Published</span><strong><?= number_format($metrics['published']) ?></strong></article><article><span>Active instances</span><strong><?= number_format($metrics['active_instances']) ?></strong></article><article><span>Open exceptions</span><strong><?= number_format($metrics['open_exceptions']) ?></strong></article><article><span>Overdue steps</span><strong><?= number_format($metrics['overdue_steps']) ?></strong></article><article><span>Touchless steps</span><strong><?= h(number_format($metrics['touchless_percent'],1)) ?>%</strong></article><article><span>Average cycle</span><strong><?= $metrics['average_cycle_seconds']?h(number_format($metrics['average_cycle_seconds']/3600,1)).'h':'—' ?></strong></article>
</section>
<nav class="tab-row" aria-label="Process mapping sections"><?php foreach($tabs as$key=>$label): ?><a class="<?= $tab===$key?'active':'' ?>" href="<?= h(app_url('process-maps.php?tab='.$key.'&process_id='.$processId.($instanceId?'&instance_id='.$instanceId:''))) ?>"><?= h($label) ?></a><?php endforeach; ?></nav>
<?php if($tab==='live'): ?>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Interactive swimlane</span><h2><?= h($model['process']['process_name']??'Process map') ?></h2><p><?= h($model['process']['value_chain']??'') ?></p></div><form method="get"><input type="hidden" name="tab" value="live"><label><span>Process</span><select name="process_id" onchange="this.form.submit()"><?php foreach($processes as$p): ?><option value="<?= (int)$p['id'] ?>" <?= (int)$p['id']===$processId?'selected':'' ?>><?= h($p['process_name']) ?></option><?php endforeach; ?></select></label><label><span>Instance</span><select name="instance_id" onchange="this.form.submit()"><option value="0">Definition only</option><?php foreach($instances as$i): ?><option value="<?= (int)$i['id'] ?>" <?= (int)$i['id']===$instanceId?'selected':'' ?>><?= h($i['instance_number'].' · '.$i['instance_title']) ?></option><?php endforeach; ?></select></label></form></header>
<div class="process-workspace-grid"><div><?php process_mapping_render_svg($model,false); ?></div><aside class="process-inspector" data-process-inspector><span class="eyebrow">Step inspector</span><h3 data-inspector-title>Select a step</h3><p>Click any visual node to inspect its live status, permission, SLA, evidence requirement, and canonical record type.</p><dl><div><dt>Type</dt><dd data-inspector-type>—</dd></div><div><dt>Status</dt><dd data-inspector-status>—</dd></div><div><dt>Permission</dt><dd data-inspector-permission>—</dd></div><div><dt>SLA</dt><dd data-inspector-sla>—</dd></div><div><dt>Evidence</dt><dd data-inspector-evidence>—</dd></div><div><dt>Canonical record</dt><dd data-inspector-record>—</dd></div></dl><?php if(!empty($model['instance'])): ?><hr><strong><?= h($model['instance']['instance_number']) ?></strong><p><?= h($model['instance']['instance_title']) ?></p><?= badge($model['instance']['status']) ?><?php endif; ?></aside></div></section>
<?php elseif($tab==='designer'): ?>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Drag-and-drop designer</span><h2><?= h($model['process']['process_name']??'Process designer') ?></h2><p>Move unlocked draft nodes, inspect controls, and save governed layout coordinates.</p></div><?= !empty($model['version'])?badge($model['version']['status']):'' ?></header><div class="process-palette"><button type="button" data-palette-type="task">＋ Task</button><button type="button" data-palette-type="approval">＋ Approval</button><button type="button" data-palette-type="gateway">◇ Gateway</button><button type="button" data-palette-type="integration">↔ Integration</button><button type="button" data-palette-type="exception">! Exception</button></div><div class="process-workspace-grid"><div><?php process_mapping_render_svg($model,true); ?><form action="<?= h(app_url('process-maps-action.php')) ?>" method="post" class="panel compact-form" data-layout-form><?= csrf_field() ?><input type="hidden" name="action" value="save_layout"><input type="hidden" name="version_id" value="<?= (int)($model['version']['id']??0) ?>"><input type="hidden" name="positions_json" value="{}" data-layout-json><label class="span-2"><span>Layout evidence</span><textarea name="evidence_note" required>Visual process layout reviewed against entity responsibilities, controls, and integration handoffs.</textarea></label><button class="button primary" type="submit" <?= (($model['version']['status']??'')==='published')?'disabled':'' ?>>Save Draft Layout</button></form></div><aside class="process-inspector" data-process-inspector><span class="eyebrow">Designer inspector</span><h3 data-inspector-title>Select a node</h3><dl><div><dt>Type</dt><dd data-inspector-type>—</dd></div><div><dt>Status</dt><dd data-inspector-status>—</dd></div><div><dt>Permission</dt><dd data-inspector-permission>—</dd></div><div><dt>SLA</dt><dd data-inspector-sla>—</dd></div><div><dt>Evidence</dt><dd data-inspector-evidence>—</dd></div><div><dt>Canonical record</dt><dd data-inspector-record>—</dd></div></dl><p>Published versions are permanently locked. Create a new draft version before changing a released operating model.</p></aside></div></section>
<?php elseif($tab==='catalog'): ?>
<section class="process-template-grid"><?php foreach($catalog as$code=>$template):$preview=process_mapping_template_preview($code); ?><article class="process-template-card"><span class="eyebrow"><?= h(status_label($template['category'])) ?></span><h3><?= h($template['name']) ?></h3><p><?= h($template['purpose']) ?></p><strong><?= h($template['value_chain']) ?></strong><ul><li><?= (int)$preview['lane_count'] ?> swimlanes</li><li><?= (int)$preview['step_count'] ?> governed steps</li><li><?= (int)$preview['transition_count'] ?> transitions</li><li><?= h(implode(', ',$template['modules'])) ?></li></ul><?php if(can('companies.administer')): ?><form action="<?= h(app_url('process-maps-action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="create_from_template"><input type="hidden" name="template_code" value="<?= h($code) ?>"><input type="hidden" name="reviewer_id" value="3"><input type="hidden" name="approver_id" value="6"><input type="hidden" name="evidence_note" value="Template preview validated against the Section 24 entity hierarchy, shared services, module authorities, and integration boundaries."><button class="button secondary full" type="submit">Create Governed Copy</button></form><?php endif; ?></article><?php endforeach; ?></section>
<?php elseif($tab==='instances'): ?>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Live operations</span><h2>Process instances</h2></div><?php if(can('companies.administer')): ?><button class="button primary" type="button" data-modal-open="startProcessModal">Start Process</button><?php endif; ?></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Instance</th><th>Process</th><th>Entity</th><th>Canonical record</th><th>Status</th><th>Due</th><th>Current step</th></tr></thead><tbody><?php foreach(process_mapping_instances() as$i):$p=process_mapping_find_process((int)$i['process_id']);$e=entity_system_find_entity((int)$i['entity_id']);$s=process_mapping_find_step((int)($i['current_step_id']??0)); ?><tr><td><a href="<?= h(app_url('process-maps.php?tab=live&process_id='.(int)$i['process_id'].'&instance_id='.(int)$i['id'])) ?>"><strong><?= h($i['instance_number']) ?></strong></a><small><?= h($i['instance_title']) ?></small></td><td><?= h($p['process_name']??'') ?></td><td><?= h($e['entity_name']??'') ?></td><td><?= h(status_label($i['canonical_record_type']).' #'.$i['canonical_record_id']) ?></td><td><?= badge($i['status']) ?></td><td><?= h(date_us($i['due_at'],true)) ?></td><td><?= h($s['step_name']??'Completed') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php if(can('companies.administer')): ?><div class="modal" id="startProcessModal" hidden><div class="modal-backdrop" data-modal-close></div><section class="modal-card"><header><div><span class="eyebrow">Live process instance</span><h2>Start process</h2></div><button type="button" data-modal-close>×</button></header><form class="modal-body form-grid" action="<?= h(app_url('process-maps-action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="start_instance"><label><span>Process</span><select name="process_id"><?php foreach($processes as$p):if($p['status']!=='published')continue; ?><option value="<?= (int)$p['id'] ?>"><?= h($p['process_name']) ?></option><?php endforeach; ?></select></label><label><span>Operating entity</span><select name="entity_id"><?php foreach(entity_system_entities() as$e): ?><option value="<?= (int)$e['id'] ?>"><?= h($e['entity_name']) ?></option><?php endforeach; ?></select></label><label><span>Canonical record type</span><input name="record_type" value="purchase_order" required></label><label><span>Canonical record ID</span><input type="number" name="record_id" value="1" required></label><label class="span-2"><span>Instance title</span><input name="instance_title" value="New governed process instance" required></label><label class="span-2"><span>Start evidence</span><textarea name="evidence_note" required>Process started from an authorized canonical record and assigned entity.</textarea></label><div class="span-2 modal-actions"><button class="button primary" type="submit">Start Process</button></div></form></section></div><?php endif; ?>
<?php elseif($tab==='analytics'): ?>
<section class="process-analytics-grid"><article class="panel"><header class="panel-head"><div><span class="eyebrow">Process performance</span><h2>Volume and completion</h2></div></header><?php foreach($analytics['by_process'] as$name=>$row): ?><div class="metric-row"><div><strong><?= h($name) ?></strong><small><?= (int)$row['volume'] ?> instances · <?= h(number_format($row['completion_percent'],1)) ?>% completed</small></div><div class="process-bar"><i style="width:<?= min(100,(float)$row['completion_percent']) ?>%"></i></div></div><?php endforeach; ?></article><article class="panel"><header class="panel-head"><div><span class="eyebrow">Control intelligence</span><h2>Bottleneck steps</h2></div></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Step</th><th>Average time</th><th>Exceptions</th></tr></thead><tbody><?php foreach(array_slice($analytics['bottlenecks'],0,10,true) as$name=>$row): ?><tr><td><?= h($name) ?></td><td><?= h(number_format($row['average_seconds']/3600,1)) ?> hours</td><td><?= (int)$row['exceptions'] ?></td></tr><?php endforeach; ?></tbody></table></div></article></section>
<?php elseif($tab==='governance'): ?>
<section class="process-analytics-grid"><article class="panel"><header class="panel-head"><div><span class="eyebrow">Exceptions</span><h2>Process control exceptions</h2></div></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Type</th><th>Instance</th><th>Severity</th><th>Status</th><th>Owner / reviewer</th></tr></thead><tbody><?php foreach($allExceptions as$e):$i=process_mapping_find_instance((int)$e['instance_id']); ?><tr><td><strong><?= h(status_label($e['exception_type'])) ?></strong><small><?= h($e['exception_description']) ?></small></td><td><?= h($i['instance_number']??'') ?></td><td><?= badge($e['severity']) ?></td><td><?= badge($e['status']) ?></td><td><?= h(data_user_name($e['owner_id']).' / '.data_user_name($e['reviewer_id'])) ?></td></tr><?php endforeach; ?></tbody></table></div></article><article class="panel"><header class="panel-head"><div><span class="eyebrow">Immutable history</span><h2>Recent process events</h2></div></header><div class="timeline-list"><?php foreach(array_slice($events,0,12) as$event): ?><article><i class="process-status-dot <?= h($event['to_status']??'') ?>"></i><div><strong><?= h(status_label($event['event_type'])) ?></strong><p><?= h($event['evidence_note']) ?></p><small><?= h(date_us($event['created_at'],true).' · '.data_user_name($event['created_by'])) ?></small></div></article><?php endforeach; ?></div></article></section>
<?php endif; ?>
<script src="<?= h(app_url('assets/js/process-maps.js?v=20260727-section25')) ?>" defer></script>
<?php render_app_end();
