<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/app/bootstrap.php';
require_permission('scorecards.view');

$allScorecards = sort_records(data_visible_collection('supplier_scorecards'),'overall','desc');
$search = strtolower(trim(query_string('q')));
$performance = query_string('performance');
$status = query_string('status');
$scorecards = array_values(array_filter($allScorecards, static function(array $score) use ($search,$performance,$status): bool {
    $supplier = data_find('suppliers',(int)($score['supplier_id']??0)) ?? [];
    if ($search !== '' && !str_contains(strtolower(($supplier['name']??'').' '.($supplier['supplier_number']??'').' '.($score['period']??'').' '.data_company_name($score['company_id']??null)), $search)) return false;
    $overall = (float)($score['overall']??0);
    if ($performance === 'preferred' && $overall < 93) return false;
    if ($performance === 'acceptable' && ($overall < 80 || $overall >= 93)) return false;
    if ($performance === 'corrective' && $overall >= 80) return false;
    if ($status !== '' && ($score['status']??'') !== $status) return false;
    return true;
}));
$pagination = paginate_records($scorecards,query_int('page',1),6);
$actions='<a class="button secondary" href="'.h(app_url('performance.php')).'">Continuous Improvement</a>';
if(can('scorecards.create'))$actions.='<button class="button primary" data-modal-open="scorecardModal" type="button">Create Scorecard</button>';
render_app_start('Supplier Scorecards','scorecards','Performance governance','Evaluate delivery, quality, responsiveness and cost competitiveness with company-specific review evidence.',$actions);
?>
<section class="metric-grid metric-grid-4"><article class="metric-card"><span>Scorecards</span><strong><?= count($allScorecards) ?></strong><small><?= h(current_scope_label()) ?></small></article><article class="metric-card"><span>Average score</span><strong><?= $allScorecards?number_format(array_sum(array_column($allScorecards,'overall'))/count($allScorecards),1):'0.0' ?></strong><small>Out of 100</small></article><article class="metric-card"><span>Preferred performance</span><strong><?= count(array_filter($allScorecards,fn($s)=>$s['overall']>=93)) ?></strong><small>93 or higher</small></article><article class="metric-card"><span>Corrective action</span><strong><?= count(array_filter($allScorecards,fn($s)=>$s['overall']<80)) ?></strong><small>Below 80</small></article></section>
<section class="panel scorecard-filter-panel"><form class="filter-bar wide-filter" method="get"><label><span>Search</span><input type="search" name="q" value="<?= h(query_string('q')) ?>" placeholder="Supplier, number, period, or company"></label><label><span>Performance</span><select name="performance"><option value="">All performance</option><option value="preferred" <?= $performance==='preferred'?'selected':'' ?>>Preferred · 93+</option><option value="acceptable" <?= $performance==='acceptable'?'selected':'' ?>>Acceptable · 80–92.9</option><option value="corrective" <?= $performance==='corrective'?'selected':'' ?>>Corrective action · below 80</option></select></label><label><span>Workflow</span><select name="status"><option value="">All workflow states</option><?php foreach(['draft','submitted','validated','approved','changes_requested'] as $value): ?><option value="<?= h($value) ?>" <?= $status===$value?'selected':'' ?>><?= h(status_label($value)) ?></option><?php endforeach; ?></select></label><button class="button secondary" type="submit">Apply filters</button><a class="button ghost" href="<?= h(app_url('scorecards.php')) ?>">Reset</a></form></section>
<section class="scorecard-grid" aria-label="Supplier scorecards"><?php foreach($pagination['items'] as $score): $supplier=data_find('suppliers',(int)$score['supplier_id'])??[]; ?><article class="scorecard-card"><header><div><span><?= h($score['period']) ?></span><h2><?= h($supplier['name']??data_supplier_name($score['supplier_id'])) ?></h2><small><?= h(data_company_name($score['company_id'])) ?> · Risk <?= h(status_label($supplier['risk']??'not_set')) ?> <?= sample_badge() ?></small></div><strong aria-label="Overall score <?= number_format($score['overall'],1) ?> out of 100"><?= number_format($score['overall'],1) ?></strong></header><div class="score-bars"><?php foreach(['on_time_delivery'=>'On-time delivery','quality'=>'Quality','responsiveness'=>'Responsiveness','cost_competitiveness'=>'Cost competitiveness'] as $key=>$label): ?><div><span><?= h($label) ?><b><?= number_format($score[$key],1) ?></b></span><div class="progress-track" role="progressbar" aria-label="<?= h($label) ?>" aria-valuemin="0" aria-valuemax="100" aria-valuenow="<?= h((string)$score[$key]) ?>"><i style="width:<?= min(100,(float)$score[$key]) ?>%"></i></div></div><?php endforeach; ?></div><footer><?= badge($score['status']) ?><?= workflow_actions('supplier_scorecards',(int)$score['id'],$score['status'],'scorecards','scorecards.php') ?><a class="mini-button" href="<?= h(app_url('performance.php?supplier_id='.(int)$score['supplier_id'])) ?>">Monitor supplier</a></footer></article><?php endforeach; ?><?php if(!$pagination['items']): ?><div class="panel"><?php render_empty_state('No scorecards found','Adjust the filters or select another permitted company scope.'); ?></div><?php endif; ?></section>
<?= render_pagination($pagination,['q'=>query_string('q'),'performance'=>$performance,'status'=>$status]) ?>
<?php if(can('scorecards.create')): ?><div class="modal" id="scorecardModal" hidden><div class="modal-backdrop" data-modal-close></div><section class="modal-card"><header><div><span class="eyebrow">New supplier evaluation</span><h2>Create supplier scorecard</h2></div><button type="button" data-modal-close aria-label="Close">×</button></header><form class="modal-body form-grid" action="<?= h(app_url('action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_scorecard"><input type="hidden" name="return_to" value="scorecards.php"><label><span>Supplier</span><select name="supplier_id" required><?= supplier_options(1) ?></select></label><label><span>Company</span><select name="company_id" required><?= company_options(current_company_id()==='enterprise'?1:current_company_id()) ?></select></label><label class="span-2"><span>Period</span><input name="period" value="<?= h(date('Y').' Q'.(string)ceil((int)date('n')/3)) ?>" required></label><?php foreach(['on_time_delivery'=>'On-time delivery','quality'=>'Quality','responsiveness'=>'Responsiveness','cost_competitiveness'=>'Cost competitiveness'] as $key=>$label): ?><label><span><?= h($label) ?></span><input type="number" min="0" max="100" step="0.1" name="<?= h($key) ?>" value="90" required></label><?php endforeach; ?><div class="span-2 modal-actions"><button class="button secondary" type="button" data-modal-close>Cancel</button><button class="button primary" type="submit">Create scorecard</button></div></form></section></div><?php endif; ?>
<?php render_app_end(); ?>