<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/app/bootstrap.php';
require_once dirname(__DIR__).'/includes/app/work_management.php';
require_permission('work_management.view');

$tab=query_string('tab','overview');
$tabs=['overview'=>'Command Center','mine'=>'My Work','team'=>'Team Queue','exceptions'=>'Exceptions','automation'=>'Automation','analytics'=>'Analytics','governance'=>'Governance'];
if(!isset($tabs[$tab]))$tab='overview';
if(query_string('export')!=='')work_management_export_csv(query_string('export','items'));
$metrics=work_management_metrics();$analytics=work_management_analytics();
$filters=['q'=>query_string('q'),'status'=>query_string('status'),'priority'=>query_string('priority'),'source'=>query_string('source'),'owner'=>query_int('owner')];
$filtered=work_management_filter_items($filters);$myItems=work_management_my_items();
$openItems=array_values(array_filter(work_management_items(),static fn(array$item):bool=>!in_array($item['status'],['completed','cancelled'],true)));
usort($openItems,static function(array$a,array$b):int{$priority=['critical'=>0,'high'=>1,'medium'=>2,'low'=>3];return($priority[$a['priority']]??9)<=>($priority[$b['priority']]??9)?:strcmp((string)$a['due_at'],(string)$b['due_at']);});
$exceptionItems=array_values(array_filter($openItems,static fn(array$item):bool=>$item['status']==='blocked'||work_management_item_overdue($item)||$item['priority']==='critical'));
$actions='<a class="button ghost" href="'.h(app_url('process-maps.php')).'">Process Maps</a><a class="button ghost" href="'.h(app_url('entity-system.php')).'">Business Entities</a>';
if(work_management_can('export'))$actions.='<a class="button secondary" href="'.h(app_url('work-management.php?export=items')).'">Export Work</a>';
$actions.='<a class="button primary" href="'.h(app_url('agent.php?prompt='.rawurlencode('Prioritize the current enterprise work queue, identify overdue and blocked items, explain owners and permissions, and recommend the next governed human action.'))).'">Analyze in Agent</a>';
render_app_start('Enterprise Work Command Center','work-management','Unified work, exceptions, SLAs and supervised automation','Coordinate company-scoped operational work across Sections 11–25 without replacing canonical procurement, supplier, inventory, process, or finance records.',$actions);
work_management_render_styles();
?>
<section class="work-summary" aria-label="Work management metrics">
<article><span>Open work</span><strong><?=number_format($metrics['open'])?></strong></article><article><span>My work</span><strong><?=number_format($metrics['my_work'])?></strong></article><article><span>Critical</span><strong><?=number_format($metrics['critical'])?></strong></article><article><span>Overdue</span><strong><?=number_format($metrics['overdue'])?></strong></article><article><span>Blocked</span><strong><?=number_format($metrics['blocked'])?></strong></article><article><span>Awaiting review</span><strong><?=number_format($metrics['waiting_review'])?></strong></article><article><span>SLA compliance</span><strong><?=h(number_format($metrics['sla_compliance_percent'],1))?>%</strong></article><article><span>Active rules</span><strong><?=number_format($metrics['automation_rules'])?></strong></article>
</section>
<nav class="tab-row" aria-label="Work management sections"><?php foreach($tabs as$key=>$label):?><a class="<?=$tab===$key?'active':''?>" href="<?=h(app_url('work-management.php?tab='.$key))?>"><?=h($label)?></a><?php endforeach;?></nav>

<?php if($tab==='overview'):?>
<div class="work-command-grid">
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Priority command queue</span><h2>What needs attention now</h2><p>Critical, overdue, and blocked work ordered by operational risk and due time.</p></div><a class="button ghost" href="<?=h(app_url('work-management.php?tab=team'))?>">Open Full Queue</a></header><?php work_management_render_queue(array_slice($openItems,0,6),'No open work is visible in this company scope.');?></section>
<aside><section class="panel"><header class="panel-head"><div><span class="eyebrow">Controlled refresh</span><h2>Queue operations</h2></div></header><p>Source synchronization creates supplemental work records from visible processes, approvals, commitments, contracts, inventory, data exceptions, and invoice exceptions. It never changes canonical statuses.</p><div class="work-inline-actions"><?php if(work_management_can('create')):?><form action="<?=h(app_url('work-management-action.php'))?>" method="post"><?=csrf_field()?><input type="hidden" name="action" value="sync_sources"><input type="hidden" name="return_to" value="work-management.php?tab=overview"><button class="button primary" type="submit">Refresh Sources</button></form><?php endif;?><?php if(work_management_can('assign')):?><form action="<?=h(app_url('work-management-action.php'))?>" method="post"><?=csrf_field()?><input type="hidden" name="action" value="scan_escalations"><input type="hidden" name="return_to" value="work-management.php?tab=overview"><button class="button secondary" type="submit">Run SLA Scan</button></form><?php endif;?></div></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Recent governed activity</span><h2>Command signals</h2></div></header><div class="work-timeline"><?php foreach(array_slice(work_management_events(),0,10)as$event):$item=work_management_find_item((int)$event['work_item_id']);?><article><i class="<?=h($event['severity'])?>"></i><div><strong><?=h(status_label($event['event_type']))?></strong><p><?=h($item['work_number']??'')?> · <?=h($event['evidence_note'])?></p><small><?=h(date_us($event['created_at'],true).' · '.data_user_name($event['actor_user_id']??null))?></small></div></article><?php endforeach;?></div></section></aside>
</div>

<?php elseif($tab==='mine'):?>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Personal operating queue</span><h2>Assigned, review, and approval work</h2><p>Work appears here when you own execution, hold the routed role, or are the independent reviewer or approver.</p></div><span class="panel-meta"><?=count($myItems)?> items</span></header><?php work_management_render_queue($myItems,'No assigned work is currently visible.');?></section>

<?php elseif($tab==='team'):?>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Scoped operating queue</span><h2>Team work across <?=h(current_scope_label())?></h2></div><?php if(work_management_can('create')):?><details class="work-action-menu"><summary>＋ Create Work</summary><div class="work-action-panel"><form action="<?=h(app_url('work-management-action.php'))?>" method="post"><?=csrf_field()?><input type="hidden" name="action" value="create_item"><input type="hidden" name="return_to" value="work-management.php?tab=team"><select name="entity_id" required><?php foreach(entity_system_entities()as$entity)if((int)($entity['company_id']??0)>0):?><option value="<?=(int)$entity['id']?>"><?=h($entity['entity_name'])?></option><?php endif;?></select><input name="title" required placeholder="Work title"><input name="source_module" value="manual" required><input name="source_type" value="manual_work" required><input type="number" name="source_id" value="0"><input name="work_type" value="general" required><select name="priority"><option>medium</option><option>high</option><option>critical</option><option>low</option></select><input name="required_permission" value="platform.view" required><textarea name="description" required placeholder="Evidence-based description and desired outcome"></textarea><button class="button primary" type="submit">Create Work</button></form></div></details><?php endif;?></header>
<form class="work-filter" method="get"><input type="hidden" name="tab" value="team"><label><span>Search</span><input name="q" value="<?=h($filters['q'])?>" placeholder="Work number, title, source or evidence"></label><label><span>Status</span><select name="status"><option value="">All</option><?php foreach(['open','in_progress','blocked','waiting_review','waiting_approval','completed','cancelled']as$status):?><option value="<?=h($status)?>" <?=$filters['status']===$status?'selected':''?>><?=h(status_label($status))?></option><?php endforeach;?></select></label><label><span>Priority</span><select name="priority"><option value="">All</option><?php foreach(['critical','high','medium','low']as$priority):?><option value="<?=h($priority)?>" <?=$filters['priority']===$priority?'selected':''?>><?=h(status_label($priority))?></option><?php endforeach;?></select></label><label><span>Source</span><select name="source"><option value="">All</option><?php foreach(array_keys($analytics['by_source'])as$source):?><option value="<?=h($source)?>" <?=$filters['source']===$source?'selected':''?>><?=h(status_label($source))?></option><?php endforeach;?></select></label><label><span>Owner</span><select name="owner"><?=user_options($filters['owner'])?></select></label><button class="button secondary" type="submit">Filter</button></form></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Filtered results</span><h2><?=count($filtered)?> work items</h2></div></header><?php work_management_render_queue($filtered);?></section>

<?php elseif($tab==='exceptions'):?>
<div class="work-command-grid"><section class="panel"><header class="panel-head"><div><span class="eyebrow">Exception command center</span><h2>Critical, overdue, and blocked work</h2><p>These records remain supplemental; source modules retain canonical status authority.</p></div><span class="panel-meta"><?=count($exceptionItems)?> exceptions</span></header><?php work_management_render_queue($exceptionItems,'No critical, overdue, or blocked work is visible.');?></section><aside><section class="panel"><header class="panel-head"><div><span class="eyebrow">Exception distribution</span><h2>By source</h2></div></header><?php work_management_render_distribution($analytics['by_source']);?></section><section class="panel"><header class="panel-head"><div><span class="eyebrow">Aging</span><h2>Open-work age</h2></div></header><?php work_management_render_distribution($analytics['aging']);?></section></aside></div>

<?php elseif($tab==='automation'):?>
<?php if(work_management_can('automate')):?><section class="panel"><header class="panel-head"><div><span class="eyebrow">Governed automation builder</span><h2>Create a supervised rule</h2><p>Rules create or escalate supplemental work only. They cannot directly modify canonical module statuses.</p></div></header><form class="form-grid" action="<?=h(app_url('work-management-action.php'))?>" method="post"><?=csrf_field()?><input type="hidden" name="action" value="create_rule"><input type="hidden" name="return_to" value="work-management.php?tab=automation"><label><span>Rule name</span><input name="rule_name" required></label><label><span>Rule code</span><input name="rule_code" placeholder="AUTO-CUSTOM"></label><label><span>Trigger event</span><input name="trigger_event" value="record.attention_required" required></label><label><span>Source module</span><input name="source_module" value="manual" required></label><label><span>Independent reviewer</span><select name="reviewed_by" required><?=user_options(3)?></select></label><label><span>Approver</span><select name="approved_by" required><?=user_options(6)?></select></label><label><span>Replay window seconds</span><input type="number" name="idempotency_window_seconds" value="86400" min="3600"></label><label class="span-2"><span>Condition JSON</span><textarea name="condition_json" required>{"field":"status","operator":"equals","value":"attention_required"}</textarea></label><label class="span-2"><span>Action JSON</span><textarea name="action_json" required>{"action":"create_work_item","work_type":"operational_exception","priority":"high","assigned_role_code":"procurement_manager","shared_service_entity_code":"GRUBER-PROCUREMENT","sla_minutes":480}</textarea></label><label class="span-2"><span>Governance evidence</span><textarea name="evidence_note" required>Rule drafted from approved source evidence; no canonical status changes are permitted.</textarea></label><div class="span-2"><button class="button primary" type="submit">Create Draft Rule</button></div></form></section><?php endif;?>
<section class="work-rule-grid"><?php foreach(work_management_automation_rules()as$rule):$version=work_management_rule_version($rule);?><article class="work-rule-card"><header><div><span class="work-number"><?=h($rule['rule_code'])?></span><h3><?=h($rule['rule_name'])?></h3></div><?=badge($rule['status'])?></header><p><?=h(status_label($rule['trigger_event']).' · '.status_label($rule['source_module']))?></p><?php if($version):?><dl><div><dt>Version</dt><dd><?=h($version['version_number'])?></dd></div><div><dt>Prepared</dt><dd><?=h(data_user_name($version['prepared_by']))?></dd></div><div><dt>Review / approval</dt><dd><?=h(data_user_name($version['reviewed_by']).' / '.data_user_name($version['approved_by']))?></dd></div></dl><pre><?=h(json_encode(json_decode((string)$version['condition_json'],true),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre><pre><?=h(json_encode(json_decode((string)$version['action_json'],true),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre><div class="work-rule-actions"><?php if($version['status']==='draft'&&(int)$version['prepared_by']===(int)current_user()['id']):?><form action="<?=h(app_url('work-management-action.php'))?>" method="post"><?=csrf_field()?><input type="hidden" name="action" value="submit_rule"><input type="hidden" name="version_id" value="<?=(int)$version['id']?>"><input type="hidden" name="return_to" value="work-management.php?tab=automation"><input name="evidence_note" value="Draft logic validated against source scope and replay controls." required><button class="button secondary" type="submit">Submit Review</button></form><?php endif;?><?php if($rule['status']==='active'&&work_management_can('automate')):?><form action="<?=h(app_url('work-management-action.php'))?>" method="post"><?=csrf_field()?><input type="hidden" name="action" value="simulate_rule"><input type="hidden" name="rule_id" value="<?=(int)$rule['id']?>"><input type="hidden" name="return_to" value="work-management.php?tab=automation"><input name="context_json" value='{"status":"past_due","entity_id":102,"source_id":1,"source_type":"purchase_order"}' required><button class="button ghost" type="submit">Simulate</button></form><?php endif;?></div><?php endif;?></article><?php endforeach;?></section>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Execution receipts</span><h2>Recent automation runs</h2></div><?php if(work_management_can('export')):?><a class="button ghost" href="<?=h(app_url('work-management.php?export=automation'))?>">Export Rules</a><?php endif;?></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Rule</th><th>Source key</th><th>Status</th><th>Matched</th><th>Work item</th><th>Completed</th></tr></thead><tbody><?php foreach(array_slice(work_management_automation_runs(),0,20)as$run):$rule=work_management_find_rule((int)$run['rule_id']);$item=!empty($run['created_work_item_id'])?work_management_find_item((int)$run['created_work_item_id']):null;?><tr><td><?=h($rule['rule_code']??'')?></td><td><code><?=h($run['source_key'])?></code></td><td><?=badge($run['status'])?></td><td><?=(int)$run['matched_count']?></td><td><?=h($item['work_number']??'—')?></td><td><?=h(date_us($run['completed_at'],true))?></td></tr><?php endforeach;?></tbody></table></div></section>

<?php elseif($tab==='analytics'):?>
<section class="work-kpi-list"><article><span>Average first response</span><strong><?=h(number_format($metrics['average_response_seconds']/3600,1))?>h</strong></article><article><span>Average resolution</span><strong><?=h(number_format($metrics['average_resolution_seconds']/3600,1))?>h</strong></article><article><span>Automation success</span><strong><?=($analytics['automation']['total']?h(number_format(($analytics['automation']['successful']/$analytics['automation']['total'])*100,1)):'100.0')?>%</strong></article></section>
<div class="work-command-grid equal"><section class="panel"><header class="panel-head"><div><span class="eyebrow">Workload</span><h2>By assigned user</h2></div></header><?php work_management_render_distribution($analytics['by_user']);?></section><section class="panel"><header class="panel-head"><div><span class="eyebrow">Portfolio</span><h2>By company</h2></div></header><?php work_management_render_distribution($analytics['by_company']);?></section><section class="panel"><header class="panel-head"><div><span class="eyebrow">Root cause</span><h2>By source module</h2></div></header><?php work_management_render_distribution($analytics['by_source']);?></section><section class="panel"><header class="panel-head"><div><span class="eyebrow">Aging</span><h2>Work age bands</h2></div></header><?php work_management_render_distribution($analytics['aging']);?></section></div>

<?php elseif($tab==='governance'):?>
<div class="work-command-grid equal"><section class="panel"><header class="panel-head"><div><span class="eyebrow">Role and entity routing</span><h2>Active routing rules</h2></div></header><div class="work-governance-list"><?php foreach(work_management_routing_rules()as$rule):?><article><header><strong><?=h($rule['rule_code'].' · '.$rule['rule_name'])?></strong><?=badge($rule['status'])?></header><p><?=h(status_label($rule['source_module']).' / '.status_label($rule['work_type']).' → '.status_label($rule['assigned_role_code']))?></p><small><?=h(($rule['shared_service_entity_code']?:'Originating entity').' · '.(int)$rule['sla_minutes'].' minute SLA · '.data_user_name($rule['reviewed_by']).' reviewed')?></small></article><?php endforeach;?></div></section><section class="panel"><header class="panel-head"><div><span class="eyebrow">SLA governance</span><h2>Escalation policies</h2></div></header><div class="work-governance-list"><?php foreach(work_management_escalation_policies()as$policy):?><article><header><strong><?=h($policy['policy_code'].' · '.$policy['policy_name'])?></strong><?=badge($policy['priority'])?></header><p><?=h('Warning '.$policy['warning_minutes'].'m · L1 '.$policy['level1_minutes'].'m · L2 '.$policy['level2_minutes'].'m · L3 '.$policy['level3_minutes'].'m')?></p><small><?=h('Backup '.status_label($policy['backup_role_code']).' · Executive '.status_label($policy['executive_role_code']))?></small></article><?php endforeach;?></div></section></div>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Immutable work history</span><h2>Recent work events</h2></div><?php if(work_management_can('export')):?><a class="button ghost" href="<?=h(app_url('work-management.php?export=events'))?>">Export Events</a><?php endif;?></header><div class="table-wrap"><table class="data-table"><thead><tr><th>Work</th><th>Event</th><th>Status</th><th>Actor</th><th>Evidence</th><th>Time</th></tr></thead><tbody><?php foreach(array_slice(work_management_events(),0,40)as$event):$item=work_management_find_item((int)$event['work_item_id']);?><tr><td><?=h($item['work_number']??'')?></td><td><?=h(status_label($event['event_type']))?></td><td><?=badge($event['to_status']??$event['severity'])?></td><td><?=h(data_user_name($event['actor_user_id']??null))?></td><td><?=h($event['evidence_note'])?></td><td><?=h(date_us($event['created_at'],true))?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php endif;?>
<?php render_app_end();?>
