-- Gruber Procurement Intelligence
-- Section 19: Inventory Operations, Replenishment & Internal Transfer Governance
-- Apply after Version 3 and Sections 11 through 18 migrations.
-- Idempotent for MySQL 8.0 and MariaDB 10.11.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS inventory_replenishment_policies (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    policy_number VARCHAR(80) NOT NULL UNIQUE,
    company_id BIGINT UNSIGNED NOT NULL,
    inventory_location_id BIGINT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    minimum_quantity DECIMAL(15,4) NOT NULL DEFAULT 0,
    maximum_quantity DECIMAL(15,4) NOT NULL DEFAULT 0,
    reorder_point DECIMAL(15,4) NOT NULL DEFAULT 0,
    safety_stock DECIMAL(15,4) NOT NULL DEFAULT 0,
    lead_time_days INT UNSIGNED NOT NULL DEFAULT 1,
    review_frequency_days INT UNSIGNED NOT NULL DEFAULT 7,
    preferred_supplier_id BIGINT UNSIGNED NULL,
    owner_id BIGINT UNSIGNED NOT NULL,
    reviewer_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    evidence_note TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_inventory_replenishment_policy (inventory_location_id,item_id),
    KEY idx_inventory_policy_company_status (company_id,status),
    KEY idx_inventory_policy_item (item_id),
    CONSTRAINT fk_inventory_policy_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_inventory_policy_location FOREIGN KEY (inventory_location_id) REFERENCES inventory_locations(id),
    CONSTRAINT fk_inventory_policy_item FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_inventory_policy_supplier FOREIGN KEY (preferred_supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_inventory_policy_owner FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT fk_inventory_policy_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_reservations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reservation_number VARCHAR(80) NOT NULL UNIQUE,
    company_id BIGINT UNSIGNED NOT NULL,
    inventory_location_id BIGINT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    project_workorder_id BIGINT UNSIGNED NULL,
    reference_type VARCHAR(48) NOT NULL,
    reference_id BIGINT UNSIGNED NULL,
    quantity DECIMAL(15,4) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    needed_date DATE NOT NULL,
    owner_id BIGINT UNSIGNED NOT NULL,
    evidence_note TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_inventory_reservation_company_status (company_id,status,needed_date),
    KEY idx_inventory_reservation_position (inventory_location_id,item_id,status),
    KEY idx_inventory_reservation_reference (reference_type,reference_id),
    CONSTRAINT fk_inventory_reservation_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_inventory_reservation_location FOREIGN KEY (inventory_location_id) REFERENCES inventory_locations(id),
    CONSTRAINT fk_inventory_reservation_item FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_inventory_reservation_project FOREIGN KEY (project_workorder_id) REFERENCES projects_workorders(id),
    CONSTRAINT fk_inventory_reservation_owner FOREIGN KEY (owner_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_transfer_requests (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    transfer_number VARCHAR(80) NOT NULL UNIQUE,
    source_company_id BIGINT UNSIGNED NOT NULL,
    destination_company_id BIGINT UNSIGNED NOT NULL,
    source_inventory_location_id BIGINT UNSIGNED NOT NULL,
    destination_inventory_location_id BIGINT UNSIGNED NOT NULL,
    project_workorder_id BIGINT UNSIGNED NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    required_date DATE NOT NULL,
    shipped_at DATETIME NULL,
    received_at DATETIME NULL,
    carrier VARCHAR(160) NULL,
    tracking_number VARCHAR(160) NULL,
    freight_cost DECIMAL(15,2) NOT NULL DEFAULT 0,
    owner_id BIGINT UNSIGNED NOT NULL,
    reviewer_id BIGINT UNSIGNED NOT NULL,
    approval_id BIGINT UNSIGNED NULL,
    evidence_note TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_inventory_transfer_source (source_company_id,status,required_date),
    KEY idx_inventory_transfer_destination (destination_company_id,status,required_date),
    KEY idx_inventory_transfer_approval (approval_id),
    CONSTRAINT fk_inventory_transfer_source_company FOREIGN KEY (source_company_id) REFERENCES companies(id),
    CONSTRAINT fk_inventory_transfer_destination_company FOREIGN KEY (destination_company_id) REFERENCES companies(id),
    CONSTRAINT fk_inventory_transfer_source_location FOREIGN KEY (source_inventory_location_id) REFERENCES inventory_locations(id),
    CONSTRAINT fk_inventory_transfer_destination_location FOREIGN KEY (destination_inventory_location_id) REFERENCES inventory_locations(id),
    CONSTRAINT fk_inventory_transfer_project FOREIGN KEY (project_workorder_id) REFERENCES projects_workorders(id),
    CONSTRAINT fk_inventory_transfer_owner FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT fk_inventory_transfer_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id),
    CONSTRAINT fk_inventory_transfer_approval FOREIGN KEY (approval_id) REFERENCES workflow_approvals(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_transfer_lines (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    transfer_request_id BIGINT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    quantity_requested DECIMAL(15,4) NOT NULL,
    quantity_shipped DECIMAL(15,4) NOT NULL DEFAULT 0,
    quantity_received DECIMAL(15,4) NOT NULL DEFAULT 0,
    unit_cost DECIMAL(15,4) NOT NULL DEFAULT 0,
    serial_or_lot_reference VARCHAR(240) NULL,
    condition_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    notes TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_inventory_transfer_item (transfer_request_id,item_id),
    KEY idx_inventory_transfer_line_item (item_id),
    CONSTRAINT fk_inventory_transfer_line_request FOREIGN KEY (transfer_request_id) REFERENCES inventory_transfer_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_transfer_line_item FOREIGN KEY (item_id) REFERENCES items(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_transfer_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    transfer_request_id BIGINT UNSIGNED NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    from_status VARCHAR(32) NULL,
    to_status VARCHAR(32) NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'medium',
    evidence_note TEXT NOT NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_inventory_transfer_event_request (transfer_request_id,created_at),
    KEY idx_inventory_transfer_event_type (event_type,created_at),
    CONSTRAINT fk_inventory_transfer_event_request FOREIGN KEY (transfer_request_id) REFERENCES inventory_transfer_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_transfer_event_user FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_replenishment_recommendations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    recommendation_number VARCHAR(80) NOT NULL UNIQUE,
    policy_id BIGINT UNSIGNED NOT NULL,
    company_id BIGINT UNSIGNED NOT NULL,
    inventory_location_id BIGINT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    available_quantity DECIMAL(15,4) NOT NULL DEFAULT 0,
    allocated_quantity DECIMAL(15,4) NOT NULL DEFAULT 0,
    open_po_quantity DECIMAL(15,4) NOT NULL DEFAULT 0,
    forecast_quantity DECIMAL(15,4) NOT NULL DEFAULT 0,
    safety_stock_quantity DECIMAL(15,4) NOT NULL DEFAULT 0,
    recommended_quantity DECIMAL(15,4) NOT NULL DEFAULT 0,
    estimated_unit_cost DECIMAL(15,4) NOT NULL DEFAULT 0,
    estimated_value DECIMAL(15,2) NOT NULL DEFAULT 0,
    recommendation_type VARCHAR(32) NOT NULL,
    source_inventory_location_id BIGINT UNSIGNED NULL,
    preferred_supplier_id BIGINT UNSIGNED NULL,
    required_date DATE NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    approval_id BIGINT UNSIGNED NULL,
    converted_request_id BIGINT UNSIGNED NULL,
    converted_transfer_id BIGINT UNSIGNED NULL,
    evidence_note TEXT NOT NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_inventory_recommendation_company_status (company_id,status,required_date),
    KEY idx_inventory_recommendation_policy (policy_id,created_at),
    KEY idx_inventory_recommendation_item (item_id),
    CONSTRAINT fk_inventory_recommendation_policy FOREIGN KEY (policy_id) REFERENCES inventory_replenishment_policies(id),
    CONSTRAINT fk_inventory_recommendation_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_inventory_recommendation_location FOREIGN KEY (inventory_location_id) REFERENCES inventory_locations(id),
    CONSTRAINT fk_inventory_recommendation_item FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_inventory_recommendation_source FOREIGN KEY (source_inventory_location_id) REFERENCES inventory_locations(id),
    CONSTRAINT fk_inventory_recommendation_supplier FOREIGN KEY (preferred_supplier_id) REFERENCES suppliers(id),
    CONSTRAINT fk_inventory_recommendation_approval FOREIGN KEY (approval_id) REFERENCES workflow_approvals(id),
    CONSTRAINT fk_inventory_recommendation_request FOREIGN KEY (converted_request_id) REFERENCES purchase_requests(id),
    CONSTRAINT fk_inventory_recommendation_transfer FOREIGN KEY (converted_transfer_id) REFERENCES inventory_transfer_requests(id),
    CONSTRAINT fk_inventory_recommendation_creator FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inventory_governance_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    inventory_location_id BIGINT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id BIGINT UNSIGNED NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    from_status VARCHAR(32) NULL,
    to_status VARCHAR(32) NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'medium',
    quantity DECIMAL(15,4) NOT NULL DEFAULT 0,
    value_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    evidence_note TEXT NOT NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_inventory_governance_company (company_id,created_at),
    KEY idx_inventory_governance_entity (entity_type,entity_id,created_at),
    KEY idx_inventory_governance_position (inventory_location_id,item_id,created_at),
    KEY idx_inventory_governance_severity (severity,created_at),
    CONSTRAINT fk_inventory_governance_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_inventory_governance_location FOREIGN KEY (inventory_location_id) REFERENCES inventory_locations(id),
    CONSTRAINT fk_inventory_governance_item FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_inventory_governance_user FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO schema_migrations (version, description, checksum_sha256)
VALUES ('4.8-section19', 'Inventory operations, replenishment policies and recommendations, reservations, transfers, cycle-count governance, controlled movements, and immutable inventory events', NULL)
ON DUPLICATE KEY UPDATE description = VALUES(description);
