<?php
declare(strict_types=1);

function entity_system_carryover_snapshot():array
{
    $companies=data_collection('companies');$companyIds=array_map('intval',array_column($companies,'id'));$users=data_collection('users');$suppliers=data_collection('suppliers');$items=data_collection('items');$contracts=data_collection('contracts');$locations=data_collection('locations');$departments=data_collection('departments');$pos=data_collection('purchase_orders');
    return[
        'companies'=>count($companies),'company_ids'=>$companyIds,'locations'=>count($locations),'departments'=>count($departments),'purchase_orders'=>count($pos),
        'user_memberships'=>array_sum(array_map(static fn(array$u):int=>count(array_unique(array_map('intval',$u['company_ids']??[]))),$users)),
        'supplier_company_links'=>array_sum(array_map(static fn(array$s):int=>count(array_unique(array_map('intval',$s['company_ids']??[]))),$suppliers)),
        'item_company_links'=>array_sum(array_map(static fn(array$i):int=>count(array_unique(array_map('intval',$i['company_ids']??(($i['company_id']??null)!==null?[(int)$i['company_id']]:[])))),$items)),
        'enterprise_contracts'=>count(array_filter($contracts,static fn(array$c):bool=>($c['company_id']??null)===null)),
        'company_contracts'=>count(array_filter($contracts,static fn(array$c):bool=>($c['company_id']??null)!==null)),
    ];
}
function entity_system_validate_current_relationships():array
{
    $errors=[];$warnings=[];$companies=data_collection('companies');$valid=array_fill_keys(array_map('intval',array_column($companies,'id')),true);$codes=[];
    foreach($companies as$c){$id=(int)$c['id'];$code=strtoupper(trim((string)($c['code']??'')));if($id<=0)$errors[]='A company has an invalid canonical ID.';if($code==='')$errors[]='Company '.$id.' has no stable code.';if(isset($codes[$code]))$errors[]='Company code '.$code.' is duplicated.';$codes[$code]=true;}
    foreach(data_collection('users')as$u)foreach(array_map('intval',$u['company_ids']??[])as$cid)if(!isset($valid[$cid]))$errors[]='User '.($u['name']??$u['id']).' references missing company '.$cid.'.';
    foreach(data_collection('suppliers')as$s)foreach(array_map('intval',$s['company_ids']??[])as$cid)if(!isset($valid[$cid]))$errors[]='Supplier '.($s['name']??$s['id']).' references missing company '.$cid.'.';
    foreach(data_collection('items')as$i){$ids=$i['company_ids']??(($i['company_id']??null)!==null?[(int)$i['company_id']]:[]);if(!$ids)$warnings[]='Item '.($i['item_number']??$i['id']).' is enterprise shared and requires an authority policy.';foreach(array_map('intval',$ids)as$cid)if(!isset($valid[$cid]))$errors[]='Item '.($i['item_number']??$i['id']).' references missing company '.$cid.'.';}
    foreach(data_collection('contracts')as$c)if(($c['company_id']??null)===null)$warnings[]='Contract '.($c['contract_number']??$c['id']).' is enterprise scoped and will remain enterprise governed.';
    return['valid'=>$errors===[],'errors'=>array_values(array_unique($errors)),'warnings'=>array_values(array_unique($warnings))];
}
function entity_system_metrics():array
{
    $entities=entity_system_entities();$connections=entity_system_connections();$mappings=entity_system_external_mappings();$conflicts=entity_system_conflicts();$bindings=entity_system_bindings();$bindingIntegrity=$bindings!==[];
    foreach($bindings as$b){$e=entity_system_find($entities,(int)$b['entity_id']);if(!$e||(int)($e['company_id']??0)!==(int)$b['company_id']){$bindingIntegrity=false;break;}}
    return[
        'entities'=>count($entities),'operating_entities'=>count(array_filter($entities,static fn(array$e):bool=>$e['entity_type']==='operating_company')),'shared_services'=>count(array_filter($entities,static fn(array$e):bool=>$e['entity_type']==='shared_service')),
        'relationships'=>count(entity_system_relationships()),'applications'=>count(entity_system_applications()),'active_connections'=>count(array_filter($connections,static fn(array$c):bool=>$c['status']==='active')),
        'pending_mappings'=>count(array_filter($mappings,static fn(array$m):bool=>$m['mapping_status']!=='validated')),'open_conflicts'=>count(array_filter($conflicts,static fn(array$c):bool=>!in_array($c['status'],['resolved','accepted'],true))),
        'preserved_company_ids'=>$bindingIntegrity,'scope_company_count'=>count(array_unique(array_map('intval',array_column($bindings,'company_id')))),
    ];
}
function entity_system_find_by_code(string$code):?array{foreach(entity_system_all_entities()as$e)if(strcasecmp((string)$e['entity_code'],$code)===0)return$e;return null;}
function entity_system_service_name(string$service):string{return match($service){'procurement'=>'Shared Procurement','accounts_payable'=>'Shared Finance & Accounts Payable','inventory_network'=>'Shared Inventory Network','integration_hub'=>'Integration Hub','governance'=>'Enterprise Governance',default=>status_label($service)};}
function entity_system_authority_entity(string$mode,array$entityMap,int$companyEntityId):int{return match($mode){'enterprise','external_governed','internal_governed','bidirectional'=>$entityMap['enterprise'],'procurement'=>$entityMap['procurement']??$entityMap['enterprise'],'finance'=>$entityMap['accounts_payable']??$entityMap['enterprise'],default=>$companyEntityId};}
function entity_system_active_user(int$id):bool{foreach(data_collection('users')as$u)if((int)$u['id']===$id)return($u['status']??'inactive')==='active';return false;}
function entity_system_apply_template(string$code,string$evidence,int$reviewerId=0,int$approverId=0):array
{
    require_permission('companies.administer');if(!can_use_enterprise_view())throw new RuntimeException('Enterprise templates can only be applied from Enterprise View.');entity_system_require_tables();$preview=entity_system_template_preview($code);if(!$preview['validation']['valid'])throw new RuntimeException('Resolve relationship validation errors before applying the template.');if(trim($evidence)==='')throw new RuntimeException('Template-application evidence is required.');$u=(int)current_user()['id'];if(count(array_unique([$u,$reviewerId,$approverId]))!==3)throw new RuntimeException('Template preparation, review, and approval must use three different users.');if(!entity_system_active_user($reviewerId)||!entity_system_active_user($approverId))throw new RuntimeException('Reviewer and approver must be active users.');
    foreach(entity_system_applications()as$a)if($a['template_code']===$code&&$a['status']==='applied')return$a;
    $manifest=['template'=>$code,'version'=>$preview['template']['version'],'canonical_company_ids_preserved'=>true,'companies'=>$preview['carryover']['company_ids'],'carryover'=>$preview['carryover'],'services'=>$preview['template']['services'],'authorities'=>$preview['template']['authority']];$hash=hash('sha256',json_encode($manifest,JSON_UNESCAPED_SLASHES));$app=entity_system_save_application(['id'=>null,'application_number'=>'ENT-APP-'.date('Ymd').'-'.str_pad((string)(count(entity_system_applications())+1),4,'0',STR_PAD_LEFT),'template_code'=>$code,'template_version'=>$preview['template']['version'],'status'=>'applied','manifest_json'=>json_encode($manifest,JSON_UNESCAPED_SLASHES),'relationship_hash'=>$hash,'prepared_by'=>$u,'reviewed_by'=>$reviewerId,'approved_by'=>$approverId,'evidence_note'=>mb_substr($evidence,0,5000),'applied_at'=>date('Y-m-d H:i:s'),'rolled_back_at'=>null,'rollback_note'=>'']);
    $root=entity_system_find_by_code('GRUBER-ENTERPRISE')??entity_system_save_entity(['id'=>null,'entity_code'=>'GRUBER-ENTERPRISE','entity_name'=>'Gruber Enterprise','legal_name'=>'Gruber Enterprise','entity_type'=>'enterprise_group','parent_entity_id'=>null,'company_id'=>null,'status'=>'active','country_code'=>'US','base_currency'=>'USD','timezone'=>'America/Phoenix','fiscal_calendar_code'=>'CALENDAR','effective_from'=>date('Y-m-d'),'effective_to'=>null,'application_id'=>$app['id']]);$map=['enterprise'=>(int)$root['id']];
    foreach($preview['template']['services']as$s){$ec='GRUBER-'.strtoupper(str_replace('_','-',$s));$service=entity_system_find_by_code($ec)??entity_system_save_entity(['id'=>null,'entity_code'=>$ec,'entity_name'=>'Gruber '.entity_system_service_name($s),'legal_name'=>'Gruber '.entity_system_service_name($s),'entity_type'=>'shared_service','parent_entity_id'=>$root['id'],'company_id'=>null,'status'=>'active','country_code'=>'US','base_currency'=>'USD','timezone'=>'America/Phoenix','fiscal_calendar_code'=>'CALENDAR','effective_from'=>date('Y-m-d'),'effective_to'=>null,'application_id'=>$app['id']]);$map[$s]=(int)$service['id'];}
    foreach(data_collection('companies')as$c){$ec='COMP-'.strtoupper((string)$c['code']);$entity=entity_system_find_by_code($ec)??entity_system_save_entity(['id'=>null,'entity_code'=>$ec,'entity_name'=>$c['name'],'legal_name'=>$c['name'],'entity_type'=>'operating_company','parent_entity_id'=>$root['id'],'company_id'=>(int)$c['id'],'status'=>'active','country_code'=>'US','base_currency'=>'USD','timezone'=>'America/Phoenix','fiscal_calendar_code'=>'CALENDAR','effective_from'=>date('Y-m-d'),'effective_to'=>null,'application_id'=>$app['id']]);$eid=(int)$entity['id'];$map['company_'.$c['id']]=$eid;
        $exists=false;foreach(entity_system_bindings()as$b)if((int)$b['company_id']===(int)$c['id'])$exists=true;if(!$exists)entity_system_save_binding(['id'=>null,'application_id'=>$app['id'],'entity_id'=>$eid,'company_id'=>(int)$c['id'],'binding_type'=>'operational','is_primary'=>1,'status'=>'active','effective_from'=>date('Y-m-d'),'effective_to'=>null]);
        entity_system_save_relationship(['id'=>null,'application_id'=>$app['id'],'from_entity_id'=>$root['id'],'to_entity_id'=>$eid,'relationship_type'=>'owns','service_domain'=>'governance','status'=>'active','effective_from'=>date('Y-m-d'),'effective_to'=>null,'evidence_note'=>'Canonical company ID '.$c['id'].' preserved.']);foreach($preview['template']['services']as$s)entity_system_save_relationship(['id'=>null,'application_id'=>$app['id'],'from_entity_id'=>$map[$s],'to_entity_id'=>$eid,'relationship_type'=>'provides_service','service_domain'=>$s,'status'=>'active','effective_from'=>date('Y-m-d'),'effective_to'=>null,'evidence_note'=>'Applied from '.$preview['template']['name'].'.']);
        foreach(array_values(array_unique(array_merge($c['modules']??[],['supplier_portal','accounts_payable','strategy'])))as$m)entity_system_save_profile(['id'=>null,'application_id'=>$app['id'],'entity_id'=>$eid,'module_code'=>$m,'enabled'=>1,'inheritance_mode'=>in_array($m,['supplier_portal','accounts_payable','strategy'],true)?'inherited':'local','source_entity_id'=>$m==='accounts_payable'?($map['accounts_payable']??null):($map['procurement']??null),'settings_json'=>'{}','status'=>'active']);
        foreach($preview['template']['authority']as$domain=>$mode)entity_system_save_authority(['id'=>null,'application_id'=>$app['id'],'entity_id'=>$eid,'domain_code'=>$domain,'authority_entity_id'=>entity_system_authority_entity($mode,$map,$eid),'authority_mode'=>$mode,'override_policy'=>in_array($mode,['local'],true)?'local_only':'governed_override','status'=>'active','effective_from'=>date('Y-m-d'),'effective_to'=>null,'evidence_note'=>'Template authority policy.']);
    }
    foreach(data_collection('users')as$user)foreach(array_unique(array_map('intval',$user['company_ids']??[]))as$cid)if(isset($map['company_'.$cid]))entity_system_save_access_scope(['id'=>null,'application_id'=>$app['id'],'user_id'=>(int)$user['id'],'entity_id'=>$map['company_'.$cid],'module_code'=>'*','scope_type'=>'entity_only','include_descendants'=>0,'status'=>'active','effective_from'=>date('Y-m-d'),'effective_to'=>null]);
    entity_system_add_event((int)$app['id'],(int)$root['id'],'template_applied','business_entity_application',(int)$app['id'],'validated','applied','medium',$evidence);data_add_audit('Business Entities','template_applied','business_entity_application',(int)$app['id'],null,$app,null);return$app;
}
function entity_system_rollback_application(int$id,string$note):array
{
    require_permission('companies.administer');if(!can_use_enterprise_view())throw new RuntimeException('Enterprise template rollback requires Enterprise View.');$app=entity_system_find_application($id);if(!$app)throw new RuntimeException('The template application was not found.');if($app['status']!=='applied')throw new RuntimeException('Only an applied template can be rolled back.');if(trim($note)==='')throw new RuntimeException('Rollback evidence is required.');$before=$app;$app['status']='rolled_back';$app['rolled_back_at']=date('Y-m-d H:i:s');$app['rollback_note']=mb_substr($note,0,5000);$saved=entity_system_save_application($app);if(data_is_demo()){foreach(entity_system_demo_collection('business_entity_relationships','entity_system_demo_relationships')as$r)if((int)($r['application_id']??0)===$id){$r['status']='inactive';entity_system_demo_save('business_entity_relationships',$r,'entity_system_demo_relationships');}}else{$p=production_database_connection();$p->prepare("UPDATE business_entity_relationships SET status='inactive' WHERE application_id=?")->execute([$id]);$p->prepare("UPDATE business_entity_module_profiles SET status='inactive' WHERE application_id=?")->execute([$id]);$p->prepare("UPDATE business_entity_data_authorities SET status='inactive' WHERE application_id=?")->execute([$id]);$p->prepare("UPDATE business_entities SET status='inactive' WHERE application_id=? AND company_id IS NULL AND entity_type='shared_service'")->execute([$id]);}entity_system_add_event($id,null,'template_rolled_back','business_entity_application',$id,'applied','rolled_back','high',$note);data_add_audit('Business Entities','template_rolled_back','business_entity_application',$id,$before,$saved,null);return$saved;
}
function entity_system_validate_connection_payload(array$r):void
{
    if(trim((string)($r['connection_name']??''))==='')throw new RuntimeException('Connection name is required.');$secret=trim((string)($r['secret_reference']??''));if($secret===''||!preg_match('#^(vault|secret|env)://#i',$secret))throw new RuntimeException('Use an external secret reference such as vault://, secret://, or env://.');$serialized=strtolower(json_encode($r));if(preg_match('/(routing_number|account_number|private_key|client_secret|password)\s*[=:]/',$serialized))throw new RuntimeException('Raw credentials or banking details cannot be stored in integration metadata.');
}
function entity_system_readiness():array
{
    $validation=entity_system_validate_current_relationships();$bindings=entity_system_bindings();$bound=array_unique(array_map('intval',array_column($bindings,'company_id')));$companyIds=can_use_enterprise_view()?array_map('intval',array_column(data_collection('companies'),'id')):permitted_company_ids();$issues=$validation['errors'];foreach(array_diff($companyIds,$bound)as$cid)$issues[]='Company '.$cid.' has no active entity binding.';foreach(entity_system_connections()as$c)if($c['status']==='active'&&!array_filter(entity_system_integration_bindings(),static fn(array$b):bool=>(int)$b['connection_id']===(int)$c['id']&&$b['status']==='active'))$issues[]='Active connection '.$c['connection_name'].' has no active entity binding.';return['ready'=>$issues===[],'issues'=>$issues,'warnings'=>$validation['warnings'],'score'=>max(0,100-count($issues)*15-count($validation['warnings'])*2)];
}
