<?php
declare(strict_types=1);
function entity_system_template_catalog():array
{
    return[
        'gruber_shared_services'=>['code'=>'gruber_shared_services','name'=>'Six-Business Gruber Shared Services','version'=>'1.0.0','description'=>'Preserves all six businesses while centralizing procurement, supplier and item governance, accounts payable, reporting, and integrations.','services'=>['procurement','accounts_payable'],'authority'=>['supplier_master'=>'enterprise','item_master'=>'enterprise','contracts'=>'procurement','sourcing'=>'procurement','purchase_orders'=>'local','inventory'=>'local','accounts_payable'=>'finance','payments'=>'finance','reporting'=>'enterprise','security'=>'enterprise']],
        'independent_businesses'=>['code'=>'independent_businesses','name'=>'Independent Businesses','version'=>'1.0.0','description'=>'Each operating business owns its modules, data, integrations, and approvals with enterprise reporting only.','services'=>[],'authority'=>['supplier_master'=>'local','item_master'=>'local','contracts'=>'local','purchase_orders'=>'local','inventory'=>'local','accounts_payable'=>'local','payments'=>'local','reporting'=>'enterprise']],
        'parent_subsidiaries'=>['code'=>'parent_subsidiaries','name'=>'Parent With Operating Subsidiaries','version'=>'1.0.0','description'=>'Enterprise parent governs policy and reporting while subsidiaries retain transaction authority.','services'=>['governance'],'authority'=>['supplier_master'=>'enterprise','item_master'=>'enterprise','contracts'=>'local','purchase_orders'=>'local','inventory'=>'local','accounts_payable'=>'local','reporting'=>'enterprise']],
        'centralized_procurement'=>['code'=>'centralized_procurement','name'=>'Centralized Procurement','version'=>'1.0.0','description'=>'Shared procurement owns sourcing, suppliers, items, contracts, and buying policy for all businesses.','services'=>['procurement'],'authority'=>['supplier_master'=>'procurement','item_master'=>'procurement','contracts'=>'procurement','sourcing'=>'procurement','purchase_orders'=>'local','inventory'=>'local','accounts_payable'=>'local','reporting'=>'enterprise']],
        'centralized_procurement_finance'=>['code'=>'centralized_procurement_finance','name'=>'Centralized Procurement & Finance','version'=>'1.0.0','description'=>'Shared procurement and shared finance coordinate the full source-to-settle lifecycle.','services'=>['procurement','accounts_payable'],'authority'=>['supplier_master'=>'procurement','item_master'=>'procurement','contracts'=>'procurement','sourcing'=>'procurement','purchase_orders'=>'local','inventory'=>'local','accounts_payable'=>'finance','payments'=>'finance','reporting'=>'enterprise']],
        'shared_inventory_network'=>['code'=>'shared_inventory_network','name'=>'Shared Inventory Network','version'=>'1.0.0','description'=>'Operating companies retain ownership while locations participate in governed cross-company inventory sharing.','services'=>['inventory_network'],'authority'=>['supplier_master'=>'enterprise','item_master'=>'enterprise','purchase_orders'=>'local','inventory'=>'local','inventory_network'=>'enterprise','accounts_payable'=>'local','reporting'=>'enterprise']],
        'holding_legal_entities'=>['code'=>'holding_legal_entities','name'=>'Holding Company With Legal Entities','version'=>'1.0.0','description'=>'Separates legal ownership, operating responsibility, shared services, and consolidated reporting.','services'=>['governance','procurement','accounts_payable'],'authority'=>['supplier_master'=>'enterprise','item_master'=>'enterprise','contracts'=>'local','purchase_orders'=>'local','inventory'=>'local','accounts_payable'=>'finance','payments'=>'finance','reporting'=>'enterprise']],
        'multi_company_erp'=>['code'=>'multi_company_erp','name'=>'Multi-Company ERP','version'=>'1.0.0','description'=>'Creates integration bindings and external-ID mapping requirements for one ERP spanning multiple businesses.','services'=>['integration_hub'],'authority'=>['supplier_master'=>'external_governed','item_master'=>'external_governed','contracts'=>'internal_governed','purchase_orders'=>'bidirectional','inventory'=>'bidirectional','accounts_payable'=>'bidirectional','reporting'=>'enterprise']],
        'custom_organization'=>['code'=>'custom_organization','name'=>'Custom Organization','version'=>'1.0.0','description'=>'Starts with the preserved company bindings and allows administrators to design all relationships and authorities.','services'=>[],'authority'=>[]],
    ];
}
function entity_system_template(string$code):?array{return entity_system_template_catalog()[$code]??null;}
function entity_system_template_preview(string$code):array
{
    $t=entity_system_template($code);if(!$t)throw new RuntimeException('Select a valid entity template.');$companies=data_collection('companies');$nodes=[['key'=>'enterprise','name'=>'Gruber Enterprise','type'=>'enterprise_group']];foreach($t['services']as$s)$nodes[]=['key'=>$s,'name'=>status_label($s).' Shared Service','type'=>'shared_service'];foreach($companies as$c)$nodes[]=['key'=>'company_'.$c['id'],'name'=>$c['name'],'type'=>'operating_company','company_id'=>(int)$c['id']];$relationships=[];foreach($companies as$c){$relationships[]=['from'=>'enterprise','to'=>'company_'.$c['id'],'type'=>'owns','domain'=>'governance'];foreach($t['services']as$s)$relationships[]=['from'=>$s,'to'=>'company_'.$c['id'],'type'=>'provides_service','domain'=>$s];}$carry=entity_system_carryover_snapshot();return['template'=>$t,'nodes'=>$nodes,'relationships'=>$relationships,'authorities'=>$t['authority'],'carryover'=>$carry,'validation'=>entity_system_validate_current_relationships()];
}
