<?php
declare(strict_types=1);

function entity_system_tables():array{return['business_entities','business_entity_relationships','business_entity_company_bindings','business_entity_module_profiles','business_entity_data_authorities','business_entity_access_scopes','business_entity_templates','business_entity_template_applications','integration_connections','integration_entity_bindings','external_id_mappings','integration_sync_runs','integration_events','integration_conflicts','business_entity_events'];}
function entity_system_tables_ready():bool{if(data_is_demo())return true;$pdo=production_database_connection();if(!$pdo)return false;try{$n=entity_system_tables();$s=$pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ('.implode(',',array_fill(0,count($n),'?')).')');$s->execute($n);return(int)$s->fetchColumn()===count($n);}catch(Throwable){return false;}}
function entity_system_require_tables():void{if(!entity_system_tables_ready())throw new RuntimeException('Import the Section 24 migration before using Production Data entity or integration writes.');}
function entity_system_demo_collection(string$key,callable$seed):array{if(!isset($_SESSION['gruber_demo_state'][$key]))$_SESSION['gruber_demo_state'][$key]=$seed();return array_values($_SESSION['gruber_demo_state'][$key]);}
function entity_system_demo_save(string$key,array$r,callable$seed):array{$rows=entity_system_demo_collection($key,$seed);$id=(int)($r['id']??0);if($id<=0){$id=max([0,...array_map('intval',array_column($rows,'id'))])+1;$r['id']=$id;$rows[]=$r;}else{$f=false;foreach($rows as$i=>$x)if((int)$x['id']===$id){$rows[$i]=array_replace($x,$r);$r=$rows[$i];$f=true;break;}if(!$f)$rows[]=$r;}$_SESSION['gruber_demo_state'][$key]=array_values($rows);return$r;}
function entity_system_raw_rows(string$table,string$key,callable$seed,string$order='id'):array{if(data_is_demo())return entity_system_demo_collection($key,$seed);if(!entity_system_tables_ready())return[];return production_database_connection()->query("SELECT * FROM {$table} ORDER BY {$order}")->fetchAll();}
function entity_system_effective(array$r):bool{$today=date('Y-m-d');return($r['status']??'active')==='active'&&empty($r['effective_from'])||(($r['status']??'active')==='active'&&(string)$r['effective_from']<=$today&&(empty($r['effective_to'])||(string)$r['effective_to']>=$today));}
function entity_system_visible_entity_ids():array
{
    $entities=entity_system_raw_rows('business_entities','business_entities','entity_system_demo_entities','parent_entity_id,id');
    if(can_use_enterprise_view())return array_map('intval',array_column($entities,'id'));
    $allowed=array_fill_keys(permitted_company_ids(),true);$visible=[];$operating=[];
    foreach($entities as$e){$cid=(int)($e['company_id']??0);if($cid>0&&isset($allowed[$cid])){$visible[(int)$e['id']]=true;$operating[(int)$e['id']]=true;if(!empty($e['parent_entity_id']))$visible[(int)$e['parent_entity_id']]=true;}}
    $relationships=entity_system_raw_rows('business_entity_relationships','business_entity_relationships','entity_system_demo_relationships');
    foreach($relationships as$r){if(!entity_system_effective($r))continue;$from=(int)$r['from_entity_id'];$to=(int)$r['to_entity_id'];if(isset($operating[$to])&&in_array((string)$r['relationship_type'],['provides_service','pays_for','purchases_for','operates','consolidates','owns'],true))$visible[$from]=true;if(isset($operating[$from]))$visible[$to]=true;}
    $authorities=entity_system_raw_rows('business_entity_data_authorities','business_entity_data_authorities','entity_system_demo_authorities');
    foreach($authorities as$a)if(entity_system_effective($a)&&isset($operating[(int)$a['entity_id']]))$visible[(int)$a['authority_entity_id']]=true;
    return array_map('intval',array_keys($visible));
}
function entity_system_entity_visible(array$e):bool{return in_array((int)$e['id'],entity_system_visible_entity_ids(),true);}
function entity_system_filter_entity_rows(array$rows,string$field='entity_id'):array{$visible=array_fill_keys(entity_system_visible_entity_ids(),true);return array_values(array_filter($rows,static fn(array$r):bool=>isset($visible[(int)($r[$field]??0)])));}
function entity_system_entities():array{return entity_system_filter_entity_rows(entity_system_raw_rows('business_entities','business_entities','entity_system_demo_entities','parent_entity_id,id'),'id');}
function entity_system_all_entities():array{return entity_system_raw_rows('business_entities','business_entities','entity_system_demo_entities','parent_entity_id,id');}
function entity_system_relationships():array{$visible=array_fill_keys(entity_system_visible_entity_ids(),true);return array_values(array_filter(entity_system_raw_rows('business_entity_relationships','business_entity_relationships','entity_system_demo_relationships'),static fn(array$r):bool=>isset($visible[(int)$r['from_entity_id']])&&isset($visible[(int)$r['to_entity_id']])));}
function entity_system_bindings():array{return entity_system_filter_entity_rows(entity_system_raw_rows('business_entity_company_bindings','business_entity_company_bindings','entity_system_demo_bindings'));}
function entity_system_module_profiles():array{return entity_system_filter_entity_rows(entity_system_raw_rows('business_entity_module_profiles','business_entity_module_profiles','entity_system_demo_module_profiles'));}
function entity_system_authorities():array{$visible=array_fill_keys(entity_system_visible_entity_ids(),true);return array_values(array_filter(entity_system_raw_rows('business_entity_data_authorities','business_entity_data_authorities','entity_system_demo_authorities'),static fn(array$r):bool=>isset($visible[(int)$r['entity_id']])&&isset($visible[(int)$r['authority_entity_id']])));}
function entity_system_access_scopes():array{return entity_system_filter_entity_rows(entity_system_raw_rows('business_entity_access_scopes','business_entity_access_scopes','entity_system_demo_access_scopes'));}
function entity_system_applications():array{return can_use_enterprise_view()?entity_system_raw_rows('business_entity_template_applications','business_entity_template_applications','entity_system_demo_applications','created_at DESC,id DESC'):[];}
function entity_system_integration_bindings():array{return entity_system_filter_entity_rows(entity_system_raw_rows('integration_entity_bindings','integration_entity_bindings','entity_system_demo_integration_bindings','id DESC'));}
function entity_system_visible_connection_ids():array{return array_values(array_unique(array_map('intval',array_column(entity_system_integration_bindings(),'connection_id'))));}
function entity_system_connections():array{$rows=entity_system_raw_rows('integration_connections','integration_connections','entity_system_demo_connections','id DESC');if(can_use_enterprise_view())return$rows;$ids=array_fill_keys(entity_system_visible_connection_ids(),true);return array_values(array_filter($rows,static fn(array$r):bool=>isset($ids[(int)$r['id']])));}
function entity_system_external_mappings():array{return entity_system_filter_entity_rows(entity_system_raw_rows('external_id_mappings','external_id_mappings','entity_system_demo_external_mappings','id DESC'));}
function entity_system_sync_runs():array{$rows=entity_system_raw_rows('integration_sync_runs','integration_sync_runs','entity_system_demo_sync_runs','id DESC');if(can_use_enterprise_view())return$rows;$visible=array_fill_keys(entity_system_visible_entity_ids(),true);$connections=array_fill_keys(entity_system_visible_connection_ids(),true);return array_values(array_filter($rows,static fn(array$r):bool=>(isset($visible[(int)($r['entity_id']??0)])||empty($r['entity_id']))&&isset($connections[(int)$r['connection_id']])));}
function entity_system_integration_events():array{return entity_system_filter_entity_rows(entity_system_raw_rows('integration_events','integration_events','entity_system_demo_integration_events','occurred_at DESC,id DESC'));}
function entity_system_conflicts():array{return entity_system_filter_entity_rows(entity_system_raw_rows('integration_conflicts','integration_conflicts','entity_system_demo_conflicts','id DESC'));}
function entity_system_events():array{$rows=entity_system_raw_rows('business_entity_events','business_entity_events','entity_system_demo_events','created_at DESC,id DESC');if(can_use_enterprise_view())return$rows;$visible=array_fill_keys(entity_system_visible_entity_ids(),true);return array_values(array_filter($rows,static fn(array$r):bool=>!empty($r['entity_id'])&&isset($visible[(int)$r['entity_id']])));}
function entity_system_find(array$rows,int$id):?array{foreach($rows as$r)if((int)$r['id']===$id)return$r;return null;}
function entity_system_find_entity(int$id):?array{return entity_system_find(entity_system_entities(),$id);}
function entity_system_find_application(int$id):?array{return entity_system_find(entity_system_applications(),$id);}
function entity_system_save_row(string$table,string$key,callable$seed,array$r,array$fields):array{entity_system_require_tables();$r['created_at']=$r['created_at']??date('Y-m-d H:i:s');$r['updated_at']=date('Y-m-d H:i:s');if(data_is_demo())return entity_system_demo_save($key,$r,$seed);$pdo=production_database_connection();$id=(int)($r['id']??0);$v=[];foreach($fields as$f){$x=$r[$f]??null;if(is_array($x))$x=json_encode($x,JSON_UNESCAPED_SLASHES);$v[]=$x;}if($id){$v[]=$id;$pdo->prepare('UPDATE '.$table.' SET '.implode(',',array_map(static fn(string$f):string=>$f.'=?',$fields)).',updated_at=NOW() WHERE id=?')->execute($v);}else{$pdo->prepare('INSERT INTO '.$table.' ('.implode(',',$fields).') VALUES ('.implode(',',array_fill(0,count($fields),'?')).')')->execute($v);$id=(int)$pdo->lastInsertId();}$r['id']=$id;return$r;}
function entity_system_save_entity(array$r):array{return entity_system_save_row('business_entities','business_entities','entity_system_demo_entities',$r,['entity_code','entity_name','legal_name','entity_type','parent_entity_id','company_id','status','country_code','base_currency','timezone','fiscal_calendar_code','effective_from','effective_to','application_id']);}
function entity_system_save_relationship(array$r):array{return entity_system_save_row('business_entity_relationships','business_entity_relationships','entity_system_demo_relationships',$r,['application_id','from_entity_id','to_entity_id','relationship_type','service_domain','status','effective_from','effective_to','evidence_note']);}
function entity_system_save_binding(array$r):array{return entity_system_save_row('business_entity_company_bindings','business_entity_company_bindings','entity_system_demo_bindings',$r,['application_id','entity_id','company_id','binding_type','is_primary','status','effective_from','effective_to']);}
function entity_system_save_profile(array$r):array{return entity_system_save_row('business_entity_module_profiles','business_entity_module_profiles','entity_system_demo_module_profiles',$r,['application_id','entity_id','module_code','enabled','inheritance_mode','source_entity_id','settings_json','status']);}
function entity_system_save_authority(array$r):array{return entity_system_save_row('business_entity_data_authorities','business_entity_data_authorities','entity_system_demo_authorities',$r,['application_id','entity_id','domain_code','authority_entity_id','authority_mode','override_policy','status','effective_from','effective_to','evidence_note']);}
function entity_system_save_access_scope(array$r):array{return entity_system_save_row('business_entity_access_scopes','business_entity_access_scopes','entity_system_demo_access_scopes',$r,['application_id','user_id','entity_id','module_code','scope_type','include_descendants','status','effective_from','effective_to']);}
function entity_system_save_application(array$r):array{return entity_system_save_row('business_entity_template_applications','business_entity_template_applications','entity_system_demo_applications',$r,['application_number','template_code','template_version','status','manifest_json','relationship_hash','prepared_by','reviewed_by','approved_by','evidence_note','applied_at','rolled_back_at','rollback_note']);}
function entity_system_save_connection(array$r):array{return entity_system_save_row('integration_connections','integration_connections','entity_system_demo_connections',$r,['connection_number','connection_name','provider','system_type','environment','auth_type','secret_reference','adapter_version','status','capabilities_json','last_success_at','created_by','reviewer_id','evidence_note']);}
function entity_system_save_integration_binding(array$r):array{return entity_system_save_row('integration_entity_bindings','integration_entity_bindings','entity_system_demo_integration_bindings',$r,['connection_id','entity_id','external_organization_id','external_company_id','external_tenant_id','sync_direction','enabled_domains_json','data_authority','status','effective_from','effective_to','evidence_note']);}
function entity_system_save_mapping(array$r):array{return entity_system_save_row('external_id_mappings','external_id_mappings','entity_system_demo_external_mappings',$r,['connection_id','entity_id','domain_code','internal_record_type','internal_record_id','external_record_type','external_record_id','external_parent_id','mapping_status','effective_from','effective_to','evidence_note']);}
function entity_system_save_conflict(array$r):array{return entity_system_save_row('integration_conflicts','integration_conflicts','entity_system_demo_conflicts',$r,['connection_id','entity_id','domain_code','internal_record_type','internal_record_id','external_record_id','conflict_type','status','internal_value_json','external_value_json','resolution_json','owner_id','reviewer_id','evidence_note','resolved_at']);}
function entity_system_add_event(?int$appId,?int$entityId,string$type,string$entityType,int$recordId,?string$from,?string$to,string$severity,string$note):array{entity_system_require_tables();$r=['id'=>null,'application_id'=>$appId,'entity_id'=>$entityId,'event_type'=>$type,'entity_type'=>$entityType,'entity_record_id'=>$recordId,'from_status'=>$from,'to_status'=>$to,'severity'=>$severity,'evidence_note'=>$note,'created_by'=>(int)current_user()['id'],'created_at'=>date('Y-m-d H:i:s')];if(data_is_demo())return entity_system_demo_save('business_entity_events',$r,'entity_system_demo_events');$p=production_database_connection();$p->prepare('INSERT INTO business_entity_events(application_id,entity_id,event_type,entity_type,entity_record_id,from_status,to_status,severity,evidence_note,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$appId,$entityId,$type,$entityType,$recordId,$from,$to,$severity,$note,$r['created_by']]);$r['id']=(int)$p->lastInsertId();return$r;}
function entity_system_queue_integration_event(int$connectionId,int$entityId,string$direction,string$type,string$recordType,int$recordId,string$key,array$payload,string$note):array{entity_system_require_tables();if(!entity_system_find_entity($entityId))throw new RuntimeException('Integration event entity is outside your permitted scope.');$hash=hash('sha256',json_encode($payload,JSON_UNESCAPED_SLASHES));foreach(entity_system_integration_events()as$e)if(hash_equals((string)$e['idempotency_key'],$key))return$e;$r=['id'=>null,'connection_id'=>$connectionId,'entity_id'=>$entityId,'direction'=>$direction,'event_type'=>$type,'record_type'=>$recordType,'record_id'=>$recordId,'idempotency_key'=>$key,'payload_checksum'=>$hash,'status'=>'ready','attempt_count'=>0,'occurred_at'=>date('Y-m-d H:i:s'),'processed_at'=>null,'evidence_note'=>$note];if(data_is_demo())return entity_system_demo_save('integration_events',$r,'entity_system_demo_integration_events');$p=production_database_connection();$p->prepare('INSERT INTO integration_events(connection_id,entity_id,direction,event_type,record_type,record_id,idempotency_key,payload_checksum,status,attempt_count,occurred_at,evidence_note) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$connectionId,$entityId,$direction,$type,$recordType,$recordId,$key,$hash,'ready',0,$r['occurred_at'],$note]);$r['id']=(int)$p->lastInsertId();return$r;}
