<style>
.execution-hero{display:grid;grid-template-columns:1.25fr .75fr;gap:20px;padding:24px;border:1px solid #dfe4ea;border-radius:20px;background:linear-gradient(135deg,#fff,#f7f9fc)}
.execution-hero h2{margin:.35rem 0 .65rem;font-size:clamp(1.7rem,3vw,2.45rem)}.execution-status{display:grid;place-items:center;min-height:190px;border-radius:18px;background:#111827;color:#fff;text-align:center;padding:22px}.execution-status strong{font-size:2.25rem}.execution-status small{opacity:.75;max-width:240px}
.execution-metrics{display:grid;grid-template-columns:repeat(6,minmax(140px,1fr));gap:12px;margin:18px 0}.execution-metric{padding:16px;border:1px solid #dfe4ea;border-radius:16px;background:#fff}.execution-metric span,.execution-metric small{display:block}.execution-metric strong{display:block;font-size:1.5rem;margin:.35rem 0}.execution-metric small{color:#64748b}
.execution-layout{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(320px,.65fr);gap:18px}.execution-card{padding:18px;border:1px solid #dfe4ea;border-radius:18px;background:#fff}.execution-card+.execution-card{margin-top:14px}.execution-card-head{display:flex;justify-content:space-between;gap:14px}.execution-card-head h3{margin:.35rem 0}.execution-meta{display:flex;flex-wrap:wrap;gap:7px}.execution-meta span{padding:5px 8px;border-radius:999px;background:#eef2ff;color:#3730a3;font-size:.78rem;font-weight:700}
.snapshot-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.snapshot-card{padding:15px;border:1px solid #e5e7eb;border-radius:15px;background:#fff}.snapshot-card dl{display:grid;grid-template-columns:1fr auto;gap:8px;margin:12px 0 0}.snapshot-card dt{color:#64748b}.snapshot-card dd{margin:0;font-weight:700}
.execution-controls{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.execution-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.execution-form-grid .span-2{grid-column:span 2}.execution-form-grid input,.execution-form-grid select,.execution-form-grid textarea{width:100%}
.timeline-row{display:grid;grid-template-columns:110px 1fr;gap:12px;padding:13px 0;border-bottom:1px solid #eef2f7}.timeline-row:last-child{border-bottom:0}.timeline-row small{color:#64748b}.verification-callout{padding:16px;border-radius:16px;background:#f8fafc;border:1px solid #dfe4ea}.verification-callout strong{font-size:1.35rem}.execution-list-row{display:flex;justify-content:space-between;gap:12px;padding:13px 0;border-bottom:1px solid #eef2f7}.execution-list-row:last-child{border-bottom:0}.execution-list-row small{display:block;color:#64748b;margin-top:4px}
@media(max-width:1180px){.execution-metrics{grid-template-columns:repeat(3,1fr)}}
@media(max-width:980px){.execution-hero,.execution-layout{grid-template-columns:1fr}.snapshot-grid{grid-template-columns:1fr}.execution-controls{grid-template-columns:1fr}}
@media(max-width:640px){.execution-metrics{grid-template-columns:1fr 1fr}.execution-form-grid{grid-template-columns:1fr}.execution-form-grid .span-2{grid-column:auto}}
</style>
