<?php if($error): ?><div class="flash error" role="alert"><?= h($error) ?></div><?php endif; ?>
<?php if(data_is_production()&&!execution_tables_ready()): ?><div class="flash warning" role="status"><strong>Production execution saving is not active yet.</strong> Import <code>database/20260726_section14_execution_recovery_verification.sql</code> after Sections 11–13 during the final deployment window. Planning analysis remains available.</div><?php endif; ?>

<section class="execution-hero">
    <div>
        <span class="eyebrow">Mitigation Execution, Recovery Verification &amp; Procurement Change Control</span>
        <h2><?= h($selected['title']??($blueprint['title']??'Select a mitigation action')) ?></h2>
        <p>Convert an approved mitigation action into a controlled operational change, preserve before-and-after evidence, and independently verify actual recovery.</p>
        <div class="company-chip-row"><span><?= h(current_scope_label()) ?></span><span><?= h($selected['execution_number']??'Execution blueprint') ?></span><span><?= h(status_label($selected?execution_effective_status($selected):'proposed')) ?></span><span><?= h(status_label($selected['change_risk']??($blueprint['change_risk']??'medium'))) ?> change risk</span></div>
    </div>
    <div class="execution-status <?= h(status_class($selected?execution_effective_status($selected):'medium')) ?>"><span>Change-control state</span><strong><?= h(status_label($selected?execution_effective_status($selected):'proposed')) ?></strong><small><?= ($selected&&execution_requires_approval($selected))?'Human approval is required before execution.':'This change may proceed under the active mitigation plan and assigned permissions.' ?></small></div>
</section>

<?php $displayMetrics=$metrics?:['planned_recovery_value'=>0,'actual_recovery_value'=>0,'recovery_attainment_pct'=>0,'cost_variance'=>0,'risk_reduction'=>0,'lead_time_improvement_days'=>0]; ?>
<section class="execution-metrics" aria-label="Execution recovery metrics">
    <article class="execution-metric"><span>Planned recovery</span><strong><?= compact_money($displayMetrics['planned_recovery_value']) ?></strong><small>Approved target value</small></article>
    <article class="execution-metric"><span>Actual recovery</span><strong><?= compact_money($displayMetrics['actual_recovery_value']) ?></strong><small>Independent evidence</small></article>
    <article class="execution-metric"><span>Recovery attainment</span><strong><?= number_format((float)$displayMetrics['recovery_attainment_pct'],1) ?>%</strong><small>Actual versus planned</small></article>
    <article class="execution-metric"><span>Cost variance</span><strong><?= compact_money($displayMetrics['cost_variance']) ?></strong><small>Actual minus planned</small></article>
    <article class="execution-metric"><span>Risk reduction</span><strong><?= number_format((float)$displayMetrics['risk_reduction'],1) ?> pts</strong><small>Before versus after</small></article>
    <article class="execution-metric"><span>Lead-time recovery</span><strong><?= (int)$displayMetrics['lead_time_improvement_days'] ?> days</strong><small>Verified improvement</small></article>
</section>

<section class="panel">
<header class="panel-head"><div><span class="eyebrow">Execution source</span><h2>Select mitigation plan and action</h2><p>Execution records remain linked to the governed mitigation plan and the exact owned action being implemented.</p></div><span class="panel-meta">Plan → action → change → verification</span></header>
<form method="get" class="execution-form-grid">
<label><span>Mitigation plan</span><select name="plan_id" onchange="this.form.submit()"><?php foreach(mitigation_records() as $row): ?><option value="<?= (int)$row['id'] ?>" <?= (int)($plan['id']??0)===(int)$row['id']?'selected':'' ?>><?= h($row['plan_number'].' · '.$row['title']) ?></option><?php endforeach; ?></select></label>
<label><span>Mitigation action</span><select name="action_id" onchange="this.form.submit()"><?php foreach($plan?mitigation_actions((int)$plan['id']):[] as $row): ?><option value="<?= (int)$row['id'] ?>" <?= (int)($action['id']??0)===(int)$row['id']?'selected':'' ?>><?= h('#'.$row['sequence_no'].' · '.$row['title']) ?></option><?php endforeach; ?></select></label>
</form>
<?php if($plan): $readiness=execution_plan_readiness((int)$plan['id']); ?><div class="company-chip-row"><span>Plan status: <?= h(status_label(mitigation_operational_status($plan))) ?></span><span><?= (int)$readiness['verified_count'] ?>/<?= (int)$readiness['required_count'] ?> completed actions verified</span><span><?= $readiness['ready']?'Containment evidence complete':'Containment remains gated' ?></span></div><?php endif; ?>
</section>

<div class="execution-layout">
<main>
<?php if($selected): $status=execution_effective_status($selected);$beforeSnapshot=$selected['before'];$targetSnapshot=$selected['target'];$actualSnapshot=$selected['actual']; ?>
<section class="panel">
<header class="panel-head"><div><span class="eyebrow">Before / target / actual</span><h2>Transparent recovery evidence</h2><p>The operational baseline, approved target, and reported actual values remain visible side by side.</p></div><span class="panel-meta">Updated <?= h(date_us($selected['updated_at'],true)) ?></span></header>
<div class="snapshot-grid">
<article class="snapshot-card"><span class="eyebrow">Before change</span><h3>Operational baseline</h3><dl><dt>Risk score</dt><dd><?= number_format((float)($beforeSnapshot['risk_score']??0),1) ?></dd><dt>Lead-time delay</dt><dd><?= (int)($beforeSnapshot['lead_time_days']??0) ?> days</dd><dt>Inventory exposure</dt><dd><?= compact_money($beforeSnapshot['inventory_exposure']??0) ?></dd><dt>Open PO value</dt><dd><?= compact_money($beforeSnapshot['open_po_value']??0) ?></dd><dt>Service level</dt><dd><?= number_format((float)($beforeSnapshot['service_level']??0),1) ?>%</dd></dl></article>
<article class="snapshot-card"><span class="eyebrow">Approved target</span><h3>Expected recovery</h3><dl><dt>Recovery value</dt><dd><?= compact_money($targetSnapshot['recovery_value']??0) ?></dd><dt>Implementation cost</dt><dd><?= compact_money($targetSnapshot['cost']??0) ?></dd><dt>Residual risk</dt><dd><?= number_format((float)($targetSnapshot['risk_score']??0),1) ?></dd><dt>Target lead time</dt><dd><?= (int)($targetSnapshot['lead_time_days']??0) ?> days</dd><dt>Service level</dt><dd><?= number_format((float)($targetSnapshot['service_level']??0),1) ?>%</dd></dl></article>
<article class="snapshot-card"><span class="eyebrow">Reported actual</span><h3>Execution outcome</h3><dl><dt>Recovery value</dt><dd><?= compact_money($actualSnapshot['recovery_value']??0) ?></dd><dt>Actual cost</dt><dd><?= compact_money($actualSnapshot['cost']??0) ?></dd><dt>After risk</dt><dd><?= number_format((float)($actualSnapshot['risk_score']??0),1) ?></dd><dt>After lead time</dt><dd><?= (int)($actualSnapshot['lead_time_days']??0) ?> days</dd><dt>Service level</dt><dd><?= number_format((float)($actualSnapshot['service_level']??0),1) ?>%</dd></dl></article>
</div>
</section>

<section class="panel">
<header class="panel-head"><div><span class="eyebrow">Controlled execution</span><h2>Governed status actions</h2><p>High-impact changes require approval, execution requires an active mitigation plan, and completed work requires independent recovery verification.</p></div><span class="panel-meta"><?= h(status_label($status)) ?></span></header>
<div class="execution-controls">
<article class="execution-card"><div class="execution-card-head"><div><div class="execution-meta"><span><?= h(status_label($selected['execution_type'])) ?></span><span><?= h(status_label($selected['change_risk'])) ?> risk</span><span><?= execution_requires_approval($selected)?'Approval required':'Direct control' ?></span></div><h3><?= h($selected['title']) ?></h3></div><?= badge($status) ?></div><p><?= h($selected['evidence_note']) ?></p><div class="verification-callout"><span>Rollback plan</span><p><?= h($selected['rollback_plan']) ?></p></div>
<?php if(can('approvals.submit')&&execution_requires_approval($selected)&&in_array($status,['proposed','changes_requested'],true)): ?><form action="<?= h(app_url('execution-action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="submit"><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><button class="button primary" type="submit">Route change approval</button></form><?php endif; ?>
<?php if(can('savings.edit')&&in_array($status,['proposed','approved','scheduled'],true)&&execution_can_start($selected)): ?><form action="<?= h(app_url('execution-action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="start"><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><button class="button primary" type="submit">Start controlled execution</button></form><?php endif; ?>
</article>

<?php if(can('savings.edit')&&in_array($status,['in_progress','blocked'],true)): ?>
<article class="execution-card"><span class="eyebrow">Execution evidence</span><h3>Update or complete change</h3><form action="<?= h(app_url('execution-action.php')) ?>" method="post" class="execution-form-grid"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>">
<label><span>Status</span><select name="status"><option value="in_progress" <?= $status==='in_progress'?'selected':'' ?>>In progress</option><option value="blocked" <?= $status==='blocked'?'selected':'' ?>>Blocked</option></select></label><label><span>Actual recovery value</span><input type="number" min="0" step="0.01" name="actual_recovery_value" value="<?= h((string)($actualSnapshot['recovery_value']??0)) ?>"></label>
<label><span>Actual cost</span><input type="number" min="0" step="0.01" name="actual_cost" value="<?= h((string)($actualSnapshot['cost']??0)) ?>"></label><label><span>After risk score</span><input type="number" min="0" max="100" step="0.1" name="after_risk_score" value="<?= h((string)($actualSnapshot['risk_score']??$beforeSnapshot['risk_score']??0)) ?>"></label>
<label><span>After lead-time days</span><input type="number" min="0" name="after_lead_time_days" value="<?= h((string)($actualSnapshot['lead_time_days']??$beforeSnapshot['lead_time_days']??0)) ?>"></label><label><span>Inventory exposure reduced</span><input type="number" min="0" step="0.01" name="inventory_exposure_reduced" value="<?= h((string)($actualSnapshot['inventory_exposure_reduced']??0)) ?>"></label>
<label><span>PO value redirected</span><input type="number" min="0" step="0.01" name="po_value_redirected" value="<?= h((string)($actualSnapshot['po_value_redirected']??0)) ?>"></label><label><span>Service level after %</span><input type="number" min="0" max="100" step="0.1" name="service_level_after" value="<?= h((string)($actualSnapshot['service_level']??$beforeSnapshot['service_level']??0)) ?>"></label>
<label class="span-2"><span>Execution evidence note</span><textarea name="evidence_note" rows="4" required><?= h($selected['evidence_note']) ?></textarea></label><div class="span-2"><button class="button secondary" name="action" value="update_progress" type="submit">Update progress</button> <button class="button primary" name="action" value="complete" type="submit">Complete execution</button></div></form></article>
<?php endif; ?>

<?php if(can('approvals.review')&&in_array($status,['completed','failed'],true)): ?>
<article class="execution-card"><span class="eyebrow">Independent recovery verification</span><h3>Verify actual business outcome</h3><form action="<?= h(app_url('execution-action.php')) ?>" method="post" class="execution-form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="verify"><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>">
<label><span>Verification outcome</span><select name="verification_status"><option value="verified">Verified recovery</option><option value="needs_follow_up">Needs follow-up</option><option value="failed">Recovery failed</option></select></label><label><span>Actual recovery value</span><input type="number" min="0" step="0.01" name="actual_recovery_value" value="<?= h((string)($actualSnapshot['recovery_value']??0)) ?>"></label>
<label><span>Actual cost</span><input type="number" min="0" step="0.01" name="actual_cost" value="<?= h((string)($actualSnapshot['cost']??0)) ?>"></label><label><span>After risk score</span><input type="number" min="0" max="100" step="0.1" name="after_risk_score" value="<?= h((string)($actualSnapshot['risk_score']??$beforeSnapshot['risk_score']??0)) ?>"></label>
<label><span>After lead-time days</span><input type="number" min="0" name="after_lead_time_days" value="<?= h((string)($actualSnapshot['lead_time_days']??$beforeSnapshot['lead_time_days']??0)) ?>"></label><label><span>Inventory exposure reduced</span><input type="number" min="0" step="0.01" name="inventory_exposure_reduced" value="<?= h((string)($actualSnapshot['inventory_exposure_reduced']??0)) ?>"></label>
<label><span>PO value redirected</span><input type="number" min="0" step="0.01" name="po_value_redirected" value="<?= h((string)($actualSnapshot['po_value_redirected']??0)) ?>"></label><label><span>Service level after %</span><input type="number" min="0" max="100" step="0.1" name="service_level_after" value="<?= h((string)($actualSnapshot['service_level']??$beforeSnapshot['service_level']??0)) ?>"></label>
<label class="span-2"><span>Verification evidence</span><textarea name="verification_evidence" rows="4" required>Verify against source purchase orders, receiving records, inventory evidence, supplier commitments, cost documentation, and service outcomes.</textarea></label><div class="span-2"><button class="button primary" type="submit">Record verification</button></div></form></article>
<?php endif; ?>

<?php if(can('savings.edit')&&in_array($status,['blocked','completed','verified','failed'],true)): ?><article class="execution-card"><span class="eyebrow">Reversal control</span><h3>Rollback controlled change</h3><form action="<?= h(app_url('execution-action.php')) ?>" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="rollback"><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><label><span>Rollback evidence</span><textarea name="rollback_evidence" rows="4" required>Document the reversal date, restored supplier/order/inventory state, affected owners, residual exposure, and follow-up decision.</textarea></label><button class="button secondary" type="submit">Record rollback</button></form></article><?php endif; ?>
</div>
</section>

<section class="panel"><header class="panel-head"><div><span class="eyebrow">Immutable execution history</span><h2>Change-control timeline</h2><p>Every state change preserves the actor, timestamp, evidence, and before/after status.</p></div><span class="panel-meta"><?= count($events) ?> events</span></header><?php foreach($events as $event): ?><div class="timeline-row"><small><?= h(date_us($event['created_at'],true)) ?></small><div><strong><?= h(status_label($event['event_type'])) ?></strong><p><?= h($event['evidence_note']) ?></p><small><?= h(status_label((string)($event['from_status']??'new'))) ?> → <?= h(status_label((string)($event['to_status']??'unchanged'))) ?> · User #<?= (int)$event['created_by'] ?></small></div></div><?php endforeach; ?><?php if(!$events)render_empty_state('No execution events','Save an execution record to begin the governed history.'); ?></section>
<?php endif; ?>
</main>

<aside>
<article class="execution-card"><span class="eyebrow">Execution portfolio</span><h2>Controlled changes</h2><?php foreach($records as $row): $rowVerification=execution_latest_verification((int)$row['id']); ?><div class="execution-list-row"><div><strong><?= h($row['title']) ?></strong><small><?= h($row['execution_number']) ?> · <?= h(status_label($row['change_risk'])) ?> risk · <?= h(date_us($row['scheduled_date'])) ?></small><div><?= badge(execution_effective_status($row)) ?><?php if($rowVerification): ?> <?= badge((string)$rowVerification['status']) ?><?php endif; ?></div></div><a href="<?= h(app_url('executions.php?id='.(int)$row['id'])) ?>">Open</a></div><?php endforeach; ?><?php if(!$records)render_empty_state('No controlled changes','Create an execution record from a mitigation action.'); ?></article>

<?php if($verification): ?><article class="execution-card"><span class="eyebrow">Recovery verification</span><h2><?= h($verification['verification_number']) ?></h2><div class="verification-callout"><strong><?= h(status_label($verification['status'])) ?></strong><p><?= h($verification['evidence_note']) ?></p><small>Reviewed <?= h(date_us($verification['verified_at'],true)) ?> by user #<?= (int)$verification['reviewer_id'] ?></small></div><dl><dt>Actual recovery</dt><dd><?= compact_money($verification['actual_recovery_value']) ?></dd><dt>Actual cost</dt><dd><?= compact_money($verification['actual_cost']) ?></dd><dt>After risk</dt><dd><?= number_format((float)$verification['after_risk_score'],1) ?></dd></dl></article><?php endif; ?>

<?php if(can('savings.edit')&&$blueprint): ?><article class="execution-card"><span class="eyebrow">Change blueprint</span><h2>Create execution record</h2><p>Protected CSV export becomes available after the record is saved.</p><form action="<?= h(app_url('execution-action.php')) ?>" method="post" class="execution-form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="save_execution"><input type="hidden" name="id" value="0"><input type="hidden" name="plan_id" value="<?= (int)$plan['id'] ?>"><input type="hidden" name="action_id" value="<?= (int)$action['id'] ?>">
<label class="span-2"><span>Execution title</span><input name="title" maxlength="190" required value="<?= h($blueprint['title']) ?>"></label><label><span>Owner</span><select name="owner_id"><?php foreach(data_admin_visible_users() as $user): ?><option value="<?= (int)$user['id'] ?>" <?= (int)$action['owner_id']===(int)$user['id']?'selected':'' ?>><?= h($user['name']) ?></option><?php endforeach; ?></select></label><label><span>Change risk</span><select name="change_risk"><?php foreach(execution_risk_levels() as $risk): ?><option value="<?= h($risk) ?>" <?= $blueprint['change_risk']===$risk?'selected':'' ?>><?= h(status_label($risk)) ?></option><?php endforeach; ?></select></label>
<label><span>Scheduled date</span><input type="date" name="scheduled_date" required value="<?= h($blueprint['scheduled_date']) ?>"></label><label><span>Approval control</span><input value="<?= execution_requires_approval(['change_risk'=>$blueprint['change_risk'],'execution_type'=>$blueprint['execution_type'],'target'=>$blueprint['target']])?'Required before execution':'Direct under active plan' ?>" readonly></label>
<label class="span-2"><span>Evidence requirements</span><textarea name="evidence_note" rows="4" required><?= h($blueprint['evidence_note']) ?></textarea></label><label class="span-2"><span>Rollback plan</span><textarea name="rollback_plan" rows="4" required><?= h($blueprint['rollback_plan']) ?></textarea></label><div class="span-2"><button class="button primary" type="submit">Save controlled change</button></div></form></article><?php endif; ?>
</aside>
</div>
