<?php
declare(strict_types=1);
$migrationReady=fulfillment_tables_ready();$effectiveInvoice=$invoice?fulfillment_invoice_effective_status($invoice):null;$locations=data_visible_collection('inventory_locations');$acceptedMap=$selected?fulfillment_received_quantities((int)$selected['id']):[];
?>
<section class="metric-grid metric-grid-4">
<article class="metric-card"><span>Open PO value</span><strong><?= money($metrics['po_value']??0) ?></strong><small><?= h($selected['po_number']??'No purchase order') ?></small></article>
<article class="metric-card"><span>Unreceived commitment</span><strong><?= money($metrics['unreceived_commitment']??0) ?></strong><small><?= number_format((float)($metrics['acceptance_pct']??0),1) ?>% accepted</small></article>
<article class="metric-card"><span>Invoice hold value</span><strong><?= money($metrics['invoice_hold_value']??0) ?></strong><small><?= (int)($metrics['open_exception_count']??0) ?> open exception(s)</small></article>
<article class="metric-card"><span>Released for payment</span><strong><?= money($metrics['released_value']??0) ?></strong><small><?= money($metrics['supplier_credit_recovery']??0) ?> supplier credits</small></article>
</section>
<?php if(data_is_production()&&!$migrationReady): ?><section class="notice-card"><div><span class="notice-icon">!</span><div><strong>Section 18 Production Data migration required</strong><p>Existing purchase orders, receipts, and inventory remain readable. Fulfillment profiles, invoices, match results, exceptions, events, and payment-release writes are disabled until the Section 18 migration is imported.</p></div></div></section><?php endif; ?>
<section class="panel"><header class="panel-head"><div><span class="eyebrow">Operational scope</span><h2>Purchase order and invoice selection</h2></div><span class="panel-meta"><?= count($orders) ?> visible POs</span></header><form class="filter-bar" method="get"><label><span>Purchase order</span><select name="id" onchange="this.form.submit()"><option value="">Select purchase order</option><?php foreach($orders as $order): ?><option value="<?= (int)$order['id'] ?>" <?= $selected&&(int)$selected['id']===(int)$order['id']?'selected':'' ?>><?= h($order['po_number'].' · '.data_supplier_name($order['supplier_id']).' · '.money($order['total_amount'])) ?></option><?php endforeach; ?></select></label><?php if($selected): ?><label><span>Supplier invoice</span><select name="invoice_id" onchange="this.form.submit()"><option value="">Latest / priority invoice</option><?php foreach($invoices as $candidate): ?><option value="<?= (int)$candidate['id'] ?>" <?= $invoice&&(int)$candidate['id']===(int)$invoice['id']?'selected':'' ?>><?= h($candidate['invoice_number'].' · '.money($candidate['total_amount']).' · '.status_label(fulfillment_invoice_effective_status($candidate))) ?></option><?php endforeach; ?></select></label><?php endif; ?><button class="button secondary" type="submit">Load workspace</button></form></section>
<?php if(!$selected): ?><?php render_empty_state('No purchase order selected','Select a visible purchase order to manage fulfillment, receipts, invoices, exceptions, and payment release.'); ?><?php else: ?>
<section class="notice-card <?= !empty($metrics['past_due'])?'opportunity-notice':'' ?>"><div><span class="notice-icon"><?= !empty($metrics['past_due'])?'!':'✓' ?></span><div><strong><?= h($selected['po_number']) ?> · <?= h(data_supplier_name($selected['supplier_id'])) ?></strong><p><?= h(data_company_name($selected['company_id'])) ?> · expected <?= h(date_us($selected['expected_date'])) ?> · shipment <?= h(status_label($selected['shipment_status'])) ?> · <?= h($selected['fulfillment_evidence']) ?></p></div></div><a href="<?= h(app_url('contracts.php?supplier_id='.(int)$selected['supplier_id'])) ?>">Contract evidence →</a></section>
<div class="fulfillment-grid"><div class="fulfillment-stack"><?php require __DIR__ . '/fulfillment_view_fulfillment.php'; ?><?php require __DIR__ . '/fulfillment_view_receiving.php'; ?><?php require __DIR__ . '/fulfillment_view_invoices.php'; ?></div><div class="fulfillment-stack"><?php require __DIR__ . '/fulfillment_view_match.php'; ?><?php require __DIR__ . '/fulfillment_view_exceptions.php'; ?><?php require __DIR__ . '/fulfillment_view_payment.php'; ?><?php require __DIR__ . '/fulfillment_view_history.php'; ?></div></div>
<?php endif; ?>
