<?php
declare(strict_types=1);

function fulfillment_match_blueprint(array $invoice,array $invoiceLines,array $po,array $poLines,array $receiptLines,float $toleranceAmount=100.0,float $tolerancePct=2.0): array
{
    if(!$invoiceLines)throw new RuntimeException('Add at least one invoice line before three-way matching.');
    $poMap=[];foreach($poLines as $line)$poMap[(int)$line['id']]=$line;$received=[];foreach($receiptLines as $line){$id=(int)$line['purchase_order_line_id'];if(!isset($received[$id]))$received[$id]=['accepted'=>0.0,'rejected'=>0.0,'held'=>0.0];$received[$id]['accepted']+=(float)$line['quantity_accepted'];$received[$id]['rejected']+=(float)$line['quantity_rejected'];if(in_array((string)$line['condition_status'],['quality_hold','damaged','incorrect','returned'],true))$received[$id]['held']+=(float)$line['quantity_rejected'];}
    $poValue=0.0;$acceptedValue=0.0;$invoiceLineValue=0.0;$quantityVariance=0.0;$priceVariance=0.0;$contractVariance=0.0;$unreceivedValue=0.0;$heldRejectedValue=0.0;$missingPoLine=false;
    foreach($invoiceLines as $line){$poLine=$poMap[(int)($line['purchase_order_line_id']??0)]??null;$invoiceQty=max(0,(float)($line['quantity_invoiced']??0));$invoicePrice=max(0,(float)($line['unit_price']??0));$invoiceValue=(float)($line['line_total']??round($invoiceQty*$invoicePrice,2));$invoiceLineValue+=$invoiceValue;if(!$poLine){$missingPoLine=true;$quantityVariance+=$invoiceValue;continue;}$ordered=max(0,(float)$poLine['quantity_ordered']);$poPrice=max(0,(float)$poLine['unit_cost']);$contractPrice=$poLine['contract_cost_at_order']!==null?(float)$poLine['contract_cost_at_order']:$poPrice;$accepted=max(0,(float)($received[(int)$poLine['id']]['accepted']??0));$held=max(0,(float)($received[(int)$poLine['id']]['held']??0));$poValue+=$ordered*$poPrice;$acceptedValue+=min($accepted,$invoiceQty)*$poPrice;$excessQty=max(0,$invoiceQty-$accepted);$quantityVariance+=$excessQty*$invoicePrice;$unreceivedValue+=$excessQty*$invoicePrice;$priceVariance+=($invoicePrice-$poPrice)*$invoiceQty;$contractVariance+=($invoicePrice-$contractPrice)*$invoiceQty;$heldRejectedValue+=min($held,$excessQty)*$poPrice;}
    $freightVariance=(float)$invoice['freight_amount']-(float)($po['freight_amount']??0);$taxVariance=(float)$invoice['tax_amount']-(float)($po['tax_amount']??0);$invoiceValue=(float)$invoice['total_amount'];$prior=0.0;foreach(fulfillment_invoices((int)$po['id']) as $other){if((int)$other['id']===(int)$invoice['id']||in_array((string)$other['status'],['void'],true))continue;$prior+=(float)$other['total_amount'];}$remaining=max(0,(float)$po['total_amount']-$prior);$duplicate=fulfillment_invoice_duplicate($invoice);$pctBase=max(1,$invoiceValue);$threshold=max($toleranceAmount,$pctBase*($tolerancePct/100));$priceExposure=max(abs($priceVariance),abs($contractVariance));$absoluteExposure=max(abs($quantityVariance),$heldRejectedValue)+$priceExposure+abs($freightVariance)+abs($taxVariance);$blocked=$duplicate||$missingPoLine||$invoiceValue>$remaining+$threshold||$unreceivedValue>$threshold;$status=$blocked?'blocked':($absoluteExposure<=$threshold?'within_tolerance':'exception');if($absoluteExposure<0.01&&!$blocked)$status='matched';$score=100.0;$score-=min(40,($absoluteExposure/$pctBase)*100);if($duplicate)$score-=35;if($missingPoLine)$score-=25;if($invoiceValue>$remaining+$threshold)$score-=20;$score=max(0,min(100,round($score,1)));
    return ['po_value'=>round($poValue,2),'accepted_receipt_value'=>round($acceptedValue,2),'invoice_value'=>round($invoiceValue,2),'quantity_variance'=>round($quantityVariance,2),'price_variance'=>round($priceVariance,2),'freight_variance'=>round($freightVariance,2),'tax_variance'=>round($taxVariance,2),'contract_variance'=>round($contractVariance,2),'unreceived_value'=>round($unreceivedValue,2),'held_rejected_value'=>round($heldRejectedValue,2),'remaining_po_balance'=>round($remaining,2),'duplicate_flag'=>$duplicate,'missing_po_line'=>$missingPoLine,'tolerance_amount'=>$toleranceAmount,'tolerance_pct'=>$tolerancePct,'match_status'=>$status,'match_score'=>$score,'exception_exposure'=>round($absoluteExposure,2)];
}

function fulfillment_metrics(array $po,array $poLines,array $receipts,array $receiptLines,array $invoices): array
{
    $orderedQty=array_sum(array_map(static fn(array $l):float=>(float)$l['quantity_ordered'],$poLines));$received=fulfillment_received_quantities((int)$po['id']);$acceptedQty=0.0;$rejectedQty=0.0;foreach($received as $row){$acceptedQty+=$row['accepted'];$rejectedQty+=$row['rejected'];}$unreceivedValue=0.0;foreach($poLines as $line){$accepted=(float)($received[(int)$line['id']]['accepted']??0);$unreceivedValue+=max(0,(float)$line['quantity_ordered']-$accepted)*(float)$line['unit_cost'];}$invoiceValue=array_sum(array_map(static fn(array $i):float=>(float)$i['total_amount'],$invoices));$holdValue=array_sum(array_map(static fn(array $i):float=>in_array((string)$i['status'],['exception','on_hold'],true)?(float)$i['total_amount']:0,$invoices));$releasedValue=array_sum(array_map(static fn(array $i):float=>in_array((string)$i['status'],['approved_for_payment','paid'],true)?(float)$i['total_amount']:0,$invoices));$exceptions=0;$credit=0.0;foreach($invoices as $invoice)foreach(fulfillment_exceptions((int)$invoice['id']) as $exception){if(!in_array((string)$exception['status'],['resolved','waived','rejected'],true))$exceptions++;$credit+=(float)($exception['supplier_credit_amount']??0);}return ['po_value'=>(float)$po['total_amount'],'ordered_quantity'=>$orderedQty,'accepted_quantity'=>$acceptedQty,'rejected_quantity'=>$rejectedQty,'acceptance_pct'=>$orderedQty>0?round(($acceptedQty/$orderedQty)*100,1):0.0,'unreceived_commitment'=>round($unreceivedValue,2),'receipt_count'=>count($receipts),'invoice_value'=>round($invoiceValue,2),'invoice_hold_value'=>round($holdValue,2),'released_value'=>round($releasedValue,2),'open_exception_count'=>$exceptions,'supplier_credit_recovery'=>round($credit,2),'past_due'=>($po['status']==='past_due'||(!empty($po['expected_date'])&&$po['expected_date']<date('Y-m-d')&&!in_array($po['status'],['received','closed','canceled'],true)))];
}

function fulfillment_payment_release_ready(array $invoice,array $match,array $exceptions): bool
{
    foreach($exceptions as $exception)if(!in_array((string)$exception['status'],['resolved','waived','rejected'],true))return false;$status=(string)$match['match_status'];if(in_array($status,['matched','within_tolerance','exception'],true))return true;return $status==='blocked'&&count($exceptions)>0;
}
