<?php
declare(strict_types=1);

function fulfillment_save_invoice(array $record): array
{
    $record['updated_at']=date('Y-m-d H:i:s');$record['created_at']=$record['created_at']??$record['updated_at'];$record['duplicate_fingerprint']=$record['duplicate_fingerprint']??hash('sha256',(int)$record['supplier_id'].'|'.strtoupper((string)$record['invoice_number']).'|'.number_format((float)$record['total_amount'],2,'.',''));
    if(data_is_demo()){$rows=$_SESSION['gruber_demo_state']['supplier_invoices']??fulfillment_demo_invoices();$id=(int)($record['id']??0);if($id<=0){$id=max([0,...array_map('intval',array_column($rows,'id'))])+1;$record['id']=$id;}$found=false;foreach($rows as $i=>$row)if((int)$row['id']===$id){$rows[$i]=array_replace($row,$record);$record=$rows[$i];$found=true;break;}if(!$found)$rows[]=$record;$_SESSION['gruber_demo_state']['supplier_invoices']=$rows;return $record;}
    if(!fulfillment_tables_ready())throw new RuntimeException('Import the Section 18 migration before saving Production Data invoices.');$pdo=production_database_connection();$id=(int)($record['id']??0);$params=[$record['invoice_number'],$record['company_id'],$record['supplier_id'],$record['purchase_order_id'],$record['contract_id'],$record['invoice_date'],$record['due_date'],$record['payment_terms'],$record['currency_code'],$record['subtotal'],$record['freight_amount'],$record['tax_amount'],$record['total_amount'],$record['document_path'],$record['status'],$record['owner_id'],$record['reviewer_id'],$record['approval_id'],$record['hold_reason'],$record['duplicate_fingerprint'],$record['released_at'],$record['paid_at']];if($id>0){$pdo->prepare('UPDATE supplier_invoices SET invoice_number=?,company_id=?,supplier_id=?,purchase_order_id=?,contract_id=?,invoice_date=?,due_date=?,payment_terms=?,currency_code=?,subtotal=?,freight_amount=?,tax_amount=?,total_amount=?,document_path=?,status=?,owner_id=?,reviewer_id=?,approval_id=?,hold_reason=?,duplicate_fingerprint=?,released_at=?,paid_at=?,updated_at=NOW() WHERE id=?')->execute([...$params,$id]);}else{$pdo->prepare('INSERT INTO supplier_invoices (invoice_number,company_id,supplier_id,purchase_order_id,contract_id,invoice_date,due_date,payment_terms,currency_code,subtotal,freight_amount,tax_amount,total_amount,document_path,status,owner_id,reviewer_id,approval_id,hold_reason,duplicate_fingerprint,released_at,paid_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute($params);$id=(int)$pdo->lastInsertId();}$record['id']=$id;return fulfillment_find_invoice($id)??$record;
}

function fulfillment_save_invoice_line(array $record): array
{
    $record['updated_at']=date('Y-m-d H:i:s');$record['created_at']=$record['created_at']??$record['updated_at'];$record['line_total']=round((float)$record['quantity_invoiced']*(float)$record['unit_price'],2);if(data_is_demo()){$rows=$_SESSION['gruber_demo_state']['supplier_invoice_lines']??fulfillment_demo_invoice_lines();$id=(int)($record['id']??0);if($id<=0){$id=max([0,...array_map('intval',array_column($rows,'id'))])+1;$record['id']=$id;}$found=false;foreach($rows as $i=>$row)if((int)$row['id']===$id){$rows[$i]=array_replace($row,$record);$record=$rows[$i];$found=true;break;}if(!$found)$rows[]=$record;$_SESSION['gruber_demo_state']['supplier_invoice_lines']=$rows;return $record;}if(!fulfillment_tables_ready())throw new RuntimeException('Import the Section 18 migration before saving invoice lines.');$pdo=production_database_connection();$id=(int)($record['id']??0);$params=[$record['invoice_id'],$record['purchase_order_line_id'],$record['item_id'],$record['description'],$record['quantity_invoiced'],$record['unit_price'],$record['line_total'],$record['tax_amount'],$record['freight_amount']];if($id>0){$pdo->prepare('UPDATE supplier_invoice_lines SET invoice_id=?,purchase_order_line_id=?,item_id=?,description=?,quantity_invoiced=?,unit_price=?,line_total=?,tax_amount=?,freight_amount=?,updated_at=NOW() WHERE id=?')->execute([...$params,$id]);}else{$pdo->prepare('INSERT INTO supplier_invoice_lines (invoice_id,purchase_order_line_id,item_id,description,quantity_invoiced,unit_price,line_total,tax_amount,freight_amount) VALUES (?,?,?,?,?,?,?,?,?)')->execute($params);$id=(int)$pdo->lastInsertId();}$record['id']=$id;return $record;
}

function fulfillment_save_match(array $record): array
{
    $record['match_number']=$record['match_number']??fulfillment_next_number('MATCH','procurement_match_results','procurement_match_results',fulfillment_demo_matches());$record['created_at']=$record['created_at']??date('Y-m-d H:i:s');if(data_is_demo()){$rows=$_SESSION['gruber_demo_state']['procurement_match_results']??fulfillment_demo_matches();$record['id']=max([0,...array_map('intval',array_column($rows,'id'))])+1;$rows[]=$record;$_SESSION['gruber_demo_state']['procurement_match_results']=$rows;return $record;}if(!fulfillment_tables_ready())throw new RuntimeException('Import the Section 18 migration before saving match results.');$pdo=production_database_connection();$pdo->prepare('INSERT INTO procurement_match_results (match_number,invoice_id,purchase_order_id,po_value,accepted_receipt_value,invoice_value,quantity_variance,price_variance,freight_variance,tax_variance,contract_variance,unreceived_value,held_rejected_value,remaining_po_balance,duplicate_flag,tolerance_amount,tolerance_pct,match_status,match_score,evidence_note,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$record['match_number'],$record['invoice_id'],$record['purchase_order_id'],$record['po_value'],$record['accepted_receipt_value'],$record['invoice_value'],$record['quantity_variance'],$record['price_variance'],$record['freight_variance'],$record['tax_variance'],$record['contract_variance'],$record['unreceived_value'],$record['held_rejected_value'],$record['remaining_po_balance'],$record['duplicate_flag']?1:0,$record['tolerance_amount'],$record['tolerance_pct'],$record['match_status'],$record['match_score'],$record['evidence_note'],$record['created_by']]);$record['id']=(int)$pdo->lastInsertId();return $record;
}

function fulfillment_save_exception(array $record): array
{
    $record['exception_number']=$record['exception_number']??fulfillment_next_number('EXC','procurement_invoice_exceptions','procurement_invoice_exceptions',fulfillment_demo_exceptions());$record['updated_at']=date('Y-m-d H:i:s');$record['created_at']=$record['created_at']??$record['updated_at'];if(data_is_demo()){$rows=$_SESSION['gruber_demo_state']['procurement_invoice_exceptions']??fulfillment_demo_exceptions();$id=(int)($record['id']??0);if($id<=0){$id=max([0,...array_map('intval',array_column($rows,'id'))])+1;$record['id']=$id;}$found=false;foreach($rows as $i=>$row)if((int)$row['id']===$id){$rows[$i]=array_replace($row,$record);$record=$rows[$i];$found=true;break;}if(!$found)$rows[]=$record;$_SESSION['gruber_demo_state']['procurement_invoice_exceptions']=$rows;return $record;}if(!fulfillment_tables_ready())throw new RuntimeException('Import the Section 18 migration before saving invoice exceptions.');$pdo=production_database_connection();$id=(int)($record['id']??0);$params=[$record['exception_number'],$record['invoice_id'],$record['match_result_id'],$record['purchase_order_id'],$record['exception_type'],$record['severity'],$record['status'],$record['owner_id'],$record['reviewer_id'],$record['due_date'],$record['disputed_amount'],$record['waiver_reason'],$record['resolution_note'],$record['supplier_credit_amount'],$record['approval_id']];if($id>0){$pdo->prepare('UPDATE procurement_invoice_exceptions SET exception_number=?,invoice_id=?,match_result_id=?,purchase_order_id=?,exception_type=?,severity=?,status=?,owner_id=?,reviewer_id=?,due_date=?,disputed_amount=?,waiver_reason=?,resolution_note=?,supplier_credit_amount=?,approval_id=?,updated_at=NOW() WHERE id=?')->execute([...$params,$id]);}else{$pdo->prepare('INSERT INTO procurement_invoice_exceptions (exception_number,invoice_id,match_result_id,purchase_order_id,exception_type,severity,status,owner_id,reviewer_id,due_date,disputed_amount,waiver_reason,resolution_note,supplier_credit_amount,approval_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute($params);$id=(int)$pdo->lastInsertId();}$record['id']=$id;return $record;
}
