<?php
declare(strict_types=1);

function fulfillment_add_event(int $poId,?int $invoiceId,string $type,string $entityType,int $entityId,?string $from,?string $to,string $severity,string $note): array
{
    if(!in_array($type,fulfillment_event_types(),true))$type='fulfillment_updated';if(!in_array($severity,['low','medium','high','critical'],true))$severity='medium';$row=['purchase_order_id'=>$poId,'invoice_id'=>$invoiceId,'event_type'=>$type,'entity_type'=>$entityType,'entity_id'=>$entityId,'from_status'=>$from,'to_status'=>$to,'severity'=>$severity,'evidence_note'=>mb_substr(trim($note),0,5000),'created_by'=>(int)current_user()['id'],'created_at'=>date('Y-m-d H:i:s')];if(data_is_demo()){$rows=$_SESSION['gruber_demo_state']['procurement_fulfillment_events']??fulfillment_demo_events();$row['id']=max([0,...array_map('intval',array_column($rows,'id'))])+1;$rows[]=$row;$_SESSION['gruber_demo_state']['procurement_fulfillment_events']=$rows;return $row;}if(!fulfillment_tables_ready())throw new RuntimeException('Import the Section 18 migration before saving fulfillment events.');$pdo=production_database_connection();$pdo->prepare('INSERT INTO procurement_fulfillment_events (purchase_order_id,invoice_id,event_type,entity_type,entity_id,from_status,to_status,severity,evidence_note,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)')->execute([$poId,$invoiceId,$type,$entityType,$entityId,$from,$to,$severity,$row['evidence_note'],$row['created_by']]);$row['id']=(int)$pdo->lastInsertId();return $row;
}

function fulfillment_create_match_exceptions(array $invoice,array $match): array
{
    $specs=[];$threshold=max((float)$match['tolerance_amount'],(float)$match['invoice_value']*((float)$match['tolerance_pct']/100));if(!empty($match['duplicate_flag']))$specs[]=['duplicate_invoice','critical',(float)$invoice['total_amount'],'Potential duplicate supplier invoice.'];if((float)$match['quantity_variance']>$threshold)$specs[]=['quantity_variance','high',(float)$match['quantity_variance'],'Invoice quantity exceeds accepted receipt quantity.'];if(abs((float)$match['price_variance'])>$threshold)$specs[]=['price_variance','high',abs((float)$match['price_variance']),'Invoice price differs from the purchase order.'];if(abs((float)$match['contract_variance'])>$threshold)$specs[]=['contract_price_variance','high',abs((float)$match['contract_variance']),'Invoice price differs from available contract evidence.'];if(abs((float)$match['freight_variance'])>$threshold)$specs[]=['freight_variance','medium',abs((float)$match['freight_variance']),'Freight charge exceeds purchase-order evidence.'];if(abs((float)$match['tax_variance'])>$threshold)$specs[]=['tax_variance','medium',abs((float)$match['tax_variance']),'Tax charge differs from purchase-order evidence.'];if((float)$match['unreceived_value']>$threshold)$specs[]=['unreceived_quantity','critical',(float)$match['unreceived_value'],'Invoice includes value not supported by accepted receipt evidence.'];if((float)$match['held_rejected_value']>0)$specs[]=['rejected_quality','high',(float)$match['held_rejected_value'],'Rejected or quality-held material remains unresolved.'];if((float)$match['invoice_value']>(float)$match['remaining_po_balance']+$threshold)$specs[]=['po_balance_exceeded','critical',(float)$match['invoice_value']-(float)$match['remaining_po_balance'],'Invoice exceeds the remaining purchase-order balance.'];$created=[];foreach($specs as [$type,$severity,$amount,$note])$created[]=fulfillment_save_exception(['id'=>null,'invoice_id'=>$invoice['id'],'match_result_id'=>$match['id'],'purchase_order_id'=>$invoice['purchase_order_id'],'exception_type'=>$type,'severity'=>$severity,'status'=>'open','owner_id'=>$invoice['owner_id'],'reviewer_id'=>$invoice['reviewer_id'],'due_date'=>date('Y-m-d',strtotime(in_array($severity,['critical','high'],true)?'+2 days':'+5 days')),'disputed_amount'=>round($amount,2),'waiver_reason'=>'','resolution_note'=>$note,'supplier_credit_amount'=>0,'approval_id'=>null]);return $created;
}

function fulfillment_notify(int $userId,int $companyId,string $title,string $message,string $severity='info'): void { data_upsert('notifications',['id'=>null,'company_id'=>$companyId,'user_id'=>$userId,'title'=>$title,'message'=>$message,'severity'=>$severity,'read'=>false,'created_at'=>date('Y-m-d H:i:s')]); }

function fulfillment_csv_cell(string $value): string { return preg_match('/^[=+\-@]/',$value)?"'".$value:$value; }

function fulfillment_export_csv(array $po,array $metrics,array $receipts,array $receiptLines,array $invoices,array $events): never
{
    require_permission('reports.export');$filename='fulfillment-'.preg_replace('/[^A-Za-z0-9_-]+/','-',(string)$po['po_number']).'.csv';header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="'.$filename.'"');$out=fopen('php://output','wb');fputcsv($out,['Section','Reference','Status','Amount / Quantity','Evidence']);fputcsv($out,['Purchase Order',fulfillment_csv_cell((string)$po['po_number']),$po['status'],number_format((float)$po['total_amount'],2,'.',''),fulfillment_csv_cell((string)$po['fulfillment_evidence'])]);foreach($receipts as $receipt)fputcsv($out,['Receipt',fulfillment_csv_cell((string)$receipt['receipt_number']),'received',$receipt['received_at'],fulfillment_csv_cell((string)$receipt['notes'])]);foreach($receiptLines as $line)fputcsv($out,['Receipt Line',fulfillment_csv_cell((string)($line['receipt_number']??$line['receipt_id'])),$line['condition_status'],number_format((float)$line['quantity_accepted'],4,'.',''),fulfillment_csv_cell((string)$line['notes'])]);foreach($invoices as $invoice)fputcsv($out,['Invoice',fulfillment_csv_cell((string)$invoice['invoice_number']),fulfillment_invoice_effective_status($invoice),number_format((float)$invoice['total_amount'],2,'.',''),fulfillment_csv_cell((string)$invoice['hold_reason'])]);foreach($events as $event)fputcsv($out,['Event',fulfillment_csv_cell((string)$event['event_type']),$event['to_status'],(string)$event['created_at'],fulfillment_csv_cell((string)$event['evidence_note'])]);fclose($out);exit;
}
