<?php
declare(strict_types=1);

function fulfillment_post_inventory(array $po,array $poLine,array $receipt,array $receiptLine): void
{
    $accepted=max(0,(float)$receiptLine['quantity_accepted']);if($accepted<=0)return;$unitCost=(float)$poLine['unit_cost'];
    if(data_is_demo()){$snapshots=data_collection('inventory_snapshots');$target=null;foreach($snapshots as $i=>$row){if((int)$row['company_id']===(int)$po['company_id']&&(int)$row['item_id']===(int)$poLine['item_id']){$target=$i;break;}}if($target===null){$snapshots[]=['id'=>data_next_id('inventory_snapshots'),'company_id'=>$po['company_id'],'location_id'=>$receipt['location_id'],'item_id'=>$poLine['item_id'],'snapshot_date'=>date('Y-m-d'),'quantity_on_hand'=>$accepted,'allocated'=>0,'available'=>$accepted,'unit_cost'=>$unitCost,'value'=>round($accepted*$unitCost,2)];}else{$snapshots[$target]['quantity_on_hand']=(float)$snapshots[$target]['quantity_on_hand']+$accepted;$snapshots[$target]['available']=(float)($snapshots[$target]['available']??0)+$accepted;$snapshots[$target]['unit_cost']=$unitCost;$snapshots[$target]['value']=round((float)$snapshots[$target]['quantity_on_hand']*$unitCost,2);$snapshots[$target]['snapshot_date']=date('Y-m-d');}data_replace_collection('inventory_snapshots',$snapshots);$poLine['quantity_received']=(float)($poLine['quantity_received']??0)+$accepted;data_upsert('purchase_order_lines',$poLine);return;}
    $pdo=production_database_connection();if(!$pdo)throw new RuntimeException('Production database unavailable.');$stmt=$pdo->prepare('SELECT id FROM inventory_locations WHERE location_id=? AND is_active=1 ORDER BY id LIMIT 1');$stmt->execute([$receipt['location_id']]);$inventoryLocationId=(int)$stmt->fetchColumn();if($inventoryLocationId<=0)throw new RuntimeException('An active inventory location is required for accepted receipt posting.');$balance=$pdo->prepare('SELECT * FROM inventory_balances WHERE inventory_location_id=? AND item_id=? FOR UPDATE');$balance->execute([$inventoryLocationId,$poLine['item_id']]);$existing=$balance->fetch();if($existing){$oldQty=(float)$existing['quantity_on_hand'];$oldCost=(float)($existing['average_unit_cost']??0);$newQty=$oldQty+$accepted;$newCost=$newQty>0?(($oldQty*$oldCost)+($accepted*$unitCost))/$newQty:$unitCost;$pdo->prepare('UPDATE inventory_balances SET quantity_on_hand=?,average_unit_cost=?,last_receipt_date=?,updated_at=NOW() WHERE id=?')->execute([$newQty,$newCost,date('Y-m-d'),$existing['id']]);}else{$pdo->prepare('INSERT INTO inventory_balances (inventory_location_id,item_id,quantity_on_hand,quantity_allocated,average_unit_cost,last_receipt_date) VALUES (?,?,?,0,?,?)')->execute([$inventoryLocationId,$poLine['item_id'],$accepted,$unitCost,date('Y-m-d')]);}$pdo->prepare('INSERT INTO inventory_transactions (item_id,from_inventory_location_id,to_inventory_location_id,project_workorder_id,transaction_type,quantity,unit_cost,reason_code,reference_type,reference_id,notes,performed_by) VALUES (?,NULL,?,?,"receipt",?,? ,"accepted_receipt","receipt",?,?,?)')->execute([$poLine['item_id'],$inventoryLocationId,$po['project_workorder_id'],$accepted,$unitCost,$receipt['id'],'Accepted quantity only; rejected and held units were not posted.',current_user()['id']]);$pdo->prepare('UPDATE purchase_order_lines SET quantity_received=quantity_received+?,status=CASE WHEN quantity_received+?>=quantity_ordered THEN "received" ELSE "partially_received" END WHERE id=?')->execute([$accepted,$accepted,$poLine['id']]);if(function_exists('mysql_repo_clear_cache'))mysql_repo_clear_cache();
}

function fulfillment_record_quality_event(array $po,array $poLine,array $receiptLine): void
{
    $affected=max(0,(float)$receiptLine['quantity_rejected']);
    if($affected<=0&&$receiptLine['condition_status']==='accepted')return;
    $row=['id'=>null,'supplier_id'=>$po['supplier_id'],'item_id'=>$poLine['item_id'],'purchase_order_line_id'=>$poLine['id'],'company_id'=>$po['company_id'],'event_type'=>match((string)$receiptLine['condition_status']){'damaged'=>'shipping_damage','incorrect'=>'wrong_item','quality_hold'=>'defect','returned'=>'defect',default=>'other'},'event_date'=>date('Y-m-d'),'quantity_affected'=>$affected,'direct_cost'=>round($affected*(float)$poLine['unit_cost'],2),'rework_cost'=>0,'freight_cost'=>0,'customer_impact_cost'=>0,'supplier_recovery'=>0,'status'=>'open','description'=>mb_substr((string)$receiptLine['notes'],0,5000),'resolution'=>'','owner_user_id'=>(int)$po['owner_id'],'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')];
    if(data_is_demo()){$rows=$_SESSION['gruber_demo_state']['quality_events']??[];$row['id']=max([0,...array_map('intval',array_column($rows,'id'))])+1;$rows[]=$row;$_SESSION['gruber_demo_state']['quality_events']=$rows;return;}
    $pdo=production_database_connection();$pdo->prepare('INSERT INTO quality_events (supplier_id,item_id,purchase_order_line_id,company_id,event_type,event_date,quantity_affected,direct_cost,rework_cost,freight_cost,customer_impact_cost,supplier_recovery,status,description,resolution,owner_user_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$row['supplier_id'],$row['item_id'],$row['purchase_order_line_id'],$row['company_id'],$row['event_type'],$row['event_date'],$row['quantity_affected'],$row['direct_cost'],0,0,0,0,'open',$row['description'],null,$row['owner_user_id']]);
}

function fulfillment_refresh_po_status(int $poId): void
{
    $po=fulfillment_find_order($poId);if(!$po)return;$all=true;$any=false;foreach(fulfillment_po_lines($poId) as $line){$qty=(float)$line['quantity_ordered'];$received=(float)$line['quantity_received'];if($received>0)$any=true;if($received+0.0001<$qty)$all=false;}$status=$all?'received':($any?'partially_received':$po['status']);if(data_is_demo()){$po['status']=$status;data_upsert('purchase_orders',$po);}else production_database_connection()->prepare('UPDATE purchase_orders SET status=?,updated_at=NOW() WHERE id=?')->execute([$status,$poId]);
}
