<?php
declare(strict_types=1);

function inventory_ops_number(string $prefix,array $rows): string
{
    return $prefix.'-'.date('Y').'-'.str_pad((string)(count($rows)+1),4,'0',STR_PAD_LEFT);
}

function inventory_ops_default_company_id(): int
{
    if(current_company_id()!=='enterprise')return (int)current_company_id();$user=current_user();$allowed=permitted_company_ids($user);$primary=(int)($user['primary_company_id']??0);return in_array($primary,$allowed,true)?$primary:(int)($allowed[0]??0);
}

function inventory_ops_location_company(int $locationId): int
{
    $location=inventory_ops_find_location($locationId);return (int)($location['company_id']??0);
}

function inventory_ops_open_po_quantity(int $companyId,int $itemId): float
{
    $orders=[];foreach(data_collection('purchase_orders') as $po)$orders[(int)$po['id']]=$po;$qty=0.0;foreach(data_collection('purchase_order_lines') as $line){if((int)($line['item_id']??0)!==$itemId)continue;$po=$orders[(int)($line['purchase_order_id']??0)]??null;if(!$po||(int)($po['company_id']??0)!==$companyId||!in_array((string)($po['status']??''),['open','past_due','partially_received'],true))continue;$ordered=(float)($line['quantity_ordered']??$line['quantity']??0);$received=(float)($line['quantity_received']??0);$qty+=max(0,$ordered-$received);}return $qty;
}

function inventory_ops_forecast_quantity(int $companyId,int $itemId): float
{
    $item=data_find('items',$itemId);$categoryId=(int)($item['category_id']??0);$total=0.0;if(function_exists('demand_forecasts'))foreach(demand_forecasts() as $forecast){if((int)($forecast['company_id']??0)!==$companyId)continue;if((int)($forecast['category_id']??0)>0&&(int)$forecast['category_id']!==$categoryId)continue;if(!in_array((string)($forecast['status']??'active'),['active','approved'],true))continue;$total+=(float)($forecast['forecast_quantity']??0);}return $total;
}

function inventory_ops_transfer_source(int $destinationCompanyId,int $itemId,float $needed): ?array
{
    $best=null;foreach(inventory_ops_positions() as $position){if((int)$position['item_id']!==$itemId||(int)$position['company_id']===$destinationCompanyId)continue;$surplus=max(0,(float)$position['available']);if($surplus<=0)continue;$candidate=array_replace($position,['transfer_quantity'=>min($needed,$surplus)]);if(!$best||(float)$candidate['transfer_quantity']>(float)$best['transfer_quantity'])$best=$candidate;}return $best;
}

function inventory_ops_policy_blueprint(array $policy): array
{
    $position=inventory_ops_find_position((int)$policy['inventory_location_id'],(int)$policy['item_id'])??['quantity_on_hand'=>0,'quantity_allocated'=>0,'available'=>0,'unit_cost'=>(float)(data_find('items',(int)$policy['item_id'])['standard_cost']??0)];$companyId=(int)$policy['company_id'];$itemId=(int)$policy['item_id'];$available=(float)$position['available'];$allocated=(float)$position['quantity_allocated'];$openPo=inventory_ops_open_po_quantity($companyId,$itemId);$forecast=inventory_ops_forecast_quantity($companyId,$itemId);$target=max((float)$policy['reorder_point'],(float)$policy['minimum_quantity'])+(float)$policy['safety_stock']+$forecast;$needed=max(0,$target-$available-$openPo);$maximum=(float)$policy['maximum_quantity'];if($maximum>0)$needed=min($needed,max(0,$maximum-$available-$openPo));$source=$needed>0?inventory_ops_transfer_source($companyId,$itemId,$needed):null;$type=$needed<=0?'hold':($source&&$source['transfer_quantity']>0?'transfer':'purchase');$quantity=$type==='transfer'?(float)$source['transfer_quantity']:$needed;$unitCost=(float)($position['unit_cost']?:data_find('items',$itemId)['standard_cost']??0);$score=100;if($available<(float)$policy['safety_stock'])$score-=25;if($openPo<=0&&$needed>0)$score-=15;if($type==='purchase'&&empty($policy['preferred_supplier_id']))$score-=20;if($forecast<=0)$score-=10;return ['position'=>$position,'available_quantity'=>$available,'allocated_quantity'=>$allocated,'open_po_quantity'=>$openPo,'forecast_quantity'=>$forecast,'safety_stock_quantity'=>(float)$policy['safety_stock'],'recommended_quantity'=>round($quantity,4),'estimated_unit_cost'=>$unitCost,'estimated_value'=>round($quantity*$unitCost,2),'recommendation_type'=>$type,'source_inventory_location_id'=>$source['inventory_location_id']??null,'required_date'=>date('Y-m-d',strtotime('+'.max(1,(int)$policy['lead_time_days']).' days')),'readiness_score'=>max(0,$score),'evidence_note'=>match($type){'hold'=>'Available inventory and open purchase orders cover the policy target, forecast, and safety stock.','transfer'=>'A permitted internal location can cover all or part of the requirement before new purchasing.','purchase'=>'No supported internal surplus covers the policy requirement; a governed purchase request is recommended.',default=>'No action.'}];
}

function inventory_ops_generate_recommendation(array $policy): array
{
    $blueprint=inventory_ops_policy_blueprint($policy);$record=array_replace($blueprint,['id'=>null,'recommendation_number'=>inventory_ops_number('REC-INV',inventory_ops_recommendations()),'policy_id'=>(int)$policy['id'],'company_id'=>(int)$policy['company_id'],'inventory_location_id'=>(int)$policy['inventory_location_id'],'item_id'=>(int)$policy['item_id'],'preferred_supplier_id'=>$policy['preferred_supplier_id']??null,'status'=>'draft','approval_id'=>null,'converted_request_id'=>null,'converted_transfer_id'=>null,'created_by'=>(int)current_user()['id']]);unset($record['position'],$record['readiness_score']);$saved=inventory_ops_save_recommendation($record);inventory_ops_add_event((int)$saved['company_id'],(int)$saved['inventory_location_id'],(int)$saved['item_id'],'replenishment_recommendation',(int)$saved['id'],'recommendation_generated',null,'draft',$saved['estimated_value']>=25000?'high':'medium',(float)$saved['recommended_quantity'],(float)$saved['estimated_value'],$saved['evidence_note']);return $saved;
}

function inventory_ops_recommendation_effective_status(array $recommendation): string
{
    $stored=(string)($recommendation['status']??'draft');if(in_array($stored,['converted','dismissed'],true))return $stored;$approvalId=(int)($recommendation['approval_id']??0);if($approvalId>0){$approval=data_find('workflow_approvals',$approvalId);if($approval&&in_array((string)($approval['status']??''),['pending','in_review','approved','changes_requested','rejected'],true))return (string)$approval['status'];}return $stored;
}

function inventory_ops_submit_recommendation(array $recommendation): array
{
    if(!in_array(inventory_ops_recommendation_effective_status($recommendation),['draft','changes_requested'],true))throw new RuntimeException('This recommendation is already routed or closed.');$policy=inventory_ops_find_policy((int)$recommendation['policy_id']);$reviewerId=(int)($policy['reviewer_id']??6);$approval=data_upsert('workflow_approvals',['id'=>null,'company_id'=>$recommendation['company_id'],'module'=>'inventory','entity_type'=>'inventory_replenishment_recommendation','entity_id'=>$recommendation['id'],'title'=>$recommendation['recommendation_number'].' · '.money((float)$recommendation['estimated_value']),'submitted_by'=>(int)current_user()['id'],'assigned_to'=>$reviewerId,'status'=>'pending','submitted_at'=>date('Y-m-d H:i:s'),'due_date'=>date('Y-m-d',strtotime('+3 days')),'notes'=>'Review on-hand, allocations, reservations, open PO coverage, forecasts, transfer opportunity, supplier, lead time, safety stock, quantity, and value evidence.']);$before=$recommendation['status'];$recommendation['approval_id']=(int)$approval['id'];$recommendation['status']='submitted';$saved=inventory_ops_save_recommendation($recommendation);inventory_ops_add_event((int)$saved['company_id'],(int)$saved['inventory_location_id'],(int)$saved['item_id'],'replenishment_recommendation',(int)$saved['id'],'submitted',$before,'submitted','medium',(float)$saved['recommended_quantity'],(float)$saved['estimated_value'],'Recommendation routed for human approval.');inventory_ops_notify($reviewerId,(int)$saved['company_id'],'Inventory recommendation awaiting approval',$saved['recommendation_number'].' requests '.number_format((float)$saved['recommended_quantity'],2).' units.','warning');return $saved;
}

function inventory_ops_convert_recommendation(array $recommendation): array
{
    if(inventory_ops_recommendation_effective_status($recommendation)!=='approved')throw new RuntimeException('The replenishment recommendation must be approved before conversion.');if((float)$recommendation['recommended_quantity']<=0||in_array((string)$recommendation['recommendation_type'],['hold','none'],true))throw new RuntimeException('This recommendation does not support a replenishment transaction.');$item=data_find('items',(int)$recommendation['item_id']);if(!$item)throw new RuntimeException('The recommended item is unavailable.');
    if($recommendation['recommendation_type']==='transfer'){$sourceLocation=inventory_ops_find_location((int)$recommendation['source_inventory_location_id']);$destination=inventory_ops_find_location((int)$recommendation['inventory_location_id']);if(!$sourceLocation||!$destination)throw new RuntimeException('Transfer locations are unavailable.');$transfer=inventory_ops_save_transfer(['id'=>null,'transfer_number'=>inventory_ops_number('TRF-INV',inventory_ops_transfers()),'source_company_id'=>$sourceLocation['company_id'],'destination_company_id'=>$destination['company_id'],'source_inventory_location_id'=>$sourceLocation['id'],'destination_inventory_location_id'=>$destination['id'],'project_workorder_id'=>null,'status'=>'draft','required_date'=>$recommendation['required_date'],'shipped_at'=>null,'received_at'=>null,'carrier'=>'','tracking_number'=>'','freight_cost'=>0,'owner_id'=>(int)current_user()['id'],'reviewer_id'=>6,'approval_id'=>null,'evidence_note'=>'Created from approved '.$recommendation['recommendation_number'].'. '.$recommendation['evidence_note']]);inventory_ops_save_transfer_line(['id'=>null,'transfer_request_id'=>$transfer['id'],'item_id'=>$recommendation['item_id'],'quantity_requested'=>$recommendation['recommended_quantity'],'quantity_shipped'=>0,'quantity_received'=>0,'unit_cost'=>$recommendation['estimated_unit_cost'],'serial_or_lot_reference'=>'','condition_status'=>'pending','notes'=>'Approved replenishment recommendation transfer line.']);inventory_ops_add_transfer_event((int)$transfer['id'],'transfer_created',null,'draft','medium','Transfer created from approved replenishment recommendation.');$reference=(int)$transfer['id'];$kind='transfer';}
    else{$request=demand_save_request(['id'=>null,'request_number'=>'REQ-INV-'.date('Y').'-'.str_pad((string)(count(demand_requests())+1),4,'0',STR_PAD_LEFT),'company_id'=>$recommendation['company_id'],'location_id'=>null,'department_id'=>null,'requested_by'=>(int)current_user()['id'],'project_workorder_id'=>null,'business_purpose'=>'inventory_replenishment','required_date'=>$recommendation['required_date'],'urgency'=>'normal','status'=>'draft','justification'=>'Approved inventory replenishment recommendation '.$recommendation['recommendation_number'].'.','estimated_total'=>$recommendation['estimated_value'],'submitted_at'=>null,'approved_at'=>null,'owner_id'=>(int)current_user()['id'],'reviewer_id'=>6,'approval_id'=>null,'budget_envelope_id'=>null,'sourcing_assessment_id'=>null,'converted_po_id'=>null,'capex_opex'=>'operating_expense','unplanned_demand'=>false,'source_status'=>'not_assessed','evidence_note'=>$recommendation['evidence_note'],'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);demand_save_line(['id'=>null,'purchase_request_id'=>$request['id'],'item_id'=>$recommendation['item_id'],'requested_description'=>$item['description'],'quantity'=>$recommendation['recommended_quantity'],'unit_of_measure'=>$item['uom']??'EA','estimated_unit_cost'=>$recommendation['estimated_unit_cost'],'preferred_supplier_id'=>$recommendation['preferred_supplier_id'],'specification_notes'=>'Created from approved replenishment policy and recommendation.','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);demand_add_event((int)$request['id'],'inventory_replenishment_created',null,'draft','medium','Created from '.$recommendation['recommendation_number'].'.');$reference=(int)$request['id'];$kind='purchase_request';}
    $before=$recommendation['status'];$recommendation['status']='converted';if($kind==='transfer'){$recommendation['converted_transfer_id']=$reference;$recommendation['converted_request_id']=null;}else{$recommendation['converted_request_id']=$reference;$recommendation['converted_transfer_id']=null;}$saved=inventory_ops_save_recommendation($recommendation);inventory_ops_add_event((int)$saved['company_id'],(int)$saved['inventory_location_id'],(int)$saved['item_id'],'replenishment_recommendation',(int)$saved['id'],'converted',$before,'converted','medium',(float)$saved['recommended_quantity'],(float)$saved['estimated_value'],'Recommendation converted to '.$kind.' #'.$reference.'.');return ['kind'=>$kind,'id'=>$reference];
}
