<?php
declare(strict_types=1);

function inventory_ops_update_balance(int $locationId,int $itemId,float $onHandDelta,float $allocatedDelta,float $unitCost): void
{
    $location=inventory_ops_find_location($locationId);if(!$location)throw new RuntimeException('The inventory location is unavailable.');if(data_is_demo()){$rows=data_collection('inventory_snapshots');$found=false;foreach($rows as $i=>$row){$rowLocation=(int)($row['inventory_location_id']??$row['location_id']??0);if($rowLocation!==$locationId||(int)$row['item_id']!==$itemId)continue;$onHand=(float)($row['quantity_on_hand']??$row['quantity']??0)+$onHandDelta;$allocated=(float)($row['allocated']??$row['quantity_allocated']??0)+$allocatedDelta;if($onHand<-0.0001||$allocated<-0.0001||$allocated>$onHand+0.0001)throw new RuntimeException('The inventory transaction would create an invalid balance.');$rows[$i]['quantity_on_hand']=$onHand;$rows[$i]['allocated']=$allocated;$rows[$i]['available']=$onHand-$allocated;$rows[$i]['unit_cost']=$unitCost?:($row['unit_cost']??0);$rows[$i]['value']=round($onHand*(float)$rows[$i]['unit_cost'],2);$rows[$i]['snapshot_date']=date('Y-m-d');$found=true;break;}if(!$found){if($onHandDelta<0||$allocatedDelta<0)throw new RuntimeException('The inventory position does not exist.');$rows[]=['id'=>data_next_id('inventory_snapshots'),'company_id'=>$location['company_id'],'location_id'=>$locationId,'item_id'=>$itemId,'snapshot_date'=>date('Y-m-d'),'quantity_on_hand'=>$onHandDelta,'allocated'=>$allocatedDelta,'available'=>$onHandDelta-$allocatedDelta,'unit_cost'=>$unitCost,'value'=>round($onHandDelta*$unitCost,2)];}data_replace_collection('inventory_snapshots',$rows);return;}
    $pdo=production_database_connection();$stmt=$pdo->prepare('SELECT * FROM inventory_balances WHERE inventory_location_id=? AND item_id=? FOR UPDATE');$stmt->execute([$locationId,$itemId]);$row=$stmt->fetch();if($row){$onHand=(float)$row['quantity_on_hand']+$onHandDelta;$allocated=(float)$row['quantity_allocated']+$allocatedDelta;if($onHand<-0.0001||$allocated<-0.0001||$allocated>$onHand+0.0001)throw new RuntimeException('The inventory transaction would create an invalid balance.');$pdo->prepare('UPDATE inventory_balances SET quantity_on_hand=?,quantity_allocated=?,average_unit_cost=CASE WHEN ?>0 THEN ? ELSE average_unit_cost END,updated_at=NOW() WHERE id=?')->execute([$onHand,$allocated,$unitCost,$unitCost,$row['id']]);}else{if($onHandDelta<0||$allocatedDelta<0)throw new RuntimeException('The inventory position does not exist.');$pdo->prepare('INSERT INTO inventory_balances (inventory_location_id,item_id,quantity_on_hand,quantity_allocated,average_unit_cost) VALUES (?,?,?,?,?)')->execute([$locationId,$itemId,$onHandDelta,$allocatedDelta,$unitCost]);}if(function_exists('mysql_repo_clear_cache'))mysql_repo_clear_cache();
}

function inventory_ops_create_reservation(array $record): array
{
    $position=inventory_ops_find_position((int)$record['inventory_location_id'],(int)$record['item_id']);if(!$position||(float)$position['available']+0.0001<(float)$record['quantity'])throw new RuntimeException('Available inventory is insufficient for this reservation.');$record['reservation_number']=$record['reservation_number']??inventory_ops_number('RSV-INV',inventory_ops_reservations());$record['status']='active';$saved=inventory_ops_save_reservation($record);inventory_ops_update_balance((int)$saved['inventory_location_id'],(int)$saved['item_id'],0,(float)$saved['quantity'],(float)$position['unit_cost']);inventory_ops_add_transaction(['id'=>null,'item_id'=>$saved['item_id'],'from_inventory_location_id'=>null,'to_inventory_location_id'=>$saved['inventory_location_id'],'project_workorder_id'=>$saved['project_workorder_id'],'transaction_type'=>'reservation','quantity'=>$saved['quantity'],'unit_cost'=>$position['unit_cost'],'reason_code'=>$saved['reference_type'],'reference_type'=>'inventory_reservation','reference_id'=>$saved['id'],'notes'=>$saved['evidence_note']]);inventory_ops_add_event((int)$saved['company_id'],(int)$saved['inventory_location_id'],(int)$saved['item_id'],'inventory_reservation',(int)$saved['id'],'reserved',null,'active','medium',(float)$saved['quantity'],(float)$saved['quantity']*(float)$position['unit_cost'],$saved['evidence_note']);return $saved;
}

function inventory_ops_release_reservation(array $reservation,string $evidence): array
{
    if((string)$reservation['status']!=='active')throw new RuntimeException('Only active reservations can be released.');$position=inventory_ops_find_position((int)$reservation['inventory_location_id'],(int)$reservation['item_id']);$before=$reservation['status'];inventory_ops_update_balance((int)$reservation['inventory_location_id'],(int)$reservation['item_id'],0,-(float)$reservation['quantity'],(float)($position['unit_cost']??0));$reservation['status']='released';$reservation['evidence_note']=mb_substr($evidence,0,5000);$saved=inventory_ops_save_reservation($reservation);inventory_ops_add_transaction(['id'=>null,'item_id'=>$saved['item_id'],'from_inventory_location_id'=>$saved['inventory_location_id'],'to_inventory_location_id'=>null,'project_workorder_id'=>$saved['project_workorder_id'],'transaction_type'=>'release','quantity'=>$saved['quantity'],'unit_cost'=>$position['unit_cost']??0,'reason_code'=>'reservation_release','reference_type'=>'inventory_reservation','reference_id'=>$saved['id'],'notes'=>$evidence]);inventory_ops_add_event((int)$saved['company_id'],(int)$saved['inventory_location_id'],(int)$saved['item_id'],'inventory_reservation',(int)$saved['id'],'released',$before,'released','medium',(float)$saved['quantity'],(float)$saved['quantity']*(float)($position['unit_cost']??0),$evidence);return $saved;
}

function inventory_ops_transfer_effective_status(array $transfer): string
{
    $stored=(string)($transfer['status']??'draft');if(in_array($stored,['in_transit','partially_received','received','canceled'],true))return $stored;$approvalId=(int)($transfer['approval_id']??0);if($approvalId>0){$approval=data_find('workflow_approvals',$approvalId);if($approval&&in_array((string)($approval['status']??''),['pending','in_review','approved','changes_requested','rejected'],true))return (string)$approval['status'];}return $stored;
}

function inventory_ops_submit_transfer(array $transfer): array
{
    if(!in_array(inventory_ops_transfer_effective_status($transfer),['draft','changes_requested'],true))throw new RuntimeException('This transfer is already routed or closed.');if(!inventory_ops_transfer_lines((int)$transfer['id']))throw new RuntimeException('Add at least one transfer line before submission.');$approval=data_upsert('workflow_approvals',['id'=>null,'company_id'=>$transfer['source_company_id'],'module'=>'inventory','entity_type'=>'inventory_transfer_request','entity_id'=>$transfer['id'],'title'=>$transfer['transfer_number'].' · '.data_company_name($transfer['source_company_id']).' to '.data_company_name($transfer['destination_company_id']),'submitted_by'=>(int)current_user()['id'],'assigned_to'=>$transfer['reviewer_id'],'status'=>'pending','submitted_at'=>date('Y-m-d H:i:s'),'due_date'=>date('Y-m-d',strtotime('+2 days')),'notes'=>'Validate source availability, destination need, custody, freight, condition, schedule, reservations, and internal-transfer economics.']);$before=$transfer['status'];$transfer['approval_id']=(int)$approval['id'];$transfer['status']='submitted';$saved=inventory_ops_save_transfer($transfer);inventory_ops_add_transfer_event((int)$saved['id'],'submitted',$before,'submitted','medium','Transfer routed for source and destination approval.');inventory_ops_notify((int)$saved['reviewer_id'],(int)$saved['source_company_id'],'Inventory transfer awaiting approval',$saved['transfer_number'].' requires review.','warning');return $saved;
}

function inventory_ops_dispatch_transfer(array $transfer,string $carrier,string $tracking,string $evidence): array
{
    if(inventory_ops_transfer_effective_status($transfer)!=='approved')throw new RuntimeException('The transfer must be approved before dispatch.');$lines=inventory_ops_transfer_lines((int)$transfer['id']);foreach($lines as $line){$position=inventory_ops_find_position((int)$transfer['source_inventory_location_id'],(int)$line['item_id']);$qty=(float)$line['quantity_requested'];if(!$position||(float)$position['available']+0.0001<$qty)throw new RuntimeException('Source inventory is insufficient for '.data_item_name((int)$line['item_id']).'.');}
    foreach($lines as $line){$qty=(float)$line['quantity_requested'];$position=inventory_ops_find_position((int)$transfer['source_inventory_location_id'],(int)$line['item_id']);inventory_ops_update_balance((int)$transfer['source_inventory_location_id'],(int)$line['item_id'],-$qty,0,(float)$line['unit_cost']);$line['quantity_shipped']=$qty;$line['condition_status']='in_transit';inventory_ops_save_transfer_line($line);inventory_ops_add_transaction(['id'=>null,'item_id'=>$line['item_id'],'from_inventory_location_id'=>$transfer['source_inventory_location_id'],'to_inventory_location_id'=>$transfer['destination_inventory_location_id'],'project_workorder_id'=>$transfer['project_workorder_id'],'transaction_type'=>'transfer','quantity'=>$qty,'unit_cost'=>$line['unit_cost'],'reason_code'=>'internal_transfer','reference_type'=>'inventory_transfer_request','reference_id'=>$transfer['id'],'notes'=>$evidence]);inventory_ops_add_event((int)$transfer['source_company_id'],(int)$transfer['source_inventory_location_id'],(int)$line['item_id'],'inventory_transfer_request',(int)$transfer['id'],'dispatched','approved','in_transit','medium',$qty,$qty*(float)$line['unit_cost'],$evidence);}
    $before=$transfer['status'];$transfer['status']='in_transit';$transfer['shipped_at']=date('Y-m-d H:i:s');$transfer['carrier']=mb_substr($carrier,0,160);$transfer['tracking_number']=mb_substr($tracking,0,160);$transfer['evidence_note']=mb_substr($evidence,0,5000);$saved=inventory_ops_save_transfer($transfer);inventory_ops_add_transfer_event((int)$saved['id'],'dispatched',$before,'in_transit','medium',$evidence);return $saved;
}

function inventory_ops_receive_transfer(array $transfer,string $evidence): array
{
    if(!in_array((string)$transfer['status'],['in_transit','partially_received'],true))throw new RuntimeException('Only an in-transit transfer can be received.');$all=true;foreach(inventory_ops_transfer_lines((int)$transfer['id']) as $line){$remaining=max(0,(float)$line['quantity_shipped']-(float)$line['quantity_received']);if($remaining<=0)continue;inventory_ops_update_balance((int)$transfer['destination_inventory_location_id'],(int)$line['item_id'],$remaining,0,(float)$line['unit_cost']);$line['quantity_received']=(float)$line['quantity_received']+$remaining;$line['condition_status']='accepted';$line['notes']=mb_substr($evidence,0,5000);inventory_ops_save_transfer_line($line);inventory_ops_add_event((int)$transfer['destination_company_id'],(int)$transfer['destination_inventory_location_id'],(int)$line['item_id'],'inventory_transfer_request',(int)$transfer['id'],'received','in_transit','received','medium',$remaining,$remaining*(float)$line['unit_cost'],$evidence);if((float)$line['quantity_received']+0.0001<(float)$line['quantity_shipped'])$all=false;}$before=$transfer['status'];$transfer['status']=$all?'received':'partially_received';$transfer['received_at']=$all?date('Y-m-d H:i:s'):null;$transfer['evidence_note']=mb_substr($evidence,0,5000);$saved=inventory_ops_save_transfer($transfer);inventory_ops_add_transfer_event((int)$saved['id'],'received',$before,$saved['status'],'medium',$evidence);return $saved;
}
