<?php
declare(strict_types=1);

function inventory_ops_export_csv(array $metrics,array $policies,array $recommendations,array $reservations,array $transfers,array $counts,array $events): never
{
    require_permission('reports.export');$filename='inventory-operations-'.date('Ymd-His').'.csv';header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="'.$filename.'"');$out=fopen('php://output','wb');fputcsv($out,['Section 19 Inventory Operations, Replenishment & Internal Transfer Governance']);fputcsv($out,['Scope',current_scope_label()]);foreach($metrics as $key=>$value)fputcsv($out,['Metric',inventory_ops_csv_cell(status_label((string)$key)),inventory_ops_csv_cell($value)]);
    fputcsv($out,[]);fputcsv($out,['Policies']);fputcsv($out,['Policy','Company','Location','Item','Minimum','Maximum','Reorder point','Safety stock','Lead time','Status','Evidence']);foreach($policies as $r)fputcsv($out,array_map('inventory_ops_csv_cell',[$r['policy_number'],data_company_name($r['company_id']),inventory_ops_find_location((int)$r['inventory_location_id'])['name']??'',data_item_name((int)$r['item_id']),$r['minimum_quantity'],$r['maximum_quantity'],$r['reorder_point'],$r['safety_stock'],$r['lead_time_days'],$r['status'],$r['evidence_note']]));
    fputcsv($out,[]);fputcsv($out,['Recommendations']);fputcsv($out,['Recommendation','Type','Item','Quantity','Value','Status','Required date','Evidence']);foreach($recommendations as $r)fputcsv($out,array_map('inventory_ops_csv_cell',[$r['recommendation_number'],$r['recommendation_type'],data_item_name((int)$r['item_id']),$r['recommended_quantity'],$r['estimated_value'],inventory_ops_recommendation_effective_status($r),$r['required_date'],$r['evidence_note']]));
    fputcsv($out,[]);fputcsv($out,['Reservations']);fputcsv($out,['Reservation','Item','Quantity','Status','Needed date','Reference','Evidence']);foreach($reservations as $r)fputcsv($out,array_map('inventory_ops_csv_cell',[$r['reservation_number'],data_item_name((int)$r['item_id']),$r['quantity'],$r['status'],$r['needed_date'],$r['reference_type'].' #'.($r['reference_id']??''),$r['evidence_note']]));
    fputcsv($out,[]);fputcsv($out,['Transfers']);fputcsv($out,['Transfer','Source company','Destination company','Status','Required date','Freight','Evidence']);foreach($transfers as $r)fputcsv($out,array_map('inventory_ops_csv_cell',[$r['transfer_number'],data_company_name($r['source_company_id']),data_company_name($r['destination_company_id']),inventory_ops_transfer_effective_status($r),$r['required_date'],$r['freight_cost'],$r['evidence_note']]));
    fputcsv($out,[]);fputcsv($out,['Cycle Counts']);fputcsv($out,['Count','Location','Status','Scheduled','Completed','Assigned','Approved']);foreach($counts as $r)fputcsv($out,array_map('inventory_ops_csv_cell',[$r['count_reference'],inventory_ops_find_location((int)$r['inventory_location_id'])['name']??'',$r['status'],$r['scheduled_date'],$r['completed_date']??'',data_user_name($r['assigned_to']??null),data_user_name($r['approved_by']??null)]));
    fputcsv($out,[]);fputcsv($out,['Immutable Events']);fputcsv($out,['Date','Entity','Event','Status','Quantity','Value','Evidence']);foreach($events as $r)fputcsv($out,array_map('inventory_ops_csv_cell',[$r['created_at'],$r['entity_type'].' #'.$r['entity_id'],$r['event_type'],($r['from_status']??'').' → '.($r['to_status']??''),$r['quantity'],$r['value_amount'],$r['evidence_note']]));fclose($out);exit;
}
