<?php
declare(strict_types=1);

function inventory_ops_save_policy(array $record): array
{
    inventory_ops_require_tables();$record['updated_at']=date('Y-m-d H:i:s');$record['created_at']=$record['created_at']??$record['updated_at'];
    if(data_is_demo())return inventory_ops_demo_save('inventory_replenishment_policies',$record,'inventory_ops_demo_policies');
    $pdo=production_database_connection();$id=(int)($record['id']??0);$params=[$record['policy_number'],$record['company_id'],$record['inventory_location_id'],$record['item_id'],$record['minimum_quantity'],$record['maximum_quantity'],$record['reorder_point'],$record['safety_stock'],$record['lead_time_days'],$record['review_frequency_days'],$record['preferred_supplier_id'],$record['owner_id'],$record['reviewer_id'],$record['status'],$record['evidence_note']];if($id){$params[]=$id;$pdo->prepare('UPDATE inventory_replenishment_policies SET policy_number=?,company_id=?,inventory_location_id=?,item_id=?,minimum_quantity=?,maximum_quantity=?,reorder_point=?,safety_stock=?,lead_time_days=?,review_frequency_days=?,preferred_supplier_id=?,owner_id=?,reviewer_id=?,status=?,evidence_note=?,updated_at=NOW() WHERE id=?')->execute($params);}else{$pdo->prepare('INSERT INTO inventory_replenishment_policies (policy_number,company_id,inventory_location_id,item_id,minimum_quantity,maximum_quantity,reorder_point,safety_stock,lead_time_days,review_frequency_days,preferred_supplier_id,owner_id,reviewer_id,status,evidence_note) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute($params);$id=(int)$pdo->lastInsertId();}$record['id']=$id;return $record;
}

function inventory_ops_save_recommendation(array $record): array
{
    inventory_ops_require_tables();$record['updated_at']=date('Y-m-d H:i:s');$record['created_at']=$record['created_at']??$record['updated_at'];
    if(data_is_demo())return inventory_ops_demo_save('inventory_replenishment_recommendations',$record,'inventory_ops_demo_recommendations');
    $pdo=production_database_connection();$id=(int)($record['id']??0);$fields=['recommendation_number','policy_id','company_id','inventory_location_id','item_id','available_quantity','allocated_quantity','open_po_quantity','forecast_quantity','safety_stock_quantity','recommended_quantity','estimated_unit_cost','estimated_value','recommendation_type','source_inventory_location_id','preferred_supplier_id','required_date','status','approval_id','converted_request_id','converted_transfer_id','evidence_note','created_by'];$values=[];foreach($fields as $f)$values[]=$record[$f]??null;if($id){$set=implode(',',array_map(static fn(string $f):string=>$f.'=?',$fields));$values[]=$id;$pdo->prepare('UPDATE inventory_replenishment_recommendations SET '.$set.',updated_at=NOW() WHERE id=?')->execute($values);}else{$pdo->prepare('INSERT INTO inventory_replenishment_recommendations ('.implode(',',$fields).') VALUES ('.implode(',',array_fill(0,count($fields),'?')).')')->execute($values);$id=(int)$pdo->lastInsertId();}$record['id']=$id;return $record;
}

function inventory_ops_save_reservation(array $record): array
{
    inventory_ops_require_tables();$record['updated_at']=date('Y-m-d H:i:s');$record['created_at']=$record['created_at']??$record['updated_at'];if(data_is_demo())return inventory_ops_demo_save('inventory_reservations',$record,'inventory_ops_demo_reservations');$pdo=production_database_connection();$id=(int)($record['id']??0);$fields=['reservation_number','company_id','inventory_location_id','item_id','project_workorder_id','reference_type','reference_id','quantity','status','needed_date','owner_id','evidence_note'];$values=[];foreach($fields as $f)$values[]=$record[$f]??null;if($id){$values[]=$id;$pdo->prepare('UPDATE inventory_reservations SET '.implode(',',array_map(static fn(string $f):string=>$f.'=?',$fields)).',updated_at=NOW() WHERE id=?')->execute($values);}else{$pdo->prepare('INSERT INTO inventory_reservations ('.implode(',',$fields).') VALUES ('.implode(',',array_fill(0,count($fields),'?')).')')->execute($values);$id=(int)$pdo->lastInsertId();}$record['id']=$id;return $record;
}

function inventory_ops_save_transfer(array $record): array
{
    inventory_ops_require_tables();$record['updated_at']=date('Y-m-d H:i:s');$record['created_at']=$record['created_at']??$record['updated_at'];if(data_is_demo())return inventory_ops_demo_save('inventory_transfer_requests',$record,'inventory_ops_demo_transfers');$pdo=production_database_connection();$id=(int)($record['id']??0);$fields=['transfer_number','source_company_id','destination_company_id','source_inventory_location_id','destination_inventory_location_id','project_workorder_id','status','required_date','shipped_at','received_at','carrier','tracking_number','freight_cost','owner_id','reviewer_id','approval_id','evidence_note'];$values=[];foreach($fields as $f)$values[]=$record[$f]??null;if($id){$values[]=$id;$pdo->prepare('UPDATE inventory_transfer_requests SET '.implode(',',array_map(static fn(string $f):string=>$f.'=?',$fields)).',updated_at=NOW() WHERE id=?')->execute($values);}else{$pdo->prepare('INSERT INTO inventory_transfer_requests ('.implode(',',$fields).') VALUES ('.implode(',',array_fill(0,count($fields),'?')).')')->execute($values);$id=(int)$pdo->lastInsertId();}$record['id']=$id;return $record;
}

function inventory_ops_save_transfer_line(array $record): array
{
    inventory_ops_require_tables();$record['updated_at']=date('Y-m-d H:i:s');$record['created_at']=$record['created_at']??$record['updated_at'];if(data_is_demo())return inventory_ops_demo_save('inventory_transfer_lines',$record,'inventory_ops_demo_transfer_lines');$pdo=production_database_connection();$id=(int)($record['id']??0);$fields=['transfer_request_id','item_id','quantity_requested','quantity_shipped','quantity_received','unit_cost','serial_or_lot_reference','condition_status','notes'];$values=[];foreach($fields as $f)$values[]=$record[$f]??null;if($id){$values[]=$id;$pdo->prepare('UPDATE inventory_transfer_lines SET '.implode(',',array_map(static fn(string $f):string=>$f.'=?',$fields)).',updated_at=NOW() WHERE id=?')->execute($values);}else{$pdo->prepare('INSERT INTO inventory_transfer_lines ('.implode(',',$fields).') VALUES ('.implode(',',array_fill(0,count($fields),'?')).')')->execute($values);$id=(int)$pdo->lastInsertId();}$record['id']=$id;return $record;
}

function inventory_ops_add_transfer_event(int $transferId,string $type,?string $from,?string $to,string $severity,string $evidence): array
{
    inventory_ops_require_tables();$record=['id'=>null,'transfer_request_id'=>$transferId,'event_type'=>$type,'from_status'=>$from,'to_status'=>$to,'severity'=>$severity,'evidence_note'=>mb_substr($evidence,0,5000),'created_by'=>(int)current_user()['id'],'created_at'=>date('Y-m-d H:i:s')];if(data_is_demo())return inventory_ops_demo_save('inventory_transfer_events',$record,'inventory_ops_demo_transfer_events');$pdo=production_database_connection();$pdo->prepare('INSERT INTO inventory_transfer_events (transfer_request_id,event_type,from_status,to_status,severity,evidence_note,created_by) VALUES (?,?,?,?,?,?,?)')->execute([$transferId,$type,$from,$to,$severity,$record['evidence_note'],$record['created_by']]);$record['id']=(int)$pdo->lastInsertId();return $record;
}

function inventory_ops_add_event(int $companyId,int $locationId,?int $itemId,string $entityType,int $entityId,string $type,?string $from,?string $to,string $severity,float $quantity,float $value,string $evidence): array
{
    inventory_ops_require_tables();$record=['id'=>null,'company_id'=>$companyId,'inventory_location_id'=>$locationId,'item_id'=>$itemId&&$itemId>0?$itemId:null,'entity_type'=>$entityType,'entity_id'=>$entityId,'event_type'=>$type,'from_status'=>$from,'to_status'=>$to,'severity'=>$severity,'quantity'=>$quantity,'value_amount'=>$value,'evidence_note'=>mb_substr($evidence,0,5000),'created_by'=>(int)current_user()['id'],'created_at'=>date('Y-m-d H:i:s')];if(data_is_demo())return inventory_ops_demo_save('inventory_governance_events',$record,'inventory_ops_demo_events');$pdo=production_database_connection();$pdo->prepare('INSERT INTO inventory_governance_events (company_id,inventory_location_id,item_id,entity_type,entity_id,event_type,from_status,to_status,severity,quantity,value_amount,evidence_note,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$companyId,$locationId,$record['item_id'],$entityType,$entityId,$type,$from,$to,$severity,$quantity,$value,$record['evidence_note'],$record['created_by']]);$record['id']=(int)$pdo->lastInsertId();return $record;
}

function inventory_ops_save_cycle_count(array $record): array
{
    inventory_ops_require_tables();if(data_is_demo())return inventory_ops_demo_save('cycle_counts',$record,'inventory_ops_demo_cycle_counts');$pdo=production_database_connection();$id=(int)($record['id']??0);if($id){$pdo->prepare('UPDATE cycle_counts SET inventory_location_id=?,count_reference=?,status=?,scheduled_date=?,completed_date=?,assigned_to=?,approved_by=?,updated_at=NOW() WHERE id=?')->execute([$record['inventory_location_id'],$record['count_reference'],$record['status'],$record['scheduled_date'],$record['completed_date'],$record['assigned_to'],$record['approved_by'],$id]);}else{$pdo->prepare('INSERT INTO cycle_counts (inventory_location_id,count_reference,status,scheduled_date,completed_date,assigned_to,approved_by) VALUES (?,?,?,?,?,?,?)')->execute([$record['inventory_location_id'],$record['count_reference'],$record['status'],$record['scheduled_date'],$record['completed_date'],$record['assigned_to'],$record['approved_by']]);$id=(int)$pdo->lastInsertId();}$record['id']=$id;return $record;
}

function inventory_ops_save_cycle_line(array $record): array
{
    inventory_ops_require_tables();if(data_is_demo())return inventory_ops_demo_save('cycle_count_lines',$record,'inventory_ops_demo_cycle_count_lines');$pdo=production_database_connection();$id=(int)($record['id']??0);if($id){$pdo->prepare('UPDATE cycle_count_lines SET item_id=?,system_quantity=?,counted_quantity=?,variance_reason=?,updated_at=NOW() WHERE id=?')->execute([$record['item_id'],$record['system_quantity'],$record['counted_quantity'],$record['variance_reason'],$id]);}else{$pdo->prepare('INSERT INTO cycle_count_lines (cycle_count_id,item_id,system_quantity,counted_quantity,variance_reason) VALUES (?,?,?,?,?)')->execute([$record['cycle_count_id'],$record['item_id'],$record['system_quantity'],$record['counted_quantity'],$record['variance_reason']]);$id=(int)$pdo->lastInsertId();}$record['id']=$id;return $record;
}

function inventory_ops_add_transaction(array $record): array
{
    inventory_ops_require_tables();$record['performed_by']=$record['performed_by']??(int)current_user()['id'];$record['performed_at']=$record['performed_at']??date('Y-m-d H:i:s');if(data_is_demo())return inventory_ops_demo_save('inventory_transactions',$record,'inventory_ops_demo_transactions');$pdo=production_database_connection();$pdo->prepare('INSERT INTO inventory_transactions (item_id,from_inventory_location_id,to_inventory_location_id,project_workorder_id,transaction_type,quantity,unit_cost,reason_code,reference_type,reference_id,notes,performed_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$record['item_id'],$record['from_inventory_location_id'],$record['to_inventory_location_id'],$record['project_workorder_id'],$record['transaction_type'],$record['quantity'],$record['unit_cost'],$record['reason_code'],$record['reference_type'],$record['reference_id'],$record['notes'],$record['performed_by']]);$record['id']=(int)$pdo->lastInsertId();return $record;
}
