<style>
.mitigation-hero{display:grid;grid-template-columns:1.25fr .75fr;gap:20px;padding:24px;border:1px solid #dfe4ea;border-radius:20px;background:linear-gradient(135deg,#fff,#f6f8fb)}
.mitigation-hero h2{font-size:clamp(1.7rem,3vw,2.45rem);margin:.35rem 0 .65rem}.mitigation-risk{display:grid;place-items:center;min-height:205px;border-radius:18px;background:#111827;color:#fff;text-align:center;padding:20px}.mitigation-risk strong{font-size:3.1rem}.mitigation-risk small{opacity:.74}.mitigation-risk.status-critical{background:#7f1d1d}.mitigation-risk.status-high{background:#9a3412}.mitigation-risk.status-medium{background:#854d0e}.mitigation-risk.status-low{background:#166534}
.mitigation-metrics{display:grid;grid-template-columns:repeat(6,minmax(130px,1fr));gap:12px}.mitigation-metric{padding:16px;border:1px solid #dfe4ea;border-radius:16px;background:#fff}.mitigation-metric span,.mitigation-metric small{display:block}.mitigation-metric strong{display:block;margin:.25rem 0;font-size:1.55rem}.mitigation-metric small{color:#64748b}
.trigger-grid{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:12px}.trigger-card{padding:16px;border:1px solid #dfe4ea;border-radius:16px;background:#fff}.trigger-card strong,.trigger-card small{display:block}.trigger-card small{margin-top:5px;color:#64748b}
.mitigation-layout{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(310px,.75fr);gap:18px}.mitigation-action-card{padding:18px;border:1px solid #dfe4ea;border-radius:18px;background:#fff;margin-bottom:14px}.mitigation-action-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.mitigation-action-head h3{margin:.25rem 0}.action-meta{display:flex;flex-wrap:wrap;gap:7px}.action-meta span{padding:5px 8px;border-radius:999px;background:#f1f5f9;font-size:.78rem;font-weight:700}.action-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:14px 0}.action-kpis div{padding:10px;border-radius:12px;background:#f8fafc}.action-kpis span,.action-kpis strong{display:block}.action-kpis span{font-size:.75rem;color:#64748b}.action-update-grid{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:10px}.action-update-grid label:last-of-type{grid-column:span 4}.action-update-grid input,.action-update-grid select,.action-update-grid textarea{width:100%}
.plan-form-actions{display:grid;gap:14px}.plan-form-action{padding:16px;border:1px solid #dfe4ea;border-radius:16px;background:#fff}.plan-form-action-grid{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:10px}.plan-form-action-grid .span-2{grid-column:span 2}.plan-form-action-grid .span-4{grid-column:span 4}.plan-form-action-grid input,.plan-form-action-grid select,.plan-form-action-grid textarea{width:100%}
.plan-side-card{padding:18px;border:1px solid #dfe4ea;border-radius:18px;background:#fff;margin-bottom:16px}.plan-side-card h2{margin:.35rem 0}.plan-history-row{padding:14px 0;border-bottom:1px solid #eef2f7}.plan-history-row:last-child{border-bottom:0}.plan-history-row strong,.plan-history-row small{display:block}.plan-history-row small{color:#64748b;margin:4px 0 8px}.plan-history-actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center}
.progress-track{height:9px;border-radius:999px;background:#e2e8f0;overflow:hidden}.progress-track span{display:block;height:100%;background:#111827}.residual-callout{padding:14px;border-radius:14px;background:#f8fafc;border:1px solid #e2e8f0}.residual-callout strong{display:block;font-size:1.3rem;margin-top:4px}
@media(max-width:1180px){.mitigation-metrics{grid-template-columns:repeat(3,1fr)}.mitigation-layout{grid-template-columns:1fr}.trigger-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:760px){.mitigation-hero{grid-template-columns:1fr}.mitigation-metrics{grid-template-columns:repeat(2,1fr)}.trigger-grid,.action-update-grid,.plan-form-action-grid{grid-template-columns:1fr}.action-update-grid label:last-of-type,.plan-form-action-grid .span-2,.plan-form-action-grid .span-4{grid-column:auto}.action-kpis{grid-template-columns:repeat(2,1fr)}}
</style>
