<?php
declare(strict_types=1);

function process_mapping_metrics(): array
{
    $processes=process_mapping_processes();$instances=process_mapping_instances();$stepInstances=process_mapping_step_instances();$exceptions=process_mapping_exceptions();
    $active=array_values(array_filter($instances,fn($r)=>in_array($r['status'],['in_progress','blocked','overdue'],true)));
    $completed=array_values(array_filter($instances,fn($r)=>$r['status']==='completed'));
    $elapsed=array_filter(array_map('intval',array_column($completed,'cycle_seconds')));$avg=$elapsed?(int)round(array_sum($elapsed)/count($elapsed)):0;
    $overdue=count(array_filter($stepInstances,fn($r)=>in_array($r['status'],['active','pending'],true)&&!empty($r['due_at'])&&strtotime((string)$r['due_at'])<time()));
    return ['processes'=>count($processes),'published'=>count(array_filter($processes,fn($r)=>$r['status']==='published')),'active_instances'=>count($active),'completed_instances'=>count($completed),'open_exceptions'=>count(array_filter($exceptions,fn($r)=>$r['status']!=='resolved')),'overdue_steps'=>$overdue,'average_cycle_seconds'=>$avg,'touchless_percent'=>process_mapping_touchless_percent()];
}
function process_mapping_touchless_percent():float{$steps=process_mapping_steps();if(!$steps)return 0.0;$automated=count(array_filter($steps,fn($s)=>in_array($s['automation_mode'],['adapter_gated','automatic'],true)));return round(($automated/count($steps))*100,1);}
function process_mapping_process_version(array$process):?array{$id=(int)($process['active_version_id']??0);if($id>0)return process_mapping_find_version($id);$versions=process_mapping_versions((int)$process['id']);return$versions[0]??null;}
function process_mapping_map_model(int$processId,?int$instanceId=null):array
{
    $process=process_mapping_find_process($processId)??process_mapping_processes()[0]??null;if(!$process)return[];$version=process_mapping_process_version($process);if(!$version)return[];
    $lanes=process_mapping_lanes((int)$version['id']);$steps=process_mapping_steps((int)$version['id']);$transitions=process_mapping_transitions((int)$version['id']);$controls=process_mapping_controls();$integrations=process_mapping_integrations();
    $instance=$instanceId?process_mapping_find_instance($instanceId):null;if(!$instance){$matching=process_mapping_instances((int)$process['id']);$instance=$matching[0]??null;}
    $statuses=[];$stepInstances=[];$exceptions=[];if($instance){$stepInstances=process_mapping_step_instances((int)$instance['id']);foreach($stepInstances as$si)$statuses[(int)$si['step_id']]=$si['status'];$exceptions=process_mapping_exceptions((int)$instance['id']);}
    foreach($steps as&$step){$step['runtime_status']=$statuses[(int)$step['id']]??'not_started';$step['controls']=array_values(array_filter($controls,fn($c)=>(int)$c['step_id']===(int)$step['id']));$step['integrations']=array_values(array_filter($integrations,fn($c)=>(int)$c['step_id']===(int)$step['id']));}unset($step);
    return compact('process','version','lanes','steps','transitions','instance','stepInstances','exceptions');
}
function process_mapping_active_user(int$id):bool{foreach(data_collection('users')as$u)if((int)$u['id']===$id)return($u['status']??'inactive')==='active';return false;}
function process_mapping_entity_company_id(int$entityId):?int{$e=entity_system_find_entity($entityId);$cid=(int)($e['company_id']??0);return$cid>0?$cid:null;}
function process_mapping_record_company_id(string$type,int$id):?int
{
    $type=strtolower(trim($type));$collection=match($type){'purchase_requisition','purchase_request'=>'purchase_requests','purchase_order'=>'purchase_orders','supplier_invoice'=>'supplier_invoices',default=>null};
    if($collection!==null)foreach(data_collection($collection)as$r)if((int)($r['id']??0)===$id){$cid=(int)($r['company_id']??0);return$cid>0?$cid:null;}
    if($type==='purchase_order_receipt'||$type==='receipt'){foreach(data_collection('receipts')as$r)if((int)($r['id']??0)===$id){$poId=(int)($r['purchase_order_id']??0);foreach(data_collection('purchase_orders')as$po)if((int)$po['id']===$poId)return(int)$po['company_id'];}}
    return null;
}
function process_mapping_process_assigned_to_entity(int$processId,int$entityId):bool{foreach(process_mapping_assignments()as$a)if((int)$a['process_id']===$processId&&(int)$a['entity_id']===$entityId&&($a['status']??'active')==='active')return true;return false;}
function process_mapping_step_assigned_entity(array$step,array$lanes,int$instanceEntityId):?int
{
    $lane=null;foreach($lanes as$l)if((int)$l['id']===(int)$step['lane_id']){$lane=$l;break;}if(!$lane)return$instanceEntityId;
    if(($lane['participant_type']??'')==='external')return null;
    if(in_array((string)($lane['lane_code']??''),['requesting_business','receiving_business'],true))return$instanceEntityId;
    $laneEntity=(int)($lane['entity_id']??0);return$laneEntity>0?$laneEntity:$instanceEntityId;
}
function process_mapping_create_from_template(string$code,string$note,int$reviewerId,int$approverId):array
{
    if(!can_use_enterprise_view())throw new RuntimeException('Enterprise process templates require Enterprise View.');$preview=process_mapping_template_preview($code);if(!$preview['valid'])throw new RuntimeException(implode(' ',$preview['errors']));$userId=(int)current_user()['id'];if(count(array_unique([$userId,$reviewerId,$approverId]))!==3)throw new RuntimeException('Process preparation, review, and approval must use three different users.');if(!process_mapping_active_user($reviewerId)||!process_mapping_active_user($approverId))throw new RuntimeException('Reviewer and approver must be active users.');if(trim($note)==='')throw new RuntimeException('Process-template evidence is required.');
    $template=$preview['template'];$root=entity_system_find_by_code('GRUBER-ENTERPRISE');$process=process_mapping_save_process(['id'=>null,'process_code'=>'PROC-'.strtoupper(substr(hash('sha256',$code.'|'.(string)microtime(true)),0,10)),'template_code'=>$code,'process_name'=>$template['name'].' Copy','purpose'=>$template['purpose'],'category_code'=>$template['category'],'value_chain'=>$template['value_chain'],'owner_entity_id'=>$root['id']??null,'is_template'=>0,'status'=>'draft','active_version_id'=>null,'created_by'=>$userId]);
    $version=process_mapping_save_version(['id'=>null,'process_id'=>$process['id'],'version_number'=>'1.0','status'=>'draft','effective_from'=>date('Y-m-d'),'effective_to'=>null,'prepared_by'=>$userId,'reviewed_by'=>$reviewerId,'approved_by'=>$approverId,'manifest_hash'=>hash('sha256',json_encode($template,JSON_UNESCAPED_SLASHES)),'evidence_note'=>$note,'published_at'=>null,'locked_at'=>null]);
    $laneMap=[];foreach($template['lanes']as$i=>$lane){$entityId=null;if(($lane['entity_code']??null)!==null){$e=entity_system_find_by_code((string)$lane['entity_code']);$entityId=$e?(int)$e['id']:null;}$saved=process_mapping_save_lane(['id'=>null,'version_id'=>$version['id'],'lane_code'=>$lane['code'],'lane_name'=>$lane['name'],'participant_type'=>$lane['participant_type'],'entity_id'=>$entityId,'role_code'=>$lane['role_code'],'sort_order'=>$i+1,'color_token'=>'lane-'.(($i%6)+1),'status'=>'active']);$laneMap[$lane['code']]=$saved['id'];}
    $stepMap=[];foreach($template['steps']as$i=>$step){$saved=process_mapping_save_step(['id'=>null,'version_id'=>$version['id'],'lane_id'=>$laneMap[$step['lane']],'step_code'=>$step['code'],'step_name'=>$step['name'],'step_type'=>$step['type'],'description'=>$step['name'].' within '.$template['name'].'.','position_x'=>$step['x'],'position_y'=>$step['y'],'node_width'=>150,'node_height'=>72,'required_permission'=>$step['permission']??'platform.view','sla_minutes'=>$step['sla']??0,'evidence_required'=>!empty($step['evidence'])?1:0,'canonical_record_type'=>$step['record']??'business_process','integration_event'=>$step['event']??'','automation_mode'=>$step['type']==='integration'?'adapter_gated':'human_supervised','sort_order'=>$i+1,'status'=>'active']);$stepMap[$step['code']]=$saved['id'];if(!empty($step['evidence'])||in_array($step['type'],['approval','control'],true))process_mapping_save_control(['id'=>null,'step_id'=>$saved['id'],'control_type'=>$step['type']==='approval'?'approval':'evidence','rule_code'=>'CTRL-'.$saved['step_code'],'control_description'=>'Require governed evidence before transition.','severity'=>$step['type']==='approval'?'high':'medium','separation_role'=>$step['type']==='approval'?'preparer':'','evidence_type'=>'record_reference','status'=>'active']);if(!empty($step['event']))process_mapping_save_integration(['id'=>null,'step_id'=>$saved['id'],'connection_id'=>null,'direction'=>'outbound','event_type'=>$step['event'],'record_type'=>$saved['canonical_record_type'],'sync_mode'=>'event','required_acknowledgment'=>1,'timeout_minutes'=>120,'status'=>'active']);}
    foreach($template['transitions']as$i=>$t)process_mapping_save_transition(['id'=>null,'version_id'=>$version['id'],'from_step_id'=>$stepMap[$t['from']],'to_step_id'=>$stepMap[$t['to']],'transition_code'=>'T'.($i+1),'condition_label'=>$t['label'],'is_default'=>!empty($t['default'])?1:0,'is_exception_path'=>!empty($t['exception'])?1:0,'sort_order'=>$i+1,'status'=>'active']);
    foreach(entity_system_bindings()as$b)process_mapping_save_assignment(['id'=>null,'process_id'=>$process['id'],'entity_id'=>$b['entity_id'],'assignment_type'=>'applicable','module_code'=>$template['category'],'inheritance_mode'=>'template','status'=>'active','effective_from'=>date('Y-m-d'),'effective_to'=>null]);
    process_mapping_add_event((int)$process['id'],(int)$version['id'],null,null,'process_created',null,'draft','medium',$note);return process_mapping_find_process((int)$process['id'])??$process;
}
function process_mapping_publish_version(array$version,string$note):array
{
    if(!can_use_enterprise_view())throw new RuntimeException('Publishing enterprise process versions requires Enterprise View.');if($version['status']==='published')return$version;$prepared=(int)$version['prepared_by'];$reviewed=(int)$version['reviewed_by'];$approved=(int)$version['approved_by'];if(count(array_unique([$prepared,$reviewed,$approved]))!==3)throw new RuntimeException('Process version publishing requires separate preparer, reviewer, and approver.');if(!process_mapping_active_user($reviewed)||!process_mapping_active_user($approved))throw new RuntimeException('The recorded reviewer and approver must remain active.');
    $steps=process_mapping_steps((int)$version['id']);$types=array_column($steps,'step_type');if(!in_array('start',$types,true)||!in_array('end',$types,true))throw new RuntimeException('A published process needs start and end steps.');if(count(process_mapping_transitions((int)$version['id']))<1)throw new RuntimeException('A published process needs transitions.');if(trim($note)==='')throw new RuntimeException('Publication evidence is required.');
    $version['status']='published';$version['published_at']=date('Y-m-d H:i:s');$version['locked_at']=$version['published_at'];$version['evidence_note']=$note;$version=process_mapping_save_version($version);$process=process_mapping_find_process((int)$version['process_id']);if($process){$process['status']='published';$process['active_version_id']=$version['id'];process_mapping_save_process($process);}process_mapping_add_event((int)$version['process_id'],(int)$version['id'],null,null,'version_published','draft','published','high',$note);return$version;
}
function process_mapping_save_layout(int$versionId,array$positions,string$note):void
{
    $version=process_mapping_find_version($versionId);if(!$version)throw new RuntimeException('Process version not found or outside your entity scope.');if($version['status']==='published')throw new RuntimeException('Published process versions are locked; create a new version before changing the map.');$steps=process_mapping_steps($versionId);foreach($steps as$step){$p=$positions[(string)$step['id']]??$positions[(int)$step['id']]??null;if(!$p)continue;$step['position_x']=max(190,min(1800,(int)($p['x']??$step['position_x'])));$step['position_y']=max(40,min(1200,(int)($p['y']??$step['position_y'])));process_mapping_save_step($step);}process_mapping_add_event((int)$version['process_id'],$versionId,null,null,'layout_saved',null,'draft','low',$note);
}
function process_mapping_start_instance(int$processId,int$entityId,string$recordType,int$recordId,string$title,string$note):array
{
    $process=process_mapping_find_process($processId);if(!$process||$process['status']!=='published')throw new RuntimeException('Select a published process within your entity scope.');$entity=entity_system_find_entity($entityId);if(!$entity)throw new RuntimeException('Select an operating entity within your permitted scope.');if((int)($entity['company_id']??0)<=0)throw new RuntimeException('A live process must start for an operating company entity.');if(!process_mapping_process_assigned_to_entity($processId,$entityId))throw new RuntimeException('This process is not assigned to the selected entity.');
    $recordCompany=process_mapping_record_company_id($recordType,$recordId);$entityCompany=(int)$entity['company_id'];if($recordCompany!==null&&$recordCompany!==$entityCompany)throw new RuntimeException('The canonical record belongs to a different company than the selected process entity.');foreach(process_mapping_instances($processId)as$existing)if((int)$existing['entity_id']===$entityId&&(string)$existing['canonical_record_type']===$recordType&&(int)$existing['canonical_record_id']===$recordId&&in_array((string)$existing['status'],['in_progress','blocked','overdue'],true))throw new RuntimeException('An active process instance already exists for this canonical record and entity.');
    $version=process_mapping_process_version($process);if(!$version)throw new RuntimeException('Published process version not found.');$steps=process_mapping_steps((int)$version['id']);$lanes=process_mapping_lanes((int)$version['id']);$start=null;foreach($steps as$s)if($s['step_type']==='start'){$start=$s;break;}if(!$start)throw new RuntimeException('The process has no start step.');if(trim($note)===''||trim($title)==='')throw new RuntimeException('Instance title and start evidence are required.');
    $number='PROC-'.date('Ymd-His').'-'.strtoupper(substr(hash('sha256',(string)microtime(true).'|'.$processId.'|'.$entityId.'|'.$recordType.'|'.$recordId),0,5));$instance=process_mapping_save_instance(['id'=>null,'process_id'=>$processId,'version_id'=>$version['id'],'instance_number'=>$number,'entity_id'=>$entityId,'canonical_record_type'=>$recordType,'canonical_record_id'=>$recordId,'instance_title'=>$title,'status'=>'in_progress','current_step_id'=>$start['id'],'started_by'=>(int)current_user()['id'],'started_at'=>date('Y-m-d H:i:s'),'due_at'=>date('Y-m-d H:i:s',strtotime('+7 days')),'completed_at'=>null,'cycle_seconds'=>0,'process_data_json'=>json_encode(['start_evidence'=>$note,'company_id'=>$entityCompany],JSON_UNESCAPED_SLASHES)]);
    foreach($steps as$s){$assignedEntity=process_mapping_step_assigned_entity($s,$lanes,$entityId);process_mapping_save_step_instance(['id'=>null,'instance_id'=>$instance['id'],'step_id'=>$s['id'],'assigned_entity_id'=>$assignedEntity,'assigned_user_id'=>null,'status'=>(int)$s['id']===(int)$start['id']?'active':'pending','started_at'=>(int)$s['id']===(int)$start['id']?date('Y-m-d H:i:s'):null,'due_at'=>$s['sla_minutes']>0?date('Y-m-d H:i:s',strtotime('+'.$s['sla_minutes'].' minutes')):null,'completed_at'=>null,'elapsed_seconds'=>0,'evidence_note'=>'','output_json'=>'{}']);}
    process_mapping_add_event($processId,(int)$version['id'],(int)$instance['id'],(int)$start['id'],'instance_started',null,'in_progress','medium',$note);return$instance;
}
function process_mapping_advance_step(int$stepInstanceId,string$decision,string$note):array
{
    $si=process_mapping_find_step_instance($stepInstanceId);if(!$si)throw new RuntimeException('Process step instance not found or outside your entity scope.');if($si['status']!=='active')throw new RuntimeException('Only the active process step can advance.');$step=process_mapping_find_step((int)$si['step_id']);$instance=process_mapping_find_instance((int)$si['instance_id']);if(!$step||!$instance)throw new RuntimeException('Process context is incomplete.');$permission=(string)($step['required_permission']??'platform.view');if($permission!==''&&!can($permission))throw new RuntimeException('You do not have the permission required to complete this process step.');if(!empty($si['assigned_entity_id'])&&!in_array((int)$si['assigned_entity_id'],process_mapping_visible_entity_ids(),true))throw new RuntimeException('The active step belongs to an entity outside your permitted scope.');if(!empty($step['evidence_required'])&&trim($note)==='')throw new RuntimeException('This step requires completion evidence.');
    $from=$si['status'];$si['status']=$decision==='exception'?'exception':'completed';$si['completed_at']=date('Y-m-d H:i:s');$si['elapsed_seconds']=max(0,time()-strtotime((string)($si['started_at']??date('Y-m-d H:i:s'))));$si['evidence_note']=$note;$si=process_mapping_save_step_instance($si);
    if($decision==='exception'){$instance['status']='blocked';process_mapping_save_instance($instance);process_mapping_add_event((int)$instance['process_id'],(int)$instance['version_id'],(int)$instance['id'],(int)$step['id'],'step_exception',$from,'exception','high',$note);return$instance;}
    $transitions=array_values(array_filter(process_mapping_transitions((int)$instance['version_id']),fn($t)=>(int)$t['from_step_id']===(int)$step['id']&&!empty($t['is_default'])));$next=$transitions[0]??null;if(!$next){$instance['status']='completed';$instance['completed_at']=date('Y-m-d H:i:s');$instance['cycle_seconds']=max(0,time()-strtotime((string)$instance['started_at']));$instance['current_step_id']=null;}else{$nextSi=null;foreach(process_mapping_step_instances((int)$instance['id'])as$candidate)if((int)$candidate['step_id']===(int)$next['to_step_id']){$nextSi=$candidate;break;}if($nextSi){$nextSi['status']='active';$nextSi['started_at']=date('Y-m-d H:i:s');process_mapping_save_step_instance($nextSi);$instance['current_step_id']=$nextSi['step_id'];$nextStep=process_mapping_find_step((int)$nextSi['step_id']);if($nextStep&&$nextStep['step_type']==='end'){$nextSi['status']='completed';$nextSi['completed_at']=date('Y-m-d H:i:s');process_mapping_save_step_instance($nextSi);$instance['status']='completed';$instance['completed_at']=date('Y-m-d H:i:s');$instance['cycle_seconds']=max(0,time()-strtotime((string)$instance['started_at']));}}}process_mapping_save_instance($instance);process_mapping_add_event((int)$instance['process_id'],(int)$instance['version_id'],(int)$instance['id'],(int)$step['id'],'step_completed',$from,$instance['status'],'medium',$note);return$instance;
}
function process_mapping_open_exception(int$stepInstanceId,string$type,string$severity,string$description,int$reviewerId):array
{
    $si=process_mapping_find_step_instance($stepInstanceId);if(!$si)throw new RuntimeException('Step instance not found or outside your entity scope.');$owner=(int)current_user()['id'];if($owner===$reviewerId)throw new RuntimeException('Exception owner and reviewer must be different users.');if(!process_mapping_active_user($reviewerId))throw new RuntimeException('The assigned exception reviewer must be active.');if(trim($description)==='')throw new RuntimeException('Exception evidence is required.');$e=process_mapping_save_exception(['id'=>null,'instance_id'=>$si['instance_id'],'step_instance_id'=>$si['id'],'exception_type'=>$type,'severity'=>$severity,'status'=>'open','owner_id'=>$owner,'reviewer_id'=>$reviewerId,'exception_description'=>$description,'resolution_note'=>'','opened_at'=>date('Y-m-d H:i:s'),'resolved_at'=>null]);$instance=process_mapping_find_instance((int)$si['instance_id']);if($instance){$instance['status']='blocked';process_mapping_save_instance($instance);process_mapping_add_event((int)$instance['process_id'],(int)$instance['version_id'],(int)$instance['id'],(int)$si['step_id'],'exception_opened',null,'blocked',$severity,$description);}return$e;
}
function process_mapping_resolve_exception(int$exceptionId,string$note):array
{
    $e=process_mapping_find(process_mapping_exceptions(),$exceptionId);if(!$e)throw new RuntimeException('Exception not found or outside your entity scope.');if((int)current_user()['id']!==(int)$e['reviewer_id'])throw new RuntimeException('Only the assigned independent reviewer can resolve this exception.');if(trim($note)==='')throw new RuntimeException('Resolution evidence is required.');$e['status']='resolved';$e['resolution_note']=$note;$e['resolved_at']=date('Y-m-d H:i:s');$e=process_mapping_save_exception($e);$instance=process_mapping_find_instance((int)$e['instance_id']);if($instance){$instance['status']='in_progress';process_mapping_save_instance($instance);process_mapping_add_event((int)$instance['process_id'],(int)$instance['version_id'],(int)$instance['id'],null,'exception_resolved','blocked','in_progress','medium',$note);}return$e;
}
function process_mapping_analytics():array
{
    $instances=process_mapping_instances();$steps=process_mapping_step_instances();$processNames=[];foreach(process_mapping_processes()as$p)$processNames[(int)$p['id']]=$p['process_name'];$byProcess=[];foreach($instances as$i){$name=$processNames[(int)$i['process_id']]??'Unknown';$byProcess[$name]['volume']=($byProcess[$name]['volume']??0)+1;$byProcess[$name]['completed']=($byProcess[$name]['completed']??0)+($i['status']==='completed'?1:0);$byProcess[$name]['cycle_total']=($byProcess[$name]['cycle_total']??0)+(int)$i['cycle_seconds'];}
    foreach($byProcess as&$row){$row['average_cycle_seconds']=$row['completed']?intdiv($row['cycle_total'],$row['completed']):0;$row['completion_percent']=round(($row['completed']/$row['volume'])*100,1);}unset($row);
    $bottlenecks=[];foreach($steps as$si){$step=process_mapping_find_step((int)$si['step_id']);if(!$step)continue;$name=$step['step_name'];$bottlenecks[$name]['elapsed']=($bottlenecks[$name]['elapsed']??0)+(int)$si['elapsed_seconds'];$bottlenecks[$name]['count']=($bottlenecks[$name]['count']??0)+1;$bottlenecks[$name]['exceptions']=($bottlenecks[$name]['exceptions']??0)+($si['status']==='exception'?1:0);}foreach($bottlenecks as&$b)$b['average_seconds']=$b['count']?intdiv($b['elapsed'],$b['count']):0;unset($b);uasort($bottlenecks,fn($a,$b)=>$b['average_seconds']<=>$a['average_seconds']);return['by_process'=>$byProcess,'bottlenecks'=>$bottlenecks];
}
