<?php
declare(strict_types=1);

function process_mapping_tables():array{return['business_processes','business_process_versions','business_process_lanes','business_process_steps','business_process_transitions','business_process_controls','business_process_integrations','business_process_assignments','business_process_instances','business_process_step_instances','business_process_exceptions','business_process_events'];}
function process_mapping_tables_ready():bool{if(data_is_demo())return true;$pdo=production_database_connection();if(!$pdo)return false;try{$n=process_mapping_tables();$s=$pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ('.implode(',',array_fill(0,count($n),'?')).')');$s->execute($n);return(int)$s->fetchColumn()===count($n);}catch(Throwable){return false;}}
function process_mapping_require_tables():void{if(!process_mapping_tables_ready())throw new RuntimeException('Import the Section 25 migration before using Production Data process-mapping writes.');}
function process_mapping_demo_collection(string$key,callable$seed):array{if(!isset($_SESSION['gruber_demo_state'][$key]))$_SESSION['gruber_demo_state'][$key]=$seed();return array_values($_SESSION['gruber_demo_state'][$key]);}
function process_mapping_demo_save(string$key,array$r,callable$seed):array{$rows=process_mapping_demo_collection($key,$seed);$id=(int)($r['id']??0);if($id<=0){$id=max([0,...array_map('intval',array_column($rows,'id'))])+1;$r['id']=$id;$rows[]=$r;}else{$found=false;foreach($rows as$i=>$row)if((int)$row['id']===$id){$rows[$i]=array_replace($row,$r);$r=$rows[$i];$found=true;break;}if(!$found)$rows[]=$r;}$_SESSION['gruber_demo_state'][$key]=array_values($rows);return$r;}
function process_mapping_raw_rows(string$table,string$key,callable$seed,string$order='id'):array{if(data_is_demo())return process_mapping_demo_collection($key,$seed);if(!process_mapping_tables_ready())return[];return production_database_connection()->query("SELECT * FROM {$table} ORDER BY {$order}")->fetchAll();}
function process_mapping_visible_entity_ids():array{return entity_system_visible_entity_ids();}
function process_mapping_visible_process_ids():array
{
    $processes=process_mapping_raw_rows('business_processes','business_processes','process_mapping_demo_processes','process_name,id');
    if(can_use_enterprise_view())return array_map('intval',array_column($processes,'id'));
    $entities=array_fill_keys(process_mapping_visible_entity_ids(),true);$visible=[];$today=date('Y-m-d');
    foreach(process_mapping_raw_rows('business_process_assignments','business_process_assignments','process_mapping_demo_assignments','process_id,entity_id')as$a){if(!isset($entities[(int)$a['entity_id']])||($a['status']??'active')!=='active')continue;if(!empty($a['effective_from'])&&(string)$a['effective_from']>$today)continue;if(!empty($a['effective_to'])&&(string)$a['effective_to']<$today)continue;$visible[(int)$a['process_id']]=true;}
    foreach(process_mapping_raw_rows('business_process_instances','business_process_instances','process_mapping_demo_instances','created_at DESC,id DESC')as$i)if(isset($entities[(int)$i['entity_id']]))$visible[(int)$i['process_id']]=true;
    return array_map('intval',array_keys($visible));
}
function process_mapping_processes():array{$visible=array_fill_keys(process_mapping_visible_process_ids(),true);return array_values(array_filter(process_mapping_raw_rows('business_processes','business_processes','process_mapping_demo_processes','process_name,id'),static fn(array$r):bool=>isset($visible[(int)$r['id']])));}
function process_mapping_versions(?int$processId=null):array{$processes=array_fill_keys(process_mapping_visible_process_ids(),true);$r=array_values(array_filter(process_mapping_raw_rows('business_process_versions','business_process_versions','process_mapping_demo_versions','process_id,id DESC'),static fn(array$x):bool=>isset($processes[(int)$x['process_id']])));return$processId===null?$r:array_values(array_filter($r,fn($x)=>(int)$x['process_id']===$processId));}
function process_mapping_visible_version_ids():array{return array_map('intval',array_column(process_mapping_versions(),'id'));}
function process_mapping_lanes(?int$versionId=null):array{$versions=array_fill_keys(process_mapping_visible_version_ids(),true);$r=array_values(array_filter(process_mapping_raw_rows('business_process_lanes','business_process_lanes','process_mapping_demo_lanes','version_id,sort_order,id'),static fn(array$x):bool=>isset($versions[(int)$x['version_id']])));return$versionId===null?$r:array_values(array_filter($r,fn($x)=>(int)$x['version_id']===$versionId));}
function process_mapping_steps(?int$versionId=null):array{$versions=array_fill_keys(process_mapping_visible_version_ids(),true);$r=array_values(array_filter(process_mapping_raw_rows('business_process_steps','business_process_steps','process_mapping_demo_steps','version_id,sort_order,id'),static fn(array$x):bool=>isset($versions[(int)$x['version_id']])));return$versionId===null?$r:array_values(array_filter($r,fn($x)=>(int)$x['version_id']===$versionId));}
function process_mapping_visible_step_ids():array{return array_map('intval',array_column(process_mapping_steps(),'id'));}
function process_mapping_transitions(?int$versionId=null):array{$versions=array_fill_keys(process_mapping_visible_version_ids(),true);$r=array_values(array_filter(process_mapping_raw_rows('business_process_transitions','business_process_transitions','process_mapping_demo_transitions','version_id,sort_order,id'),static fn(array$x):bool=>isset($versions[(int)$x['version_id']])));return$versionId===null?$r:array_values(array_filter($r,fn($x)=>(int)$x['version_id']===$versionId));}
function process_mapping_controls():array{$steps=array_fill_keys(process_mapping_visible_step_ids(),true);return array_values(array_filter(process_mapping_raw_rows('business_process_controls','business_process_controls','process_mapping_demo_controls','step_id,id'),static fn(array$r):bool=>isset($steps[(int)$r['step_id']])));}
function process_mapping_integrations():array{$steps=array_fill_keys(process_mapping_visible_step_ids(),true);return array_values(array_filter(process_mapping_raw_rows('business_process_integrations','business_process_integrations','process_mapping_demo_integrations','step_id,id'),static fn(array$r):bool=>isset($steps[(int)$r['step_id']])));}
function process_mapping_assignments():array{$processes=array_fill_keys(process_mapping_visible_process_ids(),true);$entities=array_fill_keys(process_mapping_visible_entity_ids(),true);return array_values(array_filter(process_mapping_raw_rows('business_process_assignments','business_process_assignments','process_mapping_demo_assignments','process_id,entity_id'),static fn(array$r):bool=>isset($processes[(int)$r['process_id']])&&isset($entities[(int)$r['entity_id']])));}
function process_mapping_instances(?int$processId=null):array{$processes=array_fill_keys(process_mapping_visible_process_ids(),true);$entities=array_fill_keys(process_mapping_visible_entity_ids(),true);$r=array_values(array_filter(process_mapping_raw_rows('business_process_instances','business_process_instances','process_mapping_demo_instances','created_at DESC,id DESC'),static fn(array$x):bool=>isset($processes[(int)$x['process_id']])&&isset($entities[(int)$x['entity_id']])));return$processId===null?$r:array_values(array_filter($r,fn($x)=>(int)$x['process_id']===$processId));}
function process_mapping_visible_instance_ids():array{return array_map('intval',array_column(process_mapping_instances(),'id'));}
function process_mapping_step_instances(?int$instanceId=null):array{$instances=array_fill_keys(process_mapping_visible_instance_ids(),true);$r=array_values(array_filter(process_mapping_raw_rows('business_process_step_instances','business_process_step_instances','process_mapping_demo_step_instances','instance_id,id'),static fn(array$x):bool=>isset($instances[(int)$x['instance_id']])));return$instanceId===null?$r:array_values(array_filter($r,fn($x)=>(int)$x['instance_id']===$instanceId));}
function process_mapping_exceptions(?int$instanceId=null):array{$instances=array_fill_keys(process_mapping_visible_instance_ids(),true);$r=array_values(array_filter(process_mapping_raw_rows('business_process_exceptions','business_process_exceptions','process_mapping_demo_exceptions','opened_at DESC,id DESC'),static fn(array$x):bool=>isset($instances[(int)$x['instance_id']])));return$instanceId===null?$r:array_values(array_filter($r,fn($x)=>(int)$x['instance_id']===$instanceId));}
function process_mapping_events():array{$processes=array_fill_keys(process_mapping_visible_process_ids(),true);$instances=array_fill_keys(process_mapping_visible_instance_ids(),true);return array_values(array_filter(process_mapping_raw_rows('business_process_events','business_process_events','process_mapping_demo_events','created_at DESC,id DESC'),static fn(array$r):bool=>(!empty($r['instance_id'])&&isset($instances[(int)$r['instance_id']]))||(empty($r['instance_id'])&&!empty($r['process_id'])&&isset($processes[(int)$r['process_id']]))));}
function process_mapping_find(array$rows,int$id):?array{foreach($rows as$r)if((int)$r['id']===$id)return$r;return null;}
function process_mapping_find_process(int$id):?array{return process_mapping_find(process_mapping_processes(),$id);}
function process_mapping_find_version(int$id):?array{return process_mapping_find(process_mapping_versions(),$id);}
function process_mapping_find_step(int$id):?array{return process_mapping_find(process_mapping_steps(),$id);}
function process_mapping_find_instance(int$id):?array{return process_mapping_find(process_mapping_instances(),$id);}
function process_mapping_find_step_instance(int$id):?array{return process_mapping_find(process_mapping_step_instances(),$id);}
function process_mapping_save_row(string$table,string$key,callable$seed,array$r,array$fields):array{process_mapping_require_tables();$r['created_at']=$r['created_at']??date('Y-m-d H:i:s');$r['updated_at']=date('Y-m-d H:i:s');if(data_is_demo())return process_mapping_demo_save($key,$r,$seed);$pdo=production_database_connection();$id=(int)($r['id']??0);$values=[];foreach($fields as$f){$v=$r[$f]??null;if(is_array($v))$v=json_encode($v,JSON_UNESCAPED_SLASHES);$values[]=$v;}if($id){$values[]=$id;$pdo->prepare('UPDATE '.$table.' SET '.implode(',',array_map(fn($f)=>$f.'=?',$fields)).',updated_at=NOW() WHERE id=?')->execute($values);}else{$pdo->prepare('INSERT INTO '.$table.' ('.implode(',',$fields).') VALUES ('.implode(',',array_fill(0,count($fields),'?')).')')->execute($values);$id=(int)$pdo->lastInsertId();}$r['id']=$id;return$r;}
function process_mapping_save_process(array$r):array{return process_mapping_save_row('business_processes','business_processes','process_mapping_demo_processes',$r,['process_code','template_code','process_name','purpose','category_code','value_chain','owner_entity_id','is_template','status','active_version_id','created_by']);}
function process_mapping_save_version(array$r):array{return process_mapping_save_row('business_process_versions','business_process_versions','process_mapping_demo_versions',$r,['process_id','version_number','status','effective_from','effective_to','prepared_by','reviewed_by','approved_by','manifest_hash','evidence_note','published_at','locked_at']);}
function process_mapping_save_lane(array$r):array{return process_mapping_save_row('business_process_lanes','business_process_lanes','process_mapping_demo_lanes',$r,['version_id','lane_code','lane_name','participant_type','entity_id','role_code','sort_order','color_token','status']);}
function process_mapping_save_step(array$r):array{return process_mapping_save_row('business_process_steps','business_process_steps','process_mapping_demo_steps',$r,['version_id','lane_id','step_code','step_name','step_type','description','position_x','position_y','node_width','node_height','required_permission','sla_minutes','evidence_required','canonical_record_type','integration_event','automation_mode','sort_order','status']);}
function process_mapping_save_transition(array$r):array{return process_mapping_save_row('business_process_transitions','business_process_transitions','process_mapping_demo_transitions',$r,['version_id','from_step_id','to_step_id','transition_code','condition_label','is_default','is_exception_path','sort_order','status']);}
function process_mapping_save_control(array$r):array{return process_mapping_save_row('business_process_controls','business_process_controls','process_mapping_demo_controls',$r,['step_id','control_type','rule_code','control_description','severity','separation_role','evidence_type','status']);}
function process_mapping_save_integration(array$r):array{return process_mapping_save_row('business_process_integrations','business_process_integrations','process_mapping_demo_integrations',$r,['step_id','connection_id','direction','event_type','record_type','sync_mode','required_acknowledgment','timeout_minutes','status']);}
function process_mapping_save_assignment(array$r):array{return process_mapping_save_row('business_process_assignments','business_process_assignments','process_mapping_demo_assignments',$r,['process_id','entity_id','assignment_type','module_code','inheritance_mode','status','effective_from','effective_to']);}
function process_mapping_save_instance(array$r):array{return process_mapping_save_row('business_process_instances','business_process_instances','process_mapping_demo_instances',$r,['process_id','version_id','instance_number','entity_id','canonical_record_type','canonical_record_id','instance_title','status','current_step_id','started_by','started_at','due_at','completed_at','cycle_seconds','process_data_json']);}
function process_mapping_save_step_instance(array$r):array{return process_mapping_save_row('business_process_step_instances','business_process_step_instances','process_mapping_demo_step_instances',$r,['instance_id','step_id','assigned_entity_id','assigned_user_id','status','started_at','due_at','completed_at','elapsed_seconds','evidence_note','output_json']);}
function process_mapping_save_exception(array$r):array{return process_mapping_save_row('business_process_exceptions','business_process_exceptions','process_mapping_demo_exceptions',$r,['instance_id','step_instance_id','exception_type','severity','status','owner_id','reviewer_id','exception_description','resolution_note','opened_at','resolved_at']);}
function process_mapping_add_event(?int$processId,?int$versionId,?int$instanceId,?int$stepId,string$type,?string$from,?string$to,string$severity,string$note):array{process_mapping_require_tables();$r=['id'=>null,'process_id'=>$processId,'version_id'=>$versionId,'instance_id'=>$instanceId,'step_id'=>$stepId,'event_type'=>$type,'from_status'=>$from,'to_status'=>$to,'severity'=>$severity,'evidence_note'=>$note,'created_by'=>(int)current_user()['id'],'created_at'=>date('Y-m-d H:i:s')];if(data_is_demo())return process_mapping_demo_save('business_process_events',$r,'process_mapping_demo_events');$p=production_database_connection();$p->prepare('INSERT INTO business_process_events(process_id,version_id,instance_id,step_id,event_type,from_status,to_status,severity,evidence_note,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$processId,$versionId,$instanceId,$stepId,$type,$from,$to,$severity,$note,$r['created_by']]);$r['id']=(int)$p->lastInsertId();return$r;}
