<style>
.scenario-hero{display:grid;grid-template-columns:1.2fr .8fr;gap:20px;padding:24px;border:1px solid #dfe4ea;border-radius:20px;background:linear-gradient(135deg,#fff,#f7f9fc)}
.scenario-hero h2{font-size:clamp(1.7rem,3vw,2.5rem);margin:.4rem 0}.risk-orb{display:grid;place-items:center;min-height:190px;border-radius:18px;background:#111827;color:#fff;text-align:center}.risk-orb strong{font-size:3rem}.risk-orb small{opacity:.72}.risk-orb.status-critical{background:#7f1d1d}.risk-orb.status-high{background:#9a3412}.risk-orb.status-medium{background:#854d0e}.risk-orb.status-low{background:#166534}
.scenario-controls{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:12px}.scenario-controls label span{display:block;margin-bottom:6px}.scenario-controls input,.scenario-controls select{width:100%}
.case-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.case-card{padding:18px;border:1px solid #dfe4ea;border-radius:18px;background:#fff}.case-card.expected{border-width:2px;border-color:#4f46e5}.case-card strong{display:block;font-size:2rem;margin:.4rem 0}.case-metrics{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:14px}.case-metrics span:nth-child(even){font-weight:700}
.formula-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:14px}.formula-card{padding:16px;border:1px solid #dfe4ea;border-radius:16px;background:#fff}.formula-card b{display:block;font-size:1.4rem;margin-top:6px}
.risk-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.risk-panel{padding:18px;border:1px solid #dfe4ea;border-radius:18px;background:#fff}.risk-row{display:flex;justify-content:space-between;gap:16px;padding:12px 0;border-bottom:1px solid #eef2f7}.risk-row:last-child{border-bottom:0}.risk-row small{display:block;color:#64748b}
.scenario-save-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.scenario-save-card{padding:18px;border:1px solid #dfe4ea;border-radius:18px;background:#fff}.saved-scenario{display:flex;justify-content:space-between;gap:14px;padding:14px 0;border-bottom:1px solid #eef2f7}.saved-scenario:last-child{border-bottom:0}
.active-assumption-grid{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.active-assumption-grid span{padding:6px 9px;border-radius:999px;background:#eef2ff;color:#3730a3;font-size:.82rem;font-weight:700}
@media(max-width:980px){.scenario-hero,.risk-grid,.scenario-save-grid{grid-template-columns:1fr}.scenario-controls{grid-template-columns:repeat(2,minmax(140px,1fr))}.case-grid{grid-template-columns:1fr}}
</style>
