<?php
declare(strict_types=1);
require_once __DIR__.'/strategy_portfolio_governance.php';

function strategy_assert_company_source(?array$source,int$companyId,string$label):void{if(!$source)throw new RuntimeException($label.' is outside the active scope.');$sourceCompany=(int)($source['company_id']??0);if($sourceCompany>0&&$sourceCompany!==$companyId)throw new RuntimeException($label.' belongs to a sibling company.');}
function strategy_create_governed_initiative(array$record):array{$entity=entity_system_find_entity((int)($record['entity_id']??0));$company=(int)($entity['company_id']??0);if($company<=0)throw new RuntimeException('Initiatives require a visible operating-company entity.');if(!empty($record['primary_goal_id']))strategy_assert_company_source(executive_intelligence_find_goal((int)$record['primary_goal_id']),$company,'Primary goal');if(!empty($record['primary_kpi_definition_id']))strategy_assert_company_source(executive_intelligence_find_definition((int)$record['primary_kpi_definition_id']),$company,'Primary KPI');if(!empty($record['budget_envelope_id'])){$budget=demand_find_budget((int)$record['budget_envelope_id']);if(!$budget||(int)$budget['company_id']!==$company)throw new RuntimeException('Budget envelope belongs to another company.');}if(!empty($record['savings_opportunity_id'])){$opportunity=savings_realization_find_opportunity((int)$record['savings_opportunity_id']);if(!$opportunity||(int)$opportunity['company_id']!==$company)throw new RuntimeException('Savings opportunity belongs to another company.');}return strategy_save_initiative($record);}
function strategy_reserve_governed_funding(int$initiativeId,int$budgetId,float$amount,string$evidence):array{$initiative=strategy_find_initiative($initiativeId);if(!$initiative)throw new RuntimeException('Initiative is outside the active scope.');if((int)$initiative['approver_user_id']!==(int)current_user()['id'])throw new RuntimeException('Only the assigned initiative approver may authorize funding.');return strategy_reserve_funding($initiativeId,$budgetId,$amount,$evidence);}
function strategy_create_governed_benefit(array$record):array{$initiative=strategy_find_initiative((int)($record['initiative_id']??0));if(!$initiative)throw new RuntimeException('Benefit initiative is outside the active scope.');$company=(int)$initiative['company_id'];$kpiId=!empty($record['kpi_definition_id'])?(int)$record['kpi_definition_id']:null;$periodId=!empty($record['savings_realization_period_id'])?(int)$record['savings_realization_period_id']:null;if(!$kpiId&&!$periodId)throw new RuntimeException('Benefit claims require scoped KPI evidence or an independently validated Section 20 realization period.');if($kpiId){$kpi=executive_intelligence_find_definition($kpiId);strategy_assert_company_source($kpi,$company,'Benefit KPI');foreach(['baseline_snapshot_id','actual_snapshot_id']as$field)if(!empty($record[$field])){$snapshot=executive_intelligence_find_snapshot((int)$record[$field]);if(!$snapshot||(int)$snapshot['definition_id']!==$kpiId)throw new RuntimeException('Benefit snapshots must belong to the selected KPI.');}}if($periodId){$period=savings_realization_find_period($periodId);if(!$period||!in_array(savings_realization_period_status($period),['validated','closed'],true))throw new RuntimeException('Section 20 realization evidence must be independently validated or closed.');$opportunity=savings_realization_find_opportunity((int)$period['opportunity_id']);if(!$opportunity||(int)$opportunity['company_id']!==$company)throw new RuntimeException('Section 20 realization evidence belongs to another company.');}$record['evidence_note']=mb_substr(trim((string)($record['evidence_note']??'')),0,5000);if($record['evidence_note']==='')throw new RuntimeException('Benefit evidence is required.');return strategy_save_benefit($record);}
function strategy_validate_governed_benefit(int$id,string$note):array{$benefit=strategy_find_benefit($id);if(!$benefit)throw new RuntimeException('Benefit is outside the active scope.');if(empty($benefit['kpi_definition_id'])&&empty($benefit['savings_realization_period_id']))throw new RuntimeException('Benefit validation requires governed KPI or Section 20 evidence.');return strategy_validate_benefit($id,$note);}
function strategy_assert_portfolio_capacity(int$portfolioId):array{$portfolio=strategy_find_portfolio($portfolioId);if(!$portfolio)throw new RuntimeException('Portfolio is outside the active scope.');$initiatives=strategy_initiatives($portfolioId);$funding=array_sum(array_map(static fn(array$row):float=>in_array($row['stage'],['funded','in_execution','benefits_validation','completed'],true)?(float)$row['forecast_cost']:0.0,$initiatives));$capacity=array_sum(array_map(static fn(array$row):float=>!in_array($row['stage'],['completed','cancelled'],true)?(float)$row['capacity_demand_hours']:0.0,$initiatives));return['funding'=>$funding,'funding_limit'=>(float)$portfolio['funding_limit'],'capacity'=>$capacity,'capacity_limit'=>(float)$portfolio['capacity_limit_hours'],'funding_over'=>((float)$portfolio['funding_limit']>0&&$funding>(float)$portfolio['funding_limit']),'capacity_over'=>((float)$portfolio['capacity_limit_hours']>0&&$capacity>(float)$portfolio['capacity_limit_hours'])];}
