<?php
declare(strict_types=1);

function work_management_operating_entity_for_company(int$companyId):?array{foreach(entity_system_entities()as$entity)if((int)($entity['company_id']??0)===$companyId&&($entity['entity_type']??'')==='operating_company')return$entity;return null;}
function work_management_sync_sources():array
{
    work_management_require('create');$created=0;$existing=0;$errors=[];
    $add=static function(array$payload)use(&$created,&$existing,&$errors):void{try{$sourceKey=(string)($payload['source_key']??work_management_source_key((string)$payload['source_module'],(string)$payload['source_type'],(int)$payload['source_id'],(string)$payload['work_type'],(int)$payload['entity_id']));$before=work_management_find_item_by_source_key($sourceKey);$payload['source_key']=$sourceKey;work_management_create_item($payload);$before?$existing++:$created++;}catch(Throwable$exception){$errors[]=$exception->getMessage();}};
    foreach(process_mapping_step_instances()as$stepInstance){if(!in_array((string)$stepInstance['status'],['active','exception'],true))continue;$instance=process_mapping_find_instance((int)$stepInstance['instance_id']);$step=process_mapping_find_step((int)$stepInstance['step_id']);if(!$instance||!$step)continue;$add(['source_module'=>'process_mapping','source_type'=>'process_step','source_id'=>(int)$stepInstance['id'],'entity_id'=>(int)$instance['entity_id'],'process_instance_id'=>(int)$instance['id'],'step_instance_id'=>(int)$stepInstance['id'],'work_type'=>$stepInstance['status']==='exception'?'process_exception':'process_step','title'=>$step['step_name'].' · '.$instance['instance_number'],'description'=>'The live process step requires governed action, evidence, and permission '.$step['required_permission'].'.','priority'=>$stepInstance['status']==='exception'?'critical':'high','required_permission'=>$step['required_permission'],'assigned_entity_id'=>$stepInstance['assigned_entity_id']??$instance['entity_id'],'assigned_user_id'=>$stepInstance['assigned_user_id']??null,'evidence_required'=>!empty($step['evidence_required']),'due_at'=>$stepInstance['due_at']??$instance['due_at'],'sla_minutes'=>max(30,(int)$step['sla_minutes'])]);}
    foreach(process_mapping_exceptions()as$exception){if(($exception['status']??'')==='resolved')continue;$instance=process_mapping_find_instance((int)$exception['instance_id']);if(!$instance)continue;$add(['source_module'=>'process_mapping','source_type'=>'process_exception','source_id'=>(int)$exception['id'],'entity_id'=>(int)$instance['entity_id'],'process_instance_id'=>(int)$instance['id'],'step_instance_id'=>(int)$exception['step_instance_id'],'work_type'=>'process_exception','title'=>'Review '.status_label((string)$exception['exception_type']).' · '.$instance['instance_number'],'description'=>(string)$exception['exception_description'],'priority'=>(string)$exception['severity'],'required_permission'=>'work_management.review','assigned_user_id'=>(int)$exception['reviewer_id'],'reviewer_id'=>(int)$exception['reviewer_id'],'evidence_required'=>1,'sla_minutes'=>120]);}
    foreach(data_visible_collection('purchase_orders')as$po){if(!in_array((string)$po['status'],['past_due','partially_received'],true))continue;$entity=work_management_operating_entity_for_company((int)$po['company_id']);if(!$entity)continue;$add(['source_module'=>'purchase_orders','source_type'=>'purchase_order','source_id'=>(int)$po['id'],'entity_id'=>(int)$entity['id'],'work_type'=>'commitment_exception','title'=>'Escalate '.($po['po_number']??('PO #'.$po['id'])),'description'=>'The purchase commitment is '.status_label((string)$po['status']).' and requires supplier recovery evidence.','priority'=>$po['status']==='past_due'?'critical':'high','required_permission'=>'purchase_orders.edit','assigned_user_id'=>$po['buyer_id']??$po['buyer_user_id']??null,'evidence_required'=>1,'due_at'=>$po['expected_date']??date('Y-m-d H:i:s',strtotime('+4 hours')),'sla_minutes'=>240]);}
    foreach(data_visible_collection('workflow_approvals')as$approval){if(($approval['status']??'')!=='pending')continue;$entity=work_management_operating_entity_for_company((int)$approval['company_id']);if(!$entity)continue;$add(['source_module'=>'approvals','source_type'=>'workflow_approval','source_id'=>(int)$approval['id'],'entity_id'=>(int)$entity['id'],'work_type'=>'approval','title'=>(string)($approval['title']??'Approval decision'),'description'=>'A governed approval decision requires independent evidence review before canonical records change.','priority'=>'high','required_permission'=>'approvals.review','assigned_user_id'=>$approval['assigned_to']??null,'reviewer_id'=>$approval['assigned_to']??null,'evidence_required'=>1,'due_at'=>$approval['due_date']??date('Y-m-d H:i:s',strtotime('+8 hours')),'sla_minutes'=>480]);}
    foreach(data_visible_collection('data_quality_exceptions')as$exception){if(in_array((string)$exception['status'],['resolved','closed'],true))continue;$entity=work_management_operating_entity_for_company((int)$exception['company_id']);if(!$entity)continue;$add(['source_module'=>'data_collection','source_type'=>'data_quality_exception','source_id'=>(int)$exception['id'],'entity_id'=>(int)$entity['id'],'work_type'=>'data_quality','title'=>(string)($exception['issue']??$exception['title']??'Resolve data exception'),'description'=>'Resolve the source-data exception with correction evidence, validation, and rollback readiness.','priority'=>(string)($exception['severity']??'medium'),'required_permission'=>'discovery.edit','assigned_user_id'=>$exception['owner_id']??null,'evidence_required'=>1,'sla_minutes'=>960]);}
    foreach(data_visible_collection('contracts')as$contract){$endDate=(string)($contract['end_date']??'');if($endDate===''||strtotime($endDate)>strtotime('+90 days')||in_array((string)($contract['status']??''),['terminated','expired'],true))continue;$entity=work_management_operating_entity_for_company((int)($contract['company_id']??0));if(!$entity)continue;$add(['source_module'=>'contracts','source_type'=>'contract_renewal','source_id'=>(int)$contract['id'],'entity_id'=>(int)$entity['id'],'work_type'=>'contract_renewal','title'=>'Prepare renewal · '.($contract['contract_number']??$contract['number']??('Contract #'.$contract['id'])),'description'=>'The contract is inside its renewal window and requires performance, risk, pricing, and exit analysis.','priority'=>strtotime($endDate)<strtotime('+30 days')?'high':'medium','required_permission'=>'strategy.edit','evidence_required'=>1,'due_at'=>$endDate,'sla_minutes'=>1440]);}
    foreach(data_visible_collection('supplier_invoices')as$invoice){$matchStatus=(string)($invoice['match_status']??$invoice['status']??'');if(!in_array($matchStatus,['exception','blocked','variance','on_hold'],true))continue;$entity=work_management_operating_entity_for_company((int)$invoice['company_id']);if(!$entity)continue;$add(['source_module'=>'accounts_payable','source_type'=>'invoice_match_exception','source_id'=>(int)$invoice['id'],'entity_id'=>(int)$entity['id'],'work_type'=>'financial_exception','title'=>'Clear invoice exception · '.($invoice['invoice_number']??('Invoice #'.$invoice['id'])),'description'=>'The supplier invoice cannot proceed until receipt, price, quantity, duplicate, and approval evidence reconcile.','priority'=>'critical','required_permission'=>'accounts_payable.review','evidence_required'=>1,'sla_minutes'=>240]);}
    foreach(data_visible_collection('inventory_snapshots')as$snapshot){$available=(float)($snapshot['available']??0);if($available>10)continue;$entity=work_management_operating_entity_for_company((int)$snapshot['company_id']);if(!$entity)continue;$add(['source_module'=>'inventory','source_type'=>'inventory_shortage','source_id'=>(int)$snapshot['id'],'entity_id'=>(int)$entity['id'],'work_type'=>'inventory_exception','title'=>'Review low inventory · '.data_item_name((int)$snapshot['item_id']),'description'=>'Available inventory is '.$available.' and requires replenishment, transfer, reservation, or exception review.','priority'=>$available<=0?'critical':'high','required_permission'=>'inventory.edit','evidence_required'=>1,'sla_minutes'=>360]);}
    return['created'=>$created,'existing'=>$existing,'errors'=>array_values(array_unique($errors))];
}
