<?php
declare(strict_types=1);

function work_management_assert_three_person_governance(int$preparedBy,int$reviewedBy,int$approvedBy,?int$entityId=null):void
{
    if(count(array_unique([$preparedBy,$reviewedBy,$approvedBy]))!==3)throw new RuntimeException('Automation preparation, review, and approval require three different active users.');foreach([$preparedBy,$reviewedBy,$approvedBy]as$userId){$user=work_management_active_user($userId);if(!$user)throw new RuntimeException('Every automation governance participant must be active.');if($entityId&&!work_management_user_can_receive($user,$entityId,'work_management.view'))throw new RuntimeException('Every automation governance participant must have access to the rule entity.');}
}
function work_management_rule_version(array$rule):?array{$activeId=(int)($rule['active_version_id']??0);if($activeId>0)return work_management_find_version($activeId);$versions=work_management_automation_versions((int)$rule['id']);return$versions[0]??null;}
function work_management_create_rule(array$payload):array
{
    work_management_require('automate');$entityId=(int)($payload['entity_id']??0);if($entityId<=0){if(!can_use_enterprise_view())throw new RuntimeException('Enterprise automation rules require Enterprise View.');$entityId=0;}elseif(!entity_system_find_entity($entityId))throw new RuntimeException('The automation entity is outside the active company scope.');$preparedBy=(int)current_user()['id'];$reviewedBy=(int)($payload['reviewed_by']??0);$approvedBy=(int)($payload['approved_by']??0);work_management_assert_three_person_governance($preparedBy,$reviewedBy,$approvedBy,$entityId?:null);
    $name=trim((string)($payload['rule_name']??''));$trigger=trim((string)($payload['trigger_event']??''));$sourceModule=trim((string)($payload['source_module']??''));$condition=json_decode(trim((string)($payload['condition_json']??'')),true);$action=json_decode(trim((string)($payload['action_json']??'')),true);if($name===''||$trigger===''||$sourceModule==='')throw new RuntimeException('Rule name, trigger event, and source module are required.');if(!is_array($condition)||!is_array($action)||!isset($action['action']))throw new RuntimeException('Condition and action must be valid JSON objects with an action field.');$ruleCode=trim((string)($payload['rule_code']??''));if($ruleCode==='')$ruleCode='AUTO-'.strtoupper(substr(hash('sha256',$name.'|'.microtime(true)),0,10));foreach(work_management_automation_rules()as$existing)if(strcasecmp((string)$existing['rule_code'],$ruleCode)===0)throw new RuntimeException('Automation rule code already exists.');
    $rule=work_management_save_automation_rule(['id'=>null,'rule_code'=>$ruleCode,'rule_name'=>mb_substr($name,0,160),'trigger_event'=>$trigger,'source_module'=>$sourceModule,'entity_id'=>$entityId?:null,'status'=>'draft','active_version_id'=>null,'created_by'=>$preparedBy]);
    $version=work_management_save_automation_version(['id'=>null,'rule_id'=>$rule['id'],'version_number'=>'1.0','status'=>'draft','condition_json'=>json_encode($condition,JSON_UNESCAPED_SLASHES),'action_json'=>json_encode($action,JSON_UNESCAPED_SLASHES),'idempotency_window_seconds'=>max(3600,(int)($payload['idempotency_window_seconds']??86400)),'prepared_by'=>$preparedBy,'reviewed_by'=>$reviewedBy,'approved_by'=>$approvedBy,'review_note'=>'','approval_note'=>'','evidence_note'=>work_management_require_note((string)($payload['evidence_note']??'')),'published_at'=>null,'locked_at'=>null]);$rule['draft_version_id']=$version['id'];return$rule;
}
function work_management_submit_rule(int$versionId,string$note):array{work_management_require('automate');$version=work_management_find_version($versionId);if(!$version)throw new RuntimeException('Automation-rule version not found.');if((int)$version['prepared_by']!==(int)current_user()['id']&&!work_management_can('administer'))throw new RuntimeException('Only the preparer or administrator may submit the draft rule.');if($version['status']!=='draft')throw new RuntimeException('Only a draft automation rule can be submitted.');$version['status']='in_review';$version['evidence_note']=work_management_require_note($note);return work_management_save_automation_version($version);}
function work_management_review_rule(int$versionId,string$note):array{work_management_require('review');$version=work_management_find_version($versionId);if(!$version)throw new RuntimeException('Automation-rule version not found.');if($version['status']!=='in_review')throw new RuntimeException('The automation rule is not awaiting review.');if((int)$version['reviewed_by']!==(int)current_user()['id'])throw new RuntimeException('Only the assigned independent reviewer may review this rule.');if((int)$version['reviewed_by']===(int)$version['prepared_by'])throw new RuntimeException('The preparer cannot review the same automation rule.');$version['status']='reviewed';$version['review_note']=work_management_require_note($note);return work_management_save_automation_version($version);}
function work_management_publish_rule(int$versionId,string$note):array
{
    work_management_require('approve');$version=work_management_find_version($versionId);if(!$version)throw new RuntimeException('Automation-rule version not found.');if($version['status']!=='reviewed')throw new RuntimeException('The automation rule requires independent review before approval.');if((int)$version['approved_by']!==(int)current_user()['id'])throw new RuntimeException('Only the assigned approver may publish this rule.');work_management_assert_three_person_governance((int)$version['prepared_by'],(int)$version['reviewed_by'],(int)$version['approved_by']);$version['status']='published';$version['approval_note']=work_management_require_note($note);$version['published_at']=date('Y-m-d H:i:s');$version['locked_at']=$version['published_at'];$version=work_management_save_automation_version($version);$rule=work_management_find_rule((int)$version['rule_id']);if(!$rule)throw new RuntimeException('Automation rule not found.');$rule['status']='active';$rule['active_version_id']=$version['id'];work_management_save_automation_rule($rule);return$version;
}
function work_management_suspend_rule(int$ruleId,string$note):array{work_management_require('automate');$rule=work_management_find_rule($ruleId);if(!$rule)throw new RuntimeException('Automation rule not found.');if($rule['status']!=='active')throw new RuntimeException('Only an active rule can be suspended.');work_management_require_note($note);$rule['status']='suspended';return work_management_save_automation_rule($rule);}
function work_management_condition_value(array$context,string$field):mixed{$cursor=$context;foreach(explode('.',$field)as$part){if(!is_array($cursor)||!array_key_exists($part,$cursor))return null;$cursor=$cursor[$part];}return$cursor;}
function work_management_condition_matches(array$condition,array$context):bool
{
    if(isset($condition['all'])&&is_array($condition['all'])){foreach($condition['all']as$child)if(!is_array($child)||!work_management_condition_matches($child,$context))return false;return true;}if(isset($condition['any'])&&is_array($condition['any'])){foreach($condition['any']as$child)if(is_array($child)&&work_management_condition_matches($child,$context))return true;return false;}$actual=work_management_condition_value($context,(string)($condition['field']??''));$expected=$condition['value']??null;return match((string)($condition['operator']??'equals')){'equals'=>(string)$actual===(string)$expected,'not_equals'=>(string)$actual!==(string)$expected,'in'=>is_array($expected)&&in_array((string)$actual,array_map('strval',$expected),true),'not_in'=>is_array($expected)&&!in_array((string)$actual,array_map('strval',$expected),true),'greater_than'=>(float)$actual>(float)$expected,'greater_or_equal'=>(float)$actual>=(float)$expected,'less_than'=>(float)$actual<(float)$expected,'contains'=>str_contains(strtolower((string)$actual),strtolower((string)$expected)),'exists'=>$actual!==null&&$actual!=='',default=>false};
}
function work_management_find_run_by_key(string$key):?array{foreach(work_management_automation_runs()as$run)if(hash_equals((string)$run['idempotency_key'],$key))return$run;return null;}
function work_management_simulate_rule(int$ruleId,array$context):array{$rule=work_management_find_rule($ruleId);if(!$rule)throw new RuntimeException('Automation rule not found.');$version=work_management_rule_version($rule);if(!$version)throw new RuntimeException('Automation rule has no version.');$condition=json_decode((string)$version['condition_json'],true);$action=json_decode((string)$version['action_json'],true);if(!is_array($condition)||!is_array($action))throw new RuntimeException('Automation rule JSON is invalid.');return['matched'=>work_management_condition_matches($condition,$context),'condition'=>$condition,'action'=>$action,'rule'=>$rule,'version'=>$version];}
function work_management_run_rule(int$ruleId,string$sourceKey,array$context):array
{
    work_management_require('automate');$rule=work_management_find_rule($ruleId);if(!$rule||$rule['status']!=='active')throw new RuntimeException('Select an active automation rule.');$version=work_management_rule_version($rule);if(!$version||$version['status']!=='published'||empty($version['locked_at']))throw new RuntimeException('Automation execution requires a locked published version.');$idempotencyKey=hash('sha256',$rule['id'].'|'.$version['id'].'|'.$sourceKey);$existing=work_management_find_run_by_key($idempotencyKey);if($existing)return$existing;$started=date('Y-m-d H:i:s');$simulation=work_management_simulate_rule($ruleId,$context);$matched=$simulation['matched'];$action=$simulation['action'];$createdItemId=null;$result=['matched'=>$matched,'action'=>$action['action']??null];$error='';$status='completed';
    try{if($matched&&($action['action']??'')==='create_work_item'){$entityId=(int)($context['entity_id']??0);$service=!empty($action['shared_service_entity_code'])?work_management_find_entity_by_code((string)$action['shared_service_entity_code']):null;$item=work_management_create_item(['source_key'=>hash('sha256','automation|'.$rule['id'].'|'.$sourceKey),'source_module'=>(string)$rule['source_module'],'source_type'=>(string)($context['source_type']??$rule['trigger_event']),'source_id'=>(int)($context['source_id']??0),'entity_id'=>$entityId,'process_instance_id'=>$context['process_instance_id']??null,'step_instance_id'=>$context['step_instance_id']??null,'work_type'=>(string)($action['work_type']??'automated_work'),'title'=>(string)($context['title']??$rule['rule_name']),'description'=>(string)($context['description']??'Automation rule '.$rule['rule_code'].' matched supervised source evidence.'),'priority'=>(string)($action['priority']??'medium'),'required_permission'=>(string)($context['required_permission']??'platform.view'),'assigned_role_code'=>$action['assigned_role_code']??null,'assigned_entity_id'=>$service['id']??null,'sla_minutes'=>(int)($action['sla_minutes']??480),'evidence_required'=>1],$ruleId);$createdItemId=(int)$item['id'];$result['work_item_id']=$createdItemId;}elseif($matched&&($action['action']??'')==='escalate_work_item'){$itemId=(int)($context['work_item_id']??0);if($itemId<=0)throw new RuntimeException('Escalation automation requires work_item_id.');$item=work_management_escalate_item($itemId,'Automation rule '.$rule['rule_code'].' escalated overdue work.');$createdItemId=(int)$item['id'];$result['work_item_id']=$createdItemId;}}catch(Throwable$exception){$status='failed';$error=$exception->getMessage();$result['error']=$error;}
    return work_management_save_automation_run(['id'=>null,'rule_id'=>$rule['id'],'version_id'=>$version['id'],'source_key'=>$sourceKey,'idempotency_key'=>$idempotencyKey,'status'=>$status,'matched_count'=>$matched?1:0,'created_work_item_id'=>$createdItemId,'result_json'=>json_encode($result,JSON_UNESCAPED_SLASHES),'error_message'=>$error,'started_at'=>$started,'completed_at'=>date('Y-m-d H:i:s'),'created_at'=>$started]);
}
