<?php
declare(strict_types=1);

function work_management_require_note(string$note,string$message='Governance evidence is required.'):string{$note=trim($note);if($note==='')throw new RuntimeException($message);return mb_substr($note,0,5000);}
function work_management_assert_item_action(array$item,string$capability='execute'):array
{
    work_management_require($capability);if(!work_management_find_item((int)$item['id']))throw new RuntimeException('Work item not found or outside the active company scope.');$user=current_user();if(!$user)throw new RuntimeException('Authentication is required.');if(!work_management_user_can_receive($user,(int)$item['entity_id'],(string)$item['required_permission']))throw new RuntimeException('The work item requires a permission or company scope you do not hold.');return$user;
}
function work_management_transition(array$item,string$toStatus,string$eventType,string$note,array$metadata=[]):array
{
    $allowed=['open'=>['in_progress','blocked','cancelled'],'in_progress'=>['blocked','waiting_review','completed','cancelled'],'blocked'=>['in_progress','waiting_review','cancelled'],'waiting_review'=>['waiting_approval','in_progress','completed','blocked'],'waiting_approval'=>['completed','in_progress','blocked'],'completed'=>[],'cancelled'=>[]];$from=(string)$item['status'];if(!in_array($toStatus,$allowed[$from]??[],true))throw new RuntimeException('The work item cannot move from '.status_label($from).' to '.status_label($toStatus).'.');$note=work_management_require_note($note);$item['status']=$toStatus;$item['last_activity_at']=date('Y-m-d H:i:s');if($toStatus==='in_progress'&&empty($item['started_at']))$item['started_at']=date('Y-m-d H:i:s');if($toStatus==='completed'){$item['completed_at']=date('Y-m-d H:i:s');$item['completed_by']=(int)current_user()['id'];}$item=work_management_save_item($item);work_management_add_event((int)$item['id'],$eventType,$from,$toStatus,(string)$item['priority'],$note,$metadata);return$item;
}
function work_management_claim_item(int$itemId,string$note):array
{
    $item=work_management_find_item($itemId);if(!$item)throw new RuntimeException('Work item not found.');$user=work_management_assert_item_action($item,'execute');if(!empty($item['assigned_user_id'])&&(int)$item['assigned_user_id']!==(int)$user['id']&&!work_management_can('assign',$user))throw new RuntimeException('The work item is assigned to another user.');if(in_array((int)$user['id'],array_filter([(int)($item['reviewer_id']??0),(int)($item['approver_id']??0)]),true))throw new RuntimeException('The independent reviewer or approver cannot also claim execution ownership.');$from=(string)$item['status'];if(!in_array($from,['open','blocked'],true))throw new RuntimeException('Only open or blocked work can be claimed.');$item['assigned_user_id']=(int)$user['id'];$item['claimed_at']=date('Y-m-d H:i:s');$item['started_at']=$item['started_at']??date('Y-m-d H:i:s');$item['status']='in_progress';$item['last_activity_at']=date('Y-m-d H:i:s');$item=work_management_save_item($item);work_management_add_event($itemId,'work_claimed',$from,'in_progress',(string)$item['priority'],work_management_require_note($note),['claimed_by'=>(int)$user['id']]);return$item;
}
function work_management_start_item(int$itemId,string$note):array{$item=work_management_find_item($itemId);if(!$item)throw new RuntimeException('Work item not found.');work_management_assert_item_action($item,'execute');if(!work_management_item_can_act($item))throw new RuntimeException('Only the assigned owner or role may start this work item.');if($item['status']!=='open')throw new RuntimeException('Only open work can start.');return work_management_transition($item,'in_progress','work_started',$note);}
function work_management_block_item(int$itemId,string$note):array{$item=work_management_find_item($itemId);if(!$item)throw new RuntimeException('Work item not found.');work_management_assert_item_action($item,'execute');if(!work_management_item_can_act($item))throw new RuntimeException('Only the assigned owner or administrator may block this work.');if(!in_array((string)$item['status'],['open','in_progress','waiting_review','waiting_approval'],true))throw new RuntimeException('This work item cannot be blocked from its current state.');return work_management_transition($item,'blocked','work_blocked',$note);}
function work_management_resume_item(int$itemId,string$note):array{$item=work_management_find_item($itemId);if(!$item)throw new RuntimeException('Work item not found.');work_management_assert_item_action($item,'execute');if(!work_management_item_can_act($item))throw new RuntimeException('Only the assigned owner or administrator may resume this work.');if($item['status']!=='blocked')throw new RuntimeException('Only blocked work can resume.');return work_management_transition($item,'in_progress','work_resumed',$note);}
function work_management_submit_review(int$itemId,string$note):array
{
    $item=work_management_find_item($itemId);if(!$item)throw new RuntimeException('Work item not found.');$user=work_management_assert_item_action($item,'execute');if(!work_management_item_can_act($item,$user))throw new RuntimeException('Only the assigned execution owner may submit work for review.');if(in_array((int)$user['id'],array_filter([(int)($item['reviewer_id']??0),(int)($item['approver_id']??0)]),true))throw new RuntimeException('Execution ownership must remain separate from review and approval.');if(empty($item['reviewer_id'])&&empty($item['approver_id']))throw new RuntimeException('This work item has no independent review or approval assignment.');if(!in_array((string)$item['status'],['in_progress','blocked'],true))throw new RuntimeException('Only active work can be submitted for review.');return work_management_transition($item,'waiting_review','work_submitted_for_review',$note);
}
function work_management_review_item(int$itemId,string$note):array
{
    $item=work_management_find_item($itemId);if(!$item)throw new RuntimeException('Work item not found.');$user=work_management_assert_item_action($item,'review');if($item['status']!=='waiting_review')throw new RuntimeException('The work item is not awaiting review.');if((int)($item['reviewer_id']??0)!==(int)$user['id'])throw new RuntimeException('Only the assigned independent reviewer may review this work item.');if(in_array((int)$user['id'],[(int)($item['assigned_user_id']??0),(int)($item['created_by']??0)],true))throw new RuntimeException('The execution owner or creator cannot independently review the same work item.');return!empty($item['approver_id'])?work_management_transition($item,'waiting_approval','work_reviewed',$note,['reviewed_by'=>(int)$user['id']]):work_management_transition($item,'completed','work_reviewed_and_completed',$note,['reviewed_by'=>(int)$user['id']]);
}
function work_management_approve_item(int$itemId,string$note):array
{
    $item=work_management_find_item($itemId);if(!$item)throw new RuntimeException('Work item not found.');$user=work_management_assert_item_action($item,'approve');if($item['status']!=='waiting_approval')throw new RuntimeException('The work item is not awaiting approval.');if((int)($item['approver_id']??0)!==(int)$user['id'])throw new RuntimeException('Only the assigned approver may approve this work item.');if(in_array((int)$user['id'],[(int)($item['assigned_user_id']??0),(int)($item['reviewer_id']??0),(int)($item['created_by']??0)],true))throw new RuntimeException('Approval must remain separate from creation, execution, and review.');return work_management_transition($item,'completed','work_approved_and_completed',$note,['approved_by'=>(int)$user['id']]);
}
function work_management_complete_item(int$itemId,string$note):array
{
    $item=work_management_find_item($itemId);if(!$item)throw new RuntimeException('Work item not found.');work_management_assert_item_action($item,'execute');if(!work_management_item_can_act($item))throw new RuntimeException('Only the assigned owner may complete this work item.');if(!empty($item['evidence_required']))$note=work_management_require_note($note,'Completion evidence is required.');if(!empty($item['reviewer_id'])||!empty($item['approver_id']))throw new RuntimeException('Submit this work item for independent review instead of completing it directly.');if($item['status']!=='in_progress')throw new RuntimeException('Only in-progress work can complete.');return work_management_transition($item,'completed','work_completed',$note);
}
function work_management_reassign_item(int$itemId,int$targetUserId,string$note):array
{
    work_management_require('assign');$item=work_management_find_item($itemId);if(!$item)throw new RuntimeException('Work item not found.');$target=work_management_active_user($targetUserId);if(!$target||!work_management_user_can_receive($target,(int)$item['entity_id'],(string)$item['required_permission']))throw new RuntimeException('The selected assignee is outside the permitted company or permission scope.');if(in_array($targetUserId,array_filter([(int)($item['reviewer_id']??0),(int)($item['approver_id']??0)]),true))throw new RuntimeException('The execution assignee cannot also be the reviewer or approver.');$before=(int)($item['assigned_user_id']??0);$item['assigned_user_id']=$targetUserId;$item['claimed_at']=null;$item['last_activity_at']=date('Y-m-d H:i:s');$item=work_management_save_item($item);work_management_add_event($itemId,'work_reassigned',(string)$item['status'],(string)$item['status'],(string)$item['priority'],work_management_require_note($note),['from_user_id'=>$before,'to_user_id'=>$targetUserId]);return$item;
}
function work_management_cancel_item(int$itemId,string$note):array{work_management_require('administer');$item=work_management_find_item($itemId);if(!$item)throw new RuntimeException('Work item not found.');if(in_array((string)$item['status'],['completed','cancelled'],true))throw new RuntimeException('Closed work cannot be cancelled again.');return work_management_transition($item,'cancelled','work_cancelled',$note);}
function work_management_policy_for_priority(string$priority):?array{foreach(work_management_escalation_policies()as$policy)if(($policy['status']??'')==='active'&&(string)$policy['priority']===$priority)return$policy;return null;}
function work_management_target_escalation_level(array$item,array$policy):int
{
    if(empty($item['due_at'])||strtotime((string)$item['due_at'])>=time())return 0;$minutes=(int)floor((time()-strtotime((string)$item['due_at']))/60);if($minutes>=(int)$policy['level3_minutes'])return 3;if($minutes>=(int)$policy['level2_minutes'])return 2;if($minutes>=(int)$policy['level1_minutes'])return 1;return 0;
}
function work_management_escalation_exists(string$key):bool{foreach(work_management_escalation_events()as$event)if(hash_equals((string)$event['idempotency_key'],$key))return true;return false;}
function work_management_escalate_item(int$itemId,string$note,?int$forcedLevel=null):array
{
    work_management_require('assign');$item=work_management_find_item($itemId);if(!$item)throw new RuntimeException('Work item not found.');if(in_array((string)$item['status'],['completed','cancelled'],true))throw new RuntimeException('Closed work cannot be escalated.');$policy=work_management_policy_for_priority((string)$item['priority']);if(!$policy)throw new RuntimeException('No active escalation policy is configured for this priority.');$target=$forcedLevel??max((int)$item['escalation_level']+1,work_management_target_escalation_level($item,$policy));$target=max(1,min(3,$target));if($target<=(int)$item['escalation_level'])return$item;$key=hash('sha256','work|'.$itemId.'|level|'.$target);if(work_management_escalation_exists($key))return$item;$from=(int)$item['escalation_level'];$action=['notify_roles'=>[],'reason'=>'sla_escalation'];if($target>=1)$action['notify_roles'][]=(string)$item['assigned_role_code'];if($target>=2)$action['notify_roles'][]=(string)$policy['backup_role_code'];if($target>=3)$action['notify_roles'][]=(string)$policy['executive_role_code'];$action['notify_roles']=array_values(array_unique(array_filter($action['notify_roles'])));
    if($target>=2){foreach(work_management_users_for_role((string)$policy['backup_role_code'],(int)$item['entity_id'],(string)$item['required_permission'])as$backup)if(!in_array((int)$backup['id'],array_filter([(int)($item['reviewer_id']??0),(int)($item['approver_id']??0)]),true)){$item['assigned_user_id']=(int)$backup['id'];break;}}
    if($target>=3){$executives=work_management_users_for_role((string)$policy['executive_role_code'],(int)$item['entity_id'],'work_management.approve');if($executives)$item['approver_id']=(int)$executives[0]['id'];}
    $item['escalation_level']=$target;$item['last_activity_at']=date('Y-m-d H:i:s');$item=work_management_save_item($item);work_management_save_escalation_event(['id'=>null,'work_item_id'=>$itemId,'policy_id'=>$policy['id'],'from_level'=>$from,'to_level'=>$target,'triggered_at'=>date('Y-m-d H:i:s'),'action_json'=>json_encode($action,JSON_UNESCAPED_SLASHES),'idempotency_key'=>$key,'created_by'=>(int)current_user()['id']]);work_management_add_event($itemId,'work_escalated',(string)$item['status'],(string)$item['status'],(string)$item['priority'],work_management_require_note($note),['from_level'=>$from,'to_level'=>$target,'actions'=>$action]);return$item;
}
function work_management_run_escalation_scan():array
{
    work_management_require('assign');$escalated=0;$unchanged=0;$errors=[];foreach(work_management_items()as$item){if(in_array((string)$item['status'],['completed','cancelled'],true))continue;$policy=work_management_policy_for_priority((string)$item['priority']);if(!$policy)continue;$target=work_management_target_escalation_level($item,$policy);if($target<=(int)$item['escalation_level']){$unchanged++;continue;}try{work_management_escalate_item((int)$item['id'],'Scheduled SLA scan escalated overdue work under policy '.$policy['policy_code'].'.',$target);$escalated++;}catch(Throwable$exception){$errors[]=$exception->getMessage();}}return['escalated'=>$escalated,'unchanged'=>$unchanged,'errors'=>array_values(array_unique($errors))];
}
