<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/app/bootstrap.php';
require_once dirname(__DIR__).'/includes/app/supplier_portal.php';
$account=supplier_portal_require_account();
if(request_method()!=='POST')redirect_to(root_url('supplier-portal/index.php'));
verify_csrf();

function portal_required(string $key,string $label): string{$value=trim(post_string($key));if($value==='')throw new RuntimeException($label.' is required.');return mb_substr($value,0,5000);}
function portal_date(string $key,bool $optional=false): ?string{$value=trim(post_string($key));if($value===''&&$optional)return null;$date=DateTimeImmutable::createFromFormat('!Y-m-d',$value);if(!$date||$date->format('Y-m-d')!==$value)throw new RuntimeException('Enter a valid date.');return$value;}
function portal_redirect(string $tab): never{redirect_to(root_url('supplier-portal/index.php?tab='.$tab));}

try{
    $action=post_string('action');$supplierId=(int)$account['supplier_id'];$accountId=(int)$account['id'];
    if($action==='submit_po_response'){
        supplier_portal_require_capability($account,'acknowledge_po');$po=supplier_portal_account_po($account,post_int('purchase_order_id'));if(!$po)throw new RuntimeException('The purchase order is outside your supplier access.');
        $type=post_string('response_type');if(!in_array($type,['acknowledge','accept','reject','change_request'],true))throw new RuntimeException('Select a valid purchase-order response.');
        $date=portal_date('proposed_delivery_date',true);$amount=(float)post_string('proposed_total_amount',(string)($po['total_amount']??0));if($amount<0)throw new RuntimeException('The proposed amount cannot be negative.');
        $record=supplier_portal_save_po_response(['response_number'=>supplier_portal_number('POR',supplier_portal_po_responses($supplierId)),'supplier_id'=>$supplierId,'purchase_order_id'=>(int)$po['id'],'account_id'=>$accountId,'response_type'=>$type,'proposed_delivery_date'=>$date,'proposed_total_amount'=>$amount,'currency_code'=>'USD','notes'=>portal_required('notes','Response explanation'),'evidence_reference'=>portal_required('evidence_reference','Confirmation reference'),'status'=>'submitted','reviewed_by'=>null,'reviewed_at'=>null,'review_note'=>'']);
        supplier_portal_add_event($supplierId,(int)$po['company_id'],'purchase_order_response',(int)$record['id'],'supplier_response_submitted',null,'submitted',$type==='reject'?'high':'medium',$record['notes'],'supplier',null,$accountId);flash('success','Purchase-order response submitted for internal review.');portal_redirect('orders');
    }
    if($action==='submit_asn'){
        supplier_portal_require_capability($account,'submit_asn');$po=supplier_portal_account_po($account,post_int('purchase_order_id'));if(!$po)throw new RuntimeException('The purchase order is outside your supplier access.');$lineId=post_int('purchase_order_line_id');$line=null;foreach(supplier_portal_account_po_lines($account,(int)$po['id']) as $candidate)if((int)$candidate['id']===$lineId){$line=$candidate;break;}if(!$line)throw new RuntimeException('Select a valid purchase-order line.');
        $qty=(float)post_string('quantity_shipped','0');$ordered=(float)($line['quantity_ordered']??$line['quantity']??0);if($qty<=0||$qty>$ordered+.0001)throw new RuntimeException('Shipment quantity must be positive and cannot exceed the ordered quantity.');
        $asn=supplier_portal_save_asn(['asn_number'=>portal_required('asn_number','ASN number'),'supplier_id'=>$supplierId,'purchase_order_id'=>(int)$po['id'],'account_id'=>$accountId,'ship_date'=>portal_date('ship_date'),'estimated_arrival'=>portal_date('estimated_arrival'),'carrier'=>portal_required('carrier','Carrier'),'tracking_number'=>portal_required('tracking_number','Tracking number'),'package_count'=>max(0,post_int('package_count')),'pallet_count'=>max(0,post_int('pallet_count')),'packing_slip_reference'=>portal_required('packing_slip_reference','Packing-slip reference'),'status'=>'submitted','reviewed_by'=>null,'reviewed_at'=>null,'review_note'=>'']);
        supplier_portal_save_asn_line(['shipment_notice_id'=>$asn['id'],'purchase_order_line_id'=>$lineId,'quantity_shipped'=>$qty,'lot_or_serial_reference'=>mb_substr(trim(post_string('lot_or_serial_reference')),0,240),'package_reference'=>mb_substr(trim(post_string('package_reference')),0,240),'notes'=>mb_substr(trim(post_string('notes')),0,5000)]);
        supplier_portal_add_event($supplierId,(int)$po['company_id'],'shipment_notice',(int)$asn['id'],'asn_submitted',null,'submitted','medium','ASN '.$asn['asn_number'].' submitted for '.$qty.' units.','supplier',null,$accountId);flash('success','Advance shipment notice submitted for receiving review.');portal_redirect('shipments');
    }
    if($action==='submit_invoice'){
        supplier_portal_require_capability($account,'submit_invoice');$po=supplier_portal_account_po($account,post_int('purchase_order_id'));if(!$po)throw new RuntimeException('The purchase order is outside your supplier access.');$lineId=post_int('purchase_order_line_id');$line=null;foreach(supplier_portal_account_po_lines($account,(int)$po['id']) as $candidate)if((int)$candidate['id']===$lineId){$line=$candidate;break;}if(!$line)throw new RuntimeException('Select a valid purchase-order line.');
        $invoiceNumber=portal_required('invoice_number','Invoice number');$qty=(float)post_string('quantity_invoiced','0');$unitPrice=(float)post_string('unit_price','0');$freight=max(0,(float)post_string('freight_amount','0'));$tax=max(0,(float)post_string('tax_amount','0'));if($qty<=0||$unitPrice<0)throw new RuntimeException('Invoice quantity must be positive and unit price cannot be negative.');$subtotal=round($qty*$unitPrice,2);$total=round($subtotal+$freight+$tax,2);$duplicate=supplier_portal_invoice_duplicate($supplierId,$invoiceNumber,$total);
        $submission=supplier_portal_save_invoice_submission(['submission_number'=>supplier_portal_number('INV-SUB',supplier_portal_invoice_submissions($supplierId)),'supplier_id'=>$supplierId,'purchase_order_id'=>(int)$po['id'],'account_id'=>$accountId,'invoice_number'=>$invoiceNumber,'invoice_date'=>portal_date('invoice_date'),'due_date'=>portal_date('due_date'),'currency_code'=>'USD','subtotal'=>$subtotal,'freight_amount'=>$freight,'tax_amount'=>$tax,'total_amount'=>$total,'document_reference'=>portal_required('document_reference','Invoice document reference'),'status'=>'submitted','duplicate_flag'=>$duplicate?1:0,'reviewed_by'=>null,'reviewed_at'=>null,'review_note'=>$duplicate?'Potential duplicate detected before internal acceptance.':'','canonical_invoice_id'=>null]);
        supplier_portal_save_invoice_line(['invoice_submission_id'=>$submission['id'],'purchase_order_line_id'=>$lineId,'description'=>$line['description']??'Purchase-order line','quantity_invoiced'=>$qty,'unit_price'=>$unitPrice,'tax_amount'=>$tax,'freight_amount'=>$freight,'line_total'=>$subtotal]);
        supplier_portal_add_event($supplierId,(int)$po['company_id'],'invoice_submission',(int)$submission['id'],'invoice_submitted',null,'submitted',$duplicate?'high':'medium',($duplicate?'Potential duplicate. ':'').'Invoice '.$invoiceNumber.' totals $'.number_format($total,2).'.','supplier',null,$accountId);flash($duplicate?'info':'success',$duplicate?'Invoice staged with a duplicate warning for internal review.':'Invoice staged for internal validation and three-way matching.');portal_redirect('invoices');
    }
    if($action==='submit_document'){
        supplier_portal_require_capability($account,'submit_documents');$type=post_string('document_type');$record=supplier_portal_save_document(['supplier_id'=>$supplierId,'account_id'=>$accountId,'entity_type'=>post_string('entity_type','supplier'),'entity_id'=>post_int('entity_id',$supplierId),'document_type'=>$type,'title'=>portal_required('title','Document title'),'document_reference'=>portal_required('document_reference','Controlled document reference'),'effective_date'=>portal_date('effective_date',true),'expiration_date'=>portal_date('expiration_date',true),'status'=>'submitted','reviewed_by'=>null,'reviewed_at'=>null,'review_note'=>$type==='banking_change_request'?'Verification request only. No banking credentials are stored in the portal.':'']);
        supplier_portal_add_event($supplierId,null,'document_submission',(int)$record['id'],'document_submitted',null,'submitted',$type==='banking_change_request'?'high':'medium',$record['title'],'supplier',null,$accountId);flash('success','Document reference submitted for internal verification.');portal_redirect('documents');
    }
    if($action==='submit_sourcing'){
        supplier_portal_require_capability($account,'sourcing');$deadlineInput=portal_required('bid_deadline','Bid deadline');$deadline=date('Y-m-d H:i:s',strtotime($deadlineInput));if(strtotime($deadline)<time())throw new RuntimeException('The bid deadline has passed.');$record=supplier_portal_save_sourcing_submission(['submission_number'=>supplier_portal_number('BID',supplier_portal_sourcing_submissions($supplierId)),'supplier_id'=>$supplierId,'account_id'=>$accountId,'sourcing_reference'=>portal_required('sourcing_reference','Sourcing reference'),'title'=>portal_required('title','Proposal title'),'bid_deadline'=>$deadline,'currency_code'=>'USD','proposal_value'=>max(0,(float)post_string('proposal_value','0')),'lead_time_days'=>max(0,post_int('lead_time_days')),'payment_terms'=>mb_substr(trim(post_string('payment_terms')),0,100),'freight_terms'=>mb_substr(trim(post_string('freight_terms')),0,160),'exceptions_and_assumptions'=>portal_required('exceptions_and_assumptions','Exceptions and assumptions'),'document_reference'=>portal_required('document_reference','Proposal document reference'),'revision_number'=>max(1,post_int('revision_number',1)),'status'=>'submitted','locked_at'=>date('Y-m-d H:i:s'),'reviewed_by'=>null,'reviewed_at'=>null,'review_note'=>'']);
        supplier_portal_add_event($supplierId,null,'sourcing_submission',(int)$record['id'],'proposal_locked',null,'submitted','medium','Supplier proposal locked before deadline.','supplier',null,$accountId);flash('success','Proposal submitted and locked. Internal scoring and competing proposals remain private.');portal_redirect('sourcing');
    }
    if($action==='submit_quality'){
        supplier_portal_require_capability($account,'quality');$record=supplier_portal_save_quality_response(['response_number'=>supplier_portal_number('QAR',supplier_portal_quality_responses($supplierId)),'supplier_id'=>$supplierId,'account_id'=>$accountId,'quality_reference'=>portal_required('quality_reference','Quality reference'),'response_type'=>post_string('response_type','containment'),'containment_response'=>portal_required('containment_response','Containment response'),'root_cause'=>portal_required('root_cause','Root cause'),'corrective_action'=>portal_required('corrective_action','Corrective action'),'preventive_action'=>portal_required('preventive_action','Preventive action'),'target_date'=>portal_date('target_date'),'evidence_reference'=>portal_required('evidence_reference','Evidence reference'),'status'=>'submitted','reviewed_by'=>null,'reviewed_at'=>null,'review_note'=>'']);
        supplier_portal_add_event($supplierId,null,'quality_response',(int)$record['id'],'quality_response_submitted',null,'submitted','high',$record['quality_reference'],'supplier',null,$accountId);flash('success','Quality response submitted for independent internal verification.');portal_redirect('quality');
    }
    if($action==='send_message'){
        supplier_portal_require_capability($account,'message');$entityType=post_string('entity_type','supplier');$entityId=post_int('entity_id',$supplierId);$companyId=null;if($entityType==='purchase_order'){$po=supplier_portal_account_po($account,$entityId);if(!$po)throw new RuntimeException('The purchase order is outside your supplier access.');$companyId=(int)$po['company_id'];}
        $record=supplier_portal_save_message(['supplier_id'=>$supplierId,'account_id'=>$accountId,'company_id'=>$companyId,'entity_type'=>$entityType,'entity_id'=>$entityId,'direction'=>'supplier_to_internal','subject'=>portal_required('subject','Message subject'),'message_body'=>portal_required('message_body','Message body'),'supplier_visible'=>1,'required_response_date'=>null,'status'=>'open','read_at'=>null,'acknowledged_at'=>null,'created_by_internal'=>null]);
        supplier_portal_add_event($supplierId,$companyId,'message',(int)$record['id'],'supplier_message_sent',null,'open','low',$record['subject'],'supplier',null,$accountId);flash('success','Message sent to the internal record owner.');portal_redirect('messages');
    }
    if($action==='ack_message'){
        $message=null;foreach(supplier_portal_account_records($account,'messages') as $candidate)if((int)$candidate['id']===post_int('message_id')&&(int)$candidate['supplier_id']===$supplierId&&!empty($candidate['supplier_visible'])){$message=$candidate;break;}if(!$message)throw new RuntimeException('The message is outside your supplier access.');$message['status']='acknowledged';$message['read_at']=$message['read_at']?:date('Y-m-d H:i:s');$message['acknowledged_at']=date('Y-m-d H:i:s');$saved=supplier_portal_save_message($message);supplier_portal_add_event($supplierId,$message['company_id']?:null,'message',(int)$message['id'],'message_acknowledged','open','acknowledged','low',$message['subject'],'supplier',null,$accountId);flash('success','Message acknowledged.');portal_redirect('messages');
    }
    throw new RuntimeException('Unknown supplier portal action.');
}catch(Throwable $e){flash('error',$e->getMessage());portal_redirect(post_string('return_tab','dashboard'));}
