<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/app/bootstrap.php';
require_once dirname(__DIR__).'/includes/app/supplier_portal.php';
$token=query_string('token',post_string('token'));$invitation=$token!==''?supplier_portal_invitation_by_token($token):null;$error='';$activated=false;
if(request_method()==='POST'){
    verify_csrf();
    try{$account=supplier_portal_activate_invitation($token,post_string('password'),post_string('password_confirmation'));$activated=true;}catch(Throwable $e){$error=$e->getMessage();}
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Activate Supplier Portal | Gruber</title><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="<?= h(root_url('supplier-portal/assets/portal.css?v=20260727-section22')) ?>"></head><body><main class="login-main"><section class="login-card"><img src="<?= h(app_url('assets/gruber-main.png')) ?>" alt="Gruber"><span class="eyebrow">Controlled supplier activation</span><h1>Activate account</h1><?php if($activated): ?><div class="flash flash-success">Your supplier account is active. Sign in to continue.</div><a class="button primary" href="<?= h(root_url('supplier-portal/login.php')) ?>">Continue to sign in</a><?php elseif(!$invitation): ?><div class="flash flash-error">This invitation is invalid, expired, or already used.</div><?php else: ?><p><?= h($invitation['invited_name']) ?> · <?= h($invitation['email']) ?> · <?= h(status_label($invitation['portal_role'])) ?></p><?php if($error): ?><div class="flash flash-error"><?= h($error) ?></div><?php endif; ?><form method="post"><?= csrf_field() ?><input type="hidden" name="token" value="<?= h($token) ?>"><label><span>Password</span><input type="password" name="password" required autocomplete="new-password"></label><label><span>Confirm password</span><input type="password" name="password_confirmation" required autocomplete="new-password"></label><button class="button primary">Activate supplier account</button></form><div class="demo-note">Password policy: at least 12 characters with upper and lowercase letters, a number, and a symbol.</div><?php endif; ?></section></main></body></html>
