<?php declare(strict_types=1); ?>
<style>
.portal-hero{display:grid;grid-template-columns:1.35fr .65fr;gap:20px;padding:24px;border:1px solid var(--border-color,#dfe4ea);border-radius:20px;background:linear-gradient(135deg,#fff,#f5f8fc)}.portal-hero h2{margin:.35rem 0 .65rem;font-size:clamp(1.7rem,3vw,2.5rem)}.portal-shield{display:grid;place-items:center;min-height:180px;border-radius:18px;background:#111827;color:#fff;text-align:center;padding:20px}.portal-shield strong{font-size:2.5rem}.portal-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.portal-tabs a{padding:9px 13px;border:1px solid #dfe4ea;border-radius:999px;background:#fff}.portal-tabs a.active{background:#111827;color:#fff}.portal-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.portal-queue{display:grid;gap:12px}.portal-record{border:1px solid #dfe4ea;border-radius:16px;padding:16px;background:#fff}.portal-record header{display:flex;justify-content:space-between;gap:16px}.portal-record small{display:block;color:#64748b;margin-top:4px}.portal-record form{margin-top:12px;padding-top:12px;border-top:1px solid #eef2f7}.permission-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.permission-grid label{display:flex;gap:7px;align-items:center;border:1px solid #e5e7eb;border-radius:10px;padding:8px}.portal-warning{padding:14px 16px;border-radius:14px;background:#fff7ed;border:1px solid #fed7aa;color:#9a3412}@media(max-width:920px){.portal-hero,.portal-grid{grid-template-columns:1fr}.permission-grid{grid-template-columns:1fr 1fr}}
</style>
<?php if(data_is_production()&&!supplier_portal_tables_ready()): ?><div class="portal-warning"><strong>Production Supplier Portal is not active.</strong> Import <code>database/20260727_section22_supplier_portal_collaboration_exchange.sql</code> after Sections 11–21. Demo Mode remains available; Production writes fail closed.</div><?php endif; ?>
<section class="portal-hero"><div><span class="eyebrow">Restricted external collaboration</span><h2><?= h($selectedSupplier['name']??'Supplier Portal') ?></h2><p>Supplier accounts are isolated by supplier and granted company. They cannot use Enterprise View, the internal company switcher, internal notes, approval evidence, savings records, competitor proposals, or cross-supplier data.</p><div class="company-chip-row"><span><?= h(current_scope_label()) ?></span><span><?= count($accounts) ?> portal accounts</span><span><?= array_sum([$metrics['po_responses'],$metrics['asns'],$metrics['invoices'],$metrics['documents'],$metrics['sourcing'],$metrics['quality']]) ?> review items</span></div></div><div class="portal-shield"><span>Supplier tenant boundary</span><strong>1 → 1</strong><small>One account · one supplier · explicit company grants</small></div></section>
<section class="metric-grid metric-grid-6"><article class="metric-card"><span>Active accounts</span><strong><?= $metrics['active_accounts'] ?></strong><small>Restricted supplier identities</small></article><article class="metric-card"><span>Pending invitations</span><strong><?= $metrics['pending_invitations'] ?></strong><small>Expiring activation tokens</small></article><article class="metric-card"><span>PO responses</span><strong><?= $metrics['po_responses'] ?></strong><small>Awaiting internal review</small></article><article class="metric-card"><span>Shipment notices</span><strong><?= $metrics['asns'] ?></strong><small>ASN validation queue</small></article><article class="metric-card"><span>Invoices</span><strong><?= $metrics['invoices'] ?></strong><small>Staged before Section 18</small></article><article class="metric-card"><span>Documents / quality</span><strong><?= $metrics['documents']+$metrics['quality'] ?></strong><small>Evidence review queue</small></article></section>
<form method="get" class="filter-bar"><input type="hidden" name="tab" value="<?= h($tab) ?>"><label><span>Supplier scope</span><select name="supplier_id" onchange="this.form.submit()"><?php foreach($suppliers as $supplier): ?><option value="<?= (int)$supplier['id'] ?>" <?= $selectedSupplierId===(int)$supplier['id']?'selected':'' ?>><?= h($supplier['name']) ?></option><?php endforeach; ?></select></label><noscript><button class="button secondary">Apply</button></noscript></form>
<nav class="portal-tabs" aria-label="Supplier Portal sections"><?php foreach(['overview'=>'Overview','accounts'=>'Accounts & access','review'=>'Review queue','messages'=>'Messages','events'=>'Immutable events'] as $key=>$label): ?><a class="<?= $tab===$key?'active':'' ?>" href="<?= h(app_url('supplier-portal.php?'.http_build_query(['tab'=>$key,'supplier_id'=>$selectedSupplierId]))) ?>"><?= h($label) ?></a><?php endforeach; ?></nav>
